### ISSUE TITLE
File copying and moving with verify extremely slow under Debian 12

### ISSUE THREAD

**Issue by user75367854678** [doublecmd/doublecmd#1000]
File copying or moving under Debian Gnome Wayland is extremely slow and/or crashes. The bigger the file the worse the impact seems to be.

Here a few rough numbers, I did not have an eye on it all the time

600GB File with "verify" enabled:
1) first doublecmd transfer: crashed the whole USB port after 200GB, took at least 6 hours to get there, more likely 12 hours.
2) second doublecmd transfer: manually stopped after 300GB because it was already going over 8 hours to barely reach half:
indicated transfer rate at the start 20MB/s, when I aborted 17MB/s
3)Comparison transfer: Terminal with "cp"-command: 2h48min ~50MB/s

First Test with 10GB file (2 USB3 HDDs):
1) cp transfer: 4min ~42MB/s
2) doublecmd transfer with verify enabled: 7min to copy, 2min to verify
3) doublecmd transfer without verify: 6min to copy
Enabling verify seems to make the copy process slightly slower before the comparison happens (7min to copy, 2min to compare) but a normal copy takes 6min and a subsequent manual compare 3min, so it ends up being the same speed.

Second 10GB test (2 USB3 HDDs, no verify):
1) cp: 4:05min
2) Doublecmd: 6:52min 

Third 10GB test (external HDD to internal SSD)
1) cp: 1:31min
2) Doublecmd: 1:26min 
Either it being written to an internal disk or the disk it is written to being an SSD seems to bring both speeds to about the same. 

Fourth Test (external HDD copy to same HDD)
1) cp: 220MB in 2 Minutes
2) Doublecmd: 240MB in 2 Minutes
I did not have the patience to let it run longer, they have similar enough speeds

Other observations:
1) It doesn't matter if copied or moved with Ctr+V or dialogue.
2) It happens with all transfers from an external HDD to another external HDD. Different USB ports/controllers were used as well as different kinds of hardware how the HDDs are connected (encased external HDDs or external SATA/USB3 dock).
3) At least for the 600GB file the location of where it was written to the disk should not matter as the disk only had 600GB free space, so either way, if there were a bottleneck of weak sectors, both cp and doublecmd should have run into them, but only doublecmd showed the slow speeds.
4) Sometimes closing all Doublecmd instances and restarting it makes copying faster. I see no logic though when it happens, it often does, no matter if one instance is running, multiple or restarted.

As far as I can see the speeds seem to only be off for transfers to an (external) HDD from another external HDD or internal SSD. The target drive being a SSD or it being an internal disk prevents the problem from happening. Sadly I can't test that right now. Also a copy to the same disk seems to have the same speed as cp.

Thank you very much

**Comment by alexx2000** [comment]
"Verify" option disables operating system disk cache that why copying is so slow.

**Comment by user75367854678** [comment]
Thank you for the reply, I was able to replicate that behavior now. The speed without verify is 2-4x faster.

Therefore I am wondering, is there a benefit of choosing verify during the copy process over doing a normal copy and then later "synchronize directories" with comparison by contents? 

Does the verify option correct errors during copying to mitigate bad sectors? That would make it superior when copying to older disks used as secondary backups.

Also is there a possibility to force CTRL+C and CTRL+V to use verify too? 

At the moment it seems like CTRL+C and CTRL+V doesn't use verify, for example a 10GB files with copy dialogue and verify enabled shows as transferring 1 file of 20GB. It transfers the full 10GB file and then adds another run for the same file, I assume that is the verify process. 
However when using CTRL+C and CTRL+V it only shows up as one file of 10GB and doesn't run anything after the transfer, so I assume verify is disabled.

thank you very much

**Comment by Nyanraltotlapun** [comment]
> Therefore I am wondering, is there a benefit of choosing verify during the copy process over doing a normal copy and then later "synchronize directories" with comparison by contents?

You misunderstanding of disk cache concept and how it works.

Basically, without using cache you getting real speed of data writing to disk.
If you do the file comparison afterwards - it does not actually synchronize anything. It will use data from cache in ram.
Synchronization will happen when you "safely remove" your USB storage.

Also, any concurrent access to HDD, especially to USB one, will decrease write speeds substantially.
So when you writing big file to USB HDD without using cache, you should not do anything else with it, even browse folders.

And also FS fragmentation can lead to slowdowns.

And, you should change in doublecmd settings File Operations -> Buffer Size to 8192 or 10240 or even 20480.

Ok, now the benefit of verify is very simple, you will get data actually written to external HDD in real time.
Drawback - it can be suboptimal, especially if you want to use this drive for something else in parallel. Theoretically, by using system cache, data can by written in more optimal way.

So, maybe you want to use normal copy (without Verify) or even cp command. And execute **sync** command in terminal afterward to commit any write caches.
But, still, do not forget about safely removing your USB HDD.
