### ISSUE TITLE
Window size and position reverted to default values if save configuration on exit is enabled.

### ISSUE THREAD

**Issue by gramms** [doublecmd/doublecmd#1002]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/03
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Fedora release 38 (Thirty Eight)

Widgetset library: GTK 2.24.33

### Description

I have the problem, that DC reverts the Main window size and position to it's default values, when Save configuration on Exit is enabled.

In ~/.config/doublecmd/doublecmd.xml there is this section:
`<MainWindow>
    <Position Save="True">
      <Left>80</Left>
      <Top>48</Top>
      <Width>800</Width>
      <Height>480</Height>
      <PixelsPerInch>96</PixelsPerInch>
      <Maximized>True</Maximized>
      <Splitter>50</Splitter>
    </Position>
  </MainWindow>`
If I enable Options -> Configuration -> Save on exit -> Save configuration, this section will always be reverted to it's default values, not to the actual window size and position as expected. The only way to save the main window's size and position is to uncheck the auto save option and manually save the position and size of the main window.

BTW: The size of the configuration dialog and the file viewer are very small by default and are not affected by the Save position/size options at all, is this intentional?

I am using Fedora 38 with GNOME 44.1, Wayland and kernel 6.3.4

Thanks.

**Comment by gramms** [comment]
This has no effect either. :(

**Comment by alexx2000** [comment]
I guess it is a Wayland incompatibility. Can you check with X11 session?

**Comment by gramms** [comment]
Hi, sorry for the late response. The issue seems to have fixed itself, size and position are now saved and loaded on startup as expected. There were some updates on system components lately that I installed on my machine, probably that fixed the issue.

This issue can be closed.
