### ISSUE TITLE
Indefinitely shown hourglass cursor is back again

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#1009]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10770
Commit: 977abbe1c
Build date: 2023/06/06
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.4.0

### Description

Unfortunately, the problem with the indefinitely shown hourglass cursor is back again.

To reproduce the problem, select a png file in Double Commander and press F3. As a result, the viewer will start and display the png file. Now click with the mouse on the Double Commander window. The mouse cursor will be an hourglass.

See the attached video.

https://github.com/doublecmd/doublecmd/assets/79788982/82b7457b-fe76-4615-b487-cea71c042b2d

**Comment by rich2014** [comment]
before, it was just patching the cursor at DC.

i will try to overhaul the cursor-related architecture at the Lazarus/Lcl/Cocoa level in the weekend.

**Comment by rich2014** [comment]
@Andreas0602 

should be fixed in r10776.

test it please.

**Comment by rich2014** [comment]
it's great :)
