### ISSUE TITLE
Error copying a folder contents by file mask (via F5)

### ISSUE THREAD

**Issue by duvte** [doublecmd/doublecmd#1021]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10777
Commit: f058e83
Build date: 2023/06/15
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 18.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

A folder contains the files with the same names and different extensions: 01.txt , 02.txt , ... and 01.ext, 02.ext, ...
When copying the entire folder (via F5) and specifying the mask of the files being copied *.ext, the contents of *.txt files are mistakenly copied instead, but with the names *.ext
[files.zip](https://github.com/doublecmd/doublecmd/files/11797170/files.zip)

**Comment by alexx2000** [comment]
#454
