### ISSUE TITLE
Parent directory of archive contents transferred to the other panel leads to previous directory

### ISSUE THREAD

**Issue by mormegil-cz** [doublecmd/doublecmd#1026]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/02/11
Lazarus: 2.2.4.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 23.04

Widgetset library: GTK 2.24.33

### Description

1. In the left panel, navigate to the contents of an archive file (e.g. some ZIP).
2. In the right panel, navigate to a random different folder (e.g. `/bin`).
3. In the left panel, with the cursor on a file within the archive, press [Ctrl]+[Right] (`cm_TransferRight`).
4. The right panel now shows the same contents of the archive. Everything seems fine.
5. Now, in the right panel, navigate using the `[..]` item, or press [Ctrl]+[PgUp].

**What I expected to see**
I expected to be navigated to the directory containing the archive file (as doing the same does in the left panel).

**What happened instead**
The right panel now shows the _previous_ directory (where you were after step 2).

Note that if you pressed [Ctrl]+[Right] on the archive file itself (instead of on a contained file), the right panel would show its contents just the same, but this bug would not appear, the navigation would work correctly.

**Comment by alexx2000** [comment]
Already fixed in DC 1.1.0.
