### ISSUE TITLE
Invalid type cast error - DC-1.1.0-10782/10783 macOS 13.4.1

### ISSUE THREAD

**Issue by norbert-wiener** [doublecmd/doublecmd#1027]
### Version

The last couple of DC nightly builds for macOS (I am running latest Ventura 13.4.1) intermittently throws an invalid type cast error when I am selecting a different right-pane folder via the directory hotlist. If I restart DC it seems to work fine again, but the error crops up every few days. Attached are relevant screenshot and doublecommand.err. Thanks!
<img width="246" alt="dc-mac-1 1 0-10783-macos-13 4 1-crash" src="https://github.com/doublecmd/doublecmd/assets/71738573/3b29781e-5b1b-4bfe-a7ce-844056658044">
[doublecmd-1.1.0-10783-err.txt](https://github.com/doublecmd/doublecmd/files/11872056/doublecmd-1.1.0-10783-err.txt)

### Description

Invalid type cast error - DC-1.1.0-10782/10783 macOS 13.4.1

**Comment by rich2014** [comment]
it's a bug of Lazarus.

appeared briefly on June 24.

it should have been fixed.

@alexx2000 Alex, could you regenerate r10782? or wait until the next commit is submitted?

**Comment by alexx2000** [comment]
Done.

**Comment by norbert-wiener** [comment]
The new 10783 build has been working well thus far. Thanks for the fix - I use DC every day. Cheers!
