### ISSUE TITLE
Synchronize with Archives

### ISSUE THREAD

**Issue by gilusso** [doublecmd/doublecmd#1029]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H1 x86_64

### Description

i do regulary compare directories for content with the sync function
unfortunately, comparing a normal directory with the same directory in a ZIP or RAR archive does not create valid results

verified this with TC10.5 i own, which was able to do this, DC ignores whole directories to compare

**Comment by alexx2000** [comment]
I cannot reproduce. More info please.

**Comment by gilusso** [comment]
i uploaded recent encounter, please download this (probably size overkill but) 
https://mega.nz/file/Fz5AHBpK#PlVCzKhCpaCIhJQAxbzVpuv0ZtaJPMunuEecOn5WymU

extract directory "1928 Nurburgring" in one position (let say drive E:)
extract directory "I_FRT LM1928" on another target / drive

now dive into    ....\1928 Nurburgring.rar\1928 Nurburgring\GameData
on the right side

and on the left side ....\I_FRT LM1928\gamedata\

sync the directories
and on my computer, it only shows files which are on left side, but not on right side
if i swap the sides, the result is correct

![Clipboard01](https://github.com/doublecmd/doublecmd/assets/5262240/7a39f827-3bc4-4183-b1ab-c79ff505265f)
