### ISSUE TITLE
[Feature Request] Official PPA for ubuntu

### ISSUE THREAD

**Issue by lonix1** [doublecmd/doublecmd#103]
Thanks for making this official repo!

Ubuntu packages an old version of DC. There are PPAs but they are unofficial and suspect.

I hope someone can create an official PPA for Ubuntu.

**Comment by Skif-off** [comment]
OBS is more practical, because not only Ubuntu: http://doublecmd.github.io/doc/en/faq.html#repo
Link to Qt5-alpha with small mistake and will be fixed later, use [this link](https://software.opensuse.org/download.html?project=home:Alexx2000:doublecmd-svn&package=doublecmd-qt).

**Comment by lonix1** [comment]
What is "OBS" ?

**Comment by alexx2000** [comment]
[openSUSE Build Service](https://build.opensuse.org/)

**Comment by lonix1** [comment]
Thanks. I'll look into that. Never heard of it, I learned something new.

I'm gonna close, but keep in mind ubuntu is (probably?) the most popular distro for desktop users, so having a PPA would be useful.

**Comment by KaKi87** [comment]
Hi,
It would be nice to mention the existence of this in the README.
Thanks

**Comment by alexx2000** [comment]
Hi, it is at official [download page](https://sourceforge.net/p/doublecmd/wiki/Download/).

**Comment by KaKi87** [comment]
I didn't see it there either, but after reading the link column instead of the description column, I found *Install from openSUSE Build Service* indeed, then I'd like to suggest adding *APT repository* below *DEB packages*.
Thanks
