### ISSUE TITLE
aarch64 (ARMv8) Portable package

### ISSUE THREAD

**Issue by 5A52** [doublecmd/doublecmd#1036]
### Description

Is it possible to add ARMv8 Portable package?
I know I can download from some debian repos, but in [termux](https://wiki.termux.com/wiki/Package_Management) I can use it only in proot\chroot debian environment. But not in termux itself.
Thank you

**Comment by alexx2000** [comment]
Technically I can add it. But it does not help in your case because it will be a Linux portable package.

**Comment by 5A52** [comment]
I really wish to make it work in termux, but even if not in termux , there are a lot of linux desktop ready ARM SBCs.

**Comment by alexx2000** [comment]
[Added](https://sourceforge.net/p/doublecmd/wiki/Download).
