### ISSUE TITLE
one crash on startup, during showing of the splash screen

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1037]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.2 LTS

Widgetset library: GTK 2.24.33

### Description

In Ubuntu, I pressed Ctrl+Alt+C hotkey to run DC. it shows the splash screen and crashes during it.

```

--------------- 07-07-2023, 17:02:25 ---------------
| DC v1.0.10 Rev. 239 -- x86_64-Linux-gtk2
| Ubuntu 22.04.2 LTS -- GTK 2.24.33 | PID 153398
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $000000000042CB7D in /home/user/doublecmd/doublecmd
  $00000000004E7177 line 77, column 3 of include/customform.inc in /home/user/doublecmd/doublecmd
  $000000000051D2F6 line 2847, column 3 of fmain.pas in /home/user/doublecmd/doublecmd
```

this is doublecmd.err .

**Comment by alexx2000** [comment]
No way to reproduce, stack trace does not contain useful info.
