### ISSUE TITLE
Hotkey labels from Keys show up in toolbar hover info tags

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1044]
### Version

Double Commander
Version: 1.1.0 Alpha - Linux gtk Appimage

### Description

If you create hotkeys in the Options - Keys section, when you assign a hotkey to a command, if you create a toolbar icon for that same tool, its hotkey will show up in the info tags at the end inside "(hotkey)" when hover your mouse over the button.
This may be on purpose, but not sure?
If you then assign a different hotkey to the actual button (in Options - Toolbars section)
then that hotkey shows up in the hover tag as well    (hotkey) (hotkey).

As mentioned not sure if this is on purpose or not, but where this could get tricky is when using the "cm_ExecuteScript".
If you assign a hotkey in the Options - Keys section to a custom command using this "cm_ExecuteScript" and then you also create a completely different custom command using the "cm_ExecuteScript" as a toolbar button, the custom Keys versions hotkey shows up in the hover tag, even though it has nothing to do with that toolbars command.

Hopefully I am making sense, kind of hard to explain.
Any questions please let me know.
Thank You

**Comment by alexx2000** [comment]
Now DC shows hotkey in the hint when it really execute a same action.
