### ISSUE TITLE
[MacOS] hidden files and folders don't seen on NTFS volumes

### ISSUE THREAD

**Issue by Corsten56** [doublecmd/doublecmd#1046]
### Version

DC 1.1.0 alpha
rev. 10814
commit f2d30ecce
build 2023/07/15
Lazarus 3.99.0.0
FPC 3.2.2
Platform: aarch64-Darwin-cocoa
MacOS Ventura 13.4.1 (c)
Apple Silicon M2

### Description

Hello.

I'm using Hasleo NTFS for Mac Free v4.8 for mounting NTFS volumes.
Even when I use "Show Hidden/System Files" option Double Commander doesn't show any hidden NTFS files.
So when I delete files they goes to ".Trashed" folder that seen only in Windows.
Also DC don't shows ".fsevents" and "System Volume Information" folders.
It is possible to fix it?

Best regards.

**Comment by rich2014** [comment]
@alexx2000

Alex, do you have any ideas?

**Comment by Kolcha** [comment]
DC perfectly shows any "dot files" if hidden files are enabled. if you able to see hidden files everywhere except your NTFS drive, very likely the issue in the driver itself - it just doesn't report some things (intentionally or not, who knows).
this is like new NTFS3 driver in Linux kernel - by default (without special mount options) it doesn't show files/folders hidden on Windows. and DC can't do anything here, that's how FS works.
never heard about Hasleo NTFS, used Tuxera for all time, and everything was visible with it (don't know how it is now, as so as don't use mac for personal use neither have any NTFS drives anymore).

**Comment by alexx2000** [comment]
I see only one solution: install this driver and debug.

**Comment by rich2014** [comment]
@alexx2000 

i mainly refer to the design of DC.

the current design of DC is to determine the method of system/hidden files according to the target system at compile time. instead of determining themethod of system/hidden files according to the file system at runtime.

then DC compiled for MacOS, for all file systems including NTFS, will only use whether the file name starts with '.' to determine whether it is a system/hidden file.

**Comment by rich2014** [comment]
@Corsten56 

can hidden files in this NTFS volume be seen in MacOS Finder?

**Comment by alexx2000** [comment]
And in the Terminal, by command `ls -la`.

**Comment by Corsten56** [comment]
Will check it later, thanks.

**Comment by Kolcha** [comment]
out of curiosity I decided to try mentioned driver (fortunately I have 2 MacBooks from different offices), so there is conclusion:

- driver doesn't show hidden files, so Double Commander can't do anything here

driver is FUSE-based (expected, this was the only option for Linux until NTFS3 in 5.15), running on top of macFUSE.

here is mount output (the first line) and and `ls -l(a)` output from macOS:
```
# mount output
/dev/disk4s1 on /Volumes/disk4s1 (macfuse, local, nodev, nosuid, synchronous)

╭─nickkaratysh@Nicks-Laptop ~
╰─% ls -l /Volumes/disk4s1
total 0
drwxrwxrwx  1 nickkaratysh  staff  0 Aug 15 21:45 normal
-rwxrwxrwx  1 nickkaratysh  staff  0 Aug 15 21:45 normal.txt
╭─nickkaratysh@Nicks-Laptop ~
╰─% ls -la /Volumes/disk4s1
total 8
drwxrwxrwx@ 1 nickkaratysh  staff  4096 Aug 15 21:57 .
drwxr-xr-x  4 root          wheel   128 Aug 15 21:57 ..
drwxrwxrwx  1 nickkaratysh  staff     0 Aug 15 21:45 normal
-rwxrwxrwx  1 nickkaratysh  staff     0 Aug 15 21:45 normal.txt
╭─nickkaratysh@Nicks-Laptop ~
╰─%
```

and from Linux, using the same disk device (old 16GB USB flash drive) for comparison:
```
# mount output
/dev/sda1 on /run/media/nick/2C631C1C4FEFA40F type ntfs3 (rw,nosuid,nodev,relatime,uid=1000,gid=1000,discard,sparse,windows_names,iocharset=utf8,prealloc,uhelper=udisks2)

╭─nick@redmi ~
╰─$ ls -l /run/media/nick/2C631C1C4FEFA40F/
total 0
drwxr-xr-x 1 nick nick 0 Aug 15 21:45 hidden
-rwxr-xr-x 1 nick nick 0 Aug 15 21:45 hidden.txt
drwxr-xr-x 1 nick nick 0 Aug 15 21:45 normal
-rwxr-xr-x 1 nick nick 0 Aug 15 21:45 normal.txt
╭─nick@redmi ~
╰─$ ls -la /run/media/nick/2C631C1C4FEFA40F/
total 4
drwxrwxrwx  1 nick nick 4096 Aug 15 21:45 .
drwxr-x---+ 3 root root   60 Aug 15 21:47 ..
drwxr-xr-x  1 nick nick    0 Aug 15 21:45 hidden
-rwxr-xr-x  1 nick nick    0 Aug 15 21:45 hidden.txt
drwxr-xr-x  1 nick nick    0 Aug 15 21:45 normal
-rwxr-xr-x  1 nick nick    0 Aug 15 21:45 normal.txt
╭─nick@redmi ~
╰─$
```

notice "hidden" file and folder in the listing above (they are missed in output from macOS).

P.S> Double Commander didn't recognize partition mounted by that driver as "disk device", and it didn't appear in drives list. the first "mount option" (`macfuse`) in `mount` output seems to be FS type (other partitions have the same pattern). NTFS partition mounted by built-in driver (read-only access) is recognized.
