### ISSUE TITLE
Dark Mode Setting by user supported on MacOS

### ISSUE THREAD

**Issue by rich2014** [doublecmd/doublecmd#1050]
on MacOS, DC supports dark mode with System Setting only.

it's not supported setting in Colors Dialog by user.

it's supported from r10844.

**Comment by rich2014** [comment]
<img width="569" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/5a979976-4d94-4126-a608-55ab5d62935d">

<img width="570" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/8de3f1bb-ebbc-438e-875e-62e9cfd247b0">

<img width="523" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/7f25ee4c-fefb-4009-bbbd-ac3260922b7f">

<img width="518" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/eeff2520-6578-4d9e-80f8-add144b51063">

**Comment by maxpozdeev** [comment]
Hi! After this patch I can not compile doublecmd on Mac (macOS 12.6.7 with M1)
```
... src/./platform/unix/darwin/umydarwin.pas(155,50) Error: (5000) Identifier not found "NSSTR_DARK_NAME"
umydarwin.pas(425) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
```

```
$ lazbuild --version
2.2.6
$ fpc
Free Pascal Compiler version 3.2.2 [2021/05/16] for aarch64
```

**Comment by alexx2000** [comment]
Hi, you need Lazarus 3.0 or Lazarus 3.99. Lazarus 2.2.6 has many bugs under macOS so we use latest Lazarus development version.

**Comment by maxpozdeev** [comment]
I see, thanks. 
Maybe add a note about this to docs?

**Comment by alexx2000** [comment]
Done.
