### ISSUE TITLE
Feature request - Sort order in search results

### ISSUE THREAD

**Issue by bitkleberAST** [doublecmd/doublecmd#108]
When searching for files the search result is shown as unsorted list.
Having a folder "Documents" that contains one subfolder per year and all the files within these folders start with date reversed (i.e. "yy-MM-dd ...").
When searching for a file whose name contains "canada" I am presented about 25 matches, but these are neither sorted by their folder nor by their filename which makes it cumbersome to find the latest file.

**Comment by JonnyTech** [comment]
In search results, click `feed to listbox` button, then you can sort or manipulate results as required.

**Comment by bitkleberAST** [comment]
Thanks! That was helpful :)
