### ISSUE TITLE
Terminal does not open on macOS Catalina and newer

### ISSUE THREAD

**Issue by inelisoni** [doublecmd/doublecmd#111]
Terminal does not open on macOS Catalina and newer. This happened because application was moved from _/Applications/Utilities/Terminal.app_ to _/System/Applications/Utilities/Terminal.app_

Double Commander 0.9.10 beta
Revision: 9640
Build: 2021/01/10
Lazarus: 2.0.3.0-61194
Free Pascal: 3.0.4
Platform: x86_64-Darwin-qt4
System: Mac OS X 10.16.0
Widgetset library: Qt 4.8.6, libQt4Pas 4.5.3

**Comment by yshinkarev** [comment]
Maybe helpfull. I use iterm2 and have no problems.
Try my way.
Command: /Applications/iTerm.app
Parameters: %D

**Comment by czosnkowy666** [comment]
It is working as expected on Monterey with DC 1.1.0 
Settings in DC says 
Command: `%COMMANDER_PATH%/scripts/terminal.sh`
Parameters: `'{command}'`

**Comment by inelisoni** [comment]
I just open terminal without any args. But I found that I can change the path to the terminal in the settings, so it's not such a big problem.
