### ISSUE TITLE
edit path with double click + alternate row colors options

### ISSUE THREAD

**Issue by eadmaster** [doublecmd/doublecmd#116]
i'd like to suggest 2 features i am missing from totalcmd i could not find in v0.9.10:

1. edit the path with double click instead of a right click;
2. ~~alternate row colors in the file panels ([shot](https://i.imgur.com/5r6EFzD.png))~~

**Comment by ags1234** [comment]
Being able to edit the path bar with a right click is something I have grown to like in DC. And I use this function a lot, for network paths. It is a great idea and it is much faster than double click. Twice as fast, in fact :))

**Comment by eadmaster** [comment]
> Being able to edit the path bar with a right click is something I have grown to like in DC. And I use this function a lot, for network paths. It is a great idea and it is much faster than double click. Twice as fast, in fact :))

I understand some users may prefer the current behavior, so maybe this could be added as an option?

**Comment by JonnyTech** [comment]
> 2. alternate row colors in the file panels

Menu >> Configuration >> Options >> Colours >> File Panels >> Background 2

![dc-nq8](https://user-images.githubusercontent.com/3584732/122843231-e32b8500-d2f6-11eb-9dd3-81209eb6c10d.png)

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/commit/a8a855d7f38327d40f929dff63dd21e58acff7b4
