### ISSUE TITLE
Directory not updated after deleting item.

### ISSUE THREAD

**Issue by amnond** [doublecmd/doublecmd#1182]
### Version

Double Commander
Version: 1.1.0 beta
Revision: 10668
Commit: d074d08ef
Build date: 2023/04/02
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.4.1

### Description

**Occurs on:**
macOS
Apple M1 Pro, 16 GB 
Ventura 13.4.1 (22F82)

**Problem description:**
When deleting a file or directory using F8 or Shift-F8, the directory needs to be refreshed in order to see that the file or directory has indeed been deleted.

**Comment by alexx2000** [comment]
Try with latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by sefernet** [comment]
Also check this setting : 

Configuration > Options > Auto refresh > Refresh - When ...

Regards

**Comment by sefernet** [comment]
Paradoxically, unchecking everything (the opposite I commented before) makes it work as should be ...
