### ISSUE TITLE
Active panel changed on ESC (macos)

### ISSUE THREAD

**Issue by exidler** [doublecmd/doublecmd#1184]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10869
Commit: 185c43787
Build date: 2023/07/31
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.4.1

### Description

1. Run DC, 
2. Entner something for QuickFilter, ESC to close the panel,
3. Switch active panel and press ESC again
4. Active panel changed to previous

If activate/deactivate QuickFilter in another panel - no more problems until app restart

Quick digging shows to me, btnCancelClick() called when on ESC when the QuickFilter panel already hidden. 
But when shown only in one panel during app session.

tried in Windows build (stable, latest snapshot) - no problems
tried Macos latest stable build - problem persist

**Comment by rich2014** [comment]
fixed by 889d3c705ad3337f71fe7942de18347216159453.

tested on MacOS, Windows, Linux.
