### ISSUE TITLE
File list columns header appearance changed (MacOS) 

### ISSUE THREAD

**Issue by exidler** [doublecmd/doublecmd#1187]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10877
Commit: 13f9a14f4
Build date: 2023/08/02
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.4.1

### Description

Switch to 'Full' mode files list
Navigate to root dir (/)
Type anything for a Quick Filter

Headers appearance changed and look does not restored until restart
(taller and extra space after header) 

<img width="728" alt="Screenshot 2023-08-03 at 17 31 07" src="https://github.com/doublecmd/doublecmd/assets/4411993/a76fd888-091b-470f-80cf-0526e3dc6175">
<img width="724" alt="Screenshot 2023-08-03 at 17 31 22" src="https://github.com/doublecmd/doublecmd/assets/4411993/ff9ee052-b930-44f8-a5ab-5a9567380318">

PS: idk, but sort by extension does not show arrow in header too (instead arrow displayed on Name column).

**Comment by rich2014** [comment]
fixed by 623358eb142bd8f9f9cf20ce8feadf5d17c0a44e.

it's caused by wrong height of Header in empty TColumnsFileView.

all platform affected.
