### ISSUE TITLE
[Combine Files / Linker]: combining to file with one of the part's full name fails with deleting this part

### ISSUE THREAD

**Issue by PetbkA** [doublecmd/doublecmd#1198]
### Version

Double Commander
Version: **1.1.0 beta**
Revision: 32
Commit: **cd3a69c65**
Build date: 2023/08/05
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: **x86_64-Win64-win32/win64**
OS version: **Windows 10 Home 22H2 x86_64**

### Description

I guess it appeared after #800:
1. Select two files you want to combine (e.g. _Part1.log_ and _Part2.log_) and call _Files → Combine Files..._
2. In _Linker_ dialog enter _full_ name or _full_ path to the same folder of one of the part's name to _File name_ field (e.g._ `Part1.log`) - **NOK**:
    1. Error _cannot open existing file_ is being raised;
    2. Failes aren't being combined;
    3. File with name entered in step 2 is being deleted.

Here's the [video](https://github.com/doublecmd/doublecmd/assets/22843816/8fbce110-53f6-4d5f-8681-66bf39871d49)

**Comment by alexx2000** [comment]
As I say in #800:

> Combine files to the filename which equal to one of the part's name - function not supported.

It is need to show error message in this case.

**Comment by PetbkA** [comment]
@alexx2000 , I remember it, but this issue is about *deleting* one of the parts. I thought it'll be better having it separated.

And technically the error is already being showed, but I guess by "show the error message" you meant showing *before* some combine action will start at all

**Comment by alexx2000** [comment]
>  you meant showing before some combine action will start at all

Yes

**Comment by PetbkA** [comment]
**1.1.1 beta (Revision 54 Commit ae331340e)** - fixed: now trying to combine in one of the parts ends with
> You can not copy/move a file "<Path>" to itself!
