### ISSUE TITLE
Very slow files copy to NFS share

### ISSUE THREAD

**Issue by michcior2** [doublecmd/doublecmd#12]
Hi!

I have mounted NFS share from NAS (D-Link D320L) (on Linux Ubuntu). The DC is copying a file very slow. Once copying is started, the file on NFS is created, but then the dialog shows 0/0 progress for about  40sec!!! Actually it hangs, since even cancel is effective after 40sec! It is for each file copied. Any other tools in my system, copy files with expected speed: cp/mc/Nautilius etc.
The NFS is mounted with flags: rw,hard,intr
DC:0.9.6 

Thanks in advance for your help 
Regards, 
Piotr

**Comment by SamSpiri** [comment]
In my case I changed my mount options to solve the issue
was: nfsvers=3,proto=tcp,resvport
now: nfsvers=4,proto=tcp,resvport,noatime,async

**Comment by alexx2000** [comment]
#308
