### ISSUE TITLE
Allow rename files inside 7z archives

### ISSUE THREAD

**Issue by r0polach** [doublecmd/doublecmd#1215]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

It would be nice if files inside 7zip archives can be renamed without repacking
the archive. Double Commander 1.0.11 does not support this but e.g. 7zip GUI
(for Windows) can rename files inside 7z archives without repacking.

**Comment by ags1234** [comment]
+1

**Comment by PetbkA** [comment]
@r0polach @ags1234 
It's rather FR than a bug, please see and vote for #1192
