### ISSUE TITLE
Certain option menus have dark background and black text

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1224]
### Version

Double Commander
1.2.0 gtk Alpha Appimage

### Description

If you have dark background menu bars / context menus / etc.
I noticed that in Options - Colors any of the drop down menus that allow you to select colors all contain black font color which can make it difficult to see when backgrounds are dark.  The mouse highlight works for now because then the text shows up white and is also highlighted.

I know this could be considered an issue with color choice of desktop environment but all the other drop down menus provide white text with black backgrounds.  I looked through quite a few drop downs in options, all others seem to work fine.

Hope this helps
Thank You

**Comment by alexx2000** [comment]
It depends on the GTK2 theme. Looks like your GTK2 theme has some invalid color. [No problem](https://imgur.com/PN2gZN3.png) with Yaru-dark theme.

**Comment by advice2020** [comment]
@alexx2000
Thank you for your response.
I will mess around with some themes, but....
The strange thing is though is that as mentioned it is only those couple of drop downs, all the other drop downs in options are fine with white text and black background.  Wouldn't all the drop downs be using the same coding / wouldn't you want them to be?
You would know how the coding works, obviously I do not, but just curious that they aren't all the same.
Again I will look what themes I have available.
