### ISSUE TITLE
Sync MTP - error copy file

### ISSUE THREAD

**Issue by git-tiger** [doublecmd/doublecmd#1227]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

I have my android tablet connected using MediaAudio2 plugin, and it is connected using MTP.
Perform a sync command, and view the differences in files/folders.
When start the synchronization, it errors with a pop-up, saying "Error: Copy file c:\... -> \tab\...".

**Comment by git-tiger** [comment]
Also, if I do a copy panel to panel, it works. 
Found a second bug, is that the copied file on the MTP is now today's date and not the original date.
This will cause problem when synchronizing using dates.

**Comment by alexx2000** [comment]
> Found a second bug, is that the copied file on the MTP is now today's date and not the original date.

No DC bug here, many MTP-devices does not support file time changing. Anyway DC calls [FsSetTime](https://ghisler.github.io/WFX-SDK/fssettime.htm) plugin function, the rest depends on the plugin implementation.
