### ISSUE TITLE
can not extract file.7z.zip

### ISSUE THREAD

**Issue by ivysrono** [doublecmd/doublecmd#1234]
### Version

Double Commander
Version: 1.1.1 beta
Revision: 54
Commit: ae331340e
Build date: 2023/08/19
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

### Description

Files from https://github.com/wmjordan/PDFPatcher/issues/2

Alt+F9：
```
[Error]

Archive format unknown

[OK]
```

**Comment by JonnyTech** [comment]
The files there are 7z archives, not zip ones:

Download https://github.com/wmjordan/PDFPatcher/files/11868350/PDFPatcher.1.0.0.4187.7z.zip
Rename `PDFPatcher.1.0.0.4187.7z.zip` to `PDFPatcher.1.0.0.4187.7z`
DC extracts it correctly

**Comment by alexx2000** [comment]
DC determine archive type by extension at first and by content at second. While 7-Zip determine it by content.

**Comment by j2969719** [comment]
and? dc for processing zip has the zip.wcx plugin registered by default, which for obvious reasons will not be able to open the wrong archive format that is not implemented in it.  if you register 7zip as a zip handler in the settings (since 7zip can also work with zip archives), then you can open such incorrect archives in the same way.  you can also open arbitrary files as archives using the ctrl+pgdn hotkey

**Comment by alexx2000** [comment]
I can change the order and determine archive type by content first, but this method has its drawbacks.

**Comment by j2969719** [comment]
you mean by pressing enter?  dont think this is a good idea since a lot of formats like docx/odt/jar etc are essentially zip archives, not to mention the possible false positives of multiarc or multi-format plugins when they are at the top of the list in the settings

**Comment by j2969719** [comment]
btw, is it possible to implement an internal command or hotkey that would keep looking for a registered handler for an archive, even if some handler has already been found?

**Comment by alexx2000** [comment]
> you mean by pressing enter?

No, only by Alt+F9 (cm_ExtractFiles).

> not to mention the possible false positives of multiarc or multi-format plugins when they are at the top of the list in the settings

That's why I said about drawbacks.

> even if some handler has already been found?

How it will help? It is a too difficult at first glance. It's easier not to change anything.

**Comment by Skif-off** [comment]
> It's easier not to change anything.

True. The wrong extension is a error, but FM is not required to resolve all possible error cases "on the fly". It is impossible to foresee all problems.

Maybe try something like [checkfileextwdx.lua](https://github.com/j2969719/doublecmd-plugins/blob/master/plugins/wdx/scripts/checkfileextwdx.lua)? (I will try to add 7-Zip.)
