### ISSUE TITLE
23.04 repo

### ISSUE THREAD

**Issue by pwn0r** [doublecmd/doublecmd#1237]
### Version

Doublecmd 1.0.11
ubuntu 23.04

### Description

please fix 23.04 repo.  Currently specifically 23.04 appears not working

`GPG error: http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_23.04  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 61508B60C33A8925`

22.04 ubuntu (different VM) updates as expected.

**Comment by alexx2000** [comment]
Looks like you did not install the public key. What happens when you execute the public key install command:

`curl -fsSL https://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_23.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_Alexx2000.gpg > /dev/null`
