### ISSUE TITLE
Wrong En text

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1240]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

![Screenshot from 2023-08-23 16-07-45](https://github.com/doublecmd/doublecmd/assets/4154978/d95847ab-9f9e-4a52-9907-b9f445f93200)

'The two files' i guess is not correct english. we need 'Two files'.

**Comment by JonnyTech** [comment]
I am a native English speaker, and I would always use "the two files" since it relates to specific items. Maybe better would be "the two selected files" or "the selected files".

**Comment by Alexey-T** [comment]
OK, sorry
