### ISSUE TITLE
Wrong text selection position in text viewer

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1241]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

- Make text file with 3 lines. DO NOT add LINEBREAK to the last line
- Open this text file in internal viewer.
- Try to mouse-select from the empty place (below last line 3) to the begin of line 3
---> wrong selection

![Screenshot from 2023-08-23 18-16-45](https://github.com/doublecmd/doublecmd/assets/4154978/537f5e42-27c1-4288-99e2-cf49f00dad11)

**Comment by alexx2000** [comment]
I don't think that it is a problem. Many text editors works similarly.

**Comment by Alexey-T** [comment]
sorry but no. all text editors should select from the ending of the last line, if screen coordinate (clicked) is after the last line.

**Comment by alexx2000** [comment]
It's debatable, Lazarus, KWrite, Notepad works similarly.

**Comment by Alexey-T** [comment]
@user4martin I confirm the same issue in Lazarus IDE (i never seen it before because in Pascal files last line has EOL.) Can you fix it?

**Comment by User4martin** [comment]
IMHO clicking below the end of text (below the last line) can have (at least) 4 equally expected actions.
1) do nothing
2) set caret in the last line, at the x-pos of the click (appears current behaviour)
3) set caret in the last line, at the end of that line.
If the line is longer than the visible space, clicking below the end of text would (probably unexpectedly) scroll horizontally.
To avoid such scroll 1 or 2 seem to me more appropriate.

4) Allow the caret on lines that are past the end of text. (virtual lines)
This would have to be optional, but would solve the issue

----

One may suggest 5) act depending on the click being a selection or not. But then the click may not have the shift key, it may be getting pressed once the mouse button is down - and having the caret jumping around on pressing/releasing shift - I think better not. 
Making the rule more complex => equals making it unpredictable to the average user....

----

Vaguely related to: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40399

Out of interest (comments to be left on the SynEdit issue) which existing Editors have different behaviour and how do they behave?
- for partially visible line (except if they set the caret in the partial visible line, which is already mentioned) 
- for clicks below the end of text (virtual/none-existing lines)

**Comment by Alexey-T** [comment]
@User4martin I would recomment to repeat the behaviour of CudaText - which in turn repeats the behaviour of Sublime Text AFAIR.
