### ISSUE TITLE
Text viewer: on scrolling up/down, it doesn't render last visible line

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#125]
Video shows the bug. on the bottom of viewer, we have empty space where DC __can render some text__ but it is still empty space.
[Kazam_00000.zip](https://github.com/doublecmd/doublecmd/files/6731826/Kazam_00000.zip)

Double Commander
Version: 0.9.10 beta
Revision: 9640
Build date: 2021/01/10
Lazarus: 2.0.8.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.2 LTS

Widgetset library: GTK 2.24.32

**Comment by alexx2000** [comment]
#652
