### ISSUE TITLE
Position range overflow

### ISSUE THREAD

**Issue by vnt-83** [doublecmd/doublecmd#1251]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/05/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Manjaro Linux

Widgetset library: Qt 5.15.10, libQt5Pas 5.6.1

### Description

Здравствуйте. Тут баг-трекер?

Программа просто была открыта. Отошёл на время, за это время экран заблокировался. Ввёл пароль и увидел это сообщение. После нажатия "Пропустить" остался белый экран, пришлось перезапустить программу.

Система:
Manjaro с ядром 6.5
KDE 5.27.7

Заглянул в файл, оказывается, вчера тоже такая ошибка была. Но я такого окна до этого не видел, только сегодня. Это точно.

```
--------------- 01-09-2023, 18:09:24 ---------------
| DC v1.0.11 Rev. 272 -- x86_64-Linux-qt5
| Manjaro Linux -- Qt 5.15.10, libQt5Pas 5.6.1 | PID 4751
Unhandled exception: ELayoutException: Position range overflow in pnlKeys.SendMoveSizeMessages: Left=0, Top=65455.
  Stack trace:
  $00000000005C1BDE
  $00000000005CE66F
  $00000000005DB69E
  $00000000005BED87
  $00000000005BE3DC
  $00000000005BDE9B
  $00000000004B4633
  $00000000005C6A62
  $00000000005D40C6
  $00000000005D3E14
  $00000000005BFEB1
  $00000000005DC01E
  $00000000005CAC2C
  $00000000005C8034
  $00000000004B4A41
  $00000000004B80C6
  $00000000004EF3F9

--------------- 02-09-2023, 17:48:05 ---------------
| DC v1.0.11 Rev. 272 -- x86_64-Linux-qt5
| Manjaro Linux -- Qt 5.15.10, libQt5Pas 5.6.1 | PID 2000
Unhandled exception: ELayoutException: Position range overflow in pnlKeys.SendMoveSizeMessages: Left=0, Top=65455.
  Stack trace:
  $00000000005C1BDE
  $00000000005CE66F
  $00000000005DB69E
  $00000000005BED87
  $00000000005BE3DC
  $00000000005BDE9B
  $00000000004B4633
  $00000000005C6A62
  $00000000005D40C6
  $00000000005D3E14
  $00000000005BFEB1
  $00000000005DC01E
  $00000000005CAC2C
  $00000000005C8034
  $00000000004B4A41
  $00000000004B80C6
  $00000000004EF3F9
```

[doublecmd.err.zip](https://github.com/doublecmd/doublecmd/files/12504204/doublecmd.err.zip)

![Screenshot_20230902_175318](https://github.com/doublecmd/doublecmd/assets/16693651/988df0c1-a701-4dd1-80b3-f97c7074411d)

![Screenshot_20230902_175217](https://github.com/doublecmd/doublecmd/assets/16693651/610d1131-34c5-46d2-a063-72f680ad869e)

**Comment by alexx2000** [comment]
#736
