### ISSUE TITLE
Folder sync comparison 'by content' improvement

### ISSUE THREAD

**Issue by drws** [doublecmd/doublecmd#1253]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba38
Build date: 2023/05/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Arch Linux

### Description

When two folders are compared for sync and _by content_ is selected and _ignore date_ is not selected there is a possible optimization that greatly improves comparison speed. The contents of files with differing metadata (sizes and times) don't need to be read at all since they will be marked different anyway.

**Comment by alexx2000** [comment]
DC does not compare files with different metadata.
