### ISSUE TITLE
Problems with zip archive.

### ISSUE THREAD

**Issue by watzib** [doublecmd/doublecmd#1254]
### Version

Double Commander
Version: 1.1.1 beta
Revision: 54
Commit: ae331340e
Build date: 2023/08/19
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

1. When open zip archive (key Enter) and switch on quick view (CTRL+Q), keys of cursor (Up, Down) don`t work (you can move on second file only by mouse).
2. If zip archive packed with password, to open each file in archive I need to write a password. I think it`s good to enter password only once, when open first file in archive.

**Comment by alexx2000** [comment]
1. It is not a zip specific problem, fixed.
