### ISSUE TITLE
[MacOS] Auto refresh of file list does not work on internal SSD drive

### ISSUE THREAD

**Issue by msone** [doublecmd/doublecmd#1258]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10913
Commit: b2129d779
Build date: 2023/09/03
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.5.1

### Description

Under macOS 13.5.1 the auto refresh of file lists does not work if the directory is located on the internal SSD. On external SSD the auto refresh works as expected. The [corresponding options](https://data.littlecompany.de/misc/2023-09-01_08-00-13.png) in the configuration are set.

**Comment by rich2014** [comment]
I'll check it later.

on your system, did AutoRefresh ever work properly with older DC versions?

**Comment by rich2014** [comment]
@msone 

i tested on MacOS 13.5.2 and 12.6.8, it works fine on both.

can you provide further details, or screenshots, or screen recordings?

**Comment by msone** [comment]
I was just about to record a video, but now everything works for me as it should. I had done a reboot in between, maybe that made it work now?

**Comment by rich2014** [comment]
ok, let's see.

**Comment by rich2014** [comment]
should it be closed?

**Comment by msone** [comment]
Yes
