### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by rkhl01** [doublecmd/doublecmd#1262]
### Version

 1.1.2.beta

### Description

If I edit a file, e.g. txt, when sorting by date, sorting does not occur automatically after editing. I have to press the Auto Refresh button.

**Comment by rich2014** [comment]
@alexx2000 

is this a feature or an issue?

**Comment by rkhl01** [comment]
Issue.

**Comment by alexx2000** [comment]
It depends on which [sorting settings](http://doublecmd.github.io/doc/en/configuration.html#ConfigView)  do you use. What setting do you have for `Insert new files` and `Move updated files`?

**Comment by rkhl01** [comment]
Thank you, it helped Move updated files: To sorted position.
