### ISSUE TITLE
text viewer scrolling by arrow up/down is broken

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1267]
### Version

Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

Open a text file and try to scroll it by arrow-down. When 'Show text cursor' is off.
you see it works like WITH cursor On. ie, first 20 keypresses are ignored and only then file scrolls.

![Screenshot from 2023-09-16 18-45-54](https://github.com/doublecmd/doublecmd/assets/4154978/f2c4a1dc-6be8-4e96-b510-b0c57738001e)

**Comment by Skif-off** [comment]
I.e. in the Code mode,  right? Does SynEdit support this?

**Comment by Alexey-T** [comment]
yes, in the 'code mode'.
