### ISSUE TITLE
Can't control after skip overwrite in Multi-Rename tool

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#1274]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10923
Commit: d98d27d83
Build date: 2023/09/14
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.15.7

## Steps to reproduce:
1. Create `1.txt` and `1.txt-` in the same dir
2. Select `1.txt` and open `Multi-Rename tool`
3. Set `Extension` to `[E]-` (now `1.txt` have to be renamed to existing `1.txt-`)
4. Click `Rename`
5. In "confirm overwrite" dialog click `Skip`
6. Close `Multi-Rename tool` using `Esc` key or `Close` button

## Expected:
DC returns to panels and controllable

## Actual behavior:
DC reacts with "beep" to every keypress, doesn't react to mouse clicks. Menu (macos) contain only "Double Commander" item, which allows only Quit. Also Quit hotkey works fine, DC handles it and shows confirmation dialog. But I cannot do anything else in this state.

**Comment by rich2014** [comment]
maybe a bug in Lazarus. I'll check it later.

**Comment by rich2014** [comment]
@zxcat

it's a bug of DC.

fixed by c2d947b

check the 10932 snapshoot please.

**Comment by rich2014** [comment]
@alexx2000  hi, Alex

the issue has been fixed.

however, i found that DC re-implemented ShowModal() in uOSForms.

what is the purpose of this? i'm not sure it's necessary.

**Comment by alexx2000** [comment]
It's necessary:
1. It is used to show modal progress dialog for file operations which executing in the main thread.
2. Also it is used as modal form which block only parent window.

I don't sure that this fix is correct. I guess it will broke other widgetsets.

**Comment by alexx2000** [comment]
Yes, as I thought it broken other widgetsets. So I made it Cocoa only.

**Comment by zxcat** [comment]
> check the 10932 snapshoot please.

@rich2014 
Works fine for me. Thank you!
