### ISSUE TITLE
Key F3 opens a first marked file instead selected.

### ISSUE THREAD

**Issue by av1981** [doublecmd/doublecmd#1276]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H2 x86_64

### Description

Key F3 opens a first marked file (by INS key) instead selected (under cursor).

**Comment by alexx2000** [comment]
Not a bug, it is by design.

**Comment by av1981** [comment]
How to change this behavior? Is any option in config?

**Comment by alexx2000** [comment]
No. It has been discussed many times. But the decision was never made.
