### ISSUE TITLE
[macos] Sorting files/folders ignores Case sensitivity on Cyrillic names

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#1277]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10923
Commit: d98d27d83
Build date: 2023/09/14
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.15.7

### Description

Tried every combination of "Sort method" and "Case sensitivity" options, but Uppercased names keep placed before Lowercased.

| Double Commander | Finder |
|--------|--------|
| ![DC-sort](https://github.com/doublecmd/doublecmd/assets/550974/dde38836-6ce6-483c-b4c4-293325265d99) | ![Finder sort](https://github.com/doublecmd/doublecmd/assets/550974/d9889df1-6404-431f-9dfc-22aefdce8a1f) |

**Comment by alexx2000** [comment]
I guess under macOS we should use [iosxwstr](https://wiki.freepascal.org/FPC_New_Features_3.2.0#New_iosxwstr_unit) unit instead  `cwstring`.
