### ISSUE TITLE
[KDE Plasma 5.27.8] Sorting files/folders ignores Numeric characters at beginning

### ISSUE THREAD

**Issue by kppr0** [doublecmd/doublecmd#1285]
### Version

Version: 1.2.0 alpha
Revision: 10927
Commit: bba5731
Build date: 2023/09/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Manjaro Linux
Widgetset library: Qt 5.15.10, libQt5Pas 5.6.1

### Description

Tried every combination of "Sort method" option, but Numeric characters at beginning are ignored.

<table>
<tr><td><b>Double Commander</b></td><td><b>Dolphin</b></td></tr>
<tr><td><img src="https://github.com/doublecmd/doublecmd/assets/116163807/3a2790d0-ce58-47f3-b7e8-679b88862f9a" width="281" height="246"></td><td><img src="https://github.com/doublecmd/doublecmd/assets/116163807/0c5e5807-4612-481b-933d-2367f6c7593e" width="447" height="431"></td></tr>
</table>

![1](https://github.com/doublecmd/doublecmd/assets/116163807/efa7a1dc-edd8-4ae8-9105-88348d2f0af5)

**Comment by alexx2000** [comment]
Sorting depends on the locale. What locale do you use? 
Execute `locale` and `ls -la` commands in the terminal (in the test directory) and copy output here.

**Comment by kppr0** [comment]
[test]$ locale
LANG=cs_CZ.UTF-8
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_ALL=

[test]$ ls -la
celkem 20
drwxr-xr-x  5 tux tux 4096 22. zář 20.39 .
drwx------ 29 tux tux 4096 22. zář 20.38 ..
drwxr-xr-x  2 tux tux 4096 22. zář 20.39 aa
-rw-r--r--  1 tux tux    0 22. zář 20.39 aa.txt
drwxr-xr-x  2 tux tux 4096 22. zář 20.38 a6
-rw-r--r--  1 tux tux    0 22. zář 20.39 a6.txt
drwxr-xr-x  2 tux tux 4096 22. zář 20.38 6a
-rw-r--r--  1 tux tux    0 22. zář 20.39 6a.txt

**Comment by kppr0** [comment]
sorry, reopen

**Comment by alexx2000** [comment]
It is a `LC_COLLATE="cs_CZ.UTF-8"` locale specific behavior (dolphin ignores locale settings). If you execute DC with different locale, like
```
export LC_COLLATE=C
doublecmd
```
then sorting will be as you want. So no DC bug here.

**Comment by kppr0** [comment]
Sorry and thanks, 

> LC_COLLATE=C

 solved it.
