### ISSUE TITLE
[macos] Drive list auto-hotkeys are case sensitive 

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#1289]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10931
Commit: ce81d4bbd
Build date: 2023/09/23
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.15.7

### Description

Drive list (`Alt+F1`/`Alt+F2`) allows to switch drives quickly using keyboard.
![Drive list](https://github.com/doublecmd/doublecmd/assets/550974/d68bf434-5c01-4ad5-98e6-1524ad156020)
But I had to navigate it using the cursor keys, because simple `W` key wouldn't open `WD_BLK` drive, nor `S` opened `Seagate`. 

For some reason only `T` worked for `toshiba`.
Finally understood the reason: it handles keys in **case sensitive** mode. So `Shift+W` opens `WD_BLK`, not `W`.

After writing all this, I got the idea that this might be a feature rather than a bug.
If so, it would be great to have **some option to toggle case sensitivity** here.

**Comment by zxcat** [comment]
Most likely it's not a feature, because in other similar situations (like `Directory Hotlist`) keys work in case insensitive way

**Comment by alexx2000** [comment]
I think it should be case insensitive under macOS/Windows and case sensitive under other Unix-like systems.

**Comment by rich2014** [comment]
> Maybe it should be case insensitive under macOS/Windows and case sensitive under other Unix-like systems.

completed in 1e38a54

**Comment by lprot** [comment]
@rich2014 tried hot keys on Double Commander
Version: 1.2.0 alpha
Revision: 11551
Commit: 3fc2fa342
Build date: 2024/10/05
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

and it works. So this issue can be closed?

**Comment by rich2014** [comment]
@lprot yes
