### ISSUE TITLE
Wrong display of jpg files in thumbnail mode

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#1290]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10931
Commit: ce81d4bbd
Build date: 2023/09/23
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.6.0

### Description

See screenshot below.

jpg files are not shown correctly in thumbnail mode. The jpg file in the screenshot should be shown like the png file. Both files show the same motif. 

The problem occurs with **any** jpg file.

![Screenshot](https://github.com/doublecmd/doublecmd/assets/79788982/fc9ebc3d-0771-4ce6-b1e7-83a61dca46ad)

**Comment by rich2014** [comment]
it works fine for me.

can you provide a few jpeg sample files?

**Comment by rich2014** [comment]
@Andreas0602 

**Works fine on MacOS 12.6.**


<img width="618" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/8084cc4e-dfb5-4c9c-8b30-ce045ce8e86d">

**Comment by rich2014** [comment]
@alexx2000  hi, Alex, any ideas?

**Comment by alexx2000** [comment]
Hi, no. Theoretically it is a platform independent code. I have no idea why it can work wrong.

**Comment by rich2014** [comment]
@Andreas0602 

1. did the old version of DC ever work properly?

2. did it ever work properly on older versions of MacOS?

**Comment by rich2014** [comment]
@Andreas0602 test 10944 in the snapshoot please.

**Comment by rich2014** [comment]
@alexx2000, i found that there are several Thumbnail Providers on MacOS:

1. in `uJpegThumb`: highest priority before, using `TFPReaderJPEG` in fpc
2. in `uQuickLook`: using system native QuickLook, much faster than `uJpegThumb`

in 7f5efba, i removed `uJpegThumb` on MacOS, and the speed is 3x faster.

**Comment by rich2014** [comment]
@Andreas0602 

1. try disable thumbnails cache in `Options` first
2. delete cache folder
3. restart DC

**Comment by alexx2000** [comment]
Cache should be fixed. Try to open cache image in the DC Viewer and choose a graphics mode: Menu->View->Graphics.

**Comment by alexx2000** [comment]
OK, so standard JPEG reader does not work correctly.

**Comment by rich2014** [comment]
but the thumbnails cache works fine for me.

I tested on MacOS 12.6 and 13.5

**Comment by alexx2000** [comment]
I guess [Andreas0602](https://github.com/Andreas0602) has `libturbojpeg.dylib` library installed. As I see DC works wrong with it under macOS.

**Comment by alexx2000** [comment]
OK, I found that is wrong with `libturbojpeg.dylib` in DC. I will fix it at near time.

**Comment by alexx2000** [comment]
Try with revision 10946 when it will be built.

**Comment by rich2014** [comment]
it's great.
