### ISSUE TITLE
"Print..." menu item of internal viewer is disabled

### ISSUE THREAD

**Issue by nkzmn** [doublecmd/doublecmd#1291]
### Version

Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

1. Open for example any text file in internal viewer (via F3).
2. Observe that viewer's menu item `File` -> `Print...` is disabled, while `Print Options` is enabled.

**Comment by alexx2000** [comment]
Not a bug. It is available only with WLX-plugins which support printing.

**Comment by nkzmn** [comment]
This is not very intuitive.

This menu item is available and works in Total Commander out of the box, so I would expect it to work at least for text files in DC too. It is useful to have an ability to print a text file.

The fact that printing options are always available and at the same time printing menu item is disabled feels like unfinished functionality. At the very least both these menu items should be hidden (not just disabled) when this functionality is not available.

**Comment by alexx2000** [comment]
OK, I hid it.

**Comment by nkzmn** [comment]
Thanks.

Will you accept a feature request to have basic printing functionality (for text files) in internal viewer out of the box?
