### ISSUE TITLE
Программа "зависает" при выполнении операции группового переименования

### ISSUE THREAD

**Issue by Helmir-max** [doublecmd/doublecmd#1292]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10939
Commit: ed02603
Build date: 2023/09/26
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Manjaro Linux

Widgetset library: GTK 2.24.33

### Description

При попытке выполнить операцию группового переименования программа "зависает": я захожу в каталог, выделяю файлы, нажимаю Ctrl+M, появляется окно группового переименования; ввожу условия (найти пробел в имени файла, заменить на нижнее подчеркивание); нажимаю кнопку "Rename"; ничего не происходит, кнопка становится неактивной (см. снимок экрана 1). Я закрываю окно, нажимаю правой кнопкой мыши по каталогу, файлы в котором я пытался переименовать, выбираю "Properties", появлятся окно с сообщением об ошибке (см. снимок экрана 2).

Прикладываю также файл doublecmd.err.
![1](https://github.com/doublecmd/doublecmd/assets/146160606/aafe085c-e21f-4e95-82c8-517abba26d1d)
![2](https://github.com/doublecmd/doublecmd/assets/146160606/8ee60425-6cd2-4b38-8592-f291c0e35098)
[doublecmd.err.txt](https://github.com/doublecmd/doublecmd/files/12734797/doublecmd.err.txt)

**Comment by alexx2000** [comment]
Баг Lazarus в LCLGTK2. Удалось обойти.
