### ISSUE TITLE
loading the same Thumbnails multiple times in TThumbFileView

### ISSUE THREAD

**Issue by rich2014** [doublecmd/doublecmd#1295]
### Version

DC Main Trunk

### Description

in the process of solving #1290, I found that Thumbview has one more serious bug, which will repeatedly call `TFileThumbnailsRetriever.Create()` multiple times for the same files, and all platforms are affected.

the underlying reason is that `TFileThumbnailsRetriever.Create()` is called multiple times quickly, but `TFileThumbnailsRetriever.Execute()` has not yet ended.

direct causes such as:

1. during the creation process of TThumbFileView, `TFileViewWithGrid.DoOnResize()` was called multiple times

2. quickly turn pages in ThumbFileView, especially when using the scroll wheel

If logs are added in TFileThumbnailsRetriever.Create() and TFileThumbnailsRetriever.Execute(), this process can be clearly observed. for example:
```
TFileThumbnailsRetriever.Create()
  1:Pilatus.jpg
  2:Vierwaldstättersee.jpg
  3:Zwölferhorn.jpg
TFileThumbnailsRetriever.Create()
  1:Pilatus.jpg
  2:Vierwaldstättersee.jpg
  3:Zwölferhorn.jpg
TFileThumbnailsRetriever.Create()
  1:Pilatus.jpg
  2:Vierwaldstättersee.jpg
  3:Zwölferhorn.jpg
TFileThumbnailsRetriever.Execute()
  END
TFileThumbnailsRetriever.Execute()
  END
TFileThumbnailsRetriever.Execute()
  END
```

**Comment by rich2014** [comment]
@alexx2000 

could you please check this issue? you should have a better idea to solve it.

**Comment by alexx2000** [comment]
OK, I already fixed similar problem with dynamically loaded file properties. Same solution can be applied here. I will check it.

**Comment by rich2014** [comment]
@alexx2000 @Andreas0602

great, the new version is so many times faster!
