### ISSUE TITLE
[macOS 13/14] Copy/move progress window obscures Overwrite/Skip dialog window

### ISSUE THREAD

**Issue by norbert-wiener** [doublecmd/doublecmd#1298]
### Version

Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.0.0
<img width="520" alt="Double-Commander-1 1 2-71-macos-13-14-file-overwrite-dialog-botch" src="https://github.com/doublecmd/doublecmd/assets/71738573/81db2b27-6df3-498c-8906-8e0b224f9ece">

### Description

On macOS 14.0 Sonoma Intel [also seen on macOS 13.7 Ventura] during a move / copy to an existing destination file of same name, the progress bar window appears directly on top of the confirmation dialog to overwrite / skip / cancel etc. the operation. I do not recall this happening in earlier macOS [Ventura] versions with this DC beta, definitely not with DC daily build versions prior to the beta. Not fatal, but involves more mouse/window move steps to reveal the confirmation dialog and proceed with the file operation[s]. Cheers!

**Comment by rich2014** [comment]
try the snapshoot in https://doublecmd.sourceforge.io/site/eng/snapshots.php please.

**Comment by norbert-wiener** [comment]
Looks to be fixed in 1.1.3-100 beta - Confirmation dialog now appears on top of progress window. Thanks!
