### ISSUE TITLE
App icon size is bigger than normal on MacOS

### ISSUE THREAD

**Issue by wangxuepeng** [doublecmd/doublecmd#1299]
### Version

Double Commander
Version: 1.1.3 beta
Revision: 100
Commit: 42dfbf544
Build date: 2023/10/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.0

### Description

The icon size is bigger than others on MacOS:
![image](https://github.com/doublecmd/doublecmd/assets/4516203/2cfb77be-6a48-4fe3-9e89-f6a88bbe200e)

<img width="382" alt="image" src="https://github.com/doublecmd/doublecmd/assets/4516203/0002c19e-8b9d-47a9-b0de-367a1b39de75">

**Comment by rich2014** [comment]
@alexx2000 

hi, Alex

it's a problem with `doublecmd.icns` itself.

but I'm not familiar with making icons. how was the original DC icon generated?

see also: https://stackoverflow.com/questions/71118094/why-is-my-app-icon-bigger-than-the-others-in-the-macos-dock

**Comment by alexx2000** [comment]
Hi, I created it from original SVG image. I will try to create smaller icon.

**Comment by kfkawalec** [comment]
Any update on this?
There may be a way to fix this by replacing files, but how?

**Comment by alexx2000** [comment]
I created alternative icon (revision 11103) using Apple Human Interface Guidelines (macOS 12).  But looks like, macOS stores old icon somewhere in the cache so it applied only after I rename "Double Commander.app" into "Double Commander1.app".

**Comment by kfkawalec** [comment]
Thanks, for me it works without any other action, I just installed 11103 and the icon is the right size.

**Comment by rich2014** [comment]
@alexx2000 

Alex, did you not only change the visual size, but also the logo itself?

it seems not as good looking as the original LOGO.

<img width="169" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/0ccebe8a-85a2-4b5c-afca-f51cd68d51d1">

**Comment by alexx2000** [comment]
Yes,  Apple guidelines requires more rounded angles. I can resize original icon but it will be look slightly different from other macOS icons. What is better?

**Comment by alexx2000** [comment]
Alternative versions:

![dcfinal+p77](https://github.com/doublecmd/doublecmd/assets/13401398/b4957e95-10a0-4980-a811-64872923e714)

**Comment by kfkawalec** [comment]
I prefer the old ones :)

**Comment by rich2014** [comment]
the old one is better.

just shrinking the old one is good enough.

**Comment by rich2014** [comment]
@alexx2000 

the new icon is incorrectly one pixel smaller in all four directions.

<img width="154" alt="image" src="https://github.com/doublecmd/doublecmd/assets/102933068/f5f87a25-63b8-4830-812e-ca21222c959d">

**Comment by JonnyTech** [comment]
> Alternative versions:
> 
> ![dcfinal+p77](https://private-user-images.githubusercontent.com/13401398/291988875-b4957e95-10a0-4980-a811-64872923e714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDkzMDMsIm5iZiI6MTcwMzM0OTAwMywicGF0aCI6Ii8xMzQwMTM5OC8yOTE5ODg4NzUtYjQ5NTdlOTUtMTBhMC00OTgwLWE4MTEtNjQ4NzI5MjNlNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE2MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjYzOGQ1NDE2M2NhODUyNTExYjljNmJjNGQ3NmUwYTkxZmY1YjEzZWQyMzJkOWU2YmRhM2JlOGNmZjQxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bR7tPHNAWLLrfYjZzD8z27fIT7VdFoW8HTh9ZI-hItU)

Time for a change - change is good - the new shapes look like handles - file handles ;) - nice!

**Comment by alexx2000** [comment]
@rich2014 
I guess it is because DC icon does not have a shadow borders. By Apple guidelines icon consists of two objects: icon and shadow. DC icon has a correct size but it does not have a shadow. If I increase the icon height then it will be look higher than other icons.

![Безымянный](https://github.com/doublecmd/doublecmd/assets/13401398/337abeed-5bdc-482d-9846-0a4e01ffca3d)

**Comment by ags1234** [comment]
> > Alternative versions:
> > ![dcfinal+p77](https://private-user-images.githubusercontent.com/13401398/291988875-b4957e95-10a0-4980-a811-64872923e714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDkzMDMsIm5iZiI6MTcwMzM0OTAwMywicGF0aCI6Ii8xMzQwMTM5OC8yOTE5ODg4NzUtYjQ5NTdlOTUtMTBhMC00OTgwLWE4MTEtNjQ4NzI5MjNlNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE2MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjYzOGQ1NDE2M2NhODUyNTExYjljNmJjNGQ3NmUwYTkxZmY1YjEzZWQyMzJkOWU2YmRhM2JlOGNmZjQxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bR7tPHNAWLLrfYjZzD8z27fIT7VdFoW8HTh9ZI-hItU)
> 
> Time for a change - change is good - the new shapes look like handles - file handles ;) - nice!

The link does not work

**Comment by alexx2000** [comment]
It is a link to my post above.
