### ISSUE TITLE
current path: dir item selection freezed

### ISSUE THREAD

**Issue by exidler** [doublecmd/doublecmd#1307]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10953
Commit: 0ec75f36b
Build date: 2023/10/04
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.5.2

### Description

Current path item selection on mouse hover freezing.

Lite version to reproduce:
1. Move mouse to select any item in current path
2. Switch to another app/window (without mouse move) covering Double Commander window
3. Move mouse outside Double Commander window boundaries
4. Switch back to DC without mouse
5. Selection remain, using keyboard to navigate, does not remove selection until mouse outside of DC window boundaries

* Don't know how to reproduce, but sometimes entering mouse to DC window does not reset selection until mouse moved inside current path rect.

some screen recording: https://youtu.be/hUNNYtUGZXw

**Comment by rich2014** [comment]
it's a bug of Lazaurs/Cocoa.

i'll fix it in Lazarus later.

**Comment by rich2014** [comment]
@exidler 

fixed, test the snapshoot please.

**Comment by rich2014** [comment]
fixed in Lazarus.

@exidler test the last snapshoot from https://doublecmd.sourceforge.io/site/eng/snapshots.php  please.

**Comment by exidler** [comment]
Thanks, works fine!
