### ISSUE TITLE
Snapshot doublecmd-1.2.0-10962.cocoa.x86_64.dmg is damaged

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#1309]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10962
Commit: 6ee8e81d6
Build date: 2023/10/08
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.0.0

### Description

Snapshot doublecmd-1.2.0-10962.cocoa.x86_64.dmg is damaged. It cannot be executed.

You can see immediately that something is wrong when you look at the file size: It's only half the size of the last working version.

![Screenshot](https://github.com/doublecmd/doublecmd/assets/79788982/a03c293b-5e48-4fdb-9f60-ce6829ca1c4d)

**Comment by alexx2000** [comment]
Already fixed.
