### ISSUE TITLE
Configure Custom Columns

### ISSUE THREAD

**Issue by rty65tt** [doublecmd/doublecmd#1310]
### Version

Double Commander
Version: 1.1.3 beta
Revision: 100
Commit: 42dfbf544
Build date: 2023/10/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.0

### Description

Option ->  Columns -> Custom Columns
[doublecmd.err.txt](https://github.com/doublecmd/doublecmd/files/12841900/doublecmd.err.txt)

**Comment by rty65tt** [comment]
it hapend after delete "attr" colum
my config
[doublecmd.zip](https://github.com/doublecmd/doublecmd/files/12842014/doublecmd.zip)

**Comment by alexx2000** [comment]
You have a corrupted `doublecmd.xml`.

**Comment by rty65tt** [comment]
иногда при изменении конфигураций файл doublecmd.xml сохраняется "corrupted"

**Comment by alexx2000** [comment]
I fixed crash. But I have no idea how this `<FileSystem>0</FileSystem>` wrong line appeared in your `doublecmd.xml`.
