### ISSUE TITLE
Close Viewer using Esc button

### ISSUE THREAD

**Issue by ALEUT** [doublecmd/doublecmd#1312]
### Version

Double Commander
Version: 1.1.3 beta
Revision: 100
Commit: 42dfbf544
Build date: 2023/10/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.6.0

### Description

When I open something in the internal viewer - I can't close it using Esc button, I need to focus the mouse on the small red close icon and click.

**Comment by alexx2000** [comment]
MacPreview plugin problem.

**Comment by rich2014** [comment]
fixed by f6a7835bd7756fe1ba45fd6013d88a85272e99db.
