### ISSUE TITLE
Dark mode active tab text colour

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#1315]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10974
Commit: f4a5ad5
Build date: 2023/10/14
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

### Description

The text of the active tab is difficult to read in a dark theme

![image](https://github.com/doublecmd/doublecmd/assets/3584732/77a6476b-c1aa-4582-adc9-c871361e0e3a)

Any way to change it?

**Comment by alexx2000** [comment]
No, DC use default system color in this case. So it is a Lazarus LCLQT5 bug or Qt5 theme bug.  What theme do you use?

**Comment by JonnyTech** [comment]
OK, thanks. It was `Adwaita-dark`. So I reset my user profile and tried again. This time the light themes have issues. Haha. go figure:

![image](https://github.com/doublecmd/doublecmd/assets/3584732/a3c69388-ecdd-4756-86da-11e58173a2b7)
![image](https://github.com/doublecmd/doublecmd/assets/3584732/3affe0eb-3993-471e-b934-28b4d8b60d89)
![image](https://github.com/doublecmd/doublecmd/assets/3584732/d6e61a5b-eb32-4909-a201-4ef78f6029f1)
![image](https://github.com/doublecmd/doublecmd/assets/3584732/5eeb3c9d-17d5-442d-8804-9f17c6c75aaa)
![image](https://github.com/doublecmd/doublecmd/assets/3584732/82ae9900-d9c6-47ee-ac05-489e275be285)
![image](https://github.com/doublecmd/doublecmd/assets/3584732/4d6529d8-c395-4279-a8a2-e7445d2537f9)

Maybe I should restart after theme changes. Sorry to trouble you. I shall investigate further.
