### ISSUE TITLE
[SOLVED] Cannot find "create shortcut" internal command

### ISSUE THREAD

**Issue by antodc** [doublecmd/doublecmd#132]
I am using DC 0.9.10 on Windows 10.

Unless I am missing something, I cannot find the internal command "create shortcut" (which is under the "Files" menu) to add a dedicated button in the toolbar. I can see "create directory", "create sym link" and "create hard link", but no "create shortcut".

In other words, it seems not to be possible to add a button for "create shortcut" in the toolbar.

Can anyone help?

**Comment by Skif-off** [comment]
> I cannot find the internal command "create shortcut"

Because this feature is only for Windows.

Try VBScript (`CreateShortcut` method), something like
```vbs
Set WshShell = CreateObject("WScript.Shell")
Set WshShortcut = WshShell.CreateShortcut(WScript.Arguments.Item(1) & "\" & WScript.Arguments.Item(2) & ".lnk")
WshShortcut.TargetPath = WScript.Arguments.Item(0)
WshShortcut.Save
```
save as `CreateShortcut.vbs` and add button with
_external command:_ path-to-CreateShortcut.vbs
_parameters_: `%"0 "%p0" "%Dt" "%[Fillename;%o0]"`

Or try NirCmd ([examples](http://www.nirsoft.net/utils/nircmd.html), [full help file](http://www.nirsoft.net/utils/nircmd2.html#using)).

P.S. Related DC help pages: [Toolbar](http://doublecmd.github.io/doc/en/toolbar.html) and [Variables](http://doublecmd.github.io/doc/en/variables.html).

**Comment by antodc** [comment]
Thanks a lot indeed for your kind reply, but:

1) I am using Windows 10.

2) That command is available in the "Files" menu (see screenshot 1) but not in the list of internal commands (see screenshot 2).

Any (other) suggestion?

![DC ScreenShot 1](https://user-images.githubusercontent.com/74811961/124359360-e2fb8580-dc24-11eb-9cb5-6ad52a3acfdb.jpg)

![DC ScreenShot 2](https://user-images.githubusercontent.com/74811961/124359365-e727a300-dc24-11eb-970f-0d43dbbb08e8.jpg)

**Comment by alexx2000** [comment]
It is a "menu" only command (no internal command). So using VBScript as suggested is the simplest solution.

**Comment by antodc** [comment]
Ok, great. I used the VBScript and it works perfectly!

One last thing. Can anybody suggest how to apply/extend the script to several selected files at once?

**Comment by Skif-off** [comment]
For example, selected files:
```vbs
Set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = CreateObject("WScript.Shell")
Set TextStream = FSO.OpenTextFile(WScript.Arguments.Item(0), 1, False, -1)
Dim Str
Dim Name

While Not TextStream.AtEndOfStream
    Str = TextStream.ReadLine()
    Name = FSO.GetBaseName(Str)
    Set WshShortcut = WshShell.CreateShortcut(WScript.Arguments.Item(1) & "\" & Name & ".lnk")
    WshShortcut.TargetPath = Str
    WshShortcut.Save
Wend

MsgBox "Done!", 0, WScript.ScriptName
```
_external command:_ path-to-CreateShortcuts.vbs
_parameters_: `%"0 "%LW" "%Dt"`

**Comment by antodc** [comment]
It works like a charm! Thanks a lot!!!
