### ISSUE TITLE
cm_View ignores directories

### ISSUE THREAD

**Issue by natewind** [doublecmd/doublecmd#1323]
### Version

Double Commander
Version: 1.0.5 beta
Revision: 104
Commit: c02347051
Build date: 2022/04/12
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.3 LTS

### Description

`cm_View` (both from a shortcut and a toolbar button) does nothing on directories, even though I have the “View” action configured in file associations for both `folder` and `default` pseudo-extensions. Other extensions work fine, including `default` for files.

**Comment by alexx2000** [comment]
Yes, `cm_View` does not support directories.

**Comment by natewind** [comment]
Is it a planned feature?

**Comment by ags1234** [comment]
As a third party who just watches DC activity, it is mostly consisting of fixing the easiest bugs to fix that people report. At the moment it is not about moving forward by implementing new features or missing functionality.

**Comment by natewind** [comment]
Oh, ok.

**Comment by natewind** [comment]
Wow, thanks!
