### ISSUE TITLE
Toolbar tooltips: extra shortcuts

### ISSUE THREAD

**Issue by natewind** [doublecmd/doublecmd#1324]
### Version

Double Commander
Version: 1.0.5 beta
Revision: 104
Commit: c02347051
Build date: 2022/04/12
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.3 LTS

### Description

1. I have two buttons in my toolbar that run `cm_ExecuteScript` with two different Lua scripts, and there are `F2` and `F3` assigned to them.
2. I also have several standalone `cm_ExecuteScript` shortcuts that call a different Lua script (with different parameters depending on the shortcut).
3. Now, for some reason, one of those shortcuts is displayed in the tooltips for these two toolbar buttons, like this: `(F2) (Ctrl+/)`.

**Comment by alexx2000** [comment]
#1044
