### ISSUE TITLE
Chocolatey Package Wrong Download URL Causes 404 Error

### ISSUE THREAD

**Issue by yuriykaz** [doublecmd/doublecmd#1326]
### Version

Double Commander
Version: 1.1.4 beta
Revision: 119
Commit: 21ce5665a
Build date: 2023/10/14
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64
Note: Not OS version specific

### Description

* Issues when running choco upgrade or choco install doublecmd

* Error:
Attempt to get headers for https://github.com/doublecmd/doublecmd/releases/download/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/doublecmd/doublecmd/releases/download/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
Downloading doublecmd 64 bit
  from 'https://github.com/doublecmd/doublecmd/releases/download/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/doublecmd/doublecmd/releases/download/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The upgrade of doublecmd was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\doublecmd\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - doublecmd (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\doublecmd\tools\chocolateyinstall.ps1'.
 See log for details.
 
* Cause:
Chocolatey Package has Wrong Download URL: https://github.com/doublecmd/doublecmd/releases/download/v1.1.4/
The Correct Download URL is this one: https://github.com/doublecmd/doublecmd/releases/v1.1.4/

**Comment by yuriykaz** [comment]
1] I tried editing chocolateyinstall.ps1 file in "C:\ProgramData\chocolatey\lib\doublecmd\tools":
From this:
$url                = "https://github.com/doublecmd/doublecmd/releases/download/v$version/doublecmd-$version.i386-win32.msi"
$url64              = "https://github.com/doublecmd/doublecmd/releases/download/v$version/doublecmd-$version.x86_64-win64.msi"
To this:
$url                = "https://github.com/doublecmd/doublecmd/releases/v$version/doublecmd-$version.i386-win32.msi"
$url64              = "https://github.com/doublecmd/doublecmd/releases/v$version/doublecmd-$version.x86_64-win64.msi"
...but no luck.
Then
2] I tried running these commands, but no luck. Uninstaleld doublecmd, and now cannot install it with choco.
choco install doublecmd -y --source "https://github.com/doublecmd/doublecmd/releases/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi"
choco upgrade doublecmd -y --source "https://github.com/doublecmd/doublecmd/releases/v1.1.4/doublecmd-1.1.4.x86_64-win64.msi"

**Comment by alexx2000** [comment]
It is unofficial Chocolatey Package. I don't support it.
