### ISSUE TITLE
Time Machine drive shown as empty

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#1333]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11006
Commit: bb213486a
Build date: 2023/10/31
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.1.0

### Description

Double Commander does not show any files on my external HDD that I use for Time Machine backups. `Show Hidden/System Files` does not help.

muCommander does not have this problem.

**Comment by rich2014** [comment]
I also found that this situation should be caused by MacOS's restriction on Posix, or it should be called a protection mechanism.

after all it shouldn't be accessed as a normal disk, it's too dangerous and should be accessed using TimeMachine.

what are the specific usage scenarios?
