### ISSUE TITLE
Hot keys should be ignored when entering text to doublecmd

### ISSUE THREAD

**Issue by chrisbald** [doublecmd/doublecmd#1335]
### Version

Double Commander 1.0.11 (tested on Linux)

### Description

Hot Key configuration that uses the SHIFT key does create unexpected behavior when text is entered to doublecmd.

For example, if SHIFT + F is configured to open the file properties, the renaming of a file from Kind.txt to Find.txt (with uppercase F) does not work, as "SHIFT +F" keystroke will open the File properties.
The same applies to the command line field.

**Comment by chrisbald** [comment]
After activating the `Files panel` in `Only for these controls`, the shortcut does not work at all. Also, it seems that if several hotkeys are defined, only the top one is active.
Did I miss something in the configuration?

**Comment by alexx2000** [comment]
It conflicts with [Quick Search](https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys) now. It is a bad idea to use Shift+Letter or Alt+Letter hotkeys.
