### ISSUE TITLE
Differ shows "identical" on different files

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#1338]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10939
Commit: ed026035e
Build date: 2023/09/26
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.15.7

### Description

It's expected that `cm_CompareContents` compares contents without exclusions, but in some cases `Differ` tool says "two files are identical!" for slightly different files.

![differ-fails-on-trailing-newine-diff](https://github.com/doublecmd/doublecmd/assets/550974/bef9c4f5-3690-4e8a-a27f-6e2eab08abd1)

```
$ diff boost38.txt boost35-39.txt3

26c26
< 2.674 { H59: 1768824 } 1844
---
> 2.674 { H59: 1768824 } 1844
\ No newline at end of file
```

**Comment by alexx2000** [comment]
Differ does not compare line-endings. It compares text lines only.

**Comment by zxcat** [comment]
> Differ does not compare line-endings. It compares text lines only.

But this behavior is surprising: command name is `cm_CompareContents`, not `cm_CompareText`. Message about "identical files" is misleading too. Sometimes newlines diff is a valuable knowledge

**Comment by alexx2000** [comment]
It compare text in the text mode and it compare files byte by byte in the binary mode.
