### ISSUE TITLE
Update to jammy repo for LSIO container

### ISSUE THREAD

**Issue by Beersteddy** [doublecmd/doublecmd#1341]
### Version

LSIO 1.05 beta

### Description

Double commander seems to be very outdated in Jammy repo which apparently LSIO is using to build their containers.
https://packages.ubuntu.com/jammy/doublecmd-common
As a result, the version is stuck in 1.0.5 beta.

Any chance to get it updated?

**Comment by alexx2000** [comment]
It is not a right place for such question. You should ask Ubuntu maintainers. As I know they do not update packages in the `universe` repo.

**Comment by Skif-off** [comment]
I think Double Commander is not the only example of the consequences of using Jammy :)
(But using Jammy is a smart decision, because this is the last LTS release.)

https://doublecmd.github.io/doc/en/faq.html#repo

**Comment by Beersteddy** [comment]
> It is not a right place for such question. You should ask Ubuntu maintainers. As I know they do not update packages in the `universe` repo.



> It is not a right place for such question. You should ask Ubuntu maintainers. As I know they do not update packages in the `universe` repo.

Wasn't sure who was responsible for the latest version in such a repo.
Wouldn't even know where to start with jammy
