### ISSUE TITLE
Unpacking archives into paths with symlinks doesn't work or breaks symlink

### ISSUE THREAD

**Issue by MadMaxx64** [doublecmd/doublecmd#1357]
### Version

Double Commander
Version: 1.1.5 beta
Revision: 159
Commit: f96767c13
Build date: 2023/11/05
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23.1 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

Portable version, run from user's home directory.

### Description

After upgrading from 1.0.11 to 1.1.5 I encountered this nasty bug. When unpacking a rar file into a path that contains a symlink, DC tries to replace the symlink with a normal folder. If the user has permission to delete the symlink, DC deletes it and creates a folder, then unpacks the data in the new folder/generated path.

If the user does not have permission (e.g. if symlinks are set up by root in / ) to delete the symlink only the folders get unpacked, not the files.

Expected behaviour is of course to leave the symlink intact and use it normally.

**Comment by alexx2000** [comment]
https://doublecmd.h1n.ru/viewtopic.php?t=7718

**Comment by MadMaxx64** [comment]
Thank you for the quick response. My bad for not looking through the boards ^^"

I was able to recreate the problem on a Debian 12 system with version 1.0.10. So confirmed nothing to do with 1.1 branch. I thought it still worked on 1.0.11 before, though, but I must be misremembering. By knowing about the problem I can easily work around it, so that's fine for me.

**Comment by alexx2000** [comment]
Fixed in the latest Unrar library (version 7.0.8).
