### ISSUE TITLE
Невозможно установить (ОС Fedora) - ругается на протухший ключ

### ISSUE THREAD

**Issue by dimaos32** [doublecmd/doublecmd#1362]
### Version

Double commander
Last version
Nightly version

### Description

Невозможно установить ни из dnf, ни скачав rpm-файл

Результат транзакции
====================================================================================================================================
Установка  1 Пакет

Общий размер: 9.0 M
Объем изменений: 41 M
Продолжить? [д/Н]: y
Загрузка пакетов:
[SKIPPED] doublecmd-gtk-1.2.0+svn11031+git30c36c5-964.1.x86_64.rpm: Already downloaded                                             
error: Verifying a signature using certificate 41B5132F245C8E77743285ED61508B60C33A8925 (home:Alexx2000 OBS Project <home:Alexx2000@build.opensuse.org>):
  1. Certificiate 61508B60C33A8925 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-03-22T20:10:23Z
  2. Key 61508B60C33A8925 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-03-22T20:10:23Z
error: Verifying a signature using certificate 41B5132F245C8E77743285ED61508B60C33A8925 (home:Alexx2000 OBS Project <home:Alexx2000@build.opensuse.org>):
  1. Certificiate 61508B60C33A8925 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-03-22T20:10:23Z
  2. Key 61508B60C33A8925 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-03-22T20:10:23Z
Double Commander (unstable) (Fedora_39)                                                             8.0 kB/s | 1.1 kB     00:00    
GPG ключ https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/Fedora_39/repodata/repomd.xml.key (0xC33A8925) уже установлен
GPG ключи, перечисленные для репозитория «Double Commander (unstable) (Fedora_39)», уже установлены, но они не являются правильными для этого пакета.
Проверьте, правильно ли настроены URL ключей для этого репозитория.. Сбойный пакет: doublecmd-gtk-1.2.0+svn11031+git30c36c5-964.1.x86_64
 Ключи GPG настроены как: https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/Fedora_39/repodata/repomd.xml.key
Загруженные пакеты были сохранены в кэше до следующей успешной транзакции.
Вы можете удалить кэшированные пакеты, выполнив «dnf clean packages».
Ошибка: СБОЙ проверки GPG

**Comment by alexx2000** [comment]
Проверил на виртульной машине с LiveCD Fedora 39. DC без проблем установился. Возможно у вас какой-то более старый ключ. Попробуйте его удалить и добавить ключ заново.

**Comment by dimaos32** [comment]
Да, он у меня с 36 федоры вроде... перед обновлением с 38 пришлось удалить дабл коммандер - при обновлении на него ругался обновлятор (классное слово, знаю)))

А как старый ключ удалить и где его смотреть?

**Comment by alexx2000** [comment]
Мне неизвестно как это делается на Fedora.

**Comment by dimaos32** [comment]
А как это делается просто в линуксе?

**Comment by alexx2000** [comment]
По разному, зависит от дистрибутива. Вот нашел [инструкцию](https://gist.github.com/e7d/3b786c7410ca14a5ded61eec36de9874) для Fedora.

**Comment by dimaos32** [comment]
Спасибо!!!
Ваша инструкция помогла разобраться!
П.С. Первый раз с таким столкнулся...
