### ISSUE TITLE
[macOS] first column of "fullscreen mode console" is truncated

### ISSUE THREAD

**Issue by ogm256** [doublecmd/doublecmd#1369]
### Version

Double Commander
Version: 1.1.6 beta
Revision: 179
Commit: 96fcdc230
Build date: 2023/11/18
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.6.2

### Description

When I press Ctrl+O to enter fullscreen mode of console the first column is missing and the second is half cut:

![Screenshot 2023-11-22 at 21 13 46](https://github.com/doublecmd/doublecmd/assets/5924780/f7a3cfb5-1bb8-4d2a-9fe0-e70b88c98537)

I've played already with the font settings but no luck.

**Comment by rich2014** [comment]
it works fine on MacOS 12.6.8.

I'll test it on MacOS 13 later.

**Comment by ogm256** [comment]
Yes, indeed. I tested on an old machine with Big Sur (macOS 11, Intel) and it works just fine, too. Seems to be a macOS 13+ problem.

**Comment by rich2014** [comment]
it should be caused by the Vertical ScrollBar.

it works normal without the ScrollBar.

the reason why it is not working properly in MacOS 13 is still being found.

**Comment by rich2014** [comment]
@alexx2000 Alex,

I found that: TVirtualTerminal/cmdConsole --> TTabSheet/pgConsole --> TPageControl/nbConsole  --> TPanel/pnlCommand.

what is the reason for this?

**Comment by alexx2000** [comment]
I guess it was planned multiple tabs with console. Technically it is possible in the future.

**Comment by rich2014** [comment]
@ogm256 

hi, could you download the snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php and test it

**Comment by ogm256** [comment]
> @ogm256
> 
> hi, could you download the snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php and test it

Unfortunately, the same as before. Does not work, either.

Just for the record, the tested release of Double Commander and macOS:

Double Commander
Version: 1.2.0 alpha
Revision: 11080
Commit: e9d43cf41
Build date: 2023/12/11
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.6.3

**Comment by rich2014** [comment]
@ogm256 

fixed in Lazarus/Cocoa.

should be applied in the DC snapshoots.

download from  https://doublecmd.sourceforge.io/site/eng/snapshots.php and test it please.

**Comment by ogm256** [comment]
I can confirm it. It is fixed in:

Double Commander
Version: 1.2.0 alpha
Revision: 11101
Commit: 211a9b894
Build date: 2023/12/17
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.6.3
