### ISSUE TITLE
Edit path: Tab-Key should behave as in Powershell

### ISSUE THREAD

**Issue by reneederer** [doublecmd/doublecmd#137]
Editing a path in Powershell is a little nicer than in Double Commander.
In Powershell (on my computer),
    typing `C:\u <tab>` results in `C:\Users\`. Pressing `<tab>` again results in `C:\Users\admlansweeper\` (since there are no other folders in `C:\` start start with `u`).
    Typing `C:\w <tab>` results in `C:\windows\`. Pressing `<tab>` again results in `C:\workspace\`. 

I would like to suggest this for Double Commander too.

**Comment by JonnyTech** [comment]
I disagree. Double Commander uses the same completion as Linux which is a convention that is widely used and well established. If you want a deeper path then type the separator (`\` or `/`) then press `tab`.
