### ISSUE TITLE
Sorting glyph is invisible in the columns view when using KDE Plasma

### ISSUE THREAD

**Issue by TheNicker** [doublecmd/doublecmd#1371]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11040
Commit: 3ef7774bd
Build date: 2023/11/21
Lazarus: 2.2.0.4
FPC: 3.2.0
Platform: x86_64-Linux-gtk2
OS version: Void Linux

Verified on Ubuntu 23 and void Linux 

### Description

![image](https://github.com/doublecmd/doublecmd/assets/4753283/65fdd64f-bd22-4734-bcdc-118ef962ef75)

**Comment by alexx2000** [comment]
What icon theme do you use?

**Comment by TheNicker** [comment]
Icon theme is: dctheme
used default, no other icon theme is installed

**Comment by alexx2000** [comment]
Under Linux DC uses system icon theme. What system icon theme do you use?

**Comment by TheNicker** [comment]
I use Breeze Dark
![image](https://github.com/doublecmd/doublecmd/assets/4753283/68d65d67-d2f9-4b76-8d99-78b03445924c)

I've Downloaded other icon themes and it seems to solve the issue

**Comment by alexx2000** [comment]
Yes, dark icon theme created for dark interface theme but you interface is light, so you got a colors conflict.
