### ISSUE TITLE
RAR archives support

### ISSUE THREAD

**Issue by ags1234** [doublecmd/doublecmd#1388]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11064
Commit: acf3d13b6
Build date: 2023/12/03
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

### Description

Users should be able to browse RAR archives.  At the same time, users should to be able to pack files in RAR archives.
Unrar.wcx plugin is active, WinRAR is installed and working.
Currently, I can browse and unpack RAR archives. That's fine.
If I want to pack files in a RAR archive, I get the following error:
![2023-12-06_203036](https://github.com/doublecmd/doublecmd/assets/21011513/2252f973-706d-4e64-800e-6b2c78295807)
I go to Options -> Archivers -> RAR, I enable it and set the correct path in Archiver field. Then Apply and OK. I disable unrar.wcx.
Now the packing works, but browsing archives does not: DC opens the archive, but no content is shown.

**Comment by ags1234** [comment]
I just wanted to point out that the message "Cannot open existing file" does not point the user in the right direction. Changing that to something like "Cannot find RAR archiver. Please set correct path in plugin configuration" would help a lot.

**Comment by ags1234** [comment]
That'll do. Thanks!

**Comment by Raart** [comment]
Anybody can make a screenshot of the winrar (wine) setup in the packer settings panel?
Or the same for althernative setup with linux native unrar+rar?
Thanks
