### ISSUE TITLE
Date format in "synchronize dirs" different than in file panels

### ISSUE THREAD

**Issue by michalkochanowicz** [doublecmd/doublecmd#1391]
### Version

I see it in both beta and alpha versions:

Double Commander
Version: 1.1.7 beta
Revision: 195
Commit: e35531fa7
Build date: 2023/12/02
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.2

Double Commander
Version: 1.2.0 alpha
Revision: 11079
Commit: f0320f65c
Build date: 2023/12/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.2

### Description

I selected dd/mm/yyyy hh:mm format for date in settings. It works correctly in file panel (together with 24-hour date format).

But "synchronize dirs" still uses mm/dd/yyyy and 12-hour time format.

**Comment by Skif-off** [comment]
@alexx2000 
maybe just replace 
```
DateTimeToStr(*.ModificationTime);
```
with
```
FormatDateTime('yyyy.MM.dd hh:nn:ss', *.ModificationTime);
```
in the appropriate places?
(We can try to change _ShortDateFormat_ in _TFormatSettings_ and continue using _DateTimeToStr_, but it sounds strange.)

Just in case, maybe _gDateTimeFormatSync_? To change manually.
```
FormatDateTime(gDateTimeFormatSync, *.ModificationTime);
```

I looked at how the "Date and time format" (_gDateTimeFormat_) option was added and I think there is no need to give _gDateTimeFormatSync_ so much attention and code.

**Comment by Skif-off** [comment]
Maybe something like [this](https://github.com/Skif-off/doublecmd/commit/5f29a496a8d9fa628d32fdfb3ec2380afcdaa05c) or [this](https://github.com/Skif-off/doublecmd/commit/798a028d66d396755db03fd4b6b21d5672e95909)?
Or is the option in the settings section much better?

**Comment by alexx2000** [comment]
> Maybe something like [this](https://github.com/Skif-off/doublecmd/commit/5f29a496a8d9fa628d32fdfb3ec2380afcdaa05c) or [this](https://github.com/Skif-off/doublecmd/commit/798a028d66d396755db03fd4b6b21d5672e95909)?

Yes, second variant is better. But need to replace 'DateTimeFormatSync' xml-tag by 'DateTimeFormat' because it is already in the `SyncDirs` tag.
