### ISSUE TITLE
The program does not detect portable devices.

### ISSUE THREAD

**Issue by jmartinezb3** [doublecmd/doublecmd#1392]
### Version

Version 1.0.11
Windows.

### Description

I'm not sure if it's a bug, but I have my phone connected to the PC in file transfer mode and Double Commander doesn't detect it. Other programs like Total Commander do detect it immediately.

If there are any settings I need to apply, please let me know.

**Comment by alexx2000** [comment]
Modern phones does not connect as volumes. They connects as portable devices. DC 1.1.7 has portable device support.

**Comment by ags1234** [comment]
@jmartinezb3, your post is confusing.
You wrote one thing in the title and a completely different thing in the description. You have a problem with the detection of your phone, not with "volumes". When you submit a bug report, generalization is not such a good thing.
The title of your post should be modified, as it is misleading.

**Comment by jmartinezb3** [comment]
> Modern phones does not connect as volumes. They connects as portable devices. DC 1.1.7 has portable device support.

Indeed, version 1.1.7 fixes the compatibility with mobile devices. Thanks.
