### ISSUE TITLE
Incorrect attributes for a file extracted from TAR when a relative symlink to that file is named as the file prefix

### ISSUE THREAD

**Issue by danpla** [doublecmd/doublecmd#1393]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 14.04.6 LTS

Widgetset library: GTK 2.24.23

### Description

Consider a TAR.GZ archive with two files ([test.tar.gz](https://github.com/doublecmd/doublecmd/files/13686752/test.tar.gz)):
1. `a.txt` - a regular file with attributes `-rw-rw-r--`
2. `a` (no extension) - a relative symlink to `a.txt` with attributes `lrwxrwxrwx`

When I extract the archive with DC, the attributes of the extracted `a.txt` are `-rwxrwxrwx` (apparently, copied from the symlink) instead of the original `-rw-rw-r--`.

**Comment by Skif-off** [comment]
Current release: 1.0.11.
Current beta: 1.1.7.
[Try](https://github.com/doublecmd/doublecmd/releases) portable (`doublecmd-1.1.7.gtk2.x86_64.tar.xz`).
