### ISSUE TITLE
MacOS dark mode support?

### ISSUE THREAD

**Issue by pshirshov** [doublecmd/doublecmd#14]
Hi guys,

Could you support dark mode please?

**Comment by alexx2000** [comment]
Cocoa version supports dark mode, but it is needed to enable it manually. Go to "Double Commander.app/Contents" and replace Info.plist by [this one](https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/doublecmd.app/Contents/Info.plist?format=raw).

**Comment by pshirshov** [comment]
Wouldn't it break signature?

**Comment by alexx2000** [comment]
DC does not have a signature.

**Comment by pshirshov** [comment]
Ok, thank you. Though I think it would be great if the app can choose proper UI automatically.

**Comment by alexx2000** [comment]
Will be enabled by default in the next version.
