### ISSUE TITLE
Incomplete thumbnail after auto refresh

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#1409]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11113
Commit: 021fe137a
Build date: 2023/12/21
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.2.1

### Description

Double Commander displays an incomplete thumbnail after auto refresh. To reproduce the issue, follow these steps:

1. Install [XnView MP](https://www.xnview.com/en/xnviewmp/) on your Mac. (Note: The issue does not occur with other image editing software.)
2. Activate the following options in Double Commander: Auto refresh > Refresh file list: [x] When files are created, deleted or renamed, [x] When size, date or attributes change.
3. Copy a PNG file into an empty directory.
4. Activate thumbnails view mode.
5. Right-click on the PNG file > Open with > XnViewMP.app. As a result, the PNG file will open in XnView MP.
6. In XnView MP, go to File > Save as and save the image in JPG format.
7. Quit XnView MP.

**Expected result:** Double commander will show a proper thumbnail of the new JPG file.
**Actual result:** Double commander will show an incomplete thumbnail of the new JPG file, see screenshot below.

![Screenshot](https://github.com/doublecmd/doublecmd/assets/79788982/da3c643e-49bf-42f5-98c1-952eee5e001c)

**Comment by rich2014** [comment]
@alexx2000

hi, Alex

it should be a flaw of TFileView and is not limited to macOS.

when File.tag>=0, the thumbnail of this image will not be updated.

```pascal
procedure TThumbFileView.EnsureDisplayProperties;
......
  if (AFile.Tag < 0) and AFile.FSFile.IsNameValid and (AFile.Busy * [bsTag] = []) then
  begin
    if not Assigned(AFileList) then
      AFileList := TFVWorkerFileList.Create;
    AFileList.AddClone(AFile, AFile);
    AFile.Busy := AFile.Busy + [bsTag];
  end;
......
```

**Comment by alexx2000** [comment]
Hi,

OK, I will look how to fix it.

**Comment by alexx2000** [comment]
Try with latest snapshot.
