### ISSUE TITLE
Opening this 700k one-liner HTML in internal viewer - app hangs

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1410]
### Version

Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

File in zip

[long line 700k.zip](https://github.com/doublecmd/doublecmd/files/13759704/long.line.700k.zip)

I ask @User4martin too, because it is maybe pure SynEdit fail.

**Comment by alexx2000** [comment]
It is a TSynHTMLSyn highlighter issue. It can be easy reproduced with simple Lazarus application (TSynEdit + TSynHTMLSyn ). Without highlighter SynEdit successfully opens this file.

**Comment by Alexey-T** [comment]
Posted to https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40660

closing.

**Comment by User4martin** [comment]
A 700k single line will probably trouble SynEdit even without a Highlighter present.

Unfortunately I don't think there will be any fix for it soon.

IIRC (but that needs to be checked again), a good amount of time goes into calculating the width of the entire line (for the scrollbar), and the width up to the caret pos.

**Comment by User4martin** [comment]
Ok, seems the last post is outdated info (IIRC there were issues with that in the past).

But it seems you tested without the HL.
