### ISSUE TITLE
Build with Lazarus 3.0 --> Can't find unit LazUTF8Classes used by SynUniHighlighter

### ISSUE THREAD

**Issue by antonioleal** [doublecmd/doublecmd#1422]
### Version

Version 1.0.11

LazUTF8Classes have been removed from the latest Lazarus and were deprecated from a long time.

So SynUniHighlighter needs an update...

### Description

LazUTF8Classes have been removed from the latest Lazarus and were deprecated from a long time.

So SynUniHighlighter needs an update...

**Comment by alexx2000** [comment]
DC 1.0.11 at the end of the lifecycle. DC 1.1.9 will be released at near days. You can test latest [beta release](https://github.com/doublecmd/doublecmd/releases/tag/v1.1.8) now.

**Comment by antonioleal** [comment]
Thanks. Good luck for the new release.

**Comment by alexx2000** [comment]
Yes. I don't harry to update Lazarus.
