### ISSUE TITLE
"&" for hotlist quick switch in Mac

### ISSUE THREAD

**Issue by Mickychen00** [doublecmd/doublecmd#1433]
### Version

Double Commander
Version: 1.1.8 beta
Revision: 247
Commit: b308422c3
Build date: 2023/12/16
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.2.1

### Description

Will there be a solution for a quick jump to a hotlist directory through a user-assigned  "&" key? For instance, I use "(&o)" for my OneDrive folder to quick jump in Windows and Linux. But I found it's impossible to use it on Mac.
I found a discussion in the forum from 2015:
https://doublecmd.h1n.ru/viewtopic.php?t=3092

**Comment by alexx2000** [comment]
I guess it is a Lazarus/macOS issue.

**Comment by rich2014** [comment]
fixed by 9c7051b with new Lazarus/Cocoa version.

@Mickychen00 please test the snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php.

**Comment by Mickychen00** [comment]
> fixed by [9c7051b](https://github.com/doublecmd/doublecmd/commit/9c7051bb86ef58e0c38d5a504d0742bdd1a34d7e) with new Lazarus/Cocoa version.
> 
> @Mickychen00 please test the snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php.

Hi! I have tested it in the Mac Arm64 version. It works now!  Thanks a lot for your rapid fix!
