### ISSUE TITLE
Window title with non-english characters

### ISSUE THREAD

**Issue by noctrex** [doublecmd/doublecmd#1442]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11189
Commit: 285bb31d1
Build date: 2024/01/12
Lazarus: 3.0.0.3
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 23H2 x86_64

### Description

Folders with non-english characters are not displayed correctly on the window title, or in the windows task bar.
For example, created a folder called "Δοκιμή" ("test" in Greek) 
![image](https://github.com/doublecmd/doublecmd/assets/35490284/46bba4fd-a95c-46dc-92da-6e4ecea834aa)
![image](https://github.com/doublecmd/doublecmd/assets/35490284/0f597000-50fa-4c78-9350-3df5e0d68f4c)

**Comment by JonnyTech** [comment]
Do you have the correct language pack installed in Windows settings?

**Comment by noctrex** [comment]
> Do you have the correct language pack installed in Windows settings?

Yes, as I'm from Greece, and have the Greek Language Pack installed
![image](https://github.com/doublecmd/doublecmd/assets/35490284/33326650-0183-4216-95ea-e565a91f2e32)

**Comment by JonnyTech** [comment]
@noctrex the issue has been fixed, I was wrong about language packs, please try the latest snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php (Revision 11190 or higher) to confirm.
