### ISSUE TITLE
Cannot create sub-directory, if identically named file present

### ISSUE THREAD

**Issue by mihnea-radulescu** [doublecmd/doublecmd#1443]
### Version

Double Command version: 1.1.8~247
OS version: Windows 10 22H2 (OS Build 19045.3930)
Disc partition types: NTFS and ex-FAT

### Description

**Steps to reproduce**
1. Open any directory in the file system.
2. Create a file with any name within the directory.
3. Attempt to create a sub-directory having the same name as the previously created file (screenshot1).
4. The sub-directory cannot be created, and an error is shown to the user (screenshot2).

**Expected behavior**
The sub-directory is created correctly, and no error message is shown to the user.

![screenshot1](https://github.com/doublecmd/doublecmd/assets/29178174/c1dd5d62-989a-4013-b9f2-40c18a0e77af)
![screenshot2](https://github.com/doublecmd/doublecmd/assets/29178174/c94aa3f3-d9f8-49ca-b13b-aa76d4301f7e)

**Comment by alexx2000** [comment]
It is impossible. File system cannot contain file and directory with same name.
