### ISSUE TITLE
Shortening file or sub-directory names results in name truncation visual artifact

### ISSUE THREAD

**Issue by mihnea-radulescu** [doublecmd/doublecmd#1444]
### Version

Double Command version: 1.1.8~247
OS version: Windows 10 22H2 (OS Build 19045.3930)

### Description

**Steps to reproduce**
1. Open a directory with file names of varying lengths (screenshot1).
2. Rename the file with the _longest_ file name to reach a length shorter than the _shortest_ file name in the directory (screenshot2).
3. The renaming results in a visual artifact of file name truncation (screenshot3), which also occurs when renaming sub-directories (screenshot4).

**Expected behavior**
Renaming files (or sub-directories) does not truncate the visual representation of the other files (or other sub-directories).

![screenshot1](https://github.com/doublecmd/doublecmd/assets/29178174/627298ba-614a-4ba1-9535-7a073b3a8cf7)
![screenshot2](https://github.com/doublecmd/doublecmd/assets/29178174/858e769f-379d-41e5-88b5-2ec7a1c3da5b)
![screenshot3](https://github.com/doublecmd/doublecmd/assets/29178174/f80747e6-f148-464c-827a-ac722a2fdba5)
![screenshot4](https://github.com/doublecmd/doublecmd/assets/29178174/84c29376-efea-464c-9233-83257b057043)

**Comment by alexx2000** [comment]
#321
