### ISSUE TITLE
View F3 on any file displays Error: Position range overflow in Status.SendMoveSizeMessages: Left=0, Top=65461

### ISSUE THREAD

**Issue by randoclt** [doublecmd/doublecmd#1447]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/05/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Manjaro Linux

Widgetset library: Qt 5.15.12, libQt5Pas 5.6.1
[doublecmd.txt](https://github.com/doublecmd/doublecmd/files/13973332/doublecmd.txt)

### Description

F3 on any file displays Error:
[doublecmd.txt](https://github.com/doublecmd/doublecmd/files/13973384/doublecmd.txt)

**Comment by alexx2000** [comment]
#769
