### ISSUE TITLE
Toolbar separator visibility

### ISSUE THREAD

**Issue by mpeter50** [doublecmd/doublecmd#145]
The separators on the toolbar are barely visible for me, even though they are visible in the Toolbar menu of the settings:
![image](https://user-images.githubusercontent.com/83356418/126878810-bda2c4bb-2130-453f-ac0b-f32bd4ee3498.png)

If you look very hard, you can see that the separators are actually there in the actual toolbar, they are just styled differently, both in the color and width. At the same time, the separators look different on the preview in the settings window.

If any additional details are needed, feel free to ask. I'm new to desktop Linux and have a suspicion that this might have to do a system theme, but can't verify it as of now.

**Comment by alexx2000** [comment]
No bug here, it is working as intended.

**Comment by mpeter50** [comment]
Does that mean that this depends on a system theme that I use?

**Comment by alexx2000** [comment]
Yes, separator style at toolbar depends on a system theme. And separator style at toolbar settings has fixed style.

**Comment by mpeter50** [comment]
Oh, thank you. I'll then find out how to set up my system :)
The prolem does not originate from DoubleCommander, so I'm closing this issue

Sorry for the late response
