### ISSUE TITLE
Tooltips do not work for deb and rpm plugins

### ISSUE THREAD

**Issue by antonsoroko** [doublecmd/doublecmd#1453]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11205
Commit: b5e943d
Build date: 2024/01/25
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 23.10

Widgetset library: Qt 5.15.10, libQt5Pas 5.6.1

### Description

Tooltips do not work for deb and rpm plugins (shows nothing, but i was not able to make a screenshot of tooltip), but DC shows info from those plugin in its "file properties" window.

![Screenshot_20240125_192744](https://github.com/doublecmd/doublecmd/assets/17964763/1d6feb96-1825-4fe7-84de-899b1d5e704d)
![Screenshot_20240125_192838](https://github.com/doublecmd/doublecmd/assets/17964763/f541b0ee-4720-48ea-831b-53484260f624)

**Comment by alexx2000** [comment]
I cannot reproduce. Works fine.

**Comment by alexx2000** [comment]
Try to move descript.ion file type to the bottom.

**Comment by antonsoroko** [comment]
@alexx2000 OMG. I feel stupid :-D It works now. Thank you!
