### ISSUE TITLE
Mouse Clicks nearly impossible in popup windows

### ISSUE THREAD

**Issue by aziemer** [doublecmd/doublecmd#1463]
### Version

Double Commander Version: 1.2.0 alpha Revision: 11212 Commit: 3d3263897 Build date: 2024/01/28
Lazarus: 3.99.0.0 FPC: 3.2.2 Platform: aarch64-Darwin-cocoa OS version: Mac OS X 14.3.0

### Description

First I want to thank you for your marvelous work! Double Commander is BY FAR the best file manager available for the Mac.

But since short (somewhere around Rev. 11000) I have a problem with popup boxes:
I have to click on an item for maybe 10 - 15 times before the expected action is taken. When clicking, the button does change its color to the activated state for some milliseconds then goes back to the inactive state and nothing else happens. This happens for all types - buttons, text entry fields, dropdown lists, radio buttons etc.

But selecting i.e. a button via TAB and then hitting RETURN works with no problem. Also the maximize / close buttons of the popup window itself work as expected on the first click!

best regards
Andreas

**Comment by rich2014** [comment]
@aziemer 

1. works fine on macOS 12.7 and 13.5.

2. can you test it on other computers?

3. to make sure there is no misunderstanding, can you provide some screenshots or screenshots?

**Comment by aziemer** [comment]
I'm on macOS Sonoma 14.3 on a M2 Mac mini 2023
Running on a M1 Mac Book Air runs slightly better, as I only have to click 1 or 2 times. I try to make video in the next days, as currently we are renovating our home - chaos...

**Comment by aziemer** [comment]
I now know what is the cause - and why it works better on the laptop: clicking a control only works if the mouse pointer **does not even move a single pixel** after pressing until releasing the mouse button! On the Macbook this seems to happen less often, because I use the tap action there.

**Comment by aziemer** [comment]
It looks as if a mouse move event cancels the pending mouse down/click event ?

**Comment by JonnyTech** [comment]
I can confirm this with latest snapshots on an M2 iMac, clicking dialog buttons is incredibly frustratinng.

**Comment by rich2014** [comment]
it's a bug of Lazarus/Cocoa, introduced in January and has been fixed today.

please download DC from https://doublecmd.sourceforge.io/site/eng/snapshots.php and test.

**Comment by JonnyTech** [comment]
Great, I can test later and report back. Thanks!

**Comment by aziemer** [comment]
Yep, for me it works ;-) THANK YOU

**Comment by JonnyTech** [comment]
Confirmed working for me too. Nice!

**Comment by rich2014** [comment]
it's great
