### ISSUE TITLE
Missing/wrong seperators in file list headers/size/footers

### ISSUE THREAD

**Issue by svenrat** [doublecmd/doublecmd#1465]
### Version

Double Commander Version: 1.2.0 alpha Revision: 11213 Commit: a1b3b967b Build date: 2024/02/01 Lazarus: 3.99.0.0 FPC: 3.2.2 Platform: x86_64-Darwin-cocoa OS version: Mac OS X 10.15.7

### Description

Missing/wrong separators in file list headers/sizes/footers

Missing thousands separator as specified in the control panel
Example:
macOS: 1335875825 B -> 1.335.875.825 B
Windows: Ok

Incorrect floating point separator as specified in the control panel.
Example:
macOS: 1304566.235 KB -> 1.304.566,235 KB
Windows: 1.304.566.235 KB -> 1.304.566,235 KB

**Comment by rich2014** [comment]
@alexx2000 

Alex, it seems to be a common issue, not limited to MacOS.

do you have any ideas?

**Comment by alexx2000** [comment]
It is a system specific parameter. Under macOS `iosxlocale` unit initialize default separators (`DefaultFormatSettings`). Maybe it has a some bug...

**Comment by alexx2000** [comment]
Hmm... Looks like it is a DC problem.

**Comment by alexx2000** [comment]
I fixed incorrect floating point separator (at least under Windows).

**Comment by rich2014** [comment]
works fine on macOS too :)

**Comment by rich2014** [comment]
DefaultFormatSettings needs to be initialized again on macOS (2a04efd)

**Comment by svenrat** [comment]
Now it works great on Windows and macOS (both 216).
Thanks.

**Comment by rich2014** [comment]
it's great
