### ISSUE TITLE
Multi rename issues with square brackets

### ISSUE THREAD

**Issue by Metotron** [doublecmd/doublecmd#1469]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2024/01/31
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version:   openSUSE Tumbleweed

Widgetset library: Qt 5.15.12, libQt5Pas 5.6.1

### Description

I use square brackets in rename template and have some bugs: 
template "] [N1:]" inserts two spaces before filename: "]  filename"
template "]] [N1:]" becomes "]] ]  filename"
template "]]] [N1:]" becomes "]]] ]] ]  filename" and so on

I want to use simgle brackets in name with this: "[[text]] [N1:]". It will be "[text]  filename". Can not get one space here.

**Comment by Skif-off** [comment]
I don't understand where you got `[N1:]`, this placeholder seems meaningless.

As I understand, the placeholders are made similar to the placeholders in Total Commander, so it must be `[[]text[]] [N]`.

**Comment by alexx2000** [comment]
> the placeholders are made similar to the placeholders in Total Commander, so it must be `[[]text[]] [N]`.

Yes.

**Comment by Skif-off** [comment]
I'll try adding this to "multirename.html".

It seems too early to close this: I tried `[[]text[]] [N]` (1.2.0 alpha) and one extra space character appears. Can you check it?

**Comment by Metotron** [comment]
> I don't understand where you got `[N1:]`, this placeholder seems meaningless.

Agree, it must be [N]. I just shortened name range and did not think about it. But it works.
Thank you for [[]text[]], but, yes, second space still there.
