### ISSUE TITLE
Thousand separator on KDE Plasma - diff. language settings

### ISSUE THREAD

**Issue by kppr0** [doublecmd/doublecmd#1474]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11220
Commit: d308ae7
Build date: 2024/02/06
Lazarus: 3.0.0.3
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Arch Linux

Widgetset library: Qt 5.15.12, libQt5Pas 5.6.1

### Description

Having same locale settings, thousand separator in DC works fine, e.g.
LANG=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8

But combination with different language does not work, e.g.
LANG=en_US.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8

Also is necessary to have same settings for all these parameters (LANG, LC_MEASUREMENT, LC_MONETARY, LC_NUMERIC, LC_TIME), e.g. different LC_TIME breaks thousand separator in DC.

**Comment by kppr0** [comment]
Seems its related to this commit <a href="https://github.com/doublecmd/doublecmd/commit/77a83234a741191719a5dbc4c77c01d4c23381f7">77a8323</a>, Doublecmd 1.1.9 beta rev. 350 works fine.

**Comment by alexx2000** [comment]
DC 1.1.9 always use `space` as a separator. While DC 1.2.0 tries to use system thousand separator. DC (FreePascal) use [nl_langinfo](https://linux.die.net/man/3/nl_langinfo) function to get system thousands separator.

**Comment by kppr0** [comment]
Sorry, everything is ok.

In locale.conf I had set LANG=en_US.UTF-8 & LC_NUMERIC=cs_CZ.UTF-8, but in locale.gen I had enabled only en_US.UTF-8 UTF-8 :-(
