### ISSUE TITLE
Wrong file mask in Search dialog

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#1477]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11212
Commit: 3d3263897
Build date: 2024/01/28
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.3.1

### Description

When you follow the steps shown in the video below, the file mask field in the Search dialog will be drawn wrong.

https://github.com/doublecmd/doublecmd/assets/79788982/ff1cb7b7-456c-4c3f-a5dd-44eb49f65cb8

**Comment by rich2014** [comment]
@Andreas0602

the issue cannot be reproduced on macOS 12.7 and macOS 13.6.

does it only appear on macOS 14?

can you test on other computers?

**Comment by rich2014** [comment]
@alexx2000

Alex, do you have any ideas?

**Comment by alexx2000** [comment]
I was able to reproduce this problem some time ago. But I cannot reproduce it now. I don't know how TComboBox is implemented under LCL-COCOA. But looks like a TComboBox consists of two controls: edit field and combobox. And sometimes their position is not synchronized. We can see that manual window resize recalculates positions.

**Comment by rich2014** [comment]
@Andreas0602 

have you set the fonts?

**Comment by rich2014** [comment]
TComboBox corresponds one-to-one to NSComboBox in LCL-
Cocoa.

however, in macOS itself, the internal implementation of NSComboBox does correspond to two controls, but this cannot be controlled by the APP.

> I was able to reproduce this problem some time ago. But I cannot reproduce it now. I don't know how TComboBox is implemented under LCL-COCOA. But looks like a TComboBox consists of two controls: edit field and combobox. And sometimes their position is not synchronized. We can see that manual window resize recalculates positions.
