### ISSUE TITLE
Unable to select and copy text from MacPreview

### ISSUE THREAD

**Issue by nitrostudios** [doublecmd/doublecmd#1481]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11223
Commit: a5009f63a
Build date: 2024/02/13
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 12.6.6

### Description

I'm unable to select and copy text from MacPreview when previewing the TXT files. Anyone else having the same issue?

**Comment by alexx2000** [comment]
I propose to disable MacPreview for text files. It works wrong with some formats, like .bat.

**Comment by nitrostudios** [comment]
Is there a way to use the native macOS preview, then? In finder it works without problems and can show and copy text, too. It would help with navigation when previewing files in the folder by using arrows to select the next/previous file, like in Finder.

**Comment by alexx2000** [comment]
MacPreview is a native preview.

**Comment by nitrostudios** [comment]
That's interesting since it look quite different from native preview.

**Comment by rich2014** [comment]
@nitrostudios 

it's an embedded Native Preview, to integrate with DC.

**Comment by rich2014** [comment]
@alexx2000 

how to identify whether it is a plain text file?

> I propose to disable MacPreview for text files. It works wrong with some formats, like .bat.

**Comment by alexx2000** [comment]
I guess we can use [FileIsText](https://wiki.freepascal.org/LazFileUtils) function.

**Comment by alexx2000** [comment]
No, in this case. Is no way to determine which formats QuickLook really supports?

**Comment by j2969719** [comment]
maybe simply
`EXT!=""&EXT!="TXT"&EXT!="BAT"` etc
https://ghisler.github.io/WLX-SDK/listgetdetectstring.htm

**Comment by alexx2000** [comment]
Yes, we can use this method as workaround. We can exclude most popular plain text formats.

**Comment by rich2014** [comment]
i'm afraid there are too many plain text formats.

**Comment by alexx2000** [comment]
Looks like it is a possible to determine file type supported or not, indirectly:
https://stackoverflow.com/a/56490217

**Comment by alexx2000** [comment]
I found a way how to determine which file types Quick Look supports. I am working on it implementation in the MacPreview.

**Comment by rich2014** [comment]
@alexx2000 

it's great.

just test d2bef61,  it works fine on macOS 12.

> I found a way how to determine which file types Quick Look supports. I am working on it implementation in the MacPreview.

**Comment by lprot** [comment]
Macpreview was not working properly in 1.1.12gamma. It was opening files in very small font. Selection was not working. Search was not working.
Now all listed is fixed in 1.1.13. Thank you!
![image](https://github.com/doublecmd/doublecmd/assets/2608545/ae2e40c8-0652-4bcb-b6c9-d3b3dd96ae9d)
