### ISSUE TITLE
[macOS] - Can't open under different user "because it may be damaged or incomplete."

### ISSUE THREAD

**Issue by air3ijai** [doublecmd/doublecmd#1484]
#### Version
```
Double Commander
Version: 1.1.10 beta
Revision: 387
Commit: a1e12af80
Build date: 2024/02/17
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.3.1
```

#### Description
Looks like it was already reported in 2018 and still not fixed - [0002082: App runs only for the user that installed it (no multi user support)](https://doublecmd.sourceforge.io/mantisbt/view.php?id=2082).

#### Reproduce
1. Install app under user-1
2. Run app under user-1 - 🟢 
3. Run app under user-2 - 🔴 
    > You can't open the application "Double Commander" because it may be damaged or incomplete.

   <img width="258" alt="Screenshot 2024-02-17 at 16 12 13" src="https://github.com/doublecmd/doublecmd/assets/88528265/06e03e7a-5b9a-4891-99c2-590d7fa1cf07">

#### Notes
1. `Info.plist` file permissions
    ```shell
    ls -la /Applications/Double\ Commander.app/Contents/Info.plist
    -rw-------  1 user-1  admin  2682 Feb 17 12:07 /Applications/Double Commander.app/Contents/Info.plist
    ```
2. App icon is not shown in Applications folder
    <img width="719" alt="Screenshot 2024-02-17 at 16 37 28" src="https://github.com/doublecmd/doublecmd/assets/88528265/50a33351-57b6-4318-958c-13ceda53ed4d">

#### Fix
To fix the issue we need to change `Info.plist` file permissions
```shell
sudo chmod 644 /Applications/Double\ Commander.app/Contents/Info.plist
```

**Comment by rich2014** [comment]
@air3ijai 

fixed.

please download from https://doublecmd.sourceforge.io/site/eng/snapshots.php and test it.

**Comment by air3ijai** [comment]
Works as expected, thanks!
