### ISSUE TITLE
DC does not show Time Machine disk content

### ISSUE THREAD

**Issue by SharerPL** [doublecmd/doublecmd#1485]
### Version

Double Commander 1.1.9 and 1.1.10, Mac OsX 14.2.1, ARM processor

### Description

All other programs show Time Machine disk content (with TM switched off). I've compiled DC 1.1.10 for test from sources and many things did not work properly (e.g. keyboard :) ) but the disk content was visible. In the downloaded compiled version it disappeared again :) . Tested on 10.1.9 and 10.1.10, Apple ARM processor.

**Comment by alexx2000** [comment]
Do you execute this command:
`xattr -cr "/Applications/Double Commander.app/"`

Also you can try to update digital signature:
`codesign --deep --force --verify --verbose --sign '-' '/Applications/Double Commander.app'`

Change path if needed.

**Comment by SharerPL** [comment]
@alexx2000 

Thanks for your replay. I don't think it is a general rights problem. I'm trying to copy my backup data manually from one external HDD to another. Both are on the same USB hub and both are mounted in the /Volumes folder. Nevertheless they differ in format, the new one, that is seen in DC, is APFS while the Time Machine one is "Mac OS Extended". Maybe that helps, sorry I did not notice that before, I assumed that TM HDDs are also formatted as APFS.

**Comment by alexx2000** [comment]
You wrote that DC sees the disk content when you compile it from sources. So it is not a DC problem. Here https://github.com/doublecmd/doublecmd/issues/1333#issuecomment-1802430697 was a similar problem. Have you tried the methods suggested above to solve the problem?

**Comment by rich2014** [comment]
@SharerPL 

you need to grant `Full Disk Access` to Double Commander in the `System Settings` of macOS
