### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by vvvvvx** [doublecmd/doublecmd#1487]
### Version

Double Commander 1.1.9 beta
Revision: 350
Commit: b220a50e9
Build: 2024/01/23
Lazarus: 3.0.0.3
Free Pascal: 3.2.2
Platform: x86_64-Linux-gtk2
System: Artix Linux
Desktop Environment: Xfce
Widgetset library: GTK 2.24.33
This program is free software released under terms of GNU GPL 2

### Description

When I open  Show/Quick View Panel and press Backspace key,the proram exit  immediately. 
error:
QWidget: Must construct a QApplication before a QWidget

**Comment by alexx2000** [comment]
I guess you installed incompatible Qt plugin. Remove it or install Double Commander Qt instead GTK2.

**Comment by vvvvvx** [comment]
> I guess you installed incompatible Qt plugin. Remove it or install Double Commander Qt instead GTK2.

I installed doublecmd-qt6,the bug is still there.

**Comment by j2969719** [comment]
can you show which wlx plugins are used, **qt5** plugins can also cause this crash with doublecmd-**qt6**

**Comment by alexx2000** [comment]
Double Commander and plugin widgetset should be same. So if you install DC Qt6 version then you should use Qt6 plugin version.

**Comment by vvvvvx** [comment]
Changed the version to doublecmd-qt5, error gone.

**Comment by vvvvvx** [comment]
I removed all gtk2 plugin,errors gone.
