### ISSUE TITLE
DC hangs while open big bz2 archive 

### ISSUE THREAD

**Issue by it800** [doublecmd/doublecmd#1492]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

I have an 8GB bz2 archive. DC (portable version, nothing was done in it after the initial unpacking) hangs for ever when I try to open that archive (double click on the file or press Enter on it).

![image](https://github.com/doublecmd/doublecmd/assets/146009019/0acbf292-31a4-434a-ad24-04993189f9b6)

**Comment by alexx2000** [comment]
DC extracts it into temp that can take a very long time for a such large archive, see: #471, #458.
