### ISSUE TITLE
Auto fill in History for [F7] Create New Directory modal

### ISSUE THREAD

**Issue by 2CLC** [doublecmd/doublecmd#1494]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Create New Directory modal *saves history of newly created directories*. That's very useful function.
**However when you start typing any folder name it auto fills from the history.**

This is **not always desirable and slows down the workflow significantly**.
From my research there's no way of disabling this behavior in Configuration / Options

I believe it's a UX bug but move it to feature requests section if desired.

**Comment by zieren** [comment]
Double Commander
Version: 1.1.22 gamma
Revision: 662
Commit: 6baafba86
Build date: 2025/01/21
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt6
OS version: Fedora release 41 (Forty One)
Widgetset library: Qt 6.8.2

Thank you for addressing this problem. It's also a privacy issue: The dialog leaks recently created directory names (to the evil maid).

I'm not familiar with the source code, but from looking at 14aa2b6 ISTM there should be a setting in the "Create directory" (F7) dialog, but I'm not seeing it. Am I missing something here? I'm still seeing a combobox with the names of recently created directories, and it's still autocompleting.

**Comment by alexx2000** [comment]
You can disable auto-complete using button at the right of input field.

**Comment by alexx2000** [comment]
> The button doesn't work for me in the Qt6 version.

So it is a Lazarus/Qt6 bug.

> But in both versions there is no visual indication of its state (depressed or not).

The button appearance depends on the Qt theme.

> History saving refers to the navigation history, not creation history, right?

No, this option (CreateDirectoriesHistory) controls the creation history saving.

**Comment by zieren** [comment]
> > The button doesn't work for me in the Qt6 version.
> 
> So it is a Lazarus/Qt6 bug - https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41432

Thanks for following up! And good to see it's already fixed.

> > But in both versions there is no visual indication of its state (depressed or not).
> 
> The button appearance depends on the Qt theme.

Should we file a bug for that too? Happy to do it if you point me in the right direction.

> > History saving refers to the navigation history, not creation history, right?
> 
> No, this option (CreateDirectoriesHistory) controls the creation history saving. It is a hidden option.

Yes, it's working. I had expected it to disable storing directory creation history within one session, i.e. in RAM.
