### ISSUE TITLE
Font increase & decrease arrows in options continue adding or subtracting

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1498]
### Version

Double Commander 
1.2.0 alpha
Qt5 / Qt6
portable
Debian based Linux distro

### Description

If you go into Options - Fonts and you click on the up or down arrows to increase or decrease font sizes the numbers continue to increase or decrease without stopping.  Expected behavior is one click equals one font point size up or down.
Currenlty it acts like one of those self inflating rafts where you pull a pin and it begins to quickly inflate and there is no stopping it :)   (Well in this case all you have to do is just click your mouse in field and it will stop but it is shocking at first especially if you try increasing font size and it inflates like balloon)

This does not appear to happen in the GTK2 version.

Hope this helps

**Comment by alexx2000** [comment]
Lazarus 3.0 [bug](https://forum.lazarus.freepascal.org/index.php/topic,66419.msg508828/topicseen.html).

**Comment by alexx2000** [comment]
Looks like it is already fixed in [Lazarus 3.2](https://forum.lazarus.freepascal.org/index.php/topic,66420.msg508884).
