### ISSUE TITLE
Context menu font truncation on top

### ISSUE THREAD

**Issue by ingorichter** [doublecmd/doublecmd#150]
There is not enough space between each line in the context menu and that truncates the lines at the top.

Double Commander
Version: 0.9.10 beta
Revision: 9640
Build date: 2021/01/10
Lazarus: 2.0.3.0-61194
FPC: 3.0.4
Platform: x86_64-Darwin-qt4
OS version: Mac OS X 10.16.0

Widgetset library: Qt 4.8.6, libQt4Pas 4.5.3

<img width="379" alt="image" src="https://user-images.githubusercontent.com/86214/128027369-d17c09ac-b594-427b-a425-3f619555be06.png">

**Comment by alexx2000** [comment]
DC 0.9.10 incompatible with modern macOS. Try version 1.0 from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by ingorichter** [comment]
Yes, the snapshot looks much better. Thank you
