### ISSUE TITLE
Tooltip problem on Windows in dark mode

### ISSUE THREAD

**Issue by pkzc** [doublecmd/doublecmd#1502]
### Version

Double Commander
Version: 1.1.10 beta
Revision: 387
Commit: a1e12af80
Build date: 2024/02/17
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

The font size in tooltips in dark mode of the Windows version is too big for the tooltip area. In light mode the font size is smaller and the whole text fits in the area.

It is true that I messed about with Windows fonts in order to increase its tiny system font size, but I managed only to change the font type, the size remained the same no matter how hard I tried.

But it is still a surprise that DC takes the tooltip font in dark mode from somewhere else than it does in light mode.

It seems also somewhat strange to me that the dark mode tooltip area is a borderless white patch with gray letters. 

Please note that on Fedora Linux 39 DC tooltips are nice-looking in both dark and light modes.

Here are the illustrations from the Windows DC: 

![dark-tooltip](https://github.com/doublecmd/doublecmd/assets/23018794/29bf7109-dff0-434d-bee4-95216cb7d3f1)

![light-tooltip](https://github.com/doublecmd/doublecmd/assets/23018794/99f84ee1-4578-46a8-b585-8b3d9d2c5160)

**Comment by alexx2000** [comment]
I cannot reproduce. Which font and where you did change?

**Comment by pkzc** [comment]
OK, then I messed up something in windows. Something like defining DejaVu Sans Condensed as substitution font for the Segoe UI fonts in the registry, but let it go, upgarding to Windows 11 will solve it. Sorry for making the trouble.
