### ISSUE TITLE
Lua Dialogs.InputListBox activate OK when you type in letter O

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1526]
### Version

Double Commander 
1.2.0 alpha
Qt6 / Laz 3.0
portable
Debian based Linux distro

### Description

Now that a kind of “quick search” has been added to Dialogs.InputListBox used in Lua scripts allowing users to type to select items in the list, if you type the letter “O” to find an item in the dialogs list, it appears to activate the "O" in the “OK” button and closes the dialog box automatically.

I tested the DC dialog for example the “New Directory” tool & regular Lua input dialog boxes and they both appear to work fine, just seems to be the Dialogs.InputListBox one.

Hope this helps

**Comment by Skif-off** [comment]
It seems to be working fine for me.
Do you use "O" or Alt+"O"?

**Comment by advice2020** [comment]
@Skif-off 
Hello, thank you for your response.
That is strange, I am just using "O"
Allows me to type all the other letters and finds the items on the list but if any of the column set names contain an "O" in them, then it activates the "OK" applying / closing the dialog.
Tested / happens in both DC QT5 / Laz 2.2.6 and DC QT6 / Laz 3.0
I also mentioned that it does not occur in other dialogs such as DC New Directory, so it is not a stuck Alt key or anything.

Hmmm, does anyone else experience this, or is it just me?

**Comment by advice2020** [comment]
I was wondering if any other users would be willing to test this out for me?
Can use any Lua script that contains a "Dialogs.InputListBox"
If you do not know of any to test, the following script was kindly provided to me by "Skif_off" if anyone would like to give it a try.
As he mentioned in his reply above, he does not experience this issue, so so far we are at 50-50.  I was wondering if anyone else experiences this issue or is it only me?

Thank You to anyone willing to give this a try

This Lua tool provides a dialog box that shows list of DC column set names, similar to the context menu you get if you RMB click on your column header.  This tool allows access to this column list using a keyboard shortcut.
`-- ChooseColumnsSet.lua (cross-platform)
-- 2024.03.10
--[[
Show list of columns sets.

How to use: add button with
internal command: cm_ExecuteScript
params:
  path-to-script-ChooseColumnsSet.lua

EntitiesToUTF8():
  https://stackoverflow.com/questions/18694131/how-to-convert-utf8-byte-arrays-to-string-in-lua
]]

local sScrName = debug.getinfo(1).source
if string.sub(sScrName, 1, 1) == "@" then
  sScrName = string.sub(sScrName, 2, -1)
end
sScrName = SysUtils.ExtractFileName(sScrName)

local sData

local function EntitiesToUTF8(dec)
  local bytemarkers = {{0x7FF, 192}, {0xFFFF, 224}, {0x1FFFFF, 240}}
  if dec < 128 then return string.char(dec) end
  local cbs = {}
  for bytes, vals in ipairs(bytemarkers) do
    if dec <= vals[1] then
      for b = bytes + 1, 2, -1 do
        local mod = dec % 64
        dec = (dec - mod) / 64
        cbs[b] = string.char(128 + mod)
      end
      cbs[1] = string.char(vals[2] + dec)
      break
    end
  end
  return table.concat(cbs)
end

local function ClearString(s)
  if string.find(s, "&", 1, true) ~= nil then
    s = string.gsub(s, "&amp;", "&")
    s = string.gsub(s, "&apos;", "'")
    s = string.gsub(s, "&lt;", "<")
    s = string.gsub(s, "&gt;", ">")
    s = string.gsub(s, "&#%d+;", function(e)
          return EntitiesToUTF8(tonumber(string.sub(e, 3, -2)))
        end)
    s = string.gsub(s, "&#x%x+;", function(e)
          return EntitiesToUTF8(tonumber(string.sub(e, 4, -2), 16))
        end)
  end
  return s
end

local function GetName(n)
  local n1, n2 = string.find(sData, "<Name>", n, true)
  n1 = string.find(sData, "</Name>", n2, true)
  local s = string.sub(sData, n2 + 1, n1 - 1)
  n2 = string.find(sData, "<FileSystem>", n1, true)
  if string.sub(sData, n2 + 12, n2 + 26) == "&lt;General&gt;" then
    return s
  else
    return nil
  end
end

local sConfigFile = os.getenv("COMMANDER_INI")
if sConfigFile == nil then
  Dialogs.MessageBox("Unknown error: sConfigFile == nil", sScrName, 0x0030)
  return
end
local h, err = io.open(sConfigFile, "rb")
if h == nil then
  Dialogs.MessageBox("Error: " .. err, sScrName, 0x0030)
  return
end
sData = h:read("*a")
h:close()

local aSets = {}

local n1, n2, sN
local c = 1
local n3 = string.find(sData, "<ColumnsSets ", 1, true)
while true do
  n1, n2 = string.find(sData, "<ColumnsSet ", n3, true)
  if n1 == nil then break end
  sN = GetName(n2)
  if sN ~= nil then
    aSets[c] = ClearString(sN)
    c = c + 1
  end
  n3 = n2
end
if #aSets == 0 then
  Dialogs.MessageBox("Unknown error: #aSets = 0", sScrName, 0x0030)
  return
end

local sRes = Dialogs.InputListBox(sScrName, "Columns sets:", aSets, aSets[1])
if sRes ~= nil then
  DC.ExecuteCommand("cm_ColumnsView", "columnset=" .. sRes)
end`

**Comment by JonnyTech** [comment]
> (Again I apologize I have no idea why I cannot get any formatting to work in my Github posts)

Use three backticks to enclose text spanning multiple lines ` ```hello``` `

> This tool allows access to this column list using a keyboard shortcut.

Your code above contains an error. Luckily I [found the post](https://doublecmd.h1n.ru/viewtopic.php?p=43040#p43040) you should have linked.

Result: Issue **confirmed**, but **only** in the `QT` build, with `GTK` it behaves correctly.

```
Double Commander
Version: 1.2.0 alpha
Revision: 11264
Commit: 09238c8
Build date: 2024/03/20
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23.2 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1
```

With GTK you get a dialog in the corner show what key was pressed.

![image](https://github.com/doublecmd/doublecmd/assets/3584732/ba50e343-dccf-47f3-9c78-53b0402f1bd4)

With QT you press a key but no corner dialog is shown.

![image](https://github.com/doublecmd/doublecmd/assets/3584732/92870614-efe3-4a49-b4c4-c521bc042e58)

If the key pressed is indeed the letter `o` then the dialog is immediately closed.

**Comment by advice2020** [comment]
@JonnyTech
Ahh hello again, thank you for your response.
CODE ERROR FOUND
I apologize for not leaving a link, the tool was kind of in the process of still being developed and didn't want to link just yet.  Well what was your reason for finding / needing to find the post?
You mentioned that the code above contains an error? what is the error in the code?
If you let me know what the error is, maybe I could mention it to be looked at.

ISSUE CONFIRMATION
Thank you for trying this out / confirming this for me.
Okay so this verifies that it is not just me experiencing something like this.

GITHUB FORMATTING
Also thank you for letting me know about the ```
-There is no way to make a code box with a scrollbar so the post isn't so long in Github?
-Do you or anyone else know if Bold still does not work in Github?
putting ** on each side is suppose to work
I tried *** on each side and it turns the text italic / which _ underscores on each side do as well

Anyways, thank you very much for your help with this
Also thank you again for the help you have provided for me in the past as well, I appreciate it.

**Comment by advice2020** [comment]
@Skif-off
Do you remember if you tested this out in GTK or QT5 / QT6?
If it was GTK then that would align with the results above.

**Comment by JonnyTech** [comment]
> Well what was your reason for finding / needing to find the post?

Copy/pasting your code did not work whereas from the forum did.

> You mentioned that the code above contains an error? what is the error in the code? 

Sorry, I had neither the time nor inclination to investigate.

> There is no way to make a code box with a scrollbar so the post isn't so long in Github?

Please no scrollboxes, long code blocks are preferable.

> Do you or anyone else know if Bold still does not work in Github?

Bold does work: **this is a test**. Maybe you are putting spaces there. Don't. It should be `**this is a test**`. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

> Anyways, thank you ... I appreciate it.

You're very welcome.

**Comment by JonnyTech** [comment]
<details>
  <summary>You can always use a spoiler</summary>
 
```
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
console.log("...for very long code blocks!");
```
</details>

**Comment by advice2020** [comment]
@JonnyTech 
Oh, okay the "error" you were talking about was not being able to copy the code I provided.
No I didn't expect you to analyze the code, when you mentioned there was an error, I thought you meant with the actual code itself.
CODE LENGTH
So it is preferred to paste very long code blocks like I did?  I would have thought that other would be upset about this.  Just saw your spoiler idea, that could work.
I saw the following page how to achieve this, I will give this a try.
https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287
BOLD TEXT
The bold example does not appear bold, it shows up with a different background color same as how it looks when code is added with ```
I looked this up recently and someone reported this to Github that bold text was not working, but not sure if this was fixed?

Thanks again for all the links / knowledge shared / help.

**Comment by JonnyTech** [comment]
Sorry to all, I know that this has gone off topic.

> The bold example does not appear bold, it shows up with a different background color same as how it looks when code is added with ```

Have you tried another browser? I suspect that an addon or extension or similar is injecting css into your page - bold and all other formatting work correctly for me. Try testing with a site such as https://markdownlivepreview.com/ or https://markdownpreviewlive.netlify.app/ to be sure.

**Comment by advice2020** [comment]
I decided to close this for clarity.
I created a new post for this issue with the following issue number 1899
