### ISSUE TITLE
Comparing files by content locks up DC

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#1527]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11258
Commit: 2f4a175
Build date: 2024/03/13
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23.2 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

### Description

Trying to compare two files by content locks up Double Commander. No error is generated.

The two files in [cmp.zip](https://github.com/doublecmd/doublecmd/files/14606920/cmp.zip) always reproduce the issue. Tested with latest AppImage.

**Comment by alexx2000** [comment]
It is due super long line in `min` file. I added protection.

**Comment by JonnyTech** [comment]
Thank you.
