### ISSUE TITLE
WCX support

### ISSUE THREAD

**Issue by exrom** [doublecmd/doublecmd#1535]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Linux Mint 21.2 Victoria

Widgetset library: GTK 2.24.33

### Description

Hello,

according to https://doublecmd.sourceforge.io/ WCX built for tcmd plugins are supported.

I try to add this WCX plugin https://sourceforge.net/projects/dircbm/files/dircbm%20binaries/V0.13/ and i get:
"This plugin in built for Double Commander for Windows 64 bit. It cannot work with Double Commander for Unix 64 Bit!"
This happens on both dircbm.wcx and dircbm.wcx64

Am i doing something wrong?
What does this message mean? I mean, tcmd  is a windows application, so all wcx are likely built for windows too. Do any wcx then work on unix at all?
Is this a bug in doublecmd? If so, are there plans to fix it?
Is this to be fixed in the wcx? If so, what could i do (or ask the author to do) in order to solve this issue?
Would be great if you could explain (in the README?) what the technical background for those incompatibilities are.

Besides that, thanks for building double commander. I love it and it allowed me to switch to linux :)

PS: the search form links to non-existing mantis

**Comment by alexx2000** [comment]
Hi,

> Am i doing something wrong? What does this message mean?

Yes, you cannot use Windows plugin under Linux and vice versa.

> Is this a bug in doublecmd?

No.

> Is this to be fixed in the wcx? If so, what could i do (or ask the author to do) in order to solve this issue?

Yes, plugin author should build a Linux plugin version. See [plugins development](https://github.com/doublecmd/doublecmd/wiki/Plugins-development).
