### ISSUE TITLE
Command+drag-n-drop does not work for file move on macOS

### ISSUE THREAD

**Issue by nitrostudios** [doublecmd/doublecmd#1536]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11267
Commit: 26023ec1e
Build date: 2024/03/24
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 12.6.6

### Description

When I want to move file, not copy, with drag and drop, it does not work by using Command+drag-n-drop. Thank you very much for your help, appreciate it.

**Comment by alexx2000** [comment]
DC uses Ctrl+Drag&Drop to move. Should it use Command+Drag&Drop?

**Comment by nitrostudios** [comment]
Thank you Alex for the explanation. Yes, on macOS it would be helpful, since it's the same command as in Finder:) It's similar to the command I've mentioned here: https://github.com/doublecmd/doublecmd/issues/1480#issue-2135888621

**Comment by nitrostudios** [comment]
Thank you very much, Alex, I've downloaded the latest build and it works! Appreciate it :)
