### ISSUE TITLE
Double Commander crashes when trying to view AVIF image

### ISSUE THREAD

**Issue by tyristori** [doublecmd/doublecmd#1538]
### Version

Double Commander
Version: 1.1.11 beta (doublecmd-gtk2 package from official Arch Linux extra repository)
Revision: 410
Commit: f1b449635
Build date: 2024/03/13
Lazarus: 3.2.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Arch Linux

Widgetset library: GTK 2.24.33

### Description

Double Commander crashes when trying to view AVIF image with internal viewer.

Also if folder has AVIF image then thumbnails view also crashes Double Commander.

When Double Commander is started from terminal these errors are displayed when Double Commander crashes:

corrupted size vs. prev_size
Aborted (core dumped)

**Comment by alexx2000** [comment]
I fixed a crash. But libheif library works wrong with some images so I disabled AVIF images support.

**Comment by alexx2000** [comment]
Fixed.
