### ISSUE TITLE
Autosave on system shutdown/restart

### ISSUE THREAD

**Issue by tomhanax** [doublecmd/doublecmd#154]
I have similar problem that is pictured here: https://doublecmd.sourceforge.io/mantisbt/view.php?id=2564 
I am using MATE desktop on Linux and when I shutdown the computer the application state is lost.
I don't care for crashes or periodic autosave as stated in the mantis issue, I find sufficient to save the state on the terminate signal.
Is it possible to implement it in the current application technology?

**Comment by alexx2000** [comment]
I added SIGTERM handling but I don't sure that help in this case. I checked with Xfce and it does not help.
It is needed to interact with session manager in this case. But I cannot find universal way.

**Comment by tomhanax** [comment]
Great to hear that and thanks for the time and work, surely appreciate that. How could I test it? I use opensuse repo, is there a fixed version?

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/wiki/Repositories-Linux

**Comment by tomhanax** [comment]
I downloaded latest SVN build but unfortunately it does not work for me either. But anyway, thank for the effort.

**Comment by rubaboo** [comment]
Hi @alexx2000 , could you reopen this issue please. Unless it's a definite "won't fix", for whatever reason. The issue is still present. DC does not remember the current directories, unless I close it before shutting down the OS. I'm using XFCE. Other programs are able to do that, so there must be a way...

**Comment by alexx2000** [comment]
Hi, it cannot be fixed, because no standard way to do it.
