### ISSUE TITLE
doublecmt open *.tar.xz or *.xz is empty on Mac

### ISSUE THREAD

**Issue by Liuzhj** [doublecmd/doublecmd#1545]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.0

### Description

when enter tar.xz or xz , not file list , is empty 。
and can't be unarchive, is nothing。
<img width="714" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/6b5f90fb-3dbc-4cb8-a630-57cea726954c">

**Comment by alexx2000** [comment]
You need to install `liblzma.dylib` library for .xz archive support.

**Comment by Liuzhj** [comment]
> You need to install `liblzma.dylib` library for .xz archive support.

how to install `liblzma.dylib`  on my Mac? 
I installed `brew install xz` and open the .xz file in doublecmd,  and it is empty also.

**Comment by Liuzhj** [comment]
<img width="628" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/145768f0-6cf9-4d44-837c-a84dd22ab2c5">

**Comment by alexx2000** [comment]
I don't sure that DC can find it there. It should be in the one of `$HOME/lib;/usr/local/lib;/usr/lib` directory. I have `liblzma.dylib` symlink in the `/usr/local/lib` and it works. Also check Zip-plugin association, it should be associated with `xz` extension.

**Comment by Liuzhj** [comment]
> I don't sure that DC can find it there. It should be in the one of `$HOME/lib;/usr/local/lib;/usr/lib` directory. I have `liblzma.dylib` symlink in the `/usr/local/lib` and it works. Also check Zip-plugin association, it should be associated with `xz` extension.

Thank you very much , Zip-plugin is support `.xz` extension .
But why not be associated it with Zip-pluggin at release ?

**Comment by alexx2000** [comment]
Because macOS does not have `liblzma` library by default.

**Comment by Liuzhj** [comment]
> Because macOS does not have `liblzma` library by default.

humm?   plugin WCX zip support `.xz` and `.txz`, and not need `liblzma` library.

<img width="864" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/278b6883-13dc-4c44-a21b-3aa3cdd0e414">

I mean why not association `.xz` and `.txz`  to zip.wcx
Because `/usr/bin/tar` not list file in `.xz` and `.txz`
<img width="732" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/e4496e30-dd6a-4d35-aca4-73df93af9f4b">

**Comment by alexx2000** [comment]
> humm? plugin WCX zip support `.xz` and `.txz`, and not need `liblzma` library.

No, Zip-plugin cannot work with `.xz` without `liblzma` library. If it works with `.xz` then it found `liblzma` library.

> Because `/usr/bin/tar` not list file in `.xz` and `.txz`

By [default](https://github.com/doublecmd/doublecmd/blob/e2cf8a099d8ecfb840f938c94cff9cc64ce81fe2/default/multiarc.ini#L106) `tar` accociated only with `.txz` extension. Latest `tar` version can work with `.txz` at least under Linux. Anyway I think this configuration should be removed from archivers section, it is outdated.

**Comment by Liuzhj** [comment]
> > humm? plugin WCX zip support `.xz` and `.txz`, and not need `liblzma` library.
> 
> No, Zip-plugin cannot work with `.xz` without `liblzma` library. If it works with `.xz` then it found `liblzma` library somewhere.
> 
> > Because `/usr/bin/tar` not list file in `.xz` and `.txz`
> 
> By [default](https://github.com/doublecmd/doublecmd/blob/e2cf8a099d8ecfb840f938c94cff9cc64ce81fe2/default/multiarc.ini#L106) `tar` accociated only with `.txz` extension. Latest `tar` version can work with `.txz` at least under Linux. Anyway I think this configuration should be removed from archivers section, it is outdated.

ok, get it . 
And I execute `brew uninstall xz` on my MAC.
And I don't  execute install `liblzma` with some command , may be `liblzma` is on my MAC by default. 
Thank you very much again .
