### ISSUE TITLE
Quick search box to find required command by name [feature request]

### ISSUE THREAD

**Issue by selivan** [doublecmd/doublecmd#155]
Like "Command Pallete"(Ctrl+Shift+P) in VSCode or "Find Action" in PyCharm.

**Comment by Skif-off** [comment]
Shift+F12

**Comment by selivan** [comment]
@Skif-off  Thank you, that works.

I'm closing this issue, but creating a new one to add this option to program menu, "Help" or "Command". Now it is not there, so new users like me are very unlikely to learn about it.

**Comment by selivan** [comment]
New issue: #157
