### ISSUE TITLE
Unable to set value for lines to scroll higher than 1 on Mac

### ISSUE THREAD

**Issue by muxav** [doublecmd/doublecmd#1555]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.13.6

### Description

Neither GUI options dialog nor altering the value in config file allows for more than 1 lines to scroll. Works on Windows, does not work on Mac OSX.

**Comment by camxcube** [comment]
Me too. I've met the same issue. Even now I updated to 1.1.13~453 version. It still got the same bug.

**Comment by camxcube** [comment]
I just found a work-around. Go to "/Users/Cam/Library/Preferences/doublecmd/doublecmd.xml".

Change the digit value of the following value to whatever you like.

<WheelScrollLines>4</WheelScrollLines>

**Comment by rich2014** [comment]
fixed by 0f2e388

range can be set from 1 - 10 now.

please download the snapshoot and test it.

**Comment by muxav** [comment]
Great Job, Rich. Now it works as expected!

Double Commander
Version: 1.1.15 gamma
Revision: 505
Commit: 28125592a
Build date: 2024/06/12
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.5.0
