### ISSUE TITLE
No timestamp included in "Date" Column on Mac

### ISSUE THREAD

**Issue by muxav** [doublecmd/doublecmd#1556]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.13.6

### Description

in Main View, "Date" Column only shows date but no timestamp. Works on Windows, does not work on Mac OSX.

**Comment by alexx2000** [comment]
Works fine. Check your [settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigView).

**Comment by muxav** [comment]
Ahh sorry, didn't notice. Obviously the default setting differs between Windows an Mac OS.
Thanks for the quick reply!

**Comment by alexx2000** [comment]
Yes of course. DC use system settings for date format by default. DC show time by default.
