### ISSUE TITLE
enter `.zip` ,the file name gibberish

### ISSUE THREAD

**Issue by Liuzhj** [doublecmd/doublecmd#1560]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.0

### Description

<img width="730" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/25645b44-2fe5-4ec7-a671-cd76705017ed">

the file name is CHINESE， but it's gibberish in zip

**Comment by alexx2000** [comment]
Are you using CHINESE locale in macOS?

**Comment by Liuzhj** [comment]
yes
<img width="491" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/eb46d3b6-979f-4768-b27d-029114184a11">

some zip file the file name has CHINESE is normal，but some zip file has CHINESE abnormal, I don't know why.

and I used maczip app open the zip file is normal all.

**Comment by Liuzhj** [comment]
[scripts.zip](https://github.com/doublecmd/doublecmd/files/14904137/scripts.zip)
ok

**Comment by Liuzhj** [comment]
> It depends on the zip format and a file name. New format stores file names in Unicode, while old format stores file name in non-Unicode. No way to determine encoding in the second case at 100%. We can only guessing. If you attach a sample bad zip file then I can look at it.

hello, The file has some secret info, I will send a mail to you

**Comment by Liuzhj** [comment]
> It depends on the zip format and a file name. New format stores file names in Unicode, while old format stores file name in non-Unicode. No way to determine encoding in the second case at 100%. We can only guessing. If you attach a sample bad zip file then I can look at it.

Are you received the mail and attach file.

**Comment by alexx2000** [comment]
Yes.

**Comment by alexx2000** [comment]
Looks like DC cannot determine locale on your system. Execute DC from terminal
`/Applications/Double Commander.app/Contents/MacOS/doublecmd`
and copy output here.

**Comment by alexx2000** [comment]
Yes, system language determines wrong. I will fix it.

**Comment by Liuzhj** [comment]
> Yes, system language determines wrong. I will fix it.

excellent ！

**Comment by alexx2000** [comment]
Fixed, try with latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by Liuzhj** [comment]
> Fixed, try with latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

I get the latest snapshot, That's right, It's fixed.
<img width="734" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/48df6187-c83b-4328-ba4c-d77cdce69729">
