### ISSUE TITLE
Could not ordered by create time for folders

### ISSUE THREAD

**Issue by warkcod** [doublecmd/doublecmd#1562]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11284
Commit: 1ee04fc7c
Build date: 2024/04/08
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.4.1

### Description

<img width="873" alt="image" src="https://github.com/doublecmd/doublecmd/assets/131120720/1229483f-839c-4e6c-9b46-12634a498568">

As shown in the screenshot, when I click ordered by create time, it works fine for files, but not for folders

**Comment by alexx2000** [comment]
Check your [sorting settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigView), choose `Sorting directories` -> `sort like files and show first`.

**Comment by warkcod** [comment]
@alexx2000 Thank you very much, I would like to suggest to set "sort like files and show first" by default just as total commander does, Thanks.

**Comment by alexx2000** [comment]
It is already a default setting from 2021 year. I guess you had a some old config.
