### ISSUE TITLE
auto refresh invalid

### ISSUE THREAD

**Issue by Liuzhj** [doublecmd/doublecmd#1563]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11284
Commit: 1ee04fc7c
Build date: 2024/04/08
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.0

### Description

- enable auto refresh
  <img width="774" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/82f02972-48f5-404b-8283-20e9b2d7b9c3">
- order by date desc
  <img width="734" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/a15455da-4aad-449a-acc0-f652914a2a57">
- use modify attribute modify time of file
  <img width="360" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/fba58d77-4a6f-40e4-ae8d-2b2f23e2731c">
- the file sort nothing
  <img width="721" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/74fabd1d-2510-4f51-abd9-dbb5df231df3">

- must be used butten "auto refresh"
  <img width="276" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/db6f75f4-81d6-443a-be3d-1ec29a9e2fb2">

**Comment by alexx2000** [comment]
Check your [sorting settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigView), choose `Move updated files` -> `to sorted position`.

**Comment by Liuzhj** [comment]
> Check your [sorting settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigView), choose `Move updated files` -> `to sorted position`.

yes ,you are right ,but the setting to default setting?

**Comment by alexx2000** [comment]
I don't know how is better by default.

**Comment by Liuzhj** [comment]
ok ,  thank you very much .

**Comment by antodc** [comment]
@alexx2000 Just a (very) minor issue. I noticed that in the Italian version there is an extra space before 'to sorted position', that is ' alla posizione ordinata'. Maybe you can remove that space at some point. :-)

**Comment by alexx2000** [comment]
> Maybe you can remove that space at some point. :-)

Done.
