### ISSUE TITLE
rename contents of ".zip" archives

### ISSUE THREAD

**Issue by Liuzhj** [doublecmd/doublecmd#1564]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11284
Commit: 1ee04fc7c
Build date: 2024/04/08
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.1.0

### Description

https://github.com/doublecmd/doublecmd/issues/458
Opening ".tar.bz2" archives takes a long time, can't rename contents of ".zip" archives

<img width="577" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/64234a1b-46f3-4b5b-a0af-769e67c395f6">

i try to rename file in zip archives, but is not work , i want to know is normal ?

**Comment by alexx2000** [comment]
It is normal, rename in archives is not supported.

**Comment by Liuzhj** [comment]
> It is normal, rename in archives is not supported.

has any plan ?  and I test rename in zip file with Totalcommander , it's support. want has rename file in zip with doublecmd. 

to new feature.

**Comment by Liuzhj** [comment]
and in zip file click right button, only exclude reneme can't to use , why don't to remove it ? or support it ? 

<img width="560" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/e24af371-d416-4a12-a49c-bc95746448ee">

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/discussions/1192
