### ISSUE TITLE
Wrong panel display: too short names truncating

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1565]
### Version

Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

'Brief view' is active.

1. make new dir ~/T and make these 3 filenames there:
```
-rw-rw-r-- 1 user user 0 апр  9 16:34 new.txt
-rw-rw-r-- 1 user user 0 апр  9 16:34 wwwwwwwwwwwwww.txt
-rw-rw-r-- 1 user user 0 апр  9 16:34 wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
```

panel now looks like:

![dc1](https://github.com/doublecmd/doublecmd/assets/4154978/393868c3-fcbd-4cb3-81f4-d8f309de5e30)

2. go to upper dir, to reset some internal vars. go back to T.

3. rename longest name to 'ee'. file list is now:
```
-rw-rw-r-- 1 user user 0 апр  9 16:34 ee
-rw-rw-r-- 1 user user 0 апр  9 16:34 new.txt
-rw-rw-r-- 1 user user 0 апр  9 16:34 wwwwwwwwwwwwww.txt
```

panel now looks wrong:

![dc2](https://github.com/doublecmd/doublecmd/assets/4154978/3135720e-8f00-4920-abd5-8ff01740c958)

**Comment by alexx2000** [comment]
#321
