### ISSUE TITLE
Access violation on Tab - Close All Tabs

### ISSUE THREAD

**Issue by makadizsolt** [doublecmd/doublecmd#1570]
### Version

Double Commander
Version: 1.1.12 gamma
Revision: 436
Commit: c8f17e36a
Build date: 2024/04/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 22.04.4 LTS

Widgetset library: Qt 5.15.3, libQt5Pas 5.6.1

### Description

Single tab closing is working all right. But the "Close All Tabs" function on the right click menu of a tab gives an Access violation. See the .err file: 
[doublecmd_err.zip](https://github.com/doublecmd/doublecmd/files/14937766/doublecmd_err.zip)

**Comment by JonnyTech** [comment]
Confirmed

- only on qt build, the gtk build works correctly
- only if there are tabs to the left when closing

**Comment by alexx2000** [comment]
Lazarus bug. I added workaround.
