### ISSUE TITLE
"cd" command line without parameters goes to users directory

### ISSUE THREAD

**Issue by adlabac** [doublecmd/doublecmd#1578]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Change directory command "cd" with no directory is specified changes the current directory to users directory (%USERPROFILE% on Windows) . The expected behaviour is to stay in the current directory.

**Comment by alexx2000** [comment]
Not a bug. Command `cd` opens a home directory when called without directory name. This is how it works in the DC.

**Comment by adlabac** [comment]
Aha, thanks. I could not find anything about that ih the documentation.
