### ISSUE TITLE
Problem displaying characters : terminal and editor

### ISSUE THREAD

**Issue by utilisateuralpha** [doublecmd/doublecmd#1579]
### Version

DoubleCMD version 1.1.12  on Ubuntu 22.04. 

### Description

Hi,

I am writing to report a problem in the display of characters:

— On the integrated terminal: the letters are very close to each other.
— On the integrated text editor: it's the opposite. The letters are far apart.

Look at the pictures. THANKS

![doublecmdeditor](https://github.com/doublecmd/doublecmd/assets/89381501/5f9c85de-76a3-4aac-a6b9-a0493d195da6)
![doublecmdterminal](https://github.com/doublecmd/doublecmd/assets/89381501/895f92e3-ad54-4147-8550-6c1dc8b309a0)

**Comment by alexx2000** [comment]
Hi, check your font [settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigFonts), both terminal and editor requires a monospace font.

**Comment by utilisateuralpha** [comment]
Thank you
