### ISSUE TITLE
Display problem in the integrated editor

### ISSUE THREAD

**Issue by utilisateuralpha** [doublecmd/doublecmd#1586]
### Version

doublecmd 1.1.12 ubuntu 22.04

### Description

On the application's integrated editor, a vertical line is always displayed (see photo). This line hinders readability. How to delete it?

![traiteditordoublecmd](https://github.com/doublecmd/doublecmd/assets/89381501/3059e329-2585-467f-8989-8890b7a1b3fc)

**Comment by alexx2000** [comment]
[Right margin](https://doublecmd.github.io/doc/en/configuration.html#ConfigToolsEditor)

**Comment by utilisateuralpha** [comment]
Ok it works, but in the Diff tool window, the lines are still present despite the change in the configuration in the parameters (see new photo).

![traitdiffdoublecmd](https://github.com/doublecmd/doublecmd/assets/89381501/d089fadf-38f3-4136-b9ff-69d543edd1da)

**Comment by utilisateuralpha** [comment]
Hi Alex. Please reopen this issue. thanks

**Comment by alexx2000** [comment]
Technically it is not a bug. Simply, diff tool does not have an option to disable right margin. I don't know, should it use the option from the editor or not.
