### ISSUE TITLE
opening favorites closes open tabs

### ISSUE THREAD

**Issue by djpeter84** [doublecmd/doublecmd#1589]
### Version

known issue in the 1.1 series. current 1.1.13

### Description

opening favorites closes any open tabs

![Screenshot from 2024-04-20 07-59-52](https://github.com/doublecmd/doublecmd/assets/39010720/3363f7c1-4f74-4c4c-a9e8-9289e2bef683)

![Screenshot from 2024-04-20 07-55-15](https://github.com/doublecmd/doublecmd/assets/39010720/04bb78de-9b54-4757-abb9-27895d62eb1f)

**Comment by alexx2000** [comment]
Not a bug. It is how [favorites](https://doublecmd.github.io/doc/en/help.html#mnu_fav) works, [see also](https://doublecmd.h1n.ru/viewtopic.php?p=37722#p37722).
