### ISSUE TITLE
Unrar.wcx has no write access to temp folder (Viewer cannot open files from rar archive)

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1592]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

File can be exctracted/copied from archive to any folder, but if you try to F3 directly from archive is errors: 
![image](https://github.com/doublecmd/doublecmd/assets/2608545/56fb5c28-eb96-4513-b95c-ad80278e894e)
There a no such a problem with zip, gz, tgz.gz etc.

Samples can be taken here: https://getsamplefiles.com/sample-archive-files/rar

**Comment by alexx2000** [comment]
Unrar plugin (or unrar library) bug. It cannot extract file into temporary directory for some reason. But it works fine with normal directories. It is a very strange.

**Comment by lprot** [comment]
unrar.wcx simply has no access to /var/folders/td/c2dgb8h102bc_61d7nw8thmr0000gn/T/_dc/ 
try to unpack the mentioned sample there via F5 :)

**Comment by alexx2000** [comment]
Yes, and it's very strange. Also it does not return error.

**Comment by lprot** [comment]
I kind of fixed that with disabling unrar:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/d46d95d4-e8f7-462b-acb5-63cd6b6f0c34)
And adding rar to 7zip ro:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/37c4038d-7c79-47c2-9dd6-d9077fd24f49)
Maybe it makes sense to get rid of unrar plugin and just add 7z to distribution? It supports lot more formats?

7-Zip 24.03 for Linux and macOS
- Supported formats:
     - Packing / unpacking: 7z, XZ, BZIP2, GZIP, TAR, ZIP and WIM.
     - Unpacking only: APFS, AR, ARJ, Base64, CAB, CHM, CPIO, CramFS, DMG, EXT, FAT, GPT, HFS,
                       IHEX, ISO, LZH, LZMA, MBR, MSI, NSIS, NTFS, QCOW2, RAR, 
                       RPM, SquashFS, UDF, UEFI, VDI, VHD, VHDX, VMDK, XAR, Z and ZSTD.

**Comment by j2969719** [comment]
unrar.wcx can also create and modify rar archives if rar/winrar is installed on the system

**Comment by lprot** [comment]
> unrar.wcx can also create and modify rar archives if rar/winrar is installed on the system

what is the advantage of packing with this plugin if DC can do it direcly like with 7z :)

**Comment by alexx2000** [comment]
Theoretically plugin opens archives faster. Also it works better with encrypted archives.

**Comment by j2969719** [comment]
>like with 7z :)

unlike 7zip, rar is a proprietary software and only the unrar library is free. if you want use only an external rar archiver, you need to purchase a license. while unrar.wcx uses an open library for unpacking, and a proprietary external archiver only for packaging can be called as an option if available in the system.

**Comment by alexx2000** [comment]
Fixed in the latest Unrar library.
