### ISSUE TITLE
Some popups have buttons with incorrect background colour and wrong window height with buttons cut on the bottom

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1593]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

To reproduce, open any file in Viewer F3, F7 and enter some string that does not exist: 
![image](https://github.com/doublecmd/doublecmd/assets/2608545/69170472-0693-4c01-951b-4ca0bd73fb07)

**Comment by alexx2000** [comment]
Looks like a Lazarus LCLCocoa bug. Panel under button use `clForm` color so it should have a same color as dialog window but colors doesn't match.

**Comment by lprot** [comment]
Yes, and also please note that height of the buttons is cut. Maybe that is the reason?
![image](https://github.com/doublecmd/doublecmd/assets/2608545/90157a9c-9f03-4676-a45e-019cec3c81a4)

**Comment by alexx2000** [comment]
No. It is a panel auto size works wrong also.

**Comment by lprot** [comment]
The same issue in copy and delete dialogs:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/11673e96-fa5c-460e-8216-48442a68abba)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/a171c810-d413-491d-b359-22d0349bec90)

**Comment by lprot** [comment]
In some popups it looks ok:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/cc1fe261-e0d5-49d6-bd2d-d4d554982277)

**Comment by rich2014** [comment]
> Looks like a Lazarus LCLCocoa bug. Panel under button use `clForm` color so it should have a same color as dialog window but colors doesn't match.

@alexx2000 `clForm` is not the default color of the Form on macOS.

we should set `ParentColor:=True`.

**Comment by alexx2000** [comment]
> @alexx2000 clForm is not the default color of the Form on macOS.

Then it is a bug, by [documentation](https://lazarus-ccr.sourceforge.io/docs/lcl/graphics/clform.html)  `clForm`:
> Represents the color of the background for a form.

**Comment by rich2014** [comment]
the issue of backgound has been fixed by 69ab554.

@lprot  please test the snapshot from https://doublecmd.sourceforge.io/site/eng/snapshots.php.

**Comment by rich2014** [comment]
actually, i'm not sure if this is a Bug.

on macOS, I haven't been able to find a definite value for clForm.

the background color finally displayed seems to be based on the background of the superview.

if this is indeed the case, it may be due to a different design philosophy from other operating systems.


> > @alexx2000 clForm is not the default color of the Form on macOS.
> 
> Then it is a bug, by [documentation](https://lazarus-ccr.sourceforge.io/docs/lcl/graphics/clform.html) `clForm`:
> 
> > Represents the color of the background for a form.

**Comment by lprot** [comment]
@rich2014 on
Double Commander
Version: 1.2.0 alpha
Revision: 11301
Commit: 69ab554ba
Build date: 2024/04/28
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4
is fixed:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/941af016-926f-47da-a5a3-6e1c5691aa8b)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/8d2cd560-ffb9-4aea-8121-5491b86d41bb)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/c637a7a0-d7eb-499f-9daa-a5577f1db56b)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/fc25e272-4ede-4479-a2d6-0d6bf8b3dedf)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/3f1d84a2-c4c2-4584-9c15-50f3470fe150)

Issue with the correct size of the window remains as the buttons are cut at the bottom.

**Comment by rich2014** [comment]
height of the Buttons fixed (refer to the implementation in TfrmButtonForm).

check it please.

**Comment by lprot** [comment]
Workes like magic in:
Double Commander
Version: 1.2.0 alpha
Revision: 11303
Commit: 4f0eb9bc9
Build date: 2024/05/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

![image](https://github.com/doublecmd/doublecmd/assets/2608545/9e4a75a9-38f6-4549-af35-acd354701c88)


Thank you!
