### ISSUE TITLE
Terminal settings has wrong default path to Terminal.app for MacOS 12.7

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1595]
### Version

DC 1.1.13b453. MacOS x86_64 12.7.

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/f789420b-34c0-415f-be12-44c3ea486f31)
To fix running Terminal by F9 press, I modified "Command for just running terminal" to "/System/Applications/Utilities/Terminal.app" %D as on the screenshot. It works as expected. But! 
If you type anything in the command line of Double Commander it does not even run %COMMANDER_PATH%/scripts/terminal.sh. You can reproduce it - just write into terminal.sh command like "echo >/Users/test.txt" and you will see that it is not executed.

**Comment by lprot** [comment]
Yes, Shift+Enter works like magic. Would be nice to:
1. Put hint that Shift+Enter runs command from command line into F1 help page. 
2. To set "Command for just running terminal" with "/System/Applications/Utilities/Terminal.app" and %D as a default in the distribution package, so F9 works out of the box

Maybe just renaming of the titles whould make things immediately clear:
"Command for running a command in terminal and stay open (Shift+Enter)"
"Command for just running terminal (F9)"
"Command for running a terminal and close after" how this one works?

Thank you!

**Comment by alexx2000** [comment]
Fixed, DC gets a correct path to Terminal.app when start without configuration files.

> "Command for running a terminal and close after" how this one works?

It executes command in the terminal and close it when command completed.

**Comment by lprot** [comment]
> It executes command in the terminal and close it when command completed.

The meaning is clear for me, but what is the trigger for this command type? First is triggered with F9. Third/last with Shift+Enter. But this one?
