### ISSUE TITLE
Deselection with Shift+Left in quick rename by Shift+F6 does not work on macOS

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1599]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

When you press Shift+F6 on the file or folder, you can quickly rename it. After you release F6 key but keep holding Shift, the name stays selected. 
On DC for Windows when you press left arrow key it functions as a deselector from the right side. This behaviour is also standard for Total Commander.

In the DC for MacOS deselection with Shift+Left it does not work.

![image](https://github.com/doublecmd/doublecmd/assets/2608545/e7dee848-e637-4792-a753-51e6c1b548e1)

**Comment by lprot** [comment]
Hmm, investigated this deeper, and looks like this deselection behaviour is inherited from Finder. In Finder when you click on the name on the file and it gets selected, deselection to the left does not work until you pres Shift+Right and only then Shift+Left starts working as expected.
Not sure if this strange behaviour can be fixed in DC for macOS.

**Comment by rich2014** [comment]
i think this is an usage and not a Bug on macOS.

and the rename control corresponds to the macOS standard control (NSTextField)

**Comment by lprot** [comment]
Yes, users of macOS doomed to have this non logical handling of the Shift+Left in highlighted texts :)
