### ISSUE TITLE
Add GitHub metada, link to source

### ISSUE THREAD

**Issue by paulvi** [doublecmd/doublecmd#16]
Add GitHub metadata,
"doublecmd issue tracker (only)"
 link to sources
https://sourceforge.net/p/doublecmd/code/HEAD/tree/

**Comment by outfrost** [comment]
There is also a different suggestion: #6

**Comment by paulvi** [comment]
Code migration to Git(Hub)? #6 is larger topic discussed.

This issue is about what should be done now
to reflect correctly current GitHub usage.

**Comment by paulvi** [comment]
![image](https://user-images.githubusercontent.com/1614482/67645229-64841600-f962-11e9-977b-c2b75b628ba6.png)

Now it is no description, no code, and not link to https://sourceforge.net

**Comment by outfrost** [comment]
That is true, you're right.

Just linked that issue for general awareness :)

**Comment by paulvi** [comment]
I still don't see any description for https://github.com/doublecmd/doublecmd

**Comment by outfrost** [comment]
Well, yes, that's because this issue hasn't been acted upon or even commented on by the developer.

**Comment by dandv** [comment]
I've just [pinged Alex explicitly](https://github.com/doublecmd/doublecmd/issues/49) about the current state of the project (spread in a few places).

**Comment by paulvi** [comment]
looks better now
