### ISSUE TITLE
Disable keyboard accelerators on Tab headers

### ISSUE THREAD

**Issue by MiroslavV3** [doublecmd/doublecmd#1601]
### Version

Double Commander Version 1.1.13 gamma, Revision 453, Commit f60bf09df
Lazarus 3.2.0.0
Qt 6.7.0, libQt6Pas 6.2.1
x86_64-Linux

### Description

Under QT6 in Linux, folder tabs are created with accelerator shortcuts (Alt + first letter of the folder name). This then interferes with the function of custom Alt+KEY shortcuts (these shortcuts stop working).

Possible solutions: 

- disable accelerators in tab headers altogether
- if this feature is used by other users, add an option to disable it under Tab settings in Configuration/Options

**Comment by alexx2000** [comment]
I cannot reproduce. DC does not set accelerator shortcuts for tabs.

**Comment by MPavleski** [comment]
Here is screenshot. You need to hold the Alt button down. 

![Screenshot_20240429_112159](https://github.com/doublecmd/doublecmd/assets/2526975/f7c60285-fa7c-413d-aa66-6e94d57deb6a)

I assume, first you have to disable the Quick Search or Quick Filter on Alt button in the settings.

**Comment by alexx2000** [comment]
Nothing happens with tabs when I press Alt key. Quick Search and Quick Filter on Alt key are disabled.

**Comment by alexx2000** [comment]
I guess you are using Wayland. I can reproduce it under Wayland. Works fine under X11. So I think it is a Qt + Wayland bug. I am nothing can do here.

**Comment by MPavleski** [comment]
Additional note, QT5 build does not have this issue under Wayland, so whoever is running under Wayland, seems for the time being best to use QT5 version.
