### ISSUE TITLE
Thousands separator in file size does not respect the system setting

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1602]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11303
Commit: 4f0eb9bc9
Build date: 2024/05/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

When in OS settings the dot is set it works properly:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/1da377d7-dac7-4904-93b3-041b6b6356f6)
 
But if you change separator to "empty" DC uses the space as the thousands separator:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/f6560a8e-5335-4d88-bae2-0a76a8e9f416)

**Comment by alexx2000** [comment]
It is a Free Pascal issue. I added a workaround.
