### ISSUE TITLE
terminal external editor does not work unless 'keep terminal open...' is enabled

### ISSUE THREAD

**Issue by jmlucjav** [doublecmd/doublecmd#1607]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 23.10

Widgetset library: Qt 5.15.10, libQt5Pas 5.6.1

### Description

Hi,

I set vim as external editor, with 'Execute in terminal' option.. vim is called fine, it pops up, but empty, not with the selected file open. 
If I enable 'Keep terminal open...' option, it works. I enabled logging and I think it's cause in later case single quotes are added, that are missing in the former...see the two invoktations:

```
05/03/2024 11:02:36 PM Launch external: Filename=x-terminal-emulator / Param=-e sh -c vim /tmp/dot_gitconfig.tmpl / WorkDir=
...
05/03/2024 11:03:22 PM Launch external: Filename=x-terminal-emulator / Param=-e sh -c 'vim /tmp/dot_gitconfig.tmpl; echo -n Press ENTER to exit... ; read a' / WorkDir=
```

Could the single quotes be always added?

thanks!

**Comment by alexx2000** [comment]
Add the single quotes here:

![2024-05-04_00-30-33](https://github.com/doublecmd/doublecmd/assets/13401398/f6bcfa62-7217-47a9-bf35-bf9f911746b0)

**Comment by jmlucjav** [comment]
Thanks works nicely! Had missed that config sorry (new user here...)
