### ISSUE TITLE
cannot drag files from other apps to DC

### ISSUE THREAD

**Issue by bobpox2** [doublecmd/doublecmd#1608]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.6.1

### Description

Hi,

We found it cannot drag files from other apps ( not finder, finder is OK) such as fastzip / MacZip and drop to DC, DC would not accept the files, but can drag-n-drop from finder to DC.

Is it a bug or by design? Or is there any workaround to drag and drop from other apps?

Thanks a lot!

BTW, I love DC, much appreciated for your great work! ( from an old TC/win user...)

**Comment by alexx2000** [comment]
DC supports drag&drop of real/local files only (NSFilenamesPboardType). It can't accept files from archives.

**Comment by bobpox2** [comment]
Thanks for your response!
And for this feature, I found some other file manager can do this, is it possible we support such action later in the future?
Because I find it convenient to drop some instead of all files from archive to local folder.

**Comment by bobpox2** [comment]
I find we can use Ctrl+PgDown to browse archives and F5 to copy target items, just like in TC. Great!
It's OK that cannot drag and drop then!

**Comment by timur-g** [comment]
Thanks for explanation and workaround. This seems like nice enhancement. 
When I download zip, I used to open and drag where needed to replace the existing file. DC cannot do that.
