### ISSUE TITLE
Internal Editor of DC incorrectly highlights param extension in *.sh files

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1610]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11312
Commit: 6fc5d0414
Build date: 2024/05/03
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/11bd1100-9ff6-427e-a922-a0cb6740d00f)

**Comment by alexx2000** [comment]
It is Lazarus `TSynUNIXShellScriptSyn` highlighter issue.
