### ISSUE TITLE
Copying executable files under Linux: Execution bit is cleared

### ISSUE THREAD

**Issue by roseswe** [doublecmd/doublecmd#1622]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Zorin OS 17.1/openSUSE 15.5

Widgetset library: GTK 2.24.33

### Description

This behavior is present at least since 1.0.x: When copying files or directory the execution bit "--x" is cleared. So binaries aren't executable anymore.

**Comment by alexx2000** [comment]
Check your [settings](https://doublecmd.github.io/doc/en/copymove.html), `Copy attributes` option.

**Comment by roseswe** [comment]
Thanks! That was the fix!  But this setting was not visible, because I had unchecked "Show confirmation window for - Copy operation". Great piece of software esp. for Linux!
