### ISSUE TITLE
b64 plugin does not show size

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1630]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11315
Commit: fb40c7c4a
Build date: 2024/05/04
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

Left side=b64 handled via Multiarc 7zz, right side b64 plugin
![image](https://github.com/doublecmd/doublecmd/assets/2608545/45a0f2c6-5bdf-4689-8f3b-24a615a1352f)
[test.zip](https://github.com/doublecmd/doublecmd/files/15259204/test.zip)

**Comment by alexx2000** [comment]
No bug here. Base64 "archive" does not store the original file size. So it is impossible to get original file size without decoding. As I see 7-Zip decodes "archive" while opening but I don't think that it is a good idea, it will be slow with large "archives".

**Comment by lprot** [comment]
Are there large b64 archives at all? b64 was made to send relatively small files via email.

**Comment by alexx2000** [comment]
I don't know. Technically it can has any size. In the wiki it is just an example: when mail-server has 64 Mb limit then it will be only 48 Mb of original data.

**Comment by lprot** [comment]
Tried Double Commander
Version: 1.2.0 alpha
Revision: 11320
Commit: 65e72c0d3
Build date: 2024/05/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4
![image](https://github.com/doublecmd/doublecmd/assets/2608545/b7fc1d0c-bd95-427e-b8ec-94a821e118f7)

Date and Attr have also to be removed here?
