### ISSUE TITLE
b64 plugin shows date, time and attributes on the content that does not have it

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1634]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11320
Commit: 65e72c0d3
Build date: 2024/05/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/35a5f65f-95fc-4b29-91cb-fa9dbc78531c)
Relates to https://github.com/doublecmd/doublecmd/issues/1630

**Comment by alexx2000** [comment]
Attributes always exists (directory / not directory at least).

**Comment by lprot** [comment]
> Attributes always exists (directory / not directory at least).

but a file inside b64 cannot be directory...

**Comment by alexx2000** [comment]
Yes. DC see it using attributes.

**Comment by lprot** [comment]
> Yes. DC see it using attributes.

It is just strange to see the attributes on something that does not have them at all, but ok.
