### ISSUE TITLE
DC displays wrong date, time and attributes of the parent folder

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1635]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11320
Commit: 65e72c0d3
Build date: 2024/05/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/10e87633-8cfe-40cd-828c-01b6231f5f06)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/6cf07925-e13a-4165-925d-28559258712d)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/afb063b9-d174-4c84-9c25-00b2b225a43a)

**Comment by j2969719** [comment]
`/users/lprot/downloads/..` == `/users/lprot` actually

**Comment by lprot** [comment]
> `/users/lprot/downloads/..` == `/users/lprot` actually

![image](https://github.com/doublecmd/doublecmd/assets/2608545/88ec2103-46e7-48ba-aa0c-946ff6d68dfa)

**Comment by j2969719** [comment]
do descendants have the same issue or does it only happen at this level? mb the user dir on mac actually is a mount point or something? (never used them)

**Comment by lprot** [comment]
> do descendants have the same issue or does it only happen at this level? mb the user dir on mac actually is a mount point or something? (never used them)

![image](https://github.com/doublecmd/doublecmd/assets/2608545/d6d5def0-28b3-4590-9513-855796ce1e98)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/f7eaf84f-eb4d-4d27-8878-f217f04fa968)

**Comment by lprot** [comment]
False alarm here. All good.
