### ISSUE TITLE
DC does not show /Volumes in the drive bar and list 

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1640]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11322
Commit: 832462f36
Build date: 2024/05/11
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/4f442c9a-1ab3-40d3-81e0-45ab1c82c910)

Is is absent in the drive's list too:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/2fcddee6-f4d2-48f3-92ac-e741f2fb1ae8)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/d137e169-c45b-4d34-9c61-c063a3bdaf57)
Here "NO NAME" is USB flash drive connected to USB port. SSD and Data are internal SSD drive.

**Comment by lprot** [comment]
@alexx2000 maybe this helps? 
![image](https://github.com/doublecmd/doublecmd/assets/2608545/ea339d51-e39d-4ec9-91c0-2791d43a820e)

**Comment by lprot** [comment]
But to avoid rocket science here, the simplest on macOS would be to use /Volumes
![image](https://github.com/doublecmd/doublecmd/assets/2608545/fdafdc96-7446-490d-a3eb-e77b9ed766ca)

**Comment by alexx2000** [comment]
DC simply excludes the root drive currently.

**Comment by lprot** [comment]
> DC simply excludes the root drive currently.

This is strange as it is expected to see SSD and other volumes from /Volumes if any available.

**Comment by lprot** [comment]
@alexx2000 Even lame Commander PRO shows Volumes and that means DC has not be worse :)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/05c8662b-e642-4521-9bbd-01d9ee382d7f)

**Comment by lprot** [comment]
Was long awaited. Thanks! :)
