### ISSUE TITLE
macos 14.4.1 can't preview

### ISSUE THREAD

**Issue by Liuzhj** [doublecmd/doublecmd#1644]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11322
Commit: 832462f36
Build date: 2024/05/11
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.4.1

### Description

<img width="1208" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/4059c541-8208-41b0-a4bb-2ace7cc1a7b1">

**Comment by alexx2000** [comment]
What do you expect to see?

**Comment by Liuzhj** [comment]
like linux command tree.
<img width="665" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/e3a72577-bd33-4964-9b14-2c821fd61ad7">

**Comment by Liuzhj** [comment]
> What do you expect to see? DC does not have archive preview function.

no, previous version can list archive (maybe macos 14.1.0 )

**Comment by Liuzhj** [comment]
Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.4.1

<img width="1154" alt="image" src="https://github.com/doublecmd/doublecmd/assets/14147011/c2d1b9fe-4491-40c9-8280-5a84bd020ba9">

**Comment by Liuzhj** [comment]
@alexx2000  help

**Comment by alexx2000** [comment]
#1999
