### ISSUE TITLE
Auto refresh stopped working

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1652]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11324
Commit: d2416cc2a
Build date: 2024/05/19
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/c7c6fa79-6e94-4175-ac8b-81af8eb2252b)

DC does not refresh the file panel after deletion or rename happened:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/b59c3be6-5565-4d27-98aa-6a8a55f3edbd)

**Comment by rich2014** [comment]
@alexx2000

alex, is this problem related to 17c4b7f4?

**Comment by alexx2000** [comment]
Theoretically it should not. I did not see this problem under Windows/Linux.

**Comment by lprot** [comment]
Not sure what happened but refreshing started to work again.
