### ISSUE TITLE
FTP plugin cannot connect to SFTP/SCP server via "Quick connection"

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1654]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11324
Commit: d2416cc2a
Build date: 2024/05/19
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

If you try to connect to the server via "Added connections" then it works:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/cf237d2c-94b6-4c3a-a5c7-7654499e7170)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/9922ff9f-5622-47d3-b7e9-1285df351911)

But if you use "Quick connection" then connection fails:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/e0954bdb-5657-4027-8c7f-1e4fbf835400)

![image](https://github.com/doublecmd/doublecmd/assets/2608545/388dc725-9af6-43c1-ba5b-da4f00befbe3)

Reference: https://github.com/doublecmd/doublecmd/issues/1604

**Comment by lprot** [comment]
@alexx2000 does it even makes sense to have "Quick connection" ?
IMHO it would be best just remove it and rename "Add connection" to "Connect", to unify connection functionality.
One dialog would be enough with a checkbox "Save connection" and if ticked then you just enter name and it is saved.

![image](https://github.com/doublecmd/doublecmd/assets/2608545/8656dcf4-c75e-4c31-8892-dbb4fe0c6c2f)

Here I also extended the dialog with a mode listbox "FTP, FTPS(TLS), SFTP, SCP" to follow the idea in https://github.com/doublecmd/doublecmd/issues/1604

**Comment by alexx2000** [comment]
Try with the latest snapshot. "Quick connection" should work now.

> IMHO it would be the best to just remove it and rename "Add connection" to "New connection", to unify connection functionality.
> One dialog would be enough with a checkbox "Save connection" and if ticked then you just enter name and it is saved.

Maybe...

**Comment by lprot** [comment]
Looks good!
![image](https://github.com/doublecmd/doublecmd/assets/2608545/a2967c68-491c-4b6f-be74-c0bfb78047bc)

![image](https://github.com/doublecmd/doublecmd/assets/2608545/94b3b2c7-4ac8-4a2a-a23c-eb14e627c088)

Let's get rid of "Quick connect" and "New connection" and add "Connect"?

**Comment by lprot** [comment]
Fixed in Double Commander
Version: 1.2.0 alpha
Revision: 11332
Commit: afc3a9fc9
Build date: 2024/05/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5
