### ISSUE TITLE
"Network Disconnect" in FTP plugin does not work

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1655]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11324
Commit: d2416cc2a
Build date: 2024/05/19
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/f406f18c-477a-4f5d-893b-2d6df5a666a8)

Ref: https://github.com/doublecmd/doublecmd/issues/1604

**Comment by lprot** [comment]
> You renamed a plugin and give it a bad name (with directory separator). That's why it does not work.

If some characters are restricted from use why DC allows you to use it? :)

**Comment by alexx2000** [comment]
Everything is simple here, no one has done this before.

**Comment by lprot** [comment]
Renaming to FTP does not help:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/7915401f-b215-449b-bdbd-1d2fecceeedc)

**Comment by alexx2000** [comment]
Plugin does not work with this server at all. So you should not expect that this function will to work correctly.

**Comment by lprot** [comment]
Fixed in Double Commander
Version: 1.2.0 alpha
Revision: 11332
Commit: afc3a9fc9
Build date: 2024/05/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5
