### ISSUE TITLE
Unpack files - Unpack each archive to a separate subdir

### ISSUE THREAD

**Issue by mihnea-radulescu** [doublecmd/doublecmd#1660]
### Version

Double Commander 1.1.14~468
OS: Linux Mint 21.3

### Description

**Behavior**: When attempting to unpack a zip archive, selecting _Unpack each archive to a separate subdir (name of the archive)_ will grey out the option, and will require a second click on the option to select it.

**Expected behavior**: When attempting to unpack a zip archive, selecting _Unpack each archive to a separate subdir (name of the archive)_ will select the option on the first click.

Screenshot attached.

![Unpack_Files_Issue](https://github.com/doublecmd/doublecmd/assets/29178174/da32b6fe-df34-457f-8529-b29a5eb3b3fa)

**Comment by alexx2000** [comment]
Not a bug. See [documentation](https://doublecmd.github.io/doc/en/help.html#mnu_file).
