### ISSUE TITLE
Button overlaid

### ISSUE THREAD

**Issue by mehmet-b-90** [doublecmd/doublecmd#1667]
### Version

Double Commander
Version: 1.1.14 gamma
Revision: 468
Commit: edd44b0e2
Build date: 2024/05/04
Lazarus: 3.3.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 Home 23H2 x86_64

### Description

Hello,
in the delete dialog, one button is slightly covered by another button. I use the German language.

![Screenshot 2024-05-21 222536](https://github.com/doublecmd/doublecmd/assets/110692538/2732e877-166d-4371-b008-436fc15b09e5)

**Comment by lprot** [comment]
The same story in macOS!

Double Commander
Version: 1.2.0 alpha
Revision: 11332
Commit: afc3a9fc9
Build date: 2024/05/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5


![image](https://github.com/doublecmd/doublecmd/assets/2608545/bbb66def-61eb-4d9b-b742-dbec31518c3a)
