### ISSUE TITLE
Unpacking 7z, WIM and prabably other archives crashes the whole app or causes unreliable output

### ISSUE THREAD

**Issue by digital-spinner** [doublecmd/doublecmd#1672]
### Version

Double Commander
Version: 1.1.14 gamma
Revision: 468
Commit: edd44b0e2
Build date: 2024/05/04
Lazarus: 3.3.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 23H2 x86_64

### Description

Recently I have found that 1.1.14 and 1.0.11 Double Commander version (yet didn't tested that more backwards) crashes when extracting 7zip archives leaving no error information in log entry or any error message.

I don't know when or where or how, but I found that the unplacking itself is not thrustworthy and since couple of days I just completely stopped using that function. When I use just the 7zip app everything seems to work properly. Using the Double Commander is not possible (crashes) or doesn't unpack everything. It also crashes on huge WIM archives, where 7zip itself has no issues.

**Comment by lprot** [comment]
@digital-spinner try to reproduce on https://doublecmd.sourceforge.io/site/eng/snapshots.php

**Comment by digital-spinner** [comment]
Thank you for a suggestion. I have tested revision 11336 | doublecmd-1.2.0.r11336.x86_64-win64.7z | 9347384 | 2024.05.23 18:17:48 and the issue is also present here - crash without any errors.

**Comment by lprot** [comment]
can you attach the problematic 7z archive? I cannot reproduce it on Double Commander
Version: 1.2.0 alpha
Revision: 11336
Commit: c0ff9250b
Build date: 2024/05/23
Lazarus: 3.2.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64
![image](https://github.com/doublecmd/doublecmd/assets/2608545/066492cb-71bc-4b0c-aec6-4256d7ba0780)

**Comment by digital-spinner** [comment]
Unfortunately the archive is over 6 GiB and it contains very private stuff. Maybe I will try to spin the debug instance of DC in Windows? How much can it take? hmmm Is it similar env (Lazarus) to the Visual Studio? :-)

**Comment by lprot** [comment]
> Unfortunately the archive is over 6 GiB and it contains very private stuff. Maybe I will try to spin the debug instance of DC in Windows? How much can it take? hmmm Is it similar env (Lazarus) to the Visual Studio? :-)

Try to replace 7z.dll in DC folder with the latest 7z.dll from 7z.org

**Comment by lprot** [comment]
@alexx2000 can it be that DC just does not support unpacking from 6Gb 7z file? Some kind of 4Gb limit?

**Comment by digital-spinner** [comment]
I took the newest 7z.dll from installed newest 7zip (7-Zip 24.05 (2024-05-14) for Windows x64) and it (Double Commander) crashes in the same way, unpacking exactly the same amount of data for earlier 7z.dll as well as older version. Again, 7zip itself has no issues at all. Tests and my crc (blake3) verification for that problematic archive yields no issues - just checked to be sure that there is no sneaky bit rot or something.

**Comment by lprot** [comment]
I can only do an assumption that 4Gb+ size cannot be handled by DC or 7z.dll. Checking this is simple - delete something from this 6Gb archive to say it becomes 3Gb and try to unpack. If DC can handle it then we know the reason.

**Comment by digital-spinner** [comment]
I just successfully unpacked different archive which is 25 GiB in size without any problems. Also the content of it match perfectly stored checksum file so I guess there is something else. But I have a different archive which also fails but with error message and this one again can be easily unpacked with 7zip to the same location...

---------------------------
Error
---------------------------
Unable to create file "d:\Temp\2021-03-28--AM-LAPTOP-DECOMMISIONING\xxxxxxxxxxxx\AppData\Local\Microsoft\Windows\WER\ReportQueue\Critical_Microsoft Visual_1842135174075d99b215af43fe3b6f7f81b1df_cab_07272960\Microsoft Visual C++ 2010  x86 Redistributable Setup_20190111_140602948-MSI_vc_red.msi.txt": The system cannot find the path specified.
---------------------------
OK   
---------------------------

**Comment by lprot** [comment]
Would be interesting to get a sample for test.

**Comment by digital-spinner** [comment]
Yes I have a 25GB of WIM archive with ~ 1_100_000 or 1_700_000 and it also crashes but with error message:

```---------------------------
Error
---------------------------
Unable to create file "d:\Temp\PRT\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxx_CHECK.vshost.exe.manifest": The system cannot find the path specified.
---------------------------
OK   
---------------------------


I will try to came up with something. Maybe I will be able to spin a VM with Lazarus instance for debugging also.. I will get back to it.

**Comment by lprot** [comment]
@digital-spinner try on the latest DC https://doublecmd.sourceforge.io/site/eng/snapshots.php
maybe crash was date/time related?

**Comment by alexx2000** [comment]
@digital-spinner I guess it is due a super long file name (> 260 characters). SevenZip plugin does not support them yet.

**Comment by alexx2000** [comment]
Try with the latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by digital-spinner** [comment]
Hey! Thank you! I will come back with the response about this asap.

**Comment by digital-spinner** [comment]
So far so good! I found no errors and missing files when extracting large 7zip archives (about 40G+). But I did not tested the biggest archives that I got, because I have no space to extract 2TB of data currently from the 300G WIM archive 😈
I may try to let it run for the night in few days, just to be double sure. Anyway partial extractions from that biggest archive to a long named directory structure was also successful. So I guess it's all good now!

Thank you!

**Comment by digital-spinner** [comment]
Hey I'm getting back with some more feedback what I found.

Using Double Commander operations:
- compressed to 7 zip archives contain additional 0 byte file inside with the directory name of compressed directory and extraction of such archive is not possible eg: 'My Files' and we have a 'My Files' 0 byte file - extraction of archive fails in multiple apps
- when extracting WIM archives 0 byte files are not extracted at all
- when extracting 7zip archives 0 byte files are not extracted at all
