### ISSUE TITLE
Internal Viewer of DC does not respect the selected codepage in Bin, Hex and Dec modes

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1674]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11332
Commit: afc3a9fc9
Build date: 2024/05/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

[test.csv](https://github.com/doublecmd/doublecmd/files/15438297/test.csv)

Text and Book modes look good:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/68484fc2-ab96-4444-8e71-1e678e9c8466)

But Bin, Hex and Dec not:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/b5a26c26-699e-42f2-969a-5de0df839935)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/1d0e5a63-33b9-4da2-8645-3a2c83b2b3ad)

**Comment by ags1234** [comment]
Wow! This was a big commit! Thanks for resolving this, @alexx2000
