### ISSUE TITLE
No dark mode

### ISSUE THREAD

**Issue by vitaly-zdanevich** [doublecmd/doublecmd#1675]
### Version

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: "Gentoo"  

Widgetset library: GTK 2.24.33

### Description

AppImage.

In `~/.config/gtk-3.0/settings.ini` I have

```
[Settings]
gtk-application-prefer-dark-theme = true
gtk-enable-animations = false
```

Looks like Double Commander is GTK2, should I set something in a config file?

**Comment by vitaly-zdanevich** [comment]
Enabled with [lxappearance](https://packages.gentoo.org/packages/lxde-base/lxappearance), so now my `~/.gtkrc-2.0`:

```
# DO NOT EDIT! This file will be overwritten by LXAppearance.
# Any customization should be done in ~/.gtkrc-2.0.mine instead.

include "/home/vitaly/.gtkrc-2.0.mine"
gtk-theme-name="Adwaita-dark"
gtk-icon-theme-name="gnome"
gtk-font-name="Sans 10"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintmedium"
```

![2024-may-25--04-17-58_maim](https://github.com/doublecmd/doublecmd/assets/3514015/fa06df4a-f50c-478a-8745-85546ae7447e)

**Comment by bocekm** [comment]
@vitaly-zdanevich, did you anything else besides getting the `~/.gtkrc-2.0` generated by [lxappearance](https://github.com/lxde/lxappearance)? I've done so on my Fedora 40 and it doesn't help. I've verified that the Adwaita-dark theme is installed (it's part of the adwaita-gtk2-theme package).

**Comment by vitaly-zdanevich** [comment]
I do not remember :(
