### ISSUE TITLE
Feature request: Implement option "Click on empty space to deselect items"

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [doublecmd/doublecmd#168]
It is usual in other file explorers to click on empty space in order to deselect files.

In DC, I have added button with action "cm_MarkUnmarAll" in order to easily/cuickly deselect files, this seems to be overkill :)

O suggest to implement additional checkbox in preferences "Click on empty space to deselect items"

```
Double Commander
Version: 1.0.0 alpha
Revision: 9890
Commit: 5b000ea17
Build date: 2021/08/22
Lazarus: 2.2.0.2
FPC: 3.0.4
Platform: x86_64-Win64-qt5
OS version: Windows 10 Home 20H2 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1
```

**Comment by Skif-off** [comment]
@alexx2000
Are you planning to add this feature? If true, could you turn it off by default? Typical use of single click is activation of file panel or DC main window...

**Comment by alexx2000** [comment]
May be. Yes it should be off by default. If panel is inactive then first click should activate it and only second clear selection.
