### ISSUE TITLE
Auto-size columns doesn't work properly with dark mode

### ISSUE THREAD

**Issue by mburetorp** [doublecmd/doublecmd#1683]
### Version

Version 1.1.14~468
Windows 64-bit

### Description

When using dark mode and auto-size columns (Auto fill columns checked and Auto size column set to First) the columns after a some time of use render completely white. So initially everything looks good but after some time it stops working and some columns are completely white, not sure what triggers it. You can hover with the mouse cursor over a column to temporarily redraw it with the correct color, but it only work as long as the cursor is over the column.

![image](https://github.com/doublecmd/doublecmd/assets/14858298/d4d1ae97-a7f3-44fe-9755-b0f24a6f268e)

**Comment by alexx2000** [comment]
#1668
