### ISSUE TITLE
The "Dot" menu selection element has wrong colour in the dark mode on macOS

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1691]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11350
Commit: a56d313b3
Build date: 2024/05/29
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

When you open the menu, the current coding is selected with the black dot which is not really visible in dark macOS theme:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/82ba6d1d-ac21-419e-b2b4-f6cc401fdadb)

Probably it is possible to make it white?:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/abb071a1-9ed7-42f2-b717-f08498fa61d4)
Thank you!

**Comment by alexx2000** [comment]
> When you open the menu, the current coding is selected with the black dot which does not really visible in dark macOS theme:

I wouldn't say it's hard to see. The mark is visible without problems. Anyway it is not a DC issue, it is a how Lazarus or Cocoa works.

**Comment by lprot** [comment]
Yes, on the github with a light background it has a better visibility. For example tick marks like on "Wrap mode"  the tick is white colour and is perfectly visible. But here the dot is black colour and when the background is black it is hard to see. 
Hopefully this can be easily improved.

**Comment by lprot** [comment]
@alexx2000 just for understanding how a proper selection dot looks for like:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/cea969ac-0f64-4d0a-82ba-17ceb57743ff)

So I consider it is just a UI bug with wrong colour?

**Comment by rich2014** [comment]
@lprot 

improved in Lazarus/Lcl/Cocoa, test the snapshoot please.

**Comment by lprot** [comment]
@rich2014 works like magic!
![image](https://github.com/doublecmd/doublecmd/assets/2608545/b9463d06-ae67-4dbf-8a6c-5ee21734cba3)

Thank you very much!
