### ISSUE TITLE
"Brief view", "Full" and "Thumbnails" have conflicting settings in shortcuts.scf for macOS

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1698]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11352
Commit: 01c8c0c81
Build date: 2024/06/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

You can do it via menu:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/9d38f9de-440c-4877-84fe-54f1d5b0a070)

But keyboard shortcut does not work despite it is correctly set in settings and has no conflicts:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/584f1baa-a4ce-4987-b0db-ec944d5ee56c)

Would be good to fix together with the "strange" "Show" menu behaviour reported in https://github.com/doublecmd/doublecmd/issues/1695

**Comment by lprot** [comment]
@rich2014 @alexx2000 DC does not even react on Ctrl+F1 press here:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/c0fca8f3-4826-419b-861d-e3b14b51fb93)

**Comment by rich2014** [comment]
@lprot 

`Ctrl+F1` is occupied by macOS.

you can change it in `System Preferences` > `Shortcuts (top)` > `Keyboard (left)`

**Comment by lprot** [comment]
> @lprot
> 
> `Ctrl+F1` is occupied by macOS.
> 
> you can change it in `System Preferences` > `Shortcuts (top)` > `Keyboard (left)`

Looks like a proper shortcuts.scf has to be included into dmg distribution. Is it possible to implement? If yes, then I will check all shortcuts and make them compatible with Macbook Air and Pro.
