### ISSUE TITLE
Feature Request : Synchronize directory feedback

### ISSUE THREAD

**Issue by reinhardlinardi** [doublecmd/doublecmd#17]
Synchronize directory does not provide any feedback (no progress bar, no percentage, no current processed filename).

**Comment by asvc** [comment]
Related forum thread: https://doublecmd.sourceforge.io/forum/viewtopic.php?f=7&t=5710&p=28039

**Comment by joo0ne** [comment]
In addition, the second stage (copying) needs to be improved.

Here is a comparison of the stages.

**The comparison step**

1. Controls are disabled.

2. The progress bar in the status bar.

3. ~Cancel button~

**The stage of performing operations with files**

1. ~Controls are disabled~.

2. ~The progress bar in the status bar~.

3. ~Cancel button~

**Comment by alexx2000** [comment]
Added real operation progress.

**Comment by szpak** [comment]
Confirmed, in the recent 1.0.0 alpha there is synchronization progress. Not as fancy as during a regular files copying, but represents the progress of synchronization :).

@reinhardlinardi Could it be closed?

**Comment by reinhardlinardi** [comment]
Sure
