### ISSUE TITLE
Ctrl+PgDown does not work on MacBook Air by default

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1705]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11352
Commit: 01c8c0c81
Build date: 2024/06/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

On MacBook Air there is no physical PgDown button and instead of that fn+Down is used.
So to imitate Ctrl+PgDown you need to press Ctrl+fn+Down. And these combos perfectly work in Chrome (you switch to previous/next tab).

By unknown reason Ctrl+fn+Down is not handled in DC properly. Instead of doing the action assigned in setting:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/a9562d9b-330c-4397-a8a8-24ac1f173341)

Ctrl+fn+PgDown just acts like fn+Down ie as a PgDown. But Ctrl+fn+Up acts correctly and changes directory to parent.

Other issue related to keyboard handling: https://github.com/doublecmd/doublecmd/issues/1698 https://github.com/doublecmd/doublecmd/issues/1651

**Comment by rich2014** [comment]
1. DC can handle Fn+Control+Up/Down

3. these shortcut keys have other uses by default in DC, as shown in your screenshot. you can modify the corresponding functions of the shortcut keys

**Comment by lprot** [comment]
> 1. DC can handle Fn+Control+Up/Down
> 2. these shortcut keys have other uses by default in DC, as shown in your screenshot. you can modify the corresponding functions of the shortcut keys

I do not know what happens by default, but when I opened and just reassigned this shortcut it started to work. Somehow it did not work by default. Strange...

**Comment by lprot** [comment]
Cannot reproduce after fresh installation on Double Commander
Version: 1.2.0 alpha
Revision: 11354
Commit: ce4eb5ebb
Build date: 2024/06/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5
