### ISSUE TITLE
DC does not return focus to the "Compare by Contents" window after switched by Cmd+Tab to other app and back

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1706]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11352
Commit: 01c8c0c81
Build date: 2024/06/01
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

To reproduce:
1. Run for example Chrome/Safari whatever
2. Run DC and compare any two files by "File>Compare by Content":
![image](https://github.com/doublecmd/doublecmd/assets/2608545/eb2b930a-b674-4de4-b634-99c840f2c901)
3. Ignore so it shows the window
![image](https://github.com/doublecmd/doublecmd/assets/2608545/a29a87fc-cc63-4740-b797-21ca7c6c6769)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/edd3eb1d-3bb5-4e5a-b1fb-8e5fc69e43de)
4. Press Cmd+Tab to switch to Chrome/Safari and then one more Cmd+Tab to switch back

You return not to the compare window as expected but to DC
![image](https://github.com/doublecmd/doublecmd/assets/2608545/e830d611-9242-4c6a-b6b0-273911a99612)

Compare window becomes lost somewhere in the background which is very unconvenient

**Comment by rich2014** [comment]
@lprot 

can't be reproduced on macOS 12.7.

is there anything special about your system?

**Comment by lprot** [comment]
> @lprot
> 
> can't be reproduced on macOS 12.7.
> 
> is there anything special about your system?

Looks like I cannot reproduce it on fresh Double Commander
Version: 1.2.0 alpha
Revision: 11354
Commit: ce4eb5ebb
Build date: 2024/06/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5
