### ISSUE TITLE
Multiarc config page does not allow to edit ID

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1718]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11366
Commit: 035cee8d7
Build date: 2024/06/15
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

Ctrl+PgDown on CH341SER.exe in [CH341SER_MAC.ZIP](https://github.com/user-attachments/files/15858059/CH341SER_MAC.ZIP) works. 
But for dmg or pkg only enter works.

My Multiarc settings:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/4119b633-b9d2-4bdb-83a3-c8a077b2667a)

**Comment by alexx2000** [comment]
No bug here. This does not work because there is no [signature specified](https://doublecmd.github.io/doc/en/multiarc.html#configids) for these archive types.

**Comment by lprot** [comment]
> No bug here. This does not work because there is no [signature specified](https://doublecmd.github.io/doc/en/multiarc.html#configids) for these archive types.

where to specify it? on exe files it works...

**Comment by alexx2000** [comment]
CH341SER.exe is a RAR archive and I guess it is processed by UnRAR plugin.

> where to specify it?

This is written in the documentation (link above).
