### ISSUE TITLE
Swapping panels causes the drive name in the inactive panel to be inconsistent

### ISSUE THREAD

**Issue by denis-komarov** [doublecmd/doublecmd#1723]
### Version

Double Commander
Version: 1.1.15 gamma
Revision: 505
Commit: 28125592a
Build date: 2024/06/12
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Swapping panels (Ctrl+U) causes the drive name in the inactive panel to be inconsistent:
![image](https://github.com/doublecmd/doublecmd/assets/57165393/c83f7a32-9c3c-4fb9-be46-86056c633a53)
Consistency only appears when the panel is activated.

**Comment by ags1234** [comment]
Double Commander
Version: 1.2.0 alpha
Revision: 11366
Commit: 035cee8d7
Build date: 2024/06/15
Lazarus: 3.4.0.0
FPC: 3.2.2
Platform: i386-Win32-win32/win64
OS version: Windows 11 23H2 x86_64


I confirm this.

**Comment by breaker27** [comment]
I don't have this problem under linux with an older version. Either OS dependent, or it's a new bug.

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Debian 12.6

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

**Comment by breaker27** [comment]
Now I understand that it's not about the line with the path, but the drive button.
The issue exists here under linux (version see above) in the same way. The drive icon is not updated correctly at one side.

**Comment by JonnyTech** [comment]
I confirm that I can replicate the issue.

The label above the active panel switches correctly.

The label above the inactive panel does not change.

See the text above the `tmp` tab in this video:

https://github.com/user-attachments/assets/09cee005-1d9a-4c6f-a9a1-e93fc6ec57aa

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23.3 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1
