### ISSUE TITLE
Wrong codepage autodetect

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1724]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11375
Commit: ecb6bd85e
Build date: 2024/06/19
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

[CodingLog.txt](https://github.com/user-attachments/files/15909185/CodingLog.txt)
[SRILog.txt](https://github.com/user-attachments/files/15909186/SRILog.txt)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/2369bc73-c61f-402c-b818-fcef55028ec3)
![image](https://github.com/doublecmd/doublecmd/assets/2608545/c2047ed1-0b93-44e2-b49f-9a34d1eace98)

In Total Commander no issues with that.

**Comment by alexx2000** [comment]
Execute DC from terminal and copy output here.

**Comment by rich2014** [comment]
@alexx2000 

`MyDetectCodePageType()` is WRONG.

`Detector.GetDetectedCharsetInfo()` is OK, but the Result was abandoned later, and the system encoding is used.


```pascal
function MyDetectCodePageType(const S: AnsiString): AnsiString;
var
  Detector: TnsUniversalDetector = nil;
  CharsetInfo: rCharsetInfo;
begin
  Detector:= TnsUniversalDetector.Create;
  try
    Detector.Reset;
    Detector.HandleData(PChar(S), Length(S));
    if not Detector.Done then Detector.DataEnd;
    CharsetInfo:= Detector.GetDetectedCharsetInfo;       <--- it's OK
    case CharsetInfo.CodePage of
        866: Result:= 'CP866';
        932: Result:= 'CP932';
        950: Result:= 'CP950';
       1251: Result:= 'CP1251';
       1252: Result:= 'CP1252';
       1253: Result:= 'CP1253';
       1255: Result:= 'CP1255';
      20866: Result:= 'KOI8-R';
      else                                               <--- it's WRONG
        begin
          Result:= CharsetInfo.Name;
          // When unknown encoding then use system encoding
          if SupportedEncodings.IndexOf(Result) < 0 then
          begin
            if (FallbackLang = 'be') or (FallbackLang = 'bg') or
               (FallbackLang = 'ky') or (FallbackLang = 'mk') or
               (FallbackLang = 'mn') or (FallbackLang = 'ru') or
               (FallbackLang = 'tt') then
              Result:= DetectCharsetCyrillic(S)
            else
              begin
                Result:= GetDefaultTextEncoding;
                if NormalizeEncoding(Result) = EncodingUTF8 then begin
                  // the system encoding is UTF-8, but it is not UTF-8
                  // use ISO-8859-1 instead. This encoding has a full 1:1 mapping to unicode,
                  // so no character is lost during conversions.
                  Result:= 'ISO-8859-1';
                end;
              end;
          end;
        end;
    end;
  finally
    FreeAndNil(Detector);
  end;
end;
```

**Comment by alexx2000** [comment]
`Detector.GetDetectedCharsetInfo()` is wrong too. It detects `x-mac-cyrillic` (code page 10007) but really it is a `windows -1251`. Technically it is a very hard to distinguish this two encodings on such small text because they are similar.

It works in the  Total Commander because it is a Windows application and Windows-1251 encoding is native for it.

`DetectCharsetCyrillic` is not called due wrong `FallbackLang`. I will fix it.

**Comment by rich2014** [comment]
@alexx2000 

1. `it's OK` means `Detector.GetDetectedCharsetInfo()` has done what it should do. not specifically referring to the small text.

2. `it's WRONG` means that the processing of the so-called unknown encoding is incorrect. eg. `GBK`, `GB 18030`....

3. even e410909 is just a hack. we should put all encodings supported by `chsdst` into known list.

**Comment by rich2014** [comment]
```pascal
  KNOWN_CHARSETS: array [eInternalCharsetID] of rCharsetInfo = (
......
  // PURE_ASCII_CHARSET
    (
      Name: 'ASCII';
      CodePage: 0;
      Language: 'ASCII'
    ),
  // UTF8_CHARSET
    (
      Name: 'UTF-8';
      CodePage: 65001;
      Language: 'Unicode'
    ),
  // UCS4_BE_CHARSET
    (
      Name: 'X-ISO-10646-UCS-4-3412';
      CodePage: 12001;
      Language: 'Unicode'
    ),
  // UTF16_BE_CHARSET
    (
      Name: 'UTF-16BE';
      CodePage: 1201;
      Language: 'Unicode'
    ),
  // UTF32_BE_CHARSET
    (
      Name: 'UTF-32BE';
      CodePage: 12001;
      Language: 'Unicode'
    ),
  // UCS4_LE_CHARSET
    (
      Name: 'X-ISO-10646-UCS-4-2143';
      CodePage: 12000;
      Language: 'Unicode'
    ),
  // UTF32_LE_CHARSET
    (
      Name: 'UTF-32LE';
      CodePage: 12000;
      Language: 'Unicode'
    ),
  // UTF16_LE_CHARSET
    (
      Name: 'UTF-16LE';
      CodePage: 1200;
      Language: 'Unicode'
    ),
	// LATIN5_BULGARIAN_CHARSET
    (
      Name: 'ISO-8859-5';
      CodePage: 28595;
      Language: 'Bulgarian'
    ),
  // WINDOWS_BULGARIAN_CHARSET
    (
      Name: 'windows-1251';
      CodePage: 1251;
      Language: 'Bulgarian'
    ),
  // KOI8_R_CHARSET
    (
      Name: 'KOI8-R';
      CodePage: 20866;
      Language: 'russian'
    ),
  // WINDOWS_1251_CHARSET
    (
      Name: 'windows-1251';
      CodePage: 1251;
      Language: 'russian'
    ),
  // ISO_8859_5_CHARSET
    (
      Name: 'ISO-8859-5';
      CodePage: 28595;
      Language: 'russian'
    ),
  // X_MAC_CYRILLIC_CHARSET
    (
      Name: 'x-mac-cyrillic';
      CodePage: 10007;
      Language: 'russian'
    ),
  // IBM866_CHARSET
    (
      Name: 'IBM866';
      CodePage: 866;
      Language: 'russian'
    ),
  // IBM855_CHARSET
    (
      Name: 'IBM855';
      CodePage: 855;
      Language: 'russian'
    ),
  //  ISO_8859_7_CHARSET
    (
      Name: 'ISO-8859-7';
      CodePage: 28597;
      Language: 'greek'
    ),
  // WINDOWS_1253_CHARSET
    (
      Name: 'windows-1253';
      CodePage: 1253;
      Language: 'greek'
    ),
  // ISO_8859_8_CHARSET
    (
      Name: 'ISO-8859-8';
      CodePage: 28598;
      Language: 'hebrew'
    ),
  // WINDOWS_1255_CHARSET
    (
      Name: 'windows-1255';
      CodePage: 1255;
      Language: 'hebrew'
    ),
  // BIG5_CHARSET
    (
      Name: 'Big5';
      CodePage: 950;
      Language: 'ch'
       ),
  // ISO_2022_CN_CHARSET
    (
      Name:  'ISO-2022-CN';
      CodePage:  50227;
      Language:  'ch';
      ),
  // ISO_2022_JP_CHARSET
    (
      Name:  'ISO-2022-JP';
      CodePage:  50222;
      Language:  'japanese';
    ),
  // ISO_2022_KR_CHARSET
    (
      Name:  'ISO-2022-KR';
      CodePage:  50225;
      Language:  'kr';
    ),
  // EUC_JP_CHARSET
    (
      Name:  'EUC-JP';
      CodePage:  51932;
      Language:  'japanese';
    ),
  // EUC_KR_CHARSET
    (
      Name:  'EUC-KR';
      CodePage:  51949;
      Language:  'kr';
    ),
  // X_EUC_TW_CHARSET
    (
      Name:  'x-euc-tw';
      CodePage:  51936;
      Language:  'ch';
    ),
  // SHIFT_JIS_CHARSET
    (
      Name:  'Shift_JIS';
      CodePage:  932;
      Language:  'japanese';
    ),
  // GB18030_CHARSET
    (
      Name:  'GB18030';
      CodePage:  54936;
      Language:  'ch';
    ),
  // HZ_GB_2312_CHARSET
    (
      Name:  'HZ-GB-2312';
      CodePage:  52936;
      Language:  'ch';
    ),
  // WINDOWS_1252_CHARSET
    (
      Name:  'windows-1252';
      CodePage:  1252;
      Language:  'eu';
    )

  );
```

**Comment by alexx2000** [comment]
Yes, it's a hack. But it significantly improves the quality of recognition. `chsdst` is not a perfect.

Since half of the encodings from the `KNOWN_CHARSETS` list is not supported by Viewer/Editor, so it makes no sense to add them all.

**Comment by rich2014** [comment]
why not supported?

the limitation of FPC?

**Comment by lprot** [comment]
> Execute DC from terminal, like this `/Applications/Double Commander.app/Contents/MacOS/doublecmd` and copy output here.



> Execute DC from terminal, like this `/Applications/Double Commander.app/Contents/MacOS/doublecmd` and copy output here.

![image](https://github.com/doublecmd/doublecmd/assets/2608545/3e4a9954-500a-4160-b235-ddf6c0ad64b3)

**Comment by lprot** [comment]
Works like magic on Double Commander
Version: 1.2.0 alpha
Revision: 11376
Commit: e41090916
Build date: 2024/06/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

so I'm closing this.

**Comment by alexx2000** [comment]
@rich2014 DC use encoding convert functions from `DCConvertEncoding` unit and Lazarus `LConvEncoding` unit.

I guess `iconv` supports these missing encodings. But DC don't use it in this case.

**Comment by rich2014** [comment]
@alexx2000 

as a temporary solution for Asian character encodings, I added encoding name mappings for
Chinese, Japanese, and Korean @4f4c53d.

although not perfect, at least they can be recognized in LConvEncoding() and common text in these encodings can be displayed correctly.

**Comment by alexx2000** [comment]
> what are the benefits of mixing libiconv and Lazarus LConvEncoding?

`LConvEncoding` can be used everywhere, while `libiconv` mostly under Unix. We know which encodings `LConvEncoding` supports,  `libiconv` not.

**Comment by rich2014** [comment]
@alexx2000 

another problem is that the `viewer` uses the first 2048 bytes for detection, while the `editor` uses 4096 bytes. Is this intentional or unintentional?

**Comment by alexx2000** [comment]
I guess it just happened historically. I think we can make it the same size (4096).

**Comment by rich2014** [comment]
make the same size (4096) by 900b369
