### ISSUE TITLE
error open simlink directory [LNK] in Windows

### ISSUE THREAD

**Issue by sedmoto** [doublecmd/doublecmd#1725]
### Version

Double Commander
Version: 1.1.12 gamma
Revision: 436
Commit: c8f17e36a
Build date: 2024/04/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows Server 2019 x86_64

### Description

![image](https://github.com/doublecmd/doublecmd/assets/70800767/efc9f5af-a6fa-4826-878a-68d03eb1a231)

**Comment by alexx2000** [comment]
1. I unable to reproduce.
2. This link exists only for backward compatibility, users should not use it (access to it is prohibited by the system). `AppData\Roaming` should be used instead.
