### ISSUE TITLE
Mouse cursor action indicators graphical issues

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1729]
### Version

Double Commander 
1.2.0 alpha
revision 11356
Lazarus 3.0.0.3
QT5
portable
Debian based Linux distro

### Description

Here are a couple graphical issues noticed with mouse cursor action indicators.
Only graphical, actions themselves work as intended by developer.

`"LINK" CURSOR USES DESKTOP ENVIRONMENT CURSOR`
-When you use mouse to drag and drop items the mouse cursor icons are designed to change depending on action performing.
-Copy = Green plus icon
-Move = Red minus icon
-Create Link = Blue curved arrow icon
I have only seen this blue Link cursor icon in pixmaps folder.
If you D&D while holding your “Alt” key, it appears that your desktop environments mouse cursor is used instead, not the blue arrow one provided by DC.

`ACTION INDICATORS OVERLAP WITH MOUSE CURSOR ARROW`
-Copy = Green plus = looks perfect
-Move = Red minus = the red minus is on top of the mouse cursor arrows tail, move off to the side basically the same location as the Move green plus without the vertical line.
-Link = Blue curved arrow = similar where it overlaps with mouse cursor arrow, if will fit can move over to the side of the cursor arrow like the green plus.

Thank You

**Comment by alexx2000** [comment]
`Ctrl+Shift` enables "Create Link" action. While `Alt` switches to system drag&drop, system cursor used in this case. So no bug here.

**Comment by advice2020** [comment]
@alexx2000 
Sorry to call you out specifically, but just wanted to say thank you.
I saw that this was fixed a while ago but wanted to compile new version just to try it before I responded.  I tried this a week or two ago and work/looks great, thank you very much for working on this, and in general for all the work you put into DC, really appreciate it.
