### ISSUE TITLE
Cmd key named as Winkey on DC for macOS

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1733]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11376
Commit: e41090916
Build date: 2024/06/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

![image](https://github.com/doublecmd/doublecmd/assets/2608545/9c15229f-4f46-4798-bbab-d98c11d0080a)

Never seen any MacBook with WinKey :)

**Comment by rich2014** [comment]
@alexx2000 

do you have any good ideas?

in addition to display, there are also `String-Shortcut mapping` and configuration file considerations.

**Comment by alexx2000** [comment]
I guess we can change it to `Cmd` under macOS. But `String-Shortcut mapping` should support both names for backward compatibility.

**Comment by lprot** [comment]
Updated shortcuts for the macOS distro here https://github.com/doublecmd/doublecmd/issues/1651

**Comment by rich2014** [comment]
@alexx2000 

maybe it would be better for you to implement it.

> I guess we can change it to `Cmd` under macOS. But `String-Shortcut mapping` should support both names for backward compatibility.
