### ISSUE TITLE
no thumbnails for hevc-encoded videos

### ISSUE THREAD

**Issue by superblobster** [doublecmd/doublecmd#1735]
### Version

Double Commander
Version: 1.1.12 gamma
Revision: 436
Commit: c8f17e36a
Build date: 2024/04/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

The Show Thumbnails feature does not work for some videos encoded with HEVC. It shows no thumbnail.
Please add full support for HEVC video thumbnails.

**Comment by superblobster** [comment]
> Does Windows Explorer show thumbnails for these files? Double Commander uses the capabilities of the operating system.

Nope, they aren't showing up in File Explorer either. But why?

**Comment by alexx2000** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/hevc-videos-in-windows-explorer/26d5ac37-65cd-4d1b-bd3b-fe95859fa23d

**Comment by superblobster** [comment]
> https://answers.microsoft.com/en-us/windows/forum/all/hevc-videos-in-windows-explorer/26d5ac37-65cd-4d1b-bd3b-fe95859fa23d

Thanks. The Icaros shell extension did the trick.
https://github.com/Xanashi/Icaros
