### ISSUE TITLE
Can't enter the cyrillic letter Л into any dialog field

### ISSUE THREAD

**Issue by velikodniy** [doublecmd/doublecmd#174]
It's not possible to enter the letter Л (only the capital one) into any dialog field including the "New Folder" dialog, text edit fields on the settings window, and fields that appear on renaming. When I try to enter it no letter appears in the field, the "renaming field" (that appears on F2) closes immediately.

The corresponding key combination (Shift + K) in English works perfectly. As well as typing this letter in any other application (unfortunately, I couldn't check the apps using Qt because Double Commander is the only such an application on my laptop).

The keyboard layout is Russian-PC, but Л doesn't work also for other Russial layouts.

Double Commander was installed on macOS BigSur (11.5.2 (20G95), x86) with HomeBrew. The version is `double-commander: 0.9.10-9640`.

Version info:

```
Double Commander
Version: 0.9.10 beta
Revision: 9640
Build date: 2021/01/10
Lazarus: 2.0.3.0-61194
FPC: 3.0.4
Platform: x86_64-Darwin-qt4
OS version: Mac OS X 10.16.0

Widgetset library: Qt 4.8.6, libQt4Pas 4.5.3
```

**Comment by alexx2000** [comment]
Try with native Cocoa version from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by velikodniy** [comment]
I installed the application from `doublecmd-1.0.0-9887.cocoa.x86_64.zip` and everything seems to work perfectly.

**Comment by alexx2000** [comment]
Good. But this version has other small glitches. Anyway it is another story.

**Comment by velikodniy** [comment]
Thank you very much for the suggestion. And for this brilliant project as well.

**Comment by Metotron** [comment]
Same problem in OpenSuse with version 1.0.11 from http://download.opensuse.org/repositories/home:/Alexx2000/openSUSE_Tumbleweed/, version 1.1.9 beta from https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-beta/openSUSE_Tumbleweed/ and version 1.2.0 alpha from svn repo
