### ISSUE TITLE
Crash when answering that you do not want to keep the changed file

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1744]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11393
Commit: e650495a5
Build date: 2024/07/06
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

Enter [config.tar.gz](https://github.com/user-attachments/files/16124162/config.tar.gz) and Edit (F4) the cfg-backup
![image](https://github.com/doublecmd/doublecmd/assets/2608545/c6f25278-0aee-41d2-8a7c-f5fbd494832e)
Change whatever, press ESC and answer Yes on save:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/09c0162c-26e1-458e-9407-654faa3c17e8)
When asked to copy backward, answer yes:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/4f6b73d1-1bfe-4c3e-9725-ff3d3a4bb49d)

When you got the message that the file cannot be saved answer No:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/585587fd-3d19-4e7e-a885-6d04a10759ad)

And DC crashes:
![image](https://github.com/doublecmd/doublecmd/assets/2608545/615d784d-3c7f-4f03-aa63-3578659cd852)

**Comment by JonnyTech** [comment]
Confirmed. 

```
Error:
Access violation

Please report this error to the bug tracker with a description of what you were doing and the following file:
/home/user/.config/doublecmd/doublecmd.err

Press Ignore to continue or Abort to abort the program.
```

Although, @lprot failed to follow the instructions in the error message, here is the contents of the requested error log file:

```
--------------- 08-07-2024, 11:38:12 ---------------
| DC v1.1.16 gamma Rev. 520 -- x86_64-Linux-qt5
| MX 23.3 Libretto -- Qt 5.15.8, libQt5Pas 5.6.1 | PID 4658
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007F085BF6013E in /usr/lib/doublecmd/plugins/wcx/zip/zip.wcx
```
