### ISSUE TITLE
Internal Viewer - Incorrect selection offset after search in Text mode

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1755]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11396
Commit: 752d3c9f2
Build date: 2024/07/15
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.5

### Description

1. Unpack [persistence.zip](https://github.com/user-attachments/files/16319190/persistence.zip) and press F3 on persistence.sqlite
2. Press 1 to be sure you are in Text mode
3. Press F7, enter mh2p and press ENTER
![image](https://github.com/user-attachments/assets/f09b0d4e-b66c-439d-bdca-34d0edf1ebb6)

4. Double click on MH2p and you see the selection offset is wrong:
![image](https://github.com/user-attachments/assets/19fe377d-cb95-47b8-b517-bd77a802ffcf)

If you search in Hex mode and then switch to Text mode and double click on MH2p, selection offset is correct:
![image](https://github.com/user-attachments/assets/5e5bdc7b-068b-4504-9c70-47945b633205)
![image](https://github.com/user-attachments/assets/54962e58-a1a8-43e9-8710-03314f65f2b1)

**Comment by lprot** [comment]
@rich2014 can you please take a look a this one. Very often stumble upon this bug. Thank you!

**Comment by rich2014** [comment]
@lprot   it is related to encoding. UTF8 is OK, but double-byte encoding has problems.

@alexx2000  i am not familiar with TViewControl. Alex, could you please fix this issue?

**Comment by lprot** [comment]
Dmg compilation failed.

**Comment by alexx2000** [comment]
> Dmg compilation failed.

Fixed.

**Comment by lprot** [comment]
Works like magic. In b11413. Thank you!
