### ISSUE TITLE
Find dialog: "Last search" button does nothing on new start

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [doublecmd/doublecmd#176]
![2753V](https://user-images.githubusercontent.com/46539653/131622769-a9fedbd4-88c0-4af4-b62b-66d3f1ee3729.png)

1. Do search;
2. Close DC;
3. Run DC again, open search dialog;
4. Click "Last search" button;
5. Nothing happens.

It is expected for search configuration to be recalled in step 5.

```
Double Commander
Version: 1.0.0 alpha
Revision: 9916
Commit: 3c6282a98
Build date: 2021/08/31
Lazarus: 2.0.12.0
FPC: 3.2.0
Platform: x86_64-Win64-qt5
OS version: Windows 10 Home 20H2 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1
```

**Comment by alexx2000** [comment]
It is by design. "Last search" button restore last search option only of current session.
