### ISSUE TITLE
Colors do not change in all categories. Also, the color in the tree does not change. Dark mode doesn't work.

### ISSUE THREAD

**Issue by moninahh** [doublecmd/doublecmd#1760]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 7 SP1 x86_64

### Description

Colors do not change in all categories (in the settings in _Colors_). Also, the colors in the tree do not change (in the settings in the _Tree View Menu Colors_). Dark mode does not work (in the settings in _Colors_).

**Comment by alexx2000** [comment]
Dark mode is Win10+ only feature. I forget to hide it under older Windows versions.

**Comment by moninahh** [comment]
Thanks for the quick response.


> I cannot reproduce.

I checked again and it works now.



> Dark mode is a Win10+ only feature. I forget to hide it under older Windows versions.

Can you make this possible for Windows 7? When working with light mode, my eyes are very tired. All my programs have dark mode, except yours.

**Comment by moninahh** [comment]
Thanks for the quick response.


> I cannot reproduce.

I checked again and it works now. In _Tree View Menu Colors_ also works.


> Dark mode is a Win10+ only feature. I forget to hide it under older Windows versions.

Can you make this possible for Windows 7? When working with light mode, my eyes are very tired. All my programs have dark mode, except yours.

**Comment by moninahh** [comment]
Thanks for the quick response.


> I cannot reproduce.

I checked again and it works now. In Tree View Menu Colors also works.

But when you change the _Brightess level of inactive panel_ option in the preview below, both panels change, not just the inactive one. The location of files in both panels also changes.


> Dark mode is a Win10+ only feature. I forget to hide it under older Windows versions.

Can you make this possible for Windows 7? When working with light mode, my eyes are very tired. All my programs have dark mode, except yours.

**Comment by moninahh** [comment]
Thanks for the quick response.

> I cannot reproduce.

I checked again and it works now. In Tree View Menu Colors also works.

But when you change the Brightess level of inactive panel option in the preview below, both panels change, not just the inactive one. The location of files in both panels also changes.

> Dark mode is a Win10+ only feature. I forget to hide it under older Windows versions.

Can you make this possible for Windows 7? When working with light mode, my eyes are very tired. All my programs have dark mode, except yours.

**Comment by moninahh** [comment]
Thanks for the quick response.


> I cannot reproduce.

I checked again and now it works. This also works in _Tree View Menu Colors_.

But when you change the _Brightness level of inactive panel_ option in the preview below, both panels change, not just the inactive one. The location of files in both panels also changes.


> Dark mode is a Win10+ only feature. I forget to hide it under older Windows versions.

Can you make this possible for Windows 7? When working with light mode, my eyes get very tired. All my programs have a dark mode, except yours.

**Comment by alexx2000** [comment]
> Can you make this possible for Windows 7?

No, it depends on the Windows 10 dark theme.
