### ISSUE TITLE
Unnecessary text added in doublecmd.xml config?

### ISSUE THREAD

**Issue by t0mmili** [doublecmd/doublecmd#1763]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98

### Description

I'm working on a small Python application that will allow to quickly apply different color/font themes to DC.
In the process I noticed something strange in config file. After changing Foreground/Background color additional text is added after XML tags. It seems to not influence functionality, but maybe worth looking at.

Example:
```
 <Colors>
   <Foreground>11842740</Foreground>Foreground
    <Background>1973790</Background>
    <Background2>1973790</Background2>Background2
 </Colors>
```

**Comment by alexx2000** [comment]
All colors settings is stored in `colors.json` [now](https://github.com/doublecmd/doublecmd/wiki/Changes-in-version-1.1.0).

**Comment by ags1234** [comment]
@t0mmili 
Just as an info, loosely related to coloring, only this tool is related to file coloring: https://github.com/cryham/ccc

@alexx2000
Maybe @t0mmili refers to the fact that DC adds an extra word in doublecmd.xml.

**Comment by t0mmili** [comment]
@ags1234 Exactly, I am refering to the fact that extra word is added in doublecmd.xml

@alexx2000 Didn't catch info about `colors.json`. Thanks! Why there is still `<Colors>` tag in doublecmd.xml then? And, appears to work as well.

**Comment by alexx2000** [comment]
DC don't write this tags at all. I don't know what Python tool is doing and how `doublecmd.xml` looks before DC start.

> Why there is still <Colors> tag in doublecmd.xml then? 

It stores some color related settings (but not colors).

**Comment by ags1234** [comment]
On a totally unrelated note, why is DC configuration stored using different types of files? JSON, CFG, XML, INI?
Why using JSON for information about colors, a new type of format?

**Comment by alexx2000** [comment]
Different tasks - different config types, plus evolution. Maybe some other configs will migrate to JSON.

**Comment by t0mmili** [comment]
@ags1234 Regarding coloring tool you mentioned earlier.
I had something slight different in mind - change the whole DC color theme in one click. Please have a look [here](https://github.com/t0mmili/dc-themer/releases/tag/v0.2.0) if you're interested.
I just published second release, which address breaking changes from DC v1.1.0, alexx2000 mentioned.

**Comment by ags1234** [comment]
@t0mmili I will check it out, thanks!
