### ISSUE TITLE
Crashed in window "Find Files" MacOS

### ISSUE THREAD

**Issue by kyarginski** [doublecmd/doublecmd#1764]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11400
Commit: 0092c7afa
Build date: 2024/07/25
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.5.0

### Description

DC crashed in window "Find Files".
How to reproduce:
1) open  window "Find Files" (by pressing options+F7)
2) set cursor in field "File mask"
3) press option + arrow down (I expected to see list of file masks)
Crashed!

**Comment by rich2014** [comment]
@kyarginski 

can't reproduce.

it would be best to provide a screen recording.

**Comment by kyarginski** [comment]
https://github.com/user-attachments/assets/069248b6-f3c4-4c7c-a255-ff727d9712b9

**Comment by rich2014** [comment]
follow the same operation and test it on multiple computers, and it works fine.

will other versions of DC work properly?

will it work properly on other computers?

**Comment by kyarginski** [comment]
It does not work.
I tried it with 3 version DC on 2 different computers with MacOS.
The versions which I used are
- Version: 1.2.0 alpha Revision: 11390
- Version: 1.2.0 alpha Revision: 11398
- Version: 1.2.0 alpha Revision: 11400

It's not such a serious error.
I do not encounter it in the usual scenario of using the program.
If you think everything is fine, ok.

P.S.
I just wanted to help.

**Comment by rich2014** [comment]
have you ever found out which version of DC worked properly on your computer?

**Comment by kyarginski** [comment]
Nein :-)
I try to install new versions of the program periodically.
Usually everything is more or less working.
This is the first time the program crashed.
That's why I decided to create a bug.

**Comment by JonnyTech** [comment]
Try deleting the DC config folder.

**Comment by ags1234** [comment]
Could it be related to some plugin installed in DC?

**Comment by kyarginski** [comment]
> Could it be related to some plugin installed in DC?

I don't think so.
No plug-ins have been installed.
The situation with the error is repeated on two different computers.
And two different installations.

**Comment by rich2014** [comment]
@kyarginski 

is there an error file generated?

usually `~/Library/Preferences/doublecmd/doublecmd.err`

**Comment by kyarginski** [comment]
No.
No new files `doublecmd.err` are generated.
Attached the old one.
[doublecmd.err.txt](https://github.com/user-attachments/files/16398750/doublecmd.err.txt)

**Comment by lprot** [comment]
@kyarginski do you have any assignments to Alt+Down here?
![image](https://github.com/user-attachments/assets/f86e2f1e-5640-424a-8b2e-5958770e258f)

**Comment by kyarginski** [comment]
Nothing special
![image](https://github.com/user-attachments/assets/e0bb6ffd-1db3-4b6a-a40f-4d6ac6ee2509)

**Comment by kyarginski** [comment]
By the way, I checked the stable version.
The program crashes with this version too.
![image](https://github.com/user-attachments/assets/814dd589-f309-4fe0-8a8d-506e25e0d8d5)

**Comment by lprot** [comment]
> Nothing special ![image](https://private-user-images.githubusercontent.com/16302160/353552621-e0bb6ffd-1db3-4b6a-a40f-4d6ac6ee2509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjI5MTksIm5iZiI6MTcyMjM2MjYxOSwicGF0aCI6Ii8xNjMwMjE2MC8zNTM1NTI2MjEtZTBiYjZmZmQtMWRiMy00YjZhLWE0MGYtNGQ2YWM2ZWUyNTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE4MDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjYyYmM3YjQ3OWYzNTUxYzRiNTQ1ODlkZGU3YjE4OTg2Y2RmZmFkOTE3OTM0NzhlNDJlYmRlY2U5MTFjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IthGQFLMGmhX0nkHpW3NXsLoyjTibHVKRHuBrMNZFls)

Try to delete Alt+Down. By the way DC has incorrect shortcut defaults for MacOS. You can take the correct shortcuts config here https://github.com/doublecmd/doublecmd/issues/1651

**Comment by kyarginski** [comment]
:-(
Stopped displaying the history of transition by directories.
But it still crashes in the search window

**Comment by kyarginski** [comment]
[crashes.txt](https://github.com/user-attachments/files/16431989/crashes.txt)

**Comment by lprot** [comment]
> :-( Stopped displaying the history of transition by directories. But it still crashes in the search window

Alt+Down serves as End button on MacOS (needed for MacBook Air where End button is missing). Proper shortcut for the history is Cmd+Down.

**Comment by kyarginski** [comment]
Thanks.

It's not even about which keyboard shortcut to use to display the history.
The problem is that in the "Find Files" window when you press Option+Down button combination the program terminates the work

**Comment by rich2014** [comment]
@kyarginski

**Comment by kyarginski** [comment]
Is it not fixed now?

I just rolled back to stable version
```
Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.6.0
```

**Comment by rich2014** [comment]
@kyarginski 

this is also just the gamma version, but did you choose the AArch64 version this time?

```
Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.6.0
```

**Comment by kyarginski** [comment]
It works (Version: [1.1.16 gamma Revision: 520](https://sourceforge.net/projects/doublecmd/files/macOS/Double%20Commander%201.1.16/doublecmd-1.1.16.cocoa.aarch64.dmg/download)).
Need I test something now?

**Comment by rich2014** [comment]
what do you mean `it works`?

> It works 
> Error with "Option+Down" still exists.

**Comment by kyarginski** [comment]
> what do you mean "it works"?

Sorry for the imprecise wording.
It does mean 
`It still does not work. Error with "Option+Down" still exists.`

Just checked on last version.
```
Double Commander
Version: 1.2.0 alpha
Revision: 11409
Commit: 1a6b8338a
Build date: 2024/08/03
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 14.6.0
```

**Comment by alexx2000** [comment]
If your computer has an Apple Silicon M processor then you should use `aarch64` DC version.

**Comment by rich2014** [comment]
@kyarginski 

I just fixed a bug in Lazarus/Cocoa related to ComboBox.

crash may be fixed.

test the last snapshoot(2024-8-9) please.

**Comment by kyarginski** [comment]
Testing version from [here](https://doublecmd.sourceforge.io/snapshots/doublecmd-1.2.0-11410.cocoa.aarch64.dmg)

Hooray! Error is fixed now ! The program doesn't crash anymore.

**Thanks for your work!**
