### ISSUE TITLE
No dark theme on Fedora 40

### ISSUE THREAD

**Issue by bocekm** [doublecmd/doublecmd#1767]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/07/02
Lazarus: 3.2.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Fedora release 40 (Forty)

Widgetset library: GTK 2.24.33

### Description

I've selected the dark theme on Fedora 40.
![Screenshot from 2024-08-01 13-09-50](https://github.com/user-attachments/assets/6ca19791-9018-40b4-af3f-01e5b8e1b7e3)

Because there's no theme switch in doublecmd settings I expected that the theme is inherited from the system settings.
![Screenshot from 2024-08-01 13-13-52](https://github.com/user-attachments/assets/578860af-7172-4602-9bbf-70329d2e6a33)

How do I set the dark theme? Thanks.

**Comment by alexx2000** [comment]
You should to change a GTK2 theme. I guess Gnome settings change only GTK3/GTK4 theme.

**Comment by bocekm** [comment]
@alexx2000, do you plan to switch doublecmd to GTK3/GTK4? I'm unable to change a GTK2 theme on Fedora (40 or 41) so I'm stuck with the light theme.

**Comment by JonnyTech** [comment]
> do you plan to switch doublecmd to GTK3/GTK4?

Lazarus does not have decent GTK3 support yet (alpha stage only).

![image](https://github.com/user-attachments/assets/57673dc2-54a4-4646-895d-942e4cc4a55b)

**Comment by alexx2000** [comment]
DC itself is ready to use GTK3. But Lazarus still is not ready and none of the Lazarus developers are actively working on this task. So I don't think that this will happen in the foreseeable future.

**Comment by alexx2000** [comment]
@bocekm I found only one way how to change the GTK2 theme in Fedora 40:
```
sudo mv /usr/share/themes/Adwaita /usr/share/themes/Adwaita-light
sudo ln -s /usr/share/themes/Adwaita-dark /usr/share/themes/Adwaita
```
It is not a very good method, but it works.
