### ISSUE TITLE
I have lost files while moveing files!!

### ISSUE THREAD

**Issue by AlexeiKharchev** [doublecmd/doublecmd#177]
I moved folder from one disk to another In Linux Mint (20.2 x64, fstype of both disks: NTFS)
Some moment I caught error "Unable to create folder..." (in Russian)
I pressed "Ingnore All" and expected that some files had been copied to destination, other - left in source disk
But as a result, I have nothing in destination, and lost copied files in source!!!

**Comment by alexx2000** [comment]
What version do you use? In the move operation source file deleted only after successful copy. Did you see only one error message?

**Comment by AlexeiKharchev** [comment]
Sorry, I have problems with damaged sdcard. I dont undesterdand why some time while moving everething was correct, but after error sd card erased
