### ISSUE TITLE
Buttons with the strike through in "Directory Hotlist" config

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1775]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11411
Commit: fcca7ac78
Build date: 2024/08/11
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

Are these buttons on the right stroken through on purpose?
![image](https://github.com/user-attachments/assets/be5f2544-4e27-40d1-bcae-ca7dfba2ef3b)

**Comment by alexx2000** [comment]
I cannot reproduce under macOS 11.

**Comment by maxpozdeev** [comment]
I can confirm this issue on macOS 13 with "Dark mode" enabled. In auto mode only one button - "Export".
<img width="1321" alt="dc-strike" src="https://github.com/user-attachments/assets/4f1f28d1-390b-479d-97cf-b04423647a03">

**Comment by rich2014** [comment]
on macOS, if the height of NSButton with NSRegularSquareBezelStyle is too small, a strange rectangular color block will be shown in the Button, in dark mode.

a minimum height constraint is implemented in Lazarus/Cocoa.

test the snapshoot(2024-08-12) please.

**Comment by lprot** [comment]
@rich2014 worked like magic! Thank you!
![image](https://github.com/user-attachments/assets/7140d67d-0b47-4013-b92e-f964d5735d48)
