### ISSUE TITLE
Internal Viewer - Incorrect selection offset after search in Code mode

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1778]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11413
Commit: 1812ed6e4
Build date: 2024/08/13
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

1. Unzip [pers_db.zip](https://github.com/user-attachments/files/16603316/pers_db.zip)
2. Press F3 on the pers_db.sql
3. Press F7 and search for MST2
You get:
![image](https://github.com/user-attachments/assets/16b31353-d7c3-464a-b319-05626f1f0ad7)

Related to https://github.com/doublecmd/doublecmd/issues/1755

**Comment by alexx2000** [comment]
I don't think that it is a bug. Code mode can work only with normal text files. It does not support binary files. Its behavior with binary files are undefined. Usually `.sql` files are normal text files with `SQL` code.

**Comment by lprot** [comment]
Fixed in Double Commander
Version: 1.2.0 alpha
Revision: 11416
Commit: 82e33bb64
Build date: 2024/08/14
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

Thank you!
