### ISSUE TITLE
Language configuration does not indicate currently selected language and asks about saving changes when pressing ESC

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1780]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11413
Commit: 1812ed6e4
Build date: 2024/08/13
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

Open Configuration>Options
![image](https://github.com/user-attachments/assets/a4a9ca66-d5d5-46fc-abb6-5d08a86700de)

Do not touch anything and just press ESC:
![image](https://github.com/user-attachments/assets/ea738387-b60c-4c65-9053-e5b8327cc5c9)

**Comment by rich2014** [comment]
@lprot 

it's caused by a bug in ListBox that was recently introduced into Lazarus/Cocoa and has been fixed.

test the snapshoot(2024-08-18) please.

**Comment by lprot** [comment]
Worked like magic in Double Commander
Version: 1.2.0 alpha
Revision: 11418
Commit: 81616d392
Build date: 2024/08/18
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

![image](https://github.com/user-attachments/assets/6c02c482-1ff9-4caa-85f9-70092826e5d1)

Thank you!
