### ISSUE TITLE
Directory copy ignores only overwrite older flag

### ISSUE THREAD

**Issue by geokimbo** [doublecmd/doublecmd#1786]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

When copying a directory to another path TC is now ignoring the Option, When File Exists = Overwrite Older and instead copies all files. Using Mark/Compare directories or Commands/Synchronise Directories works as expected and only copies newer versions of the files . I just updated to 1.1.17 with the same results.

**Comment by alexx2000** [comment]
Works fine for me.

**Comment by geokimbo** [comment]
Alexx

I've just repeated as a test. Steps to reproduce.
Create a directory and put a large file in it - I used a 2.5Gb movie
Copy that directory to another place in the file system with F5 and the option set to Overwirte older.
Now copy it again. - the progress bar moves at the same rate and the copy takes just as long as the original.
This is more obvious if you are copying to a slow writer like a USB HDD than an internal disk and may require a very large file to see it if using SSDs.

I checked with iotop as I was copying and on both the original and the repeated copy DC shows as writing to the disk

Do you see the same?
Cheers
Kim

**Comment by alexx2000** [comment]
OK, I can reproduce in this case.
