### ISSUE TITLE
Plugin ADB let doublecmd freeze

### ISSUE THREAD

**Issue by Mannshoch** [doublecmd/doublecmd#179]
the Plugin for ADB https://github.com/doublecmd/doublecmd/wiki/Plugins#Android_ADB
works quite well but:

If you open the Plugin Settings the dialog could not any more get closed pressing OK do not work.
![adb - doublecmd](https://user-images.githubusercontent.com/7795891/131980983-b1e31bf9-6cbe-4e87-87c0-e92998f5bd3c.png)

after open this dialog the only possibility to proceed further is to kill doublecmd

**Comment by alexx2000** [comment]
It is a third-party plugin, so bug should be reported to plugin author first.

**Comment by Mannshoch** [comment]
In my opinion a plugin should not be able to freeze the main application. So even the plugin has a problem, it should not affect doublecmd in that way.

**Comment by alexx2000** [comment]
Plugin is working in the main application address space (because it is a shared library). It can do anything with the main application. This is how shared libraries work, this cannot be changed.

**Comment by gitgt** [comment]
Please close and write if you reported to plugin author (a link).
