### ISSUE TITLE
crash on packing file into .tar.xz archive

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#1792]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.4 LTS

Widgetset library: GTK 2.24.33

### Description

```
--------------- 23-08-2024, 07:34:29 ---------------
| DC v1.1.16 gamma Rev. 520 -- x86_64-Linux-gtk2
| Ubuntu 22.04.4 LTS -- GTK 2.24.33 | PID 45073
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $000073B04415F06E in /home/user/doublecmd/plugins/wcx/zip/zip.wcx   
```

- get .xz file: https://sourceforge.net/projects/cudatext/files/release/1.216.0.0/cudatext-linux-qt5-armhf-1.216.0.0.tar.xz/download
- enter into it on left panel, into cudatext/py dir
- from right panel, copy changed file cudatext.py to archive

**Comment by lprot** [comment]
@Alexey-T is it reproducible on https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/AppImage/doublecmd-gtk-latest-x86_64.AppImage ?

**Comment by Alexey-T** [comment]
no, AppImages runs ok.
