### ISSUE TITLE
AppImage links outdated

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#1798]
### Version

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: MX 23.3 Libretto

Widgetset library: GTK 2.24.33

Double Commander
Version: 1.1.16 gamma
Revision: 520
Commit: ca77fea98
Build date: 2024/06/22
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 23.3 Libretto

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

### Description

https://github.com/doublecmd/doublecmd/releases/tag/v1.1.17

Both AppImage links on the release page download v1.1.16 rather than v1.1.17 (see version details above)

**Comment by alexx2000** [comment]
Fixed.
