### ISSUE TITLE
Toggle "Filter" is switched off after starting DC

### ISSUE THREAD

**Issue by RhysSpellbinder** [doublecmd/doublecmd#180]
In the quick filter the user always have to switch the toggle "Filter" (TfrmQuickSearch.tglFilter.checked) after starting DoubleCommander.
The other toggle button status are saved in the XML (Node := FindNode(Root, 'QuickSearch', True); )
Could you add "Filter" True/False to the configuration?
![QuickSearchFilterToggleNotSet](https://user-images.githubusercontent.com/23404338/132565047-5eba8c45-b39b-4e0a-b648-c1280ee2485c.jpg)

**Comment by alexx2000** [comment]
No, it is two different commands. It depends on how you execute it. Ctrl+F - quick filter, Ctrl+S - quick search. See also "Options"->"Keyboard" and cm_QuickSearch, cm_QuickFilter internal commands.

**Comment by RhysSpellbinder** [comment]
Thank you very much. This is really nice. :-)
Unfortunately I didn't find this option, so I put this issue up. Sorry.
