### ISSUE TITLE
Dark mode search results background all white

### ISSUE THREAD

**Issue by dweiss** [doublecmd/doublecmd#1800]
### Version

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.6.1

### Description

Search results in dark mode show up on an all-white background, making them invisible.

![image](https://github.com/user-attachments/assets/66dae8a2-3d2f-4da4-917e-18e48efa6717)

**Comment by alexx2000** [comment]
#1791

**Comment by alexx2000** [comment]
Download again.

**Comment by dweiss** [comment]
Thanks. Tried the snapshot version and it works. The one I have is the latest from brew so I'll wait for an official relase.
