### ISSUE TITLE
"Unsupported function!" when clicking in "Search" button

### ISSUE THREAD

**Issue by RafaelLinux** [doublecmd/doublecmd#1804]
### Version

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/29
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: openSUSE Tumbleweed

Widgetset library: Qt 5.15.14, libQt5Pas 5.6.1

### Description

When I click in the binoculars button on the toolbar, DC shows a window warming me about "Unsupported function" (maybe "feature" in English).

![imagen](https://github.com/user-attachments/assets/0ca80629-5540-49e3-a57d-29f76ebbea06)

**Comment by alexx2000** [comment]
This function works only with a real filesystem. I guess you call it from somewhere else.

**Comment by RafaelLinux** [comment]
I understand. Search fails with remote folders, like SMB and FTP folders. I thought it will work like Krusader.
Will be this feature available?
Thanks

**Comment by alexx2000** [comment]
I guess it will be in the future.
