### ISSUE TITLE
external terminal tilix can't run via parameter

### ISSUE THREAD

**Issue by freeman35-5** [doublecmd/doublecmd#1805]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11423
Commit: c159f39
Build date: 2024/08/27
Lazarus: 3.4.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

### Description

I wanna add this parameter
"-s ~/tilix_layout.json" (open tilix and change windos sizes and position then click to S and save this.)
but if I add this to from option " Command for just running terminal"
Command :tilix
parameters: -s ~/tilix_layout.json

Parameters run, but always open in "home" folder. If I remove parameters, work normal, I mean folder is, where I click to F9, (Panel show folder) tilix terminal open in that folder. work like a "x-terminal-emulator"

And looked to help, but not any info about parameter(s) and how to work.
regards

**Comment by j2969719** [comment]
>Parameters run, but always open in "home" folder. 

erm
`cat ~/tilix_layout.json | grep directory`

**Comment by alexx2000** [comment]
Tilix layout file contains a default directory that's why it always opens there. Add `-w %D` to parameters field to use directory from DC: `-s ~/tilix_layout.json -w %D`.

**Comment by freeman35-5** [comment]
> Tilix layout file contains a default directory that's why it always opens there. Add `-w %D` to parameters field to use directory from DC: `-s ~/tilix_layout.json -w %D`.

Thank you, working.
