### ISSUE TITLE
Panel doesn't get focus by mouse click on free space

### ISSUE THREAD

**Issue by VijitCoder** [doublecmd/doublecmd#1808]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/04/01
Lazarus: 3.0.0.3
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 24.04.1 LTS

Widgetset library: Qt 5.15.13, libQt5Pas 5.6.1

### Description

Here is the problem: in the recent past I could click by mouse on panel, where is _no directories or files_ - this panel got focus. But now I need to click to _any element on panel_ to reach the same result. It's inconvenient, at least. And even worse, it can lead to unwanted action on the element.

I don't know what or when changed. I updated KUbuntu 22.04.4 -> 24.04, obviously DC updated too. That's all I've been able to find out.

**Comment by JonnyTech** [comment]
> Version: 1.1.11 beta

Please test with v1.1.17 - both gtk2 and qt5 builds - to confirm whether the issue still exists.

**Comment by VijitCoder** [comment]
Great! It works again. Thanks a lot.
```
Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 3.4.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 24.04.1 LTS

Widgetset library: Qt 5.15.13, libQt5Pas 5.6.1
```

> Please test gtk2 and qt5 builds

You're asking too much )) I'm using KDE with qt5 and have no desire to test soft with gtk. There is a lot of space for unpredictable bugs on the edge of two libraries and I don't want to solve them.
