### ISSUE TITLE
Incorrect directory name abbreviation

### ISSUE THREAD

**Issue by hikikomori4** [doublecmd/doublecmd#1811]
### Version

Double Commander Version: 1.1.15 gamma Revision: 505 Commit: 28125592a Build date: 2024/06/12 Lazarus: 3.4.0.0 FPC: 3.2.2 Platform: x86_64-Linux-qt6 OS version: Manjaro Linux Widgetset library: Qt 6.7.1, libQt6Pas 6.2.1

### Description

![Screenshot_%Y%M%D_%H%m%S](https://github.com/user-attachments/assets/4fdccd47-ed89-4ca1-8cef-de1f168f59ec)

If you mark Files view/Column like this:
[   ] Cut text to column width
[ v ] Extend cell width if text is not fitting into column
then long directory names overlap the information in the following columns. And the logical behavior if cut is not selected is auto-expansion of the column to the length of the name.
An example of a directory name on which a glitch was noticed:
Boombox Panasonic XBS RX-CT820 sn CW12345678

---------

If you mark Files view/Column like this:
[ v ] Cut text to column width
[ v ] Extend cell width if text is not fitting into column
then directory names from non-Latin letters are abbreviated incorrectly and illogically. For example:

Город -> Гор..
чудо -> чу..

This is very inconvenient and strange, because long names in Latin remain untouched nearby.
The following name remains unchanged: "Очень странное название каталога".
But in this one the last word is shortened:  "Чудо какое странное название". 

---------

I was able to find an acceptable look like this:
[ v ] Cut text to column width
[   ] Extend cell width if text is not fitting into column
But I would like the glitches to be fixed.

**Comment by alexx2000** [comment]
#260

**Comment by alexx2000** [comment]
Fixed.

> And the logical behavior if cut is not selected is auto-expansion of the column to the length of the name.

No, this option only enables/disables of adding '..' at the end when text is too long. It has nothing to do with the auto-expansion.
