### ISSUE TITLE
NOT Execute command in terminal if filename has space char

### ISSUE THREAD

**Issue by freeman35-5** [doublecmd/doublecmd#1812]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11425
Commit: 7d64405
Build date: 2024/09/04
Lazarus: 3.4.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

### Description

Hello,
Bug :
if file name has a space, example "1- build.sh", 
"Shift+Enter" -> Execute command in terminal (choose in Options..)
wrote this error !
sh: 1: /home/folder_name/1-: not found

Question:
How to add this parameter  -s ~/tilix_layout.json -w %D  to
-e sh -c '{command};echo -n Press ENTER to exit... ; read a' 
regards

**Comment by alexx2000** [comment]
#1607
