### ISSUE TITLE
Wrong text decoding in internal differ tool

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1816]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11421
Commit: de5e1d44e
Build date: 2024/08/23
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

[DC_tests.zip](https://github.com/user-attachments/files/16912876/DC_tests.zip)

Compare 1.bin and 2.bin:
![image](https://github.com/user-attachments/assets/a2813b15-7202-4905-a108-b7c7c6d18601)
in the left panel "49" has to be decoded as "I"?

**Comment by alexx2000** [comment]
What is wrong here? 0x49 = "I".
