### ISSUE TITLE
doublecmd-1.2.0-11438.cocoa.aarch64 crashes during startup

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#1819]
### Version

see screenshot

### Description

doublecmd-1.2.0-11438.cocoa.aarch64 crashes during startup.

![version](https://github.com/user-attachments/assets/ce064e39-d594-490b-a4ee-6f8d9392c8f8)

[doublecmd.err.zip](https://github.com/user-attachments/files/16923268/doublecmd.err.zip)

**Comment by alexx2000** [comment]
Crashes in the `TfrmMain.NSServiceMenuGetFilenames`.

**Comment by rich2014** [comment]
fixed in 9310362

try again please.
