### ISSUE TITLE
Terminal Output

### ISSUE THREAD

**Issue by daniilpetrov** [doublecmd/doublecmd#182]
Поскольку товарищ главный разработчик владеет русским, я не стану мудрить псевдоаглицкий машинный перевод, а напишу на русском. Пытался писать на почту, но ответа не дождался, а вопрос актуальный для многих:

Файловые менеджеры Norton и Total Commander полноценно работают с терминалом, позволяя запускать скрипты и консольные программы. При их запуске панели скрываются, открывая вывод в консоль, и по окончанию выполнения снова появляются, позволяя всегда скрыть и открыть их нажатием Ctrl+O, что позволяет не только копировать файлы, но и заниматься разработкой. Вы не думали сделать полноценный взрослый командер или Double Commander так и останется поделкой, требующей для разработки ещё и Midnight Commander?

Gnome Connamder к сожалению тоже разрабатывают на коленке и используют морально устаревшие пакеты, что до сих пор не дало возможности собрать и опробовать их чудо программистской мысли. Разработчики Ubuntu в последней версии своей ОС наконец избавились от зависания звукового сервера на картах Sound Blaster, что позволяет наконец наслаждаться работой в Линукс, однако вопрос с полноценным командером до сих пор остаётся открытым, поскольку его просто нет.

**Comment by Skif-off** [comment]
Вы не могли бы как-то повнятнее/поопределённее написать, что именно получается в ТС и не очень в DC?

> нажатием Ctrl+O

В Total Commander в стандартных такой хоткей не вижу.

**Comment by alexx2000** [comment]
В Total Commander такой функции нет. Консоль там можно приделать только с помощью плагинов TConsole и TotalConsole (плюс была еще какая-то третья штука), которые с помощью хаков встраивают окно консоли в программу.

В Double Commander подобная функция есть, включается в настройках на странице "Вид окна" галочкой "Окно терминала". После этого будет работать комбинация клавиш Ctrl+O. 

Однако она не доведена до ума, написать полноценный эмулятор терминала не просто. Да и особого желания нет, т.к. в графическом файловом менеджере проще запустить консоль в отдельном окне (клавишей F9), чем я всегда и пользуюсь при разработке. Так что это дело привычки, не более того. Это в консольных файловых менеджерах она жизненно необходима, т.к. они могут работать в чистой консоли.

**Comment by daniilpetrov** [comment]
Вы работали с Norton, Midnight или Total Commander? Там в фоновом режиме доступна консоль / терминал, на неё и обратно всегда можно переключиться нажатием Ctrl+O - консоль <-> панели. При запуске скриптов или консольных приложений из панелей приложение переключается на вывод в консоль. Поработайте с данными командерами и поймёте, о чём я говорю. Double Commander функций хватает лишь для копирования файлов, но для разработки он не годится, так как нет полноценной работы с терминалом, как в выше указанных командерах, и для разработки приходится дополнительно использовать Midnight Commander.

**Comment by Skif-off** [comment]
> Norton, Midnight или Total Commander

Вы валите в одну кучу консольные ФМ и самый что ни на есть гуёвый.
И повторю ещё раз: в Total Commander по умолчанию клавиатурное сочетание Ctrl+O **не** задействовано. Что у вас на нём висит?

> При запуске скриптов или консольных приложений из панелей приложение переключается на вывод в консоль.

Двойной клик по умолчанию откроет и закроет окно коноли. Как вы это делаете в Total Commander и пытаетесь  в Double Commander?

**Comment by daniilpetrov** [comment]
**Skif-off**: Я уже год как не пользуюсь Виндой, поэтому точно не вспомню, но припоминаю, что в нём при запуске консольных приложений выходила консоль и проблем с консольной разработкой не было, так как собирал всё в MinGW, и Ctrl+O вроде как выводила весь предыдущий вывод в консоль. У меня был PowerPack, который во многом был мощнее начальных сборок, вполне возможно, что это именно его преимущество. У многих сборок под MinGW был цветной вывод в консоль и я его прекрасно помню, но вполне возможно, что TC выводил и в отдельном приложении-консоли, но в Double Commander консоль не выводится вообще - скрипты и консольные приложения запускаются в фоне.

**Comment by Skif-off** [comment]
> но припоминаю, что в нём при запуске консольных приложений выходила консоль и проблем с консольной разработкой не было

Это не совсем так, по умолчанию окно сразу же закрывалось, но это не суть.
И это особенность ОСи, а не файлового менеджера(ов) с графическим интерфейсом: запуск в оболочке c учётом файловых асоциаций из системы (ShellExecute). В Linux эта функция работает немного иначе.

Попробуйте запуск не с Enter/двойной клик, а с Shift+Enter, так DC должен явно запустить приложение в терминале (будет использоваться команда из раздела настроек Инструменты > Терминал (первая)).

Ну и DC, всё-таки, не консольный ФМ :) Если нужен запуск с параметрами, то можно навесить кнопки/хоткей, навскидку для распаковки архива tar под курсором:
команда: ```tar```
параметры: ```%t1 -xvf %f0```

**Comment by daniilpetrov** [comment]
**Skif-off**: Ну да - это уже выход из ситуации :) премного благодарен!
