### ISSUE TITLE
Broken snapshot doublecmd-1.2.0-11463.cocoa.aarch64.dmg

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#1836]
### Version

doublecmd-1.2.0-11463.cocoa.aarch64.dmg

### Description

The snapshot doublecmd-1.2.0-11463.cocoa.aarch64.dmg is broken. It has only half of the size of previous, working snapshots, and it cannot be installed or started.

**Comment by alexx2000** [comment]
Lazarus (lazbuild) was broken.

**Comment by alexx2000** [comment]
Fixed.
