### ISSUE TITLE
Unprovoked Tab Switch

### ISSUE THREAD

**Issue by kaitrek** [doublecmd/doublecmd#184]
I've been having unprovoked tab switches since at least revision 8800.
I've noticed that this tends to happen when the folder name is long and I have a bunch of tabs open. Haven't repro the exact conditions but basically the tab in the pane switches to a different random or previous tab. When I clicked on another tab within the pane I got this List index error first time (just upgraded to latest nightly, so some error notification must have been added).

--------------- 22-09-2021, 14:21:02 ---------------
| DC v1.0.0 alpha Rev. 9887 -- x86_64-Darwin-cocoa
| Mac OS X 10.16.0 | PID 68809
Unhandled exception: EListError: List index (-1) out of bounds
  Stack trace:
  $0000000100026CB9 in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100485CD7 line 728, column 9 of ufileviewnotebook.pas in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100114ACC line 3913, column 17 of include/wincontrol.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100108546 line 122, column 21 of include/dragmanager.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100108C9D line 254, column 7 of include/dragmanager.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010010A425 line 739, column 27 of include/dragmanager.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010010A90A line 834, column 16 of include/dragmanager.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100124E38 line 2344, column 52 of include/control.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $0000000100125C3F line 2829, column 20 of include/control.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010000E27A in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010011804D line 5429, column 28 of include/wincontrol.inc in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010024FA6D line 112, column 36 of lclmessageglue.pas in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010024DD4D line 1407, column 51 of cocoa/cocoawscommon.pas in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $000000010024CE15 line 1043, column 7 of cocoa/cocoawscommon.pas in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $00000001002ABECB line 600, column 7 of cocoa/cocoatabcontrols.pas in /Applications/Double Commander cocoa 64bit v1.0.0r9887.app/Contents/MacOS/doublecmd
  $00007FFF22FF0878 in /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  $00007FFF22FF8BF1 in /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

Double Commander
Version: 1.0.0 alpha
Revision: 9887
Commit: d61ab7af9
Build date: 2021/08/22
Lazarus: 2.2.0.2
FPC: 3.2.1
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by rich2014** [comment]
the same as #657.

fixed by https://gitlab.com/freepascal.org/lazarus/lazarus/-/merge_requests/119

should be closed.
