### ISSUE TITLE
4-key shortcuts don't work (<key>+<key>+<key>+<key>). "Network" and "Favorites" do not have an underlined letter.

### ISSUE THREAD

**Issue by moninahh** [doublecmd/doublecmd#1841]
### Version

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 7 SP1 x86_64

### Description

4-key shortcuts don't work.
For example, "Ctrl+Shift+Alt+F9".

"_Network_" and "_Favorites_" in the menu do not have an underlined letter, so they cannot be opened using the keyboard via the "Alt+[key]".

**Comment by alexx2000** [comment]
> For example, "Ctrl+Shift+Alt+F9".

Works fine for me. With some keyboards `Ctrl+Alt` can have a [special meaning](https://en.wikipedia.org/wiki/AltGr_key#Ctrl+Alt), maybe that's the reason.

**Comment by alexx2000** [comment]
`Ctrl+Alt` also can conflict with [Ctrl+Alt+Letters](https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys) option. You should to disable it, if you want to use such hotkeys.

**Comment by moninahh** [comment]
> `Ctrl+Alt` also can conflict with [Ctrl+Alt+Letters](https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys) option. You should to disable it, if you want to use such hotkeys.

If disable it, then it works. Does it work for you without disabling it?

**Comment by alexx2000** [comment]
No.

**Comment by alexx2000** [comment]
I updated [all language files](https://github.com/doublecmd/doublecmd/commit/3b22b4b5c65591a24410ba60a5639fba894fdf9f). But of course only original English text. The translator decides which letter to use. Some of translations already has it.
