### ISSUE TITLE
The function "Show Occupied Space" does not distinguish between 0-size directories and non-accessible directories

### ISSUE THREAD

**Issue by antodc** [doublecmd/doublecmd#1846]
### Version

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Not sure it is a bug or a feature request, but at the moment it is shown “0” in both cases. Maybe DC might use “??” in the second case?

**Comment by alexx2000** [comment]
It can be implemented when a whole directory is inaccessible. But what to do if only some subdirectories are inaccessible?

**Comment by antodc** [comment]
Perhaps it could be something like "0 (?)" when the whole directory is inaccessible and, say, "X Mb (?)" when only some subdirectories are inaccessible. So, DC would show what was able to measure and, at the same time, would highlight that the true size may be different. Though, I understand that it might be confusing for someone.

**Comment by alexx2000** [comment]
I added indication when a whole directory is inaccessible.

> "X Mb (?)" when only some subdirectories are inaccessible.

It is too hard.  I looked at how Total Commander behaves in this case, it has not a special indication. So I prefer to leave everything as is in this case.
