### ISSUE TITLE
Hot Key File Rename Does Not Obey Configuration Setting to Only Select Filename Without Extension

### ISSUE THREAD

**Issue by kaitrek** [doublecmd/doublecmd#185]
My config is setup such that rename operation is supposed to select ONLY the filename, without the extension.
Right Click on File -> Rename: selects without extension
![image](https://user-images.githubusercontent.com/24997534/134580481-9452a5ea-7e2f-4b0e-b889-11b4686faa3e.png)

Double Delayed Click: selects without extension
![image](https://user-images.githubusercontent.com/24997534/134580555-dd73108e-fe71-4089-a8f8-979aa069c307.png)

**F2 hot key: selects entire filename, this is a BUG!**
![image](https://user-images.githubusercontent.com/24997534/134580723-0760cddf-bde0-48be-8b7e-cd9802951eda.png)

**Shift+F6 hot key: selects entire filename, this is a BUG!**
![image](https://user-images.githubusercontent.com/24997534/134580622-6ff747e6-8816-4ea4-8484-bcd3d9ec5094.png)

![image](https://user-images.githubusercontent.com/24997534/134580057-9c3b3a74-40a4-4276-90f9-2770accf8003.png)

![image](https://user-images.githubusercontent.com/24997534/134580117-91f27362-1da8-4aa7-919d-410721735bac.png)

Double Commander
Version: 1.0.0 alpha
Revision: 9887
Commit: d61ab7af9
Build date: 2021/08/22
Lazarus: 2.2.0.2
FPC: 3.2.1
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by alexx2000** [comment]
Sorry, macOS version is not supported anymore. Snapshots provided as is.

**Comment by fosemberg** [comment]
still relevant for:
Double Commander
Version: 1.1.0 alpha
Revision: 10045
Commit: bffeb175a
Build date: 2022/01/06
Lazarus: 2.2.0.4
FPC: 3.2.1
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by fosemberg** [comment]
[In this post I describe different options to fix it through karabiner-elements](https://github.com/pqrs-org/Karabiner-Elements/issues/2966#issuecomment-1024434763).
Maybe it will be useful to someone.

**Comment by rich2014** [comment]
the same as #296.

fixed by #545.

should be closed.
