### ISSUE TITLE
Broken multiple file permissions dialog in Linux

### ISSUE THREAD

**Issue by D0m0** [doublecmd/doublecmd#1864]
### Version

Double Commander Version 1.1.18 gamma Revision 568, Commit c45365d1b, Build 2024/09/21

### Description

Since version ~1.1.0 on Linux I can't set file permissions on multiple files, which was a cool feature.
If I select multiple files and open properties (Alt+Enter) all permission checkboxes are cleared, and even if I set them, they are not applied.

**Comment by alexx2000** [comment]
> all permission checkboxes are cleared

They are not cleared, they have a "grey"/uncertain state.

> even if I set them, they are not applied.

They are applied without any problems.

**Comment by D0m0** [comment]
Sorry, it does actually work. My installation had this "Numix" theme for GTK3, which poorly displays grey/uncertain checkboxes (they all seem unchecked). I'm closing the issue!
