### ISSUE TITLE
the file filter doesn't work on Windows

### ISSUE THREAD

**Issue by muellerto** [doublecmd/doublecmd#1872]
### Version

Double Commander
Version: 1.1.18 gamma
Revision: 568
Commit: c45365d1b
Build date: 2024/09/21
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 23H2 x86_64

### Description

When I hit `/` in the files list I get the filter dialog at the bottom. I can do what I want there, the result list is always empty.

I have a directory with lots of DLLs:
![1](https://github.com/user-attachments/assets/fbe68db0-48d5-4f40-ba9f-0cb3d15a23c6)

When I use a filter there to show only DLL files the resulting list is empty:
![2](https://github.com/user-attachments/assets/41851798-73ac-456f-b8f3-8d70421c7bae)

I played a lot with `{` and `}` and uppercase/lowercase and all that, nothing works.

Note: I checked this on Linux because I was also not sure about the syntax, perhaps I made a syntax error. But on Linux it works without any problem. Every input gives the expected reaction.

BTW: It would also be good when the filter dialog could react on ENTER. I hit ENTER all the time but the result is that the dialog just closes as if I had used ESC. So you need indeed a keystroke (`/`) to open the dialog (is there any other way???) but a damned mouse click to close it successfully.

**Comment by alexx2000** [comment]
You are using it wrong. You should not press `/`. Press `Ctrl+F` and enter `*.dll`. See documentation for details:

https://doublecmd.github.io/doc/en/help.html#cm_QuickSearch
https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys
https://doublecmd.github.io/doc/en/configuration.html#ConfigQuick

**Comment by muellerto** [comment]
But on Linux `/` works for filtering. And on Windows `/` leads to the same filter dialog like Ctrl-F. So why should Ctrl-F work but not `/`? - OK, I can live with that.

**Comment by alexx2000** [comment]
Any key press (almost) opens this dialog. But `/*.dll` is invalid mask.
