### ISSUE TITLE
Strange background colouring in file properties popup

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1885]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11538
Commit: 6c24641cd
Build date: 2024/10/04
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

Press Alt+Enter to reproduce:
![image](https://github.com/user-attachments/assets/5ce5631d-a515-4c1b-a41b-67b4dcf3829a)

@rich2014 please see the buttons row on the screenshot above. Looks like something strange is happening in Options>Directory Hotlist:
![image](https://github.com/user-attachments/assets/d11f99d6-215d-428a-9d6c-0f509267d71c)

**Comment by lprot** [comment]
In checksum popup the button background is not correct as well https://github.com/doublecmd/doublecmd/issues/1817

**Comment by lprot** [comment]
@rich2014 it is not completely fixed:
![image](https://github.com/user-attachments/assets/d61caa5b-aef3-4d71-8455-470a887d096f)
![image](https://github.com/user-attachments/assets/523f39e6-8263-47e5-8e52-b6e97d16c0e9)

**Comment by rich2014** [comment]
@lprot 

where?

> it is not completely fixed

**Comment by lprot** [comment]
@rich2014 still not properly fixed in Double Commander
Version: 1.2.0 alpha
Revision: 11542
Commit: 04babd85e
Build date: 2024/10/05
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

Background colour of the text on the boxes of "Properties" is wrong:
![image](https://github.com/user-attachments/assets/06f691f4-8e3b-46c7-af52-9681b7f4448a)

On the "Attributes" it is correct:
![image](https://github.com/user-attachments/assets/8018e65f-395b-429d-af06-01253b6e0bb3)

**Comment by lprot** [comment]
@rich2014 please reopen. It is still not fixed on:
Double Commander
Version: 1.2.0 alpha
Revision: 11545
Commit: d51ac676f
Build date: 2024/10/05
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

**Comment by lprot** [comment]
@alexx2000 but I wonder why these elements are editboxes?
![image](https://github.com/user-attachments/assets/bdf49aa7-3388-4b19-84b4-a3faa3322f4d)

If they really are, then I would expect the same colouring as for the "Octal" on the "Attibutes" tab :)

**Comment by alexx2000** [comment]
They are not edit boxes. They are text labels with text selection capability.

**Comment by lprot** [comment]
> They are not edit boxes. They are text labels with text selection capability.

As you can see on the screenshot above, these labels are editable.

**Comment by alexx2000** [comment]
It is a bug.

**Comment by lprot** [comment]
> They are not edit boxes. They are text labels with text selection capability.

This is how labels look like in Finder:
![image](https://github.com/user-attachments/assets/f21945c8-d479-4c0a-9dfb-df4a3bee23a9)

That's why lighter colour looks freaky in DC :)

**Comment by lprot** [comment]
Now it's perfect in both modes:
![image](https://github.com/user-attachments/assets/efaa2f6d-5a23-42f6-b924-c6fda783f23d)
![image](https://github.com/user-attachments/assets/58bd50f1-da3b-46a0-9f2c-35624364f8a4)
Thank you!
