### ISSUE TITLE
Wrong button and background colouring in pack, unpack, split, combine, directory hotlist and  popups

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1887]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11539
Commit: 6394f2165
Build date: 2024/10/04
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

@rich2014 related to https://github.com/doublecmd/doublecmd/issues/1885

Button background colour is wrong:
![image](https://github.com/user-attachments/assets/631acedd-3b3b-43cc-9d13-346ae303d5e3)

Button and child background colour is wrong:
![image](https://github.com/user-attachments/assets/0d217cc5-66ee-4997-a58f-17e73eacf6e4)

Button and child background colour is wrong:
![image](https://github.com/user-attachments/assets/40eabd71-b857-40fb-a3ea-23245c629e16)

Button and child background colour is wrong:
![image](https://github.com/user-attachments/assets/662f0c9a-d07b-47bd-ba1a-1cc2264df889)

Directory hotlist
![image](https://github.com/user-attachments/assets/14766ca2-e4dd-4fcd-8210-a8be84fabb31)

Favorite tabs
![image](https://github.com/user-attachments/assets/f81a6d6e-8347-462e-8080-7e6dd9a12160)

@rich2014 hope that is all I could find

**Comment by rich2014** [comment]
@lprot 

the background color of the button panels fixed.

the other colors i think are intentional and need to be looked at by @alexx2000
