### ISSUE TITLE
Wrong background coloring in "Unpack file", "Split file", "Combine file", "Directory hotlist" and "Favorite tabs"

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1889]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11542
Commit: 04babd85e
Build date: 2024/10/05
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

In "Pack files" background of all UI elements is ok:
![image](https://github.com/user-attachments/assets/3eb1db40-05f0-49ea-958b-8048fbd212ab)

In "Unpack files" lighter colouring is used and this looks strange/wrong:
![image](https://github.com/user-attachments/assets/3773afa3-19a8-4f99-9656-1d4cb0b21e67)

The same in "Split file":
![image](https://github.com/user-attachments/assets/9de23b64-0c4a-49c7-904f-134928827326)

"Combine files":
![image](https://github.com/user-attachments/assets/156fbb22-137c-4ac6-8d85-8fd7efafc34c)

Configuration of Directory Hotlists:
![image](https://github.com/user-attachments/assets/4ea09fe4-59ed-4bda-b908-5ebe0c34e262)

Configuration of Favorite Tabs
![image](https://github.com/user-attachments/assets/d95f3276-c23e-4edd-b29d-0796aea8af76)

@alexx2000 related to https://github.com/doublecmd/doublecmd/issues/1887 and https://github.com/doublecmd/doublecmd/issues/1885
@rich2014 FYI

**Comment by rich2014** [comment]
the other colors i think are intentional and need to be looked at by @alexx2000

**Comment by alexx2000** [comment]
Fixed.
