### ISSUE TITLE
Feature Request: Use upper case drive letters on Windows

### ISSUE THREAD

**Issue by noctrex** [doublecmd/doublecmd#19]
Discovered your file manager by change on linux, and now I install it on my windows machines too. Very nice project!
The only issue, if you can call it that, is that it seems all the Windows drive letters are lowercase. Is it reasonably possible to present them in uppercase, for a more complete windows experience?
![image](https://user-images.githubusercontent.com/35490284/71747915-9db49700-2e79-11ea-94f3-6324f33040b4.png)

**Comment by Asherathe** [comment]
It's a small thing, but I would also like this.

**Comment by alexx2000** [comment]
Added, see <UppercaseDriveLetter> in doublecmd.xml.
