### ISSUE TITLE
WFX: FTP: DC crashes as soon as folder copying from ftp server is started

### ISSUE THREAD

**Issue by alex1yaremchuk** [doublecmd/doublecmd#1908]
### Version

Double Commander
Version: 1.1.17 gamma
Revision: 548
Commit: f4189f213
Build date: 2024/08/19
Lazarus: 3.5.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 23H2 x86_64

### Description

DC crashes as soon as I try to download folder from ftp site. 

1. open ftp with wfx in the left panel
2. open local destination folder in the right panel
3. copy some folder from ftp site
4. blank message box appears and DC becomes unresponsive.
5. trying to close message box leads to closing of DC

![image](https://github.com/user-attachments/assets/9a5ddfa0-6309-4216-a929-409deb47cb70)

**Comment by alex1yaremchuk** [comment]
Well, after a bit of playing with the thing I noticed 
that if I transfer relatively small folders then 
hanging message box disappears and transfer starts. 

question is what if I need to transfer large directory (~1GB) with thousands of files - 
is this tool suitable for it?

**Comment by alex1yaremchuk** [comment]
it errored after some time saying it cannot download some file with only options to skip or to abort. 

I think it is not the tool for such transfers.

**Comment by alexx2000** [comment]
It does not crash, it counts files. It is better to enable "Work in background" option when copy a large directories:

![1](https://github.com/user-attachments/assets/cd1d30a4-628a-4ec6-b46c-4ef6c0dad2ba)

> it cannot download some file with only options to skip or to abort.

The reason why the file was not copied is displayed in the log (at window bottom).
