### ISSUE TITLE
DC does not close "Options" on pressing ESC after you selected "Tooltips" section

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1929]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11571
Commit: ea812adf0
Build date: 2024/10/11
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.6

### Description

![image](https://github.com/user-attachments/assets/ca1afddc-a45b-44a3-84b2-30c80381173b)

**Comment by rich2014** [comment]
@alexx2000 hi, Alex

do you have any ideas?

**Comment by lprot** [comment]
Still reproducible on Double Commander
Version: 1.2.0 alpha
Revision: 11619
Commit: a7093dbd9
Build date: 2024/10/26
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.7.0

**Comment by alexx2000** [comment]
Hi, fixed.
