### ISSUE TITLE
Double Commander in Wayland, KDE Plasma 5 and 4K shows blurry text

### ISSUE THREAD

**Issue by elman22** [doublecmd/doublecmd#193]
When I run Double Commander in Wayland session in KDE Plasma 5 and use 4K display with scaling set to 200 %, all fonts are blurry (as with other application which do not support Wayland). Could you please add support for Wayland?

Double Commander 0.9.10 beta
Revision: 9640
Build: 2021/06/01
Lazarus: 2.0.12.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-qt5
System: Manjaro Linux
Desktop Environment: KDE
Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

**Comment by altosch** [comment]
Hi, I have pretty much the same problem.  

Double Commander 1.0.1 beta, revision 35 
-> from official download site https://sourceforge.net/p/doublecmd/wiki/Download/
-> package doublecmd-1.0.1.qt.x86_64.tar.xz

I'm using KDE Neon 5.23, Qt 5.15.3, Wayland, Full HD 1920x1080, scale 150%. 

It's blurry. On About screen I can see: Lazarus 2.0.12.0. 

If I try to run it with -platform wayland it won't start and there is an error: "[FORMS.PP] ExceptionOccurred".
I take the Lazarus 2.2 is needed. 

If I get it right Lazarus 2.2.0 is not yet released but it will be soon. 
Can we hope that when it is released the official versions will be build with it?

**Comment by alexx2000** [comment]
Hi, yes.

**Comment by dandv** [comment]
@alexx2000: What is the recommended version to run on KDE, the Qt or GTK version?

BTW, I know this is a question, and it would be best suited for the Discussions section of the repo. Would you consider [enabling Discussions](https://docs.github.com/en/discussions/quickstart) for this repo?

**Comment by elman22** [comment]
@dandv KDE Plasma is Qt based desktop environment, so run Qt version. I also tried GTK version and if you have correctly configured GTK theme it looks all right.

**Comment by alexx2000** [comment]
@dandv, Qt5 of course. I thought about Discussions section, but we have already [forum](https://doublecmd.h1n.ru).

**Comment by Vascom** [comment]
The same problem with doublecmd 1.0.5.
Adding `-platform wayland` cause crash:
```
$ doublecmd-qt -platform wayland
SystemLocale ru_RU
SystemLanguage ru
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $000000000059F723
  $00000000005EA2B9
  $000000000073E6BD
  $000000000073E09D
  $000000000073A1D3
  $00000000006F3DB1
  $00000000006F3CCB
  $00000000004B228A
[FORMS.PP] ExceptionOccurred 
Warning: Skip libKF5IconThemes exit handler
```

**Comment by alexx2000** [comment]
My builds still use Lazarus 2.0.12.

**Comment by Vascom** [comment]
Doublecmd has minimal requred version of lazarus?

**Comment by elman22** [comment]
If you want to use Wayland platform, yes. You need at least Lazarus 2.2.

**Comment by Vascom** [comment]
Thanks, it works.

**Comment by regs01** [comment]
> doublecmd -platform wayland

Is this QT-only? Any way to do the same with GTK?

**Comment by alexx2000** [comment]
Qt only, GTK2 does not support Wayland.

**Comment by alexx2000** [comment]
DC builds using Lazarus 2.2.2 now.
