### ISSUE TITLE
Directory Sync doesn't handle empty directories

### ISSUE THREAD

**Issue by Romano44** [doublecmd/doublecmd#1930]
### Version

Double Commander
Version: 1.1.19 gamma
Revision: 585
Commit: 9dd31c2e9
Build date: 2024/10/17
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt6
OS version: Arch Linux

Widgetset library: Qt 6.8.0, libQt6Pas 6.2.1

### Description

DC will not add/remove empty directory in the [target] to mirror [source].
It will also not delete directory itself in the [target] that contained files, if in the [source] dir with those files was removed, and will simply sync/delete only files in the [target] dir.

That is also with _"Asymmetric"_ and _"Subdirs"_ checked.

Example, create:
```
's' as a [source]:
s/a
s/b/file
't' as a [target]:
t/a
t/b/file
```
^So top _'s'_ and _'t'_ dirs are equal and contain one empty dir and one dir with file inside.
Now in the _'s'_ dir, delete empty _'a'_ folder and try to sync _'t'_ to it == **it will not delete _'a'_ in the _'t'_**.
Likewise, try to delete _'b'_ folder(that contain file) in the _'s'_ folder and try to sync _'t'_ to it == it will delete file inside(_t/b/file_), **but it will not delete _'b'_ folder(_t/b_) itself**.

**Comment by alexx2000** [comment]
#1163
Function is not supported.
