### ISSUE TITLE
Category colour titles are cut in selection list

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1944]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11619
Commit: a7093dbd9
Build date: 2024/10/26
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.7.0

### Description

![image](https://github.com/user-attachments/assets/b142dabc-4f7f-44c3-b15a-d3de6bea7aeb)
![image](https://github.com/user-attachments/assets/9274d6d0-e0bf-4a1b-a0d3-a4bb429af10c)

**Comment by rich2014** [comment]
sorry, but i don't understand how the user operates?

**Comment by lprot** [comment]
> sorry, but i don't understand how the user operates?

1. Configuration>Options>Colors>File types>Add
2. Click on "Category color", scroll down

**Comment by rich2014** [comment]
OMG, it has been a problem since last year.

@alexx2000 

i found that TColorBox works fine.

so it should be a problem caused by the integration of TKASColorBoxButton with TColorBox.

the problem occurs in all places where TKASColorBoxButton is referenced in DC. It seems that the width is fixed at 100 points.

**Comment by alexx2000** [comment]
It works fine under Linux/Windows. It is LCLCocoa only problem.

**Comment by rich2014** [comment]
@lprot test the snapshoot please

@alexx2000 Cocoa already supports dynamically setting the width of TColorBox

**Comment by lprot** [comment]
@rich2014 looks good:
![image](https://github.com/user-attachments/assets/ecad0481-136b-4b08-b52a-2cee1b53ce34)
Not sure if the width of the dropdown list should not match the width of the parent combobox. In File panels it looks this way:
![image](https://github.com/user-attachments/assets/3c96e52d-5ffb-4a25-8c10-ffc035824e21)

Anyway thank you very much and I'm closing this.
