### ISSUE TITLE
Shortcut not working with cm_ColumnsView

### ISSUE THREAD

**Issue by antodc** [doublecmd/doublecmd#1951]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11594
Commit: 904e910e8
Build date: 2024/10/20
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

I have defined two custom column views. To switch easily among them I created two buttons defined as follows:

icon: cm_columnsview
tooltip: Vista colonne - MyView1
command: cm_ColumnsView
parameters: columnset=MyView1
shortcut: ctrl+alt+1

The second button is the same but with "1" replaced by "2".

Pushing the buttons works fine, but the shortcuts do not work. I also tried with other combinations of ctrl, alt, numbers and letters without success.

By the way, please let me know if there is a simpler way to use shortcuts to select custom views.

**Comment by antodc** [comment]
Sorry, just found out that Ctrl+Shift+1 works. For some reason DC does not accept Ctrl+Alt as a combination for shortcuts, does it?
Anyway, is it possible to have shortcuts to select custom views without creating specific buttons?

**Comment by alexx2000** [comment]
> For some reason DC does not accept Ctrl+Alt as a combination for shortcuts, does it?

By [default](https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys) `Ctrl+Alt+Letters` are busy by `Quick Filter`.

> Anyway, is it possible to have shortcuts to select custom views without creating specific buttons?

Yes, you can configure it in the hot keys [settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigHotKeys).

**Comment by antodc** [comment]
> By [default](https://doublecmd.github.io/doc/en/configuration.html#ConfigKeys) `Ctrl+Alt+Letters` are busy by `Quick Filter`.

I have both `Alt+Letters` and `Ctrl+Alt+Letters` set to 'none' and I have shortcuts with `Alt+Letters` that work properly. Only shortcuts with `Ctrl+Alt+Letters` do not. Are the two groups implemented differently?

> Yes, you can configure it in the hot keys [settings](https://doublecmd.github.io/doc/en/configuration.html#ConfigHotKeys).

Can you kindly clarify how to set parameters there? I would like to use the command `cm_ColumnsView` with the parameter `columnset`. Alternatively, could it be possible for you to add the possibility to set shortcuts in [Custom Columns](https://doublecmd.github.io/doc/en/configuration.html#ConfigColumns) for customized columns views?

**Comment by antodc** [comment]
Sorry!! What a stupid I am! I found the parameters in the hot keys. Still, Ctrl+Alt+Letters do not work. But I can use something else. :-)

**Comment by antodc** [comment]
I am writing faster than I think. Really apologize.
Ok, I can set a shortcut for cm_ColumnsView and columset=MyView1 in hot keys, but how can I set another shortcut for the same command but a different parameter?

**Comment by alexx2000** [comment]
You can add any number of shortcuts to a single command using the `Add hotkey` [button](https://doublecmd.github.io/doc/en/configuration.html#ConfigHotKeys).
