### ISSUE TITLE
Wrong hotkey combo assigned to FTP drive tabs

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#1953]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11643
Commit: d498e63c2
Build date: 2024/11/01
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.7.1

### Description

To reproduce:
1. Connect to FTP source
2. Right click on the drive button:
![image](https://github.com/user-attachments/assets/89fb0f55-6135-4e48-b17f-c6879adbeaf5)
There you see D hotkey tip which does not work
It is expected that that should be cm_NetworkDisconnect hotkey:
![image](https://github.com/user-attachments/assets/ed4e275e-0571-4a92-9231-766d9a83bc72)

**Comment by alexx2000** [comment]
No, it is a two independent commands. cm_NetworkDisconnect disconnects active connection, while context menu command disconnects a selected connection. Context menu command cannot have a shortcut at all (because you cannot select drive button without mouse).

**Comment by alexx2000** [comment]
`D` is a menu shortcut in this case. A key that can be used to select menu item from keyboard. Under other operating systems it displayed differently as a character with underscore.

**Comment by lprot** [comment]
Cmd-E works perfectly. That D hotkey is strange there

**Comment by alexx2000** [comment]
Of course it works, but it's a different function as I explained above.

**Comment by lprot** [comment]
I don't get how why FTP tabs have useless "Network Disconnect D" popup then. You cannot use it from keyboard.

**Comment by alexx2000** [comment]
You can use it. If you call a context menu and press `D` then disconnect will be called.

**Comment by lprot** [comment]
It just makes no sense as if you call it, you just mouse click then. It is strange usability approach to expect that user will right mouse click and then press D if can just left mouse click immediately. Cmd+E there makes more sense but whatever. There are more important issues to fix on DC.
