### ISSUE TITLE
Quick filter ignores quit via ESC

### ISSUE THREAD

**Issue by r5to** [doublecmd/doublecmd#1961]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11652
Commit: fd70dbe29
Build date: 2024/11/05
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 23H2 x86_64

### Description

Quick filter ignores quit via ESC key, if ESC is assigned to something in keyboard shortcuts menu. If unassigned, it works ok.

**Comment by antodc** [comment]
I use ESC for cm_MarkUnmarkAll with the control for "Files panel" selected. In that way, ESC continues to work also as quit for quick filter.

**Comment by r5to** [comment]
Shieee... i did not select "Files panel" in cm_MarkUnmarkAll. Now it works - thank you :)
