### ISSUE TITLE
Free space icorrectly reported for large USB drive

### ISSUE THREAD

**Issue by geokimbo** [doublecmd/doublecmd#1963]
### Version

Double Commander
Version: 1.1.19 gamma
Revision: 585
Commit: 9dd31c2e9
Build date: 2024/10/06
Lazarus: 3.4.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 24.04.1 LTS

Widgetset library: Qt 5.15.13, libQt5Pas 5.6.1

### Description

DC is not reporting the free space correctly for an 8Tb drive in a USB caddy. I've refreshed as well as moving from the directory and then reentering. See screen grab.
![DC_free_space_wrong](https://github.com/user-attachments/assets/41cf9ed1-ea4a-4f97-8085-0ad5b66f7a5e)
Screen resolution is low because of old KVM hardware.
Nautilus properties reports 7.5Tb free space
Trash is empty.

**Comment by j2969719** [comment]
switch to plain bytes and check if there is a difference. the difference between T and Tb is most likely caused by the fact that when converting units doublecmd uses the oldschool powers of 2 standard, while nautilus uses the mathematical powers of 10. the larger the size the more noticeable the difference will be

**Comment by alexx2000** [comment]
You can execute `df -h` in a terminal and compare.

**Comment by geokimbo** [comment]
Correct
![DC_size_in_bytes](https://github.com/user-attachments/assets/655f26dd-600f-41c1-a3e2-f4c703b6961c)
That was my first thought but (8/1024)*1000 came to 7.8 and even (7.5/1024)*1000 only gets to 7.3 I was however forgetting about the compounding effect of going from Kb to Mb to Gb to Tb so yes 7537208811520÷(1024^4) =6.8Tb
Thanks
