### ISSUE TITLE
Unzipping files over NFS can silently corrupt files in destination

### ISSUE THREAD

**Issue by abartov** [doublecmd/doublecmd#1964]
### Version

Version info:

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/04/01
Lazarus: 3.0.0.3
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

### Description

Unzipping ZIP files with JPEG images over an NFS connection to a NAS on a local WiFi network *silently* resulted in corrupted files.  I have encountered it multiple times over many months, but only now managed to pinpoint the problem specifically to doublecmd and specifically to unzipping over NFS. 

Regular copying or moving of files over NFS does work reliably! It is only unzipping -- i.e. copying files out of a ZIP file in one pane onto an NFS-mounted directory on the other pane -- that occasionally causes silent corruption in the files in the destination.

**Comment by JonnyTech** [comment]
> Version: 1.1.11 beta

Please test with a newer [release](https://github.com/doublecmd/doublecmd/releases) or [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php)

**Comment by abartov** [comment]
Just tried and confirmed same issue with:

Double Commander
Version: 1.1.19 gamma
Revision: 585
Commit: 9dd31c2e9
Build date: 2024/10/06
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

**Comment by abartov** [comment]
As a rough indication of incidence frequency, in this latest test, I unzipped 800MBs' worth of JPEGs (180 individual files) from a single ZIP file, and two files were corrupted. 
(Though I assume it's not a constant rate, but chaotically depends on network noise.)

**Comment by abartov** [comment]
(using unzip(1) to extract the same archive over the same NFS connection extracts the files without corruption.)

**Comment by abartov** [comment]
If it would help I can provide examples of the corrupted file versus an uncorrupted file, though I doubt that would shed light on the root cause.

**Comment by alexx2000** [comment]
Try with the latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by abartov** [comment]
Thank you. I have tried, and the corruptions still happen. (Same test archvie, different random files got corrupted this time).

Tested version info:

Double Commander
Version: 1.2.0 alpha
Revision: 11657
Commit: f113928
Build date: 2024/11/08
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

**Comment by alexx2000** [comment]
I have no more ideas. DC uses a standard system calls `open`, `write` and `close`, nothing special. Is it a normal .zip archive with a deflate compression?

**Comment by abartov** [comment]
Yes, deflate, and zip -T on the archive says it's fine. (The fact *different* files get corrupted in each extraction also suggests it's not about the source data.)

My best guess is that there is some NFS error that, instead of being caught and retried, is silently tolerated.  And it may be useful to compare the copying code of the main DC with that of the unzip plugin. (But I can't do it myself.)

**Comment by JonnyTech** [comment]
> I unzipped 800MBs' worth of JPEGs (180 individual files) from a single ZIP file, and two files were corrupted.

How big is the actual archive? Is it filling all of your RAM? Do you get the issue with smaller archives?

**Comment by abartov** [comment]
The archive is 843M in size, but I have plenty of free RAM.  I did get the issue with smaller (~100MB) archives as well, yes.

(thank you both very much for the time you are taking to attempt to solve this!)

**Comment by abartov** [comment]
One additional piece of information: whatever network hiccups my setup has *do* cause errors in regular DC copying too -- *however*, when that happens in a regular copy (not unzipping), an error message is shown (it alternates between a spurious "permission denied" to "write error"), but when I hit "retry", it always proceeds fine, and the files are copied correctly.

Presumably, those same errors (and I don't know why they are falsely reported as "permission denied" by the NFS client -- there's certainly no permission issue, or the retry would have failed too) happen when unzipping too, but they are *not* reported in a pop-up -- instead, unzipping proceeds silently, and a small (random) subset of the files gets corrupted on the destination folder.

**Comment by JonnyTech** [comment]
Please launch DC from terminal then recreate the error and post all text logged in the console.

> cause errors in regular DC copying too

Ah, this is crucial information. What else is running in your session? Post the output of `ps -aux`

**Comment by abartov** [comment]
I've run DC from the terminal and recreated the NFS error while copying a regular file (**not** unzipping). The error shown was this:
![Screenshot from 2024-11-11 19-40-03](https://github.com/user-attachments/assets/0b1e14cf-d6d7-4f68-847b-c69353553321)

As I mentioned above, the error message is **spurious**, because hitting retry immediately proceeds without issue, and the file is eventually copied, without any permissions change.

And the command line showed nothing new, neither before nor after hitting retry:
![image](https://github.com/user-attachments/assets/1a3d1843-d60b-4eb3-8989-719beedf51a8)

**Comment by abartov** [comment]
Further investigations revealed that my laptop's WLAN card is (or has become) faulty, corrupting data when CPU usage is high.  I am closing this issue, as it does not seem to be DC's fault. Thanks for the time you have put into it!
