### ISSUE TITLE
Alt+F7 - the search window does not appear

### ISSUE THREAD

**Issue by faludiz** [doublecmd/doublecmd#1967]
### Version

Double Commander
Version: 1.1.19 gamma
Revision: 585
Commit: 9dd31c2e9
Build date: 2024/10/06
Lazarus: 3.7.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 Home 24H2 x86_64

### Description

If I assign a different key combination to the command, the search window appears, but not with Alt+F7
In my case the Ctrl+F7 works well, the Alt+F7 does nothing.
![image](https://github.com/user-attachments/assets/f985f01b-c115-47ea-9115-79be3f4358b1)

**Comment by alexx2000** [comment]
https://ghisler.ch/board/viewtopic.php?t=50148

**Comment by faludiz** [comment]
Unbelievable, but it's working. I removed that garbage :) 

Thank You!
