### ISSUE TITLE
Right-click on files and folders does no longer work

### ISSUE THREAD

**Issue by flberger** [doublecmd/doublecmd#1977]
### Version

Double Commander
Version: 1.1.19 gamma
Revision: 585
Commit: 9dd31c2e9
Build date: 2024/10/18
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Artix Linux

Widgetset library: GTK 2.24.33

### Description

When right-clicking on files and folders, a context menu is supposed to pop up. This is no longer the case with the current version on Linux.

**Steps to reproduce:**
1. Open DoubleCmd
2. Navigate to an ordinary local folder
3. Right-click on a file or folder

**Expected behaviour:**
A context menu should open.

**Actual behaviour:**
Nothing happens.

**Additional information:**
- Right-click works in all other applications.
- DoubleCmd still recognises the right mouse button in some cases:
    - The left or right pane can be selected with a right-click, and is being highlighted.
    - Menu bar menus and menu items can be opened, selected and activated with a right-click.

I'll gladly provide more information if needed.

**Comment by Skif-off** [comment]
Have you already checked the program settings? [1](https://doublecmd.github.io/doc/en/configuration.html#ConfigMouse), [2](https://doublecmd.github.io/doc/en/help.html#select_files).

P.S. 1.1.20 is available.

**Comment by alexx2000** [comment]
Works fine under Arch Linux.

**Comment by flberger** [comment]
> Have you already checked the program settings? [1](https://doublecmd.github.io/doc/en/configuration.html#ConfigMouse)

These settings do not regard the right-click context menu.

> [2](https://doublecmd.github.io/doc/en/help.html#select_files).

This section concerns the selection of files, which works without problems.

The behaviour as described in the [section on the Context Menu](https://doublecmd.github.io/doc/en/help.html#cm_ContextMenu) does no longer work.

> P.S. 1.1.20 is available.

An update to 1.1.20 gamma, revision: 607, commit: d7d098956, build date: 2024/11/12 solved the issue.

**Comment by Skif-off** [comment]
> These settings do not regard the right-click context menu.

_Selection by mouse_ > Mode > _Right button_.

> This section concerns the selection of files

Quote: "_Right button_ – ... A slightly longer hold of the right button will call the context menu of files."
