### ISSUE TITLE
folders with dots sorts incorrectly

### ISSUE THREAD

**Issue by 1vanK** [doublecmd/doublecmd#1979]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11526
Commit: dabd5fb
Build date: 2024/09/30
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Linux Mint 22 Wilma

Widgetset library: GTK 2.24.33

### Description

![изображение](https://github.com/user-attachments/assets/8b613402-863d-4fb6-bf44-f72b3b1c055c)

**Comment by Skif-off** [comment]
What about Nemo? The same result?

Not a bug, the result of sorting depends on your current locale. Try another [sort method](https://doublecmd.github.io/doc/en/configuration.html#ConfigView).

**Comment by 1vanK** [comment]
I use the "sort folders as files" setting, the files are sorted normally

**Comment by 1vanK** [comment]
Nemo

![image](https://github.com/user-attachments/assets/a6f3da38-068e-4303-bad7-5949e4050b6e)

**Comment by 1vanK** [comment]
There is no difference between "sort by name and show firts" and "sort as files and show first"

**Comment by 1vanK** [comment]
![image](https://github.com/user-attachments/assets/69de61d0-bb9a-4048-8ec1-1046326f3caf)
