### ISSUE TITLE
Problem with playing videos using the wlxmplayer plugin

### ISSUE THREAD

**Issue by kivandpr** [doublecmd/doublecmd#1991]
### Version

Double Commander
Version: 1.1.20 gamma
Revision: 607
Commit: d7d098956
Build date: 2024/11/21
Lazarus: 3.0.0.3
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: ROSA Fresh Desktop 12.5.1, platform 2021.1

Widgetset library: Qt 5.15.10, libQt5Pas 5.6.1

### Description

When trying to watch a video using the CTRL+Q combination in Double Commander, an error message appears:

"Access violation

Please report this error to the bug tracker with a description of your actions and the file:
/home/kivan/.config/doublecmd/doublecmd-qt5.err

Click Skip to continue working or Abort to exit the program."

--------------- 22-11-2024, 07:05:43 ---------------
| DC v1.1.20 gamma Rev. 607 -- x86_64-Linux-qt5
| ROSA Fresh Desktop 12.5.1, platform 2021.1 -- Qt 5.15.10, libQt5Pas 5.6.1 | PID 3208
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007FE9C01B8851 in /usr/lib64/libQt5Widgets.so.5

--------------- 22-11-2024, 07:05:45 ---------------
| DC v1.1.20 gamma Rev. 607 -- x86_64-Linux-qt5
| ROSA Fresh Desktop 12.5.1, platform 2021.1 -- Qt 5.15.10, libQt5Pas 5.6.1 | PID 3208
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007FE9C01B8851 in /usr/lib64/libQt5Widgets.so.5

--------------- 22-11-2024, 07:06:06 ---------------
| DC v1.1.20 gamma Rev. 607 -- x86_64-Linux-qt5
| ROSA Fresh Desktop 12.5.1, platform 2021.1 -- Qt 5.15.10, libQt5Pas 5.6.1 | PID 3208
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007FE9C01B8851 in /usr/lib64/libQt5Widgets.so.5

**Comment by JonnyTech** [comment]
What happens if you try to play the file with `mplayer` from a terminal?: ie: `mplayer /path/to/video/file.mp4`

**Comment by kivandpr** [comment]
![image](https://github.com/user-attachments/assets/5e2b3154-12ae-4e25-95ab-bbb1ee52dd11)

**Comment by kivandpr** [comment]
It plays normally. Problems arise if there are gaps in the path. Then use commas. For example:

mplayer '/home/kivan/Рабочий стол/111.mp4'

But in TC, the problem is in both cases.

**Comment by JonnyTech** [comment]
Thanks, can you also show the outputs of:

```
ldd `which doublecmd`
readelf -d `which doublecmd`
```

**Comment by alexx2000** [comment]
Wayland or X11?

**Comment by alexx2000** [comment]
Looks like you are using the `wlxmplayer` plugin from Qt6 or GTK2 version. Plugin works fine with in the  [portable version](https://github.com/doublecmd/doublecmd/releases/download/v1.1.20/doublecmd-1.1.20.qt.x86_64.tar.xz).

**Comment by kivandpr** [comment]
Thanks a lot. Your advice helped. I just replaced the old plugin with the one you recommended. Everything is working now.
