### ISSUE TITLE
Clear field hotkey does not fully clear any fields with items that start with a dot

### ISSUE THREAD

**Issue by advice2020** [doublecmd/doublecmd#1992]
### Version

Double Commander 
1.2.0 alpha
Revision 11533
Commit 6a99fd2eb
Lazarus 3.0.0.3
Free Pascal  3.2.2
QT5
Standalone Version
Debian based Linux distro / GTK based Desktop Environment

### Description

I tried this out in a couple of fields within DC.
-Quick search / Quick filter
-Find dialog
etc.

If you type a keyword that starts with or contains a "." dot/period in general
If you apply the hotkey to clear the field "Ctrl+Backspace", it removes all the text, but does not remove the "." at the beginning or up to that dot.

EXAMPLE:
`.txt`
becomes
`.`

`apple.txt`
becomes
`apple.~

Seems like it should clear the entire field when this hotkey is applied.

Thank You

**Comment by alexx2000** [comment]
`Ctrl+Backspace` is not a DC hotkey. It is a system hotkey. It works same way in the pcmanfm-qt for example.
