### ISSUE TITLE
missing deb packages for v1.1.21 amd64

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#1995]
### Version

Double Commander 1.1.21 gamma

### Description

https://download.opensuse.org/repositories/home:/Alexx2000/Debian_12/amd64/

No builds available for v1.1.21 amd64

**Comment by Skif-off** [comment]
"Debian_10" and "Debian_11" too.
All this three repositories contain the source code "1.1.20" and "1.1.21" at the same time. (The contents of the repositories for Ubuntu look correct.)

**Comment by alexx2000** [comment]
Something wrong with openSUSE Build Service. Debian amd64 builds are broken.

**Comment by R7010A** [comment]
> Something wrong with openSUSE Build Service. Debian amd64 builds are broken.

`sudo apt install doublecmd-gtk`

`The following packages have unfulfilled dependencies: doublecmd-gtk: Depends on: doublecmd-common (= 1.1.20-0+svn607~testing) but 1.1.21-0+svn630~testing should be installed`

Unable to update/install double commander

**Comment by alexx2000** [comment]
https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/ZOGE5DV75TWVZVGDCZSLNWNZ24P5QIIL/

**Comment by sysms** [comment]
Problem seems to be solvde on openSUSE Build Service. 

I just could install the new .deb-Files from the repo (Bookworm/Debian 12).

**Comment by alexx2000** [comment]
Yes, looks like it fixed.
