### ISSUE TITLE
Trojan detected by VirusTotal?

### ISSUE THREAD

**Issue by Mardoek53** [doublecmd/doublecmd#2]
When I check the Double Commander Installer with VirusTotal, I get one positive detection. Is this a false positive?

![double_commander_trojan](https://user-images.githubusercontent.com/41394112/50577320-15468500-0e26-11e9-84ca-1a391ea6ea01.jpg)

**Comment by alexx2000** [comment]
Do you believe to one "noname" antivirus, but do not believe to 69 others?

I don't know this antivirus and I don't know why it think this way.

**Comment by Mardoek53** [comment]
Well, I actually could not believe this, but I wanted to know what you had to say about it. And you are now also aware of this flag at VirusTotal and maybe you can do something about it. (I checked CMC and it is a dubious Vietnamese antivirus company. And I do not know why VirusTotal have included this virus scanner in their list of virus scanners, VirusTotal is still well known?). 

And I love your program and I will download and install it right away. Thank you for developing Double Commander and making it available to the public!)

With regards,
Mardoek53
