### ISSUE TITLE
Error when unpacking archive if administrator rights are required

### ISSUE THREAD

**Issue by xboxones1** [doublecmd/doublecmd#2003]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.7.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11

### Description

When I try to extract the archive to a folder for which I need to request admin rights, I get an error. I have to unpack the archive and then move the files, only in this case the request for administrator rights appears.

**Comment by alexx2000** [comment]
#84
