### ISSUE TITLE
Trying to load the Project into Lazarus 3.6 throws errors

### ISSUE THREAD

**Issue by tukanos** [doublecmd/doublecmd#2006]
### Version

Not applicable.

### Description

I wanted to be able to send some PR, but it appears that during the load of the project I got errors (followed the Development guide).  I'm loading it to Lazarus 3.6, but that should not be an issue.  I would appreciate if anyone could help me with these errors.

First error message (I tried to search for the file, but could not find it):

```
Unable to find file "laz.virtualtrees.pas".
If it belongs to your project, check search path in
Project -> Compiler Options -> Search Paths -> Other Unit Files. If this file belongs to a package, check the appropriate package compiler options. If this file belongs to Lazarus, make sure compiling clean. If the file belongs to FPC then check fpc.cfg. If unsure, check Project -> CompilerOptions -> Test
```

Second error (project could not find a component class, which is weird as this would be found soon):
```
Unable to find the component class "TComboBoxWithDelItems".
It is not registered via RegisterClass and no lfm was found.
It is needed by unit:
/home/tukan/Application/build/doublecmd/src/fmain.pas
```

**Comment by j2969719** [comment]
https://github.com/doublecmd/doublecmd/wiki/Development#using-lazarus-ide

**Comment by tukanos** [comment]
> https://github.com/doublecmd/doublecmd/wiki/Development#using-lazarus-ide

Yes, those are the steps I have followed.

**Comment by j2969719** [comment]
when you open lazarus do you see KASComponents/SeksiCmd in the component palette tabs? if not, you probably either havent installed the component or havent recompiled lazarus with the installed components (tools>build lazarus with ...)

also check if you are using components from the same working copy that you plan to work with. this is not necessary but can save you from unnecessary headaches if you forget to update components or accidentally delete them.
