### ISSUE TITLE
Windows 11 crash while in background.

### ISSUE THREAD

**Issue by RenegadeJr** [doublecmd/doublecmd#201]
On Windows 11, with my download directory open in DC 0.9.10 x64, I downloaded a file from Firefox to that directory. When switching back to DC, it would crash and close immediately without error message. I tried turning on and off setting for "Disable auto-refresh" "When application is in the background", but was able to reproduce this error 6 times.

**Comment by alexx2000** [comment]
Upgrade DC to version 1.0.
