### ISSUE TITLE
Quick view panel crash

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#2011]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt6
OS version: MX 23.3 Libretto

Widgetset library: Qt 6.4.2, libQt6Pas 6.2.1

### Description

Quick view panel crash after accidentally pressing the Q key

- select an image file
- press CTRL+Q
- click bar under image
- press F to stretch image
- press Q (accidentally, was meant to press CTRL+Q) quick view panel quits
- press CTRL+Q = Error: Access Violation

**Comment by ags1234** [comment]
Double Commander
Version: 1.2.0 alpha
Revision: 11659
Commit: defc20560
Build date: 2024/11/09
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: i386-Win32-win32/win64
OS version: Windows 11 24H2 x86_64


DC throws an acces violation error.

Steps to reproduce:
- select a file, let's say in the left panel (any file I tried crashed the same)
- press CTRL+Q, the file content opens in the right panel
- click the right panel with the contents to focus it
- press Q
- the file contents disappear
- click the left panel
- DC shows access violation error every time

PS: possibly related to the one above?

**Comment by alexx2000** [comment]
@ags1234 It is a same issue.
