### ISSUE TITLE
Internal text viewer: problem with RegEx search, it cannot find 'qt' case-insensitive

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#2012]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.5 LTS

Widgetset library: GTK 2.24.33

### Description

Open this text file in text viewer

[history.zip](https://github.com/user-attachments/files/18136592/history.zip)

- search for 'qt' with option RegEx ON and case-sensitive OFF

![Screenshot from 2024-12-14 19-05-10](https://github.com/user-attachments/assets/1dc33afc-4cf3-4f6b-8d0a-db3012f072db)

it must be found MANY TIMES but viewer shows 'not found'

![Screenshot from 2024-12-14 19-05-06](https://github.com/user-attachments/assets/9f368577-e383-4ab2-a183-229fe3282772)

**Comment by alexx2000** [comment]
This option is not used in this case. Modifier `(?i)` should be used instead: `(?i)qt`.

**Comment by Alexey-T** [comment]
If checkbox CaseSensitive is enabled, it must work. Or disable the checkbox.
