### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by SirHesti** [doublecmd/doublecmd#2013]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11723
Commit: 530aafd
Build date: 2024/12/14
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: MX 23.4 Libretto

Widgetset library: GTK 2.24.33

### Description

apt update failure for  https://debrepo.freedownloadmanager.org

---> msg from apt
Ign:6 https://debrepo.freedownloadmanager.org jammy InRelease
Ign:6 https://debrepo.freedownloadmanager.org jammy InRelease
Fehl:6 https://debrepo.freedownloadmanager.org jammy InRelease                                                       
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Fehler in der Verifizierung des Zertifikats. [IP: 156.146.58.169 443]
Es wurden 103 kB in 8 s geholt (13,0 kB/s).                                                                          
Paketlisten werden gelesen… Fertig
W: Fehlschlag beim Holen von https://debrepo.freedownloadmanager.org/dists/jammy/InRelease Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Fehler in der Verifizierung des Zertifikats. [IP: 156.146.58.169 443]
W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
apt full-upgrade

----> apt is in german sorry for this.

MfG Hesti

**Comment by Skif-off** [comment]
This repository has nothing to do with Double Commander. Contact the site administrators or try to delete the certificate and add it again (perhaps it just expired).

IMHO, [better way](https://doublecmd.github.io/doc/en/faq.html#repo) (use "Debian 12").

**Comment by alexx2000** [comment]
Looks like it is the Free Download Manager repo.
