### ISSUE TITLE
Main menu separators aren't skipped

### ISSUE THREAD

**Issue by R0bur** [doublecmd/doublecmd#2014]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.7.0.0
FPC: 3.2.2
Platform: i386-Win32-win32/win64
OS version: Windows 10 Home 22H2 i386

### Description

When navigating the main menu using the up and down arrow keys on the keyboard, horizontal separation lines are not skipped.

**Comment by alexx2000** [comment]
#916

**Comment by R0bur** [comment]
Note: But menu separators are skipped as expected in the built-in editor.

**Comment by antodc** [comment]
If I may add, in my case separators are also skipped in the main menu. My understanding is that the only difference with @R0bur is the 32/64 bit version of Windows.

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.7.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64
