### ISSUE TITLE
Error moving files to .. on Windows

### ISSUE THREAD

**Issue by fewbig** [doublecmd/doublecmd#2017]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11724
Commit: d5b2c51a6
Build date: 2024/12/16
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 24H2 x86_64

and some older builds

### Description

1. select one or more files on a panel
2. press F6 (F5 works correct)
3. type ..
4. press Enter
Error: files moved to target panel instead of entered path

**Comment by rich2014** [comment]
@fewbig 

test the last snapshot please.
