### ISSUE TITLE
can NOT copy file and folder

### ISSUE THREAD

**Issue by freeman35-5** [doublecmd/doublecmd#2022]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11732
Commit: c0629da
Build date: 2024/12/22
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 24.04.1 LTS

Widgetset library: GTK 2.24.33

### Description

When try to copy file or folder, path Edit is read only, I can not change. And all files try copy to "/tmp/_dc/" and so get error, rename or permission etc.

**Comment by ard-av** [comment]
Double Commander
Version: 1.2.0 alpha
Revision: 11732
Commit: c0629daf0
Build date: 2024/12/22
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 Home 22H2 x86_64

Версия для Windows - перемещение работает. Копирование не работает. Перетягивание в активное окно - не работает

**Comment by ard-av** [comment]
https://github.com/user-attachments/assets/62a614ad-4ea1-4964-b4f5-88a15caed67a
