### ISSUE TITLE
Can't set background color for file panels

### ISSUE THREAD

**Issue by freetz13** [doublecmd/doublecmd#2027]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt6
OS version: Manjaro Linux

Widgetset library: Qt 6.8.1, libQt6Pas 6.2.1

### Description

In the Options window there is background color, but not in actual file panels (black color appears only outside of file list).

![2024-12-26_20-40](https://github.com/user-attachments/assets/c7a20bea-e5c7-42f1-a636-dfcd41d0d7de)

I played with QT_STYLE_OVERRIDE, but no luck.

**Comment by antodc** [comment]
You have to set ‘cursor color’ to black, if you want the selected file/folder to be shown with that color as well.

**Comment by freetz13** [comment]
No, it's not working:

![2024-12-26_21-20](https://github.com/user-attachments/assets/d34f410b-162b-4b49-a569-d5213297bb3f)
ll.

**Comment by antodc** [comment]
Sorry, maybe I misunderstood your point. Have you pushed ‘apply’ and then ‘ok’? Maybe after that try to close and reopen DC.

**Comment by freetz13** [comment]
No, still not working. I think that the background color of file list is somehow related to Kvantum theme, even if I run Double Commander with `QT_STYLE_OVERRIDE`

![2024-12-26_21-28](https://github.com/user-attachments/assets/f0b58d82-24a5-4cc3-8952-8743c7a0f50c)

**Comment by j2969719** [comment]
did you override colors in fileviews>columns>custom columns?

**Comment by freetz13** [comment]
> did you override colors in fileviews>columns>custom columns?

Sorry, my bad. Yes, I did override them.

Why it was so unclear?...
