### ISSUE TITLE
Unjustified error "You can not copy/move a file to itself!"

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#2035]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11752
Commit: c7cf06829
Build date: 2024/12/28
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 15.2.0

### Description

1. Uncheck Options > File operations > Show confirmation window for: Copy operation
2. Make sure that the left and the right file pane show different directories
3. Select a file and press F5

**Expected result:** The selected file will be copied
**Actual result:** The selected file will not be copied. DC shows the unjustified error message "You can not copy/move a file to itself!"

When checking the option in step 1, everything works as expected.

**Comment by rich2014** [comment]
@Andreas0602 

fixed.

test the last snapshot please.
