### ISSUE TITLE
Compare by Contents ( the result is inverted! the file selected in the left is show in the right and the file selected in the right is show in the left)

### ISSUE THREAD

**Issue by wadysal** [doublecmd/doublecmd#2038]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 3.7.0.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Compare by Contents ( the result is inverted! the file selected in the left is show in the right and the file selected in the right is show in the left)

**Comment by alexx2000** [comment]
[Position of frame panel after the comparison](https://doublecmd.github.io/doc/en/configuration.html#ConfigToolsDiffer)

**Comment by wadysal** [comment]
Thank's alexx2000. But it would be preferable if this option was set by default when installing the program. Greetings from Argentina.
