### ISSUE TITLE
Search dialog Tab switching via hot keys does not respect hot keys settings

### ISSUE THREAD

**Issue by lprot** [doublecmd/doublecmd#2042]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11761
Commit: 112ffaa59
Build date: 2024/12/29
Lazarus: 4.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 15.2.0

### Description

On MacOS, Alt+key does not behave like on Windows. For example Alt+2 is used for entering @ symbol.
That's why I changed bad DC hot key defaults from Alt+Num to Ctrl+Num:
![image](https://github.com/user-attachments/assets/7b764356-47d5-4d19-a33a-bdefbd3f634a)

But search dialog does not respect Ctrl+Num combos and instead uses hardcoded Alt+Num tab switch combos.
That makes it not possible to enter @ via Alt+2:
![image](https://github.com/user-attachments/assets/3fbec5f8-39aa-4eb6-9039-7949b5a6ff06)

If you beside fixind this bug will also decide to include proper hot keys defaults into MacOS DC distro, it can be taken from here https://github.com/doublecmd/doublecmd/issues/1651

**Comment by Skif-off** [comment]
First, switch the category, because the "Main" category for the DC's main window.

**Comment by lprot** [comment]
> First, switch the category, because the "Main" category for the DC's main window.

Thank you, fixed in https://github.com/doublecmd/doublecmd/issues/1651
