### ISSUE TITLE
Show filename in status bar when nothing is selected. [Feature Request]

### ISSUE THREAD

**Issue by corvus1** [doublecmd/doublecmd#207]
In Full view currently when nothing is selected it shows "Selected 0 of..." which is not very useful. It'd would be nice to show current filename under the cursor like in FlatView or BriefView, because filenames are sometimes long and don't fit into the column.

**Comment by corvus1** [comment]
Ping. Any thoughts on the proposition?

**Comment by alexx2000** [comment]
It's useful, it shows file/folder count. At my system for example most of file names are fit to panel width.

**Comment by corvus1** [comment]
Yeah, but when they don't, the only way to see the full name is mouse cursor hint, when you hover over it.

**Comment by corvus1** [comment]
I'm not sure it's a great argument, but that's what Total Commander does.

**Comment by alexx2000** [comment]
Total Commander works same way as DC by default.

**Comment by corvus1** [comment]
Is that not the default?

![Screenshot_20220919_001504](https://user-images.githubusercontent.com/4068104/190926592-c1e07c5c-bfed-44ba-8aba-5cc0efa76213.png)

I didn't know that.
But anyway, I'd appreciate the option.

**Comment by frithrah** [comment]
I would find it helpful too. I like to do everything with the keyboard so having to hover over a file with the mouse just to see the full name is a shame.

**Comment by alexx2000** [comment]
> Is that not the default?

No. It depends on the `LongInStatus` key in wincmd.ini, by default `LongInStatus=0` .

**Comment by corvus1** [comment]
I must've set it 20 years ago and forgot about it.

**Comment by corvus1** [comment]
Just tested. Seems to work as expected. Thanks!

**Comment by corvus1** [comment]
Maybe a cosmetic change to add [brackets] for directories? :-)
To look more like Total Commander.
