### ISSUE TITLE
Context (right-click) menu issue on Windows 11

### ISSUE THREAD

**Issue by RenegadeJr** [doublecmd/doublecmd#208]
I realize that DC doesn't officially support Windows 11 yet. I am posting this in case it is more widespread than Windows 11.
When I right-click on the XML file within DC, this menu item is un-scaled. I opened explorer and right-clicked afterwards and it did not exhibit this anomaly. This is from the Dark Mode version 1.0 beta.
![Screenshot 2021-10-19 112812](https://user-images.githubusercontent.com/3649254/137901155-7aa53b22-f403-4fd8-a62b-b0d54000d0a8.png)

**Comment by alexx2000** [comment]
The problem only with dark edition. I cannot find how to fix it yet.
