### ISSUE TITLE
Can't add file descrip.ion on samba network shares

### ISSUE THREAD

**Issue by muchachagrande** [doublecmd/doublecmd#213]
Hi, when I press CTRL+Z to add a description to a file, the description editor opens and allows me to write a text.
After that, when I accept the text, it creates the descript.ion file but with zero bytes.
If a previous descript.ion file existed, it truncates to zero bytes, so you loose any previous description.
This happens when I'm working on remote drives over samba. It works right on local drives.
Other operations as copy, rename, delete, and even editing a file works so I think I have the right permissions to work with the cifs share.
Another, may be related, problem is that I can't download a file using FTP plugin directly to the remote share. So I download it to a local disk and then move it to the remote share.
The same happens trying to unzip files to remote shares. The error says "stream write error".
I tried different archives and had problems with zip and jar. Extracting from rar, tar, iso, 7z and even apk worked fine.

**Comment by alexx2000** [comment]
Hi,

Execute in the console:

`stat -f -c "%t %T" /path_to_samba_network_share`

and copy output here.
