### ISSUE TITLE
Cannot connect to server via ssh

### ISSUE THREAD

**Issue by Skeeve** [doublecmd/doublecmd#227]
I tried to open a new ftp connection selecting "SSH". I got the 

```text
LibSSH2 library not found!
To use SSH2 connections, pleaseinstall the
LibSSH2 library (libssh2.dylib)!
```

While it's quite clear what it means, it's absolutely useless, because it gives no hint at all how one would achieve this, let alone where to get this library.

**Comment by rich2014** [comment]
Double Commander 1.1.0 beta for macOS officially supported released!
https://doublecmd.h1n.ru/viewtopic.php?f=5&t=7694

and DC can also be installed through homebrew now.

**Comment by freebrowser1** [comment]
libssh2 still missing when I click on SSH.
Running doublecmd-1.1.13 on Mac M1 Sonoma, installed via Homebrew.

**Comment by alexx2000** [comment]
Did you install libssh2 library?

**Comment by freebrowser1** [comment]
> Did you install libssh2 library?
Yes, it was already installed according to Homebrew.
```
libssh2 1.11.0_1 is already installed and up-to-date.
To reinstall 1.11.0_1, run:
  brew reinstall libssh2
```
And, yet, doublecmd complains that libssh2 is not installed.

**Comment by freebrowser1** [comment]
> Try this: `brew link --overwrite libssh2`

To no avail.
```
mymac.local:~/scratch % brew link --overwrite libssh2 
Warning: Already linked: /opt/homebrew/Cellar/libssh2/1.11.0_1
To relink, run:
  brew unlink libssh2 && brew link libssh2
mymac.local:~/scratch % brew unlink libssh2 && brew link libssh2
Unlinking /opt/homebrew/Cellar/libssh2/1.11.0_1... 190 symlinks removed.
Linking /opt/homebrew/Cellar/libssh2/1.11.0_1... 190 symlinks created.
mymac.local:~/scratch %  brew install --cask double-commander  
```
They do exist.
```
lrwxr-xr-x  1 user  admin  46 May  2 17:34 /opt/homebrew/lib/libssh2.1.dylib -> ../Cellar/libssh2/1.11.0_1/lib/libssh2.1.dylib
lrwxr-xr-x  1 user  admin  40 May  2 17:34 /opt/homebrew/lib/libssh2.a -> ../Cellar/libssh2/1.11.0_1/lib/libssh2.a
lrwxr-xr-x  1 user  admin  44 May  2 17:34 /opt/homebrew/lib/libssh2.dylib -> ../Cellar/libssh2/1.11.0_1/lib/libssh2.dylib
```
So doublecmd does not see them.
<img width="462" alt="Screenshot 2024-05-02 at 17 35 42" src="https://github.com/doublecmd/doublecmd/assets/26625141/d2bf8200-8cd3-4857-bb1d-f9d36c28ebe3">

**Comment by alexx2000** [comment]
It is not a standard library path so DC can't find it there. Under macOS 11 x86_64 the link are created in the `/usr/local/lib` and works fine.

**Comment by freebrowser1** [comment]
See #1604.

**Comment by mr-anton-t** [comment]
@freebrowser1  check as

```
file /Applications/Double\ Commander.app/Contents/MacOS/doublecmd
file /opt/homebrew/opt/libssh2/lib/libssh2.dylib

```

If:
Double Commander = x86_64
libssh2 = arm64

➡️ They are not compatible
