### ISSUE TITLE
More human readable bytes formatting in "Synchronize dirs"

### ISSUE THREAD

**Issue by szpak** [doublecmd/doublecmd#23]
With large dirs to synchonize the currently existing formatting of number of bytes can be quite unreadable:

![doublecmd-synchonize-dirs-bytes-formatting](https://user-images.githubusercontent.com/148013/75082056-177c0f00-5512-11ea-93aa-874565eb863c.png)

1GB? 10GB? 100GB? :-). You need to take a closer look to distinguish them.

Maybe it would be possible to format it in "human readable form" M, G, T instead of just bytes (usually precised number of bytes is not crucial here)? Alternatively maybe just `100 000 000 bytes` instead of `100000000 bytes`

Tested with 1.0.0 alpha - revision: 9321.

**Comment by alexx2000** [comment]
Done (revision: 9331).

**Comment by szpak** [comment]
Beautiful, thanks!

![image](https://user-images.githubusercontent.com/148013/75113162-86a94e80-564b-11ea-86c0-2ddb45313520.png)
