### ISSUE TITLE
Download source

### ISSUE THREAD

**Issue by yashpalgoyal1304** [doublecmd/doublecmd#232]
This issue is to request you to provide the doublecmd to be downloaded via more trusted sources i.e. other than sourceforge – GitHub for example. The request is based on this conclusive article from N++ author: https://notepad-plus-plus.org/news/npp-leaves-sourceforge/

I hope u consider this humble request.

Thanking u.

**Comment by JonnyTech** [comment]
Binary buildd already available as from release 1.0.0 beta: https://github.com/doublecmd/doublecmd/releases

**Comment by yashpalgoyal1304** [comment]
I meant the builds for stable releases

**Comment by alexx2000** [comment]
This article is slightly outdated, SourceForge had many owners. Current owner as I know does not use these bad practices.
Some history about problem: https://en.wikipedia.org/wiki/SourceForge#Controversies
Anyway as stated above same files can be downloaded from GitHub.

**Comment by yashpalgoyal1304** [comment]
if there's no plan to release stable builds on other sources, then this issue can be closed from my side :(

**Comment by alexx2000** [comment]
It is already released here: https://github.com/doublecmd/doublecmd/releases

**Comment by yashpalgoyal1304** [comment]
Ohh, u meant that current available version (which is beta) is there, and future stable will be there too? I thought that gh release was only for beta (looking at the ~~release history~~)
Edit: ohwww, I saw the page versions page, and mistook it for the release page, and inferred the above said thing.

**Comment by alexx2000** [comment]
All Double Commander releases are **beta**. [Versions](https://github.com/doublecmd/doublecmd/wiki/Versions) page contains all released versions list, both [SourceForge](https://sourceforge.net/p/doublecmd/wiki/Download) and [GitHub](https://github.com/doublecmd/doublecmd/releases) pages contains latest **1.0.0 beta** release.
