### ISSUE TITLE
Light snapshot: Ole Drag and drop leap when returning to DC window

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [doublecmd/doublecmd#239]
Drag file outside DC towards windows explorer, drag it back and forth. Sometimes, usually when using higher mouse speed, mouse cursor jumps far away from DC window edge to the right:

https://user-images.githubusercontent.com/46539653/139752636-fd71503d-c365-41fb-9d49-e102b4b1658b.mp4

This happens with official light theme DC snapshot.

```
Double Commander
Version: 1.1.0 alpha
Revision: 9976
Commit: 62220e1b9
Build date: 2021/11/01
Lazarus: 2.2.0.2
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 1809 x86_64

```

**Comment by alexx2000** [comment]
I cannot reproduce.
