### ISSUE TITLE
Sub context menu won't show up

### ISSUE THREAD

**Issue by Neur1n** [doublecmd/doublecmd#24]
I better post a screen capture to address it:
![2020-03-13-10-29-52](https://user-images.githubusercontent.com/17579247/76585677-e5127000-6519-11ea-99a8-2dc8c0e59e74.gif)
 Some of the sub- context menu won't show up properly.

Related: kerol2r20/Windows-terminal-context-menu#12

**Comment by alexx2000** [comment]
Sorry I don't know how to fix it. DC simply query system background menu, adds first three items and show it. Why some submenu does not work I have no idea.

**Comment by Neur1n** [comment]
Could you please point out the related codes? Thanks.

**Comment by alexx2000** [comment]
https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/src/platform/win/ushellcontextmenu.pas

**Comment by asvc** [comment]
Can't replicate. Build details:
```
Double Commander
Version: 0.9.8 beta
Revision: 9296M
Build date: 2020/02/01
Lazarus: 2.0.6.0
FPC: 3.0.4
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 1909 x86_64
```
@Neur1n , perhaps you have used some tool that modifies Explorer menus and it has affected DC?

**Comment by Neur1n** [comment]
@asvc Thanks for your reply. I tested on a newly setup virtual machine with same version OS and Double Commander as yours, but still couldn't get it works.

**Comment by asvc** [comment]
@Neur1n Let's try it again, bog-standard DC, same version as before. No plugins:

![Video_2020-04-03_231746](https://user-images.githubusercontent.com/300146/78362566-dfccb080-7601-11ea-9d80-b58d0dafb58c.gif)

Is this what you expect?

**Comment by Neur1n** [comment]
Yes, this is what I expect and I got it except for `Open Windows Terminal here` or `Give access to`.

**Comment by asvc** [comment]
I have no clue why "give access to" doesn't work (are you trying on locally-mounted NTFS volume?..), however for the former you might want to check out the https://github.com/microsoft/terminal/issues/1060

**Comment by Neur1n** [comment]
@asvc  Actually I got the Windows terminal context menu from the issue you mention, but thank you anyway. Your effort is much appreciated.

And what do you mean by "locally-mounted NTFS volume"? If you mean the hard drive physically install in my machine, then yes, all the volumes are in NTFS format.

**Comment by alexx2000** [comment]
It does not work with "background" menu only, which called from empty space on the panel.

**Comment by Neur1n** [comment]
@alexx2000 Works like magic.

**Comment by majkinetor** [comment]
This still shouldn't get closed as problem isn't really fixed (it behaves the same way on my machine).

Perhaps DC should automatically apply context menu on `..` when user is doing it via empty space.

**Comment by Neur1n** [comment]
@majkinetor I'm using doublecmd 0.9.9 and switched from [kerol2r20/Windows-terminal-context-menu](https://www.github.com/kerol2r20/Windows-terminal-context-menu) to [lextm/windowsterminal-shell](https://www.github.com/lextm/windowsterminal-shell), now the context menu works fine even I don't right click on  `..`. But the downside is that the latter does not have sub-menus so that you may not choose which shell to be opened from context menu.
