### ISSUE TITLE
Can't turn on client. GTX 1660ti Windows 10.

### ISSUE THREAD

**Issue by punpun1** [doublecmd/doublecmd#240]
Switching on the plugin blinks orange briefly before turning off instantly. 

[client.log](https://github.com/doublecmd/doublecmd/files/7464289/client.log)

Things I have tried to absolve issue.
1. Update graphics drivers. (and windows)
2. Reinstalling runelite in both 32/64 bit
3. Updating windows
4. Reinstalling plugin
5. Disabling hardware acceleration in runelite
6. Selecting 1660ti as OpenGL rendering GPU in Nvidia Control panel
7.Running with administrative privileges
8. Using .Jar version of runelite
9. Using both switchable/discrete GPU settings in BIOS 

**Computer Specs: Lenovo Legion Y540**
Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
GPU: Nvidia GeForce 1660 TI
16GB Ram

Windows 10 Home, 64-bit, DX12

I've done just about everything a non tech savy person can think of.  Appreciate any help, thanks!

**Comment by alexx2000** [comment]
How this related to Double Commander?
