### ISSUE TITLE
[Feature Request] Simple Format For Displaying File Size

### ISSUE THREAD

**Issue by sohotcall** [doublecmd/doublecmd#244]
I want to suggest simple format for displaying file size.

Example (binary prefix):
- 1023Ki
- 102Ki
- 10.2Ki
- 1.02Ki

Example (metric prefix):
- 999kB
- 99.9kB
- 9.99kB

Feature:
- three significant digits
- max column length: 6

**Comment by avmaksimov** [comment]
Do you mean always use Ki / kB and three digits? Why existence options is not good?

**Comment by JonnyTech** [comment]
![image](https://user-images.githubusercontent.com/3584732/216777896-c42bcca8-b535-4aee-96f4-e02d3f5aeca1.png)

**Comment by alexx2000** [comment]
https://doublecmd.github.io/doc/en/configuration.html#ConfigView
