### ISSUE TITLE
Doublecmd Freeze when copying files with Long names and other Languages.

### ISSUE THREAD

**Issue by Optivan** [doublecmd/doublecmd#245]
Hi, today i try to Backup a Game.

When i startet to Copy, doublecmd Freezes complete (i only can close it via Taskmanager), a Window shows up and says Syntax of Filename, Folder or Harddrive are wrong. (Screenshot) 
[](url)https://bilderupload.org/bild/977831323-bug402cac3dacf2ef35035931

When i Copy the game with Windows 10 Explorer it works Normal.

I dont know if there is any Logfile in Doublecmd, or where to find it. 
So i cant Post it.

Regrads Optivan

**Comment by alexx2000** [comment]
Hi, copy here full file name as text. I will check it.

**Comment by Optivan** [comment]
䳪䖋ꀛ칺䌆ឳ䧂줳ᜑ଎啀荈좢Ⴙ諪䁍欇묵刾ឯ�䡕ꁱ煺寨ｐ抭ꎼ荈⃄Ď짓￿䃌ꀁ睲䠰挝ჰ䠐䲉쁲콸․赌撶䳿䖋挨譈恍枱撾郿荈�墬䃌䡕ːႹ㌁臉鯱࿀솔⧖墬䃌啓欖팝譈䣪ꗖ펡䶉訤搎譈肍폱䢉䡰귩펹ᢋⷨᜁ팎䮋䠸ꃭ펙䶋왈찡髉荈⑤ｲ⠤䠀淬魑

hope this is the right one, its from PUBG (Player Unknown Battlegrounds). There are more than one File with names like this i also copy the other ones now. 
׸耀੐㦀ǆ
׎耀煰觢ɥ

**Comment by alexx2000** [comment]
Looks like name did not paste correctly.  Can you save it in the text file and attach here?

**Comment by Optivan** [comment]
[filename.txt](https://github.com/doublecmd/doublecmd/files/7491333/filename.txt)
