### ISSUE TITLE
Change icons to SVG instead of PNG

### ISSUE THREAD

**Issue by referi** [doublecmd/doublecmd#246]
Why don't you change standard icons to svg witch is scalable and look very good instead of ugly png.
I'm trying to make doublecmd look great and modern by myself, but when I change some icons to svg they are ugly in doublecmd.
And if it is possible it would be better to have option of scalable icons and text like in Dolphin (by scrolling mouse wheel). If it is not, when add please 20x20 and 22x22 size option.

original
![image](https://user-images.githubusercontent.com/5438295/140531411-ac23c0da-09ca-4351-be4e-21471a451e16.png)
in doublecmd
![image](https://user-images.githubusercontent.com/5438295/140530938-94ed26d6-3bf6-4222-9b9a-63da5715acb9.png)

**Comment by alexx2000** [comment]
I added SVG support for standard icons. So if standard .svg icon exists then it will be used.

**Comment by referi** [comment]
> I added SVG support for standard icons. So if standard .svg icon exists then it will be used.
I go to menu Configuration - Options - Icons and choose only standard icons.
Then I replace 2 png files in /usr/share/doublecmd/pixmaps/dctheme/16x16/mimetypes/ with new svg
application-pdf.svg
application-x-cd-image.svg
They are used and visible but why are they look so ugly and pixelated? As you can see above the result of change.

**Comment by alexx2000** [comment]
Do you checked with latest DC 1.1.0? It's not enough to replace icons. You should also edit "index.theme" and mark this directory as scalable with correct Type/Size/MinSize/MaxSize.

**Comment by referi** [comment]
Just checked that in DC 1.1.0 (revision 9983) with edited "index.theme" It's the same.

**Comment by alexx2000** [comment]
Do you have librsvg library installed? Works for me. But don't expect perfect result. SVG is not a "silver bullet", at small resolutions (like 16x16) it can look ugly two.

**Comment by referi** [comment]
Yes a have librsvg library installed.
You can reproduce it in windows version too. Go to setting and choose use standard icons and icon size 48x48 for file panel. Than go to doublecmd/pixmaps/dctheme/48x48/mimetypes/ and put here application-pdf.svg and brose some pdf file how it looks like
[application-pdf.zip](https://github.com/doublecmd/doublecmd/files/7490211/application-pdf.zip)

**Comment by alexx2000** [comment]
Looks normal:
![1](https://user-images.githubusercontent.com/13401398/140608231-d86ce645-1ef5-496f-b519-006de68b543f.png)
