### ISSUE TITLE
Tar contentviewer shows not all files

### ISSUE THREAD

**Issue by lopiuh** [doublecmd/doublecmd#255]
Having a .tar file and entering it, the shown contents in the directory pane are:
super.img.lz4
dtbo.img.lz4
recovery.img.lz4

missing are the files:
userdata.img.lz4
metadata.img.lz4
vbmeta_samsung.img.lz4
boot.img
vbmeta.img

Filesize of magisk_patched-23000_1vAkx.tar is 5.6GB

Totalcomd 10 (win) shows the content correctly
Double Commander
Version: 0.9.1 beta
Revision: 8664
Build date: 2019/02/24
Lazarus: 1.8.4.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Debian 10.11

Widgetset library: GTK 2.24.32

**Comment by alexx2000** [comment]
Version 0.9.1 is obsolete and unsupported. Version 1.0.1 should show all files.

**Comment by lopiuh** [comment]
Hi alexx,

sorry for not checking latest version. I can confirm, it works.

Ciao

lopiuh
