### ISSUE TITLE
Fedora 35 : Missing folder on openSUSE Build Service

### ISSUE THREAD

**Issue by skipperTux** [doublecmd/doublecmd#256]
[Fedora 35](https://fedoramagazine.org/announcing-fedora-35/) is out, no folder for Fedora 35 on [openSUSE Build Service](https://download.opensuse.org/repositories/home:/Alexx2000/).
Is it really an extra build for Fedora 35, or would a link to the Fedora 34 folder be sufficient?

**Comment by alexx2000** [comment]
It is really an extra build for Fedora 35. I tried to build it but it failed, something changed in Fedora 35.

**Comment by skipperTux** [comment]
Output I get following the [build instructions](https://github.com/doublecmd/doublecmd/wiki/Development) on Fedora 35.
`Free Pascal Compiler version 3.2.2 [2021/09/21] for x86_64`
`Lazatus 2.0.12`
[dcmd-output.log](https://github.com/doublecmd/doublecmd/files/7533686/dcmd-output.log)

Btw, doublecmd Fedora 34 installs and works on Fedora 35.

**Comment by rabin-io** [comment]
Hi @alexx2000 , have you able to work on this ?

**Comment by alexx2000** [comment]
Build [failed](https://build.opensuse.org/package/live_build_log/home:Alexx2000:doublecmd-svn/doublecmd-gtk/Fedora_35/aarch64), something wrong with linker.

**Comment by rabin-io** [comment]
for the QT version i see this error, 

```
[  173s] 	file /usr/lib64/libQt5Pas.so.1.2.6 from install of libQt5Pas1-2.6-43.1.x86_64 conflicts with file from package qt5pas-2.6-2001203.fc35.x86_64
```

**Comment by alexx2000** [comment]
I fixed it, something was wrong with my Lazarus package.

**Comment by rabin-io** [comment]
What about the QT build ?

**Comment by skipperTux** [comment]
I would like to close this issue, but as @rabin-io pointed out, no QT build for Fedora 35 (like for Fedora 34 or OpenSUSE rpm). Is this an easy fix, or shall we open up a new issue for this? Thanks.

**Comment by alexx2000** [comment]
Fixed, Qt5 build is there.
