### ISSUE TITLE
Samba shares are not accessible on Linux

### ISSUE THREAD

**Issue by domy-os** [doublecmd/doublecmd#258]
Dear all,

I do have a problem with accessing samba shares on Linux machine, getting a message "Change current directory to smb://servername/sharename/ failed".

![Screenshot_20211110_202640_linux](https://user-images.githubusercontent.com/84593035/141181450-8a800e0a-b8bd-400a-b96d-01592199dbff.png)

This is the default installation, so SMB plug-in is installed and active.

```
[domy@Domy-NB ~]$ locate samba.wfx
/usr/lib64/doublecmd/plugins/wfx/samba/samba.wfx
[domy@Domy-NB ~]$ ls -alh /usr/lib64/doublecmd/plugins/wfx/samba/samba.wfx
-rw-r--r--. 1 root root 338K ruj  23 15:58 /usr/lib64/doublecmd/plugins/wfx/samba/samba.wfx
```

![Screenshot_20211110_204331_linux](https://user-images.githubusercontent.com/84593035/141182585-fcdf7be0-427a-4d73-b72d-9d07bd05b605.png)

If I try the same using Dolphin, it works fine. I type the address of Windows share, it asks me for user credentials and then jumps in.

![Screenshot_20211110_202857_linux](https://user-images.githubusercontent.com/84593035/141181410-3f7de6d0-1132-4443-926e-42578850efb4.png)

If i mount all shares through terminal or /etc/fstab file, it works fine in Double Commander but this is not practical for a notebook and accessing plethora of different shares.

This is the output from terminal:

```
Starting Double Commander
Double Commander 0.9.10 beta
Revision: 9640
Build: 2021/07/21
Lazarus: 2.0.12.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-gtk2
System: Fedora release 35 (Thirty Five)
Desktop Environment: KDE
Widgetset library: GTK 2.24.33
```

Does anyone have some advice, please?

**Comment by alexx2000** [comment]
Samba plugin doesn't work in that way. You should open a list of added file system plugins (WFX plugins): Menu->"Commands"->"Open VFS List" and choose "Windows Network" (it is a samba plugin). However, it may or may not work. Depends on the settings of the operating system. 

If you want to open samba shares by address then you should install GVFS, see [details](https://doublecmd.github.io/doc/en/faq.html#gvfs).

**Comment by hgdrn** [comment]
> If you want to open samba shares by address then you should install GVFS, see [details](https://doublecmd.github.io/doc/en/faq.html#gvfs).

That works, if I add a link to my Directory List (Ctrl-D) or a bar button, that's fine.

Feature request: Please make it possible to enter "cd smb://foo/bar/" in the command line to access a GVFS share. This a the way I access Windows/SMB shares with the original Total Commander ever since. (cd \\foo\bar)

Currently DC wants to cd to $(pwd)smb://foo/bar/ and that fails for good reasons.

**Comment by alexx2000** [comment]
Also you can enter address directly to the [current directory bar](https://doublecmd.github.io/doc/en/help.html#iface_dir).

Yes, "cd" command has limited functional.

**Comment by domy-os** [comment]
> Samba plugin doesn't work in that way. You should open a list of added file system plugins (WFX plugins): Menu->"Commands"->"Open VFS List" and choose "Windows Network" (it is a samba plugin). However, it may or may not work. Depends on the settings of the operating system.
> 
> If you want to open samba shares by address then you should install GVFS, see [details](https://doublecmd.github.io/doc/en/faq.html#gvfs).

The first suggestion using VFS List doesn't work, it asks me for some user credentials but won't let me in whatever I put there, tried both local and network accounts. We do not use network discovery, maybe that's the problem.

The second suggestion works fine, thanks! I have installed gvfs, gvfs-client and gvfs-smb packages here on Fedora 35. Tried both FQDN and IP addresses, admin and regular share folder, all good!

![Screenshot_20211111_202326_linux](https://user-images.githubusercontent.com/84593035/141356759-3a2093f6-1b4e-415d-9247-223998746bcb.png)

I can create directory hotlist now and remove fstab mounts.

**Comment by wojnilowicz** [comment]
> Samba plugin doesn't work in that way. You should open a list of added file system plugins (WFX plugins): Menu->"Commands"->"Open VFS List" and choose "Windows Network" (it is a samba plugin). However, it may or may not work. Depends on the settings of the operating system.
> 
> If you want to open samba shares by address then you should install GVFS, see [details](https://doublecmd.github.io/doc/en/faq.html#gvfs).

The "Windows Network" plugin doesn't work for me on Fedora 39. It's strange because I get exactly the same dialog when using GVFS and give exactly the same credentials there, and it works there, so I don't understand why the "Windows Network" plugin displays me this dialog in a loop.

Are the settings of the operating system that it depends on documented somewhere?
