### ISSUE TITLE
Не скрывается диск из панели, если добавить его в черный список дисков

### ISSUE THREAD

**Issue by ZhymabekRoman** [doublecmd/doublecmd#259]
Здравствуйте, попробовал добавить точку монтирования и сам диск в черный список, но он не исчезает из панели дисков. Возможно я что-то не то делаю, но могу предположить что функционал не адаптирован под Линукс просто. Специально поставил саму последнию версию, проблема так же есть.

Дополнительная информация:
```
greta@greta-pc:~$ doublecmd 
SystemLocale ru_RU
SystemLanguage ru
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.1.0 alpha
Revision: 9990
Commit: 93eab094c
Build: 2021/11/09
Lazarus: 2.0.12.0
Free Pascal: 3.0.4
Platform: x86_64-Linux-qt5
System: Ubuntu 20.04.3 LTS
Desktop Environment: LXQt
Widgetset library: Qt 5.12.8, libQt5Pas 5.6.1
```

**Comment by ZhymabekRoman** [comment]
Записал видео где видно самое проявление бага: https://youtu.be/cDk2HIdFHt0

**Comment by Skif-off** [comment]
Попробуйте убрать слэш в конце или допишите после него звёздочку.

И не лень вам было видео писать? :) Показали бы точку монтирования и что указываете в поле ввода...

**Comment by ZhymabekRoman** [comment]
> Попробуйте убрать слэш в конце

Ахахахаха, всего лишь, спасибо, заработало!

> И не лень вам было видео писать?

Я хотел максимально помочь исправить этот баг) Уже был готов подучить Паскаль и исправить баг самостоятельно)

**Comment by ZhymabekRoman** [comment]
@Skif-off все же, ИМХО убирать слэш в пути к диску - это больше воркароунд, исправьте пожалуйста)

**Comment by Skif-off** [comment]
И в подсказке, и в справке написано "точка монтирования", ни разу не видел точки монтирования со слэшем в конце :)

P.S. Я не разработчик.
