### ISSUE TITLE
Scrolling and navigation is extremely slow on macOS!

### ISSUE THREAD

**Issue by aadrian** [doublecmd/doublecmd#26]
Hi,

Scrolling and navigation (e.g. in the home directory with active "Show Hidden Files") is extremely slow on macOS - and this on very powerful machines :( .

It makes the application practically useless :( .

Thank you.
P.S. This can't be a machine/OS issue since on the same machines, https://github.com/mucommander/mucommander is very snappy doing all these operations.

**Comment by rich2014** [comment]
@aadrian 

hi, does this problem still exist in the latest 1.1.0 version?

**Comment by aadrian** [comment]
@rich2014 with v1.1.0, I can't reproduce the issue on a M2 based machine.
