### ISSUE TITLE
Config: "CutTextToColumnWidth" is cutting to small on Linux

### ISSUE THREAD

**Issue by funkymaster** [doublecmd/doublecmd#260]
Hi,
with the following settings, the text is cut off in the wrong place.

AutoFillColumns>True
AutoSizeColumn>0
CustomColumnsChangeAllColumns>False
CutTextToColumnWidth>True
ExtendCellWidth>True

Tree view is on and left panel size is 100%.

![image](https://user-images.githubusercontent.com/21222589/141700229-f5836deb-c2e3-4c2c-8860-dda043980201.png)

Please fix.
Thank you!

> Double Commander
Version: 1.1.0 alpha
Revision: 9978
Commit: 137c2af38
Build date: 2021/11/03
Lazarus: 2.0.12.0
FPC: 3.2.0
Platform: x86_64-Linux-qt5
OS version: Debian bookworm/sid
Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

**Comment by funkymaster** [comment]
For information only, the parameter works correctly under Windows

**Comment by alexx2000** [comment]
As I know it does not work only when ExtendCellWidth=True and Qt version.

**Comment by funkymaster** [comment]
Hm, strange.
I switched to the GTK version for a test and it really seems to work with GTK.
Is it a Qt bug?

**Comment by alexx2000** [comment]
I guess it is Lazarus LCL-Qt5 bug.

**Comment by alexx2000** [comment]
Fixed.
