### ISSUE TITLE
Copy window size wrong on Linux

### ISSUE THREAD

**Issue by funkymaster** [doublecmd/doublecmd#261]
Hi,

if I copy something on Linux, the copy window is too small.
![image](https://user-images.githubusercontent.com/21222589/141700627-66e35d3b-4e3d-40d6-9689-7581292413a7.png)
I can resize the window to the correct size, that I can also see the "Pause" button.
But the next time a copy is done, the window is too small again.

Please adjust the copy window size or save the adjusted window size in the doublecmd.xml file.
Thank you!

> Double Commander
Version: 1.1.0 alpha
Revision: 9978
Commit: 137c2af38
Build date: 2021/11/03
Lazarus: 2.0.12.0
FPC: 3.2.0
Platform: x86_64-Linux-qt5
OS version: Debian bookworm/sid
Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

For information only, the window size is correct under Windows.

**Comment by funkymaster** [comment]
After further testing, I found out that it is not the size of the window which is wrong.
It is the distance from the counter in the middle to the buttons on the left and right of it ("Alle anzeigen" and "Abbrechen") that is too big.
If I don't adjust the window size and instead move the whole window, the distance from the counter to the buttons is suddenly corrected to the correct distance.

**Comment by funkymaster** [comment]
Here is a screenshot of what this looks like on Windows.

![image](https://user-images.githubusercontent.com/21222589/141768517-76ec2db6-fb2e-484a-8c42-ced9018927cd.png)

I would say that this should also be the template for the look on Linux.
Thx.

**Comment by funkymaster** [comment]
If I set the language to English, the size seems to be correct on Linux also.

![image](https://user-images.githubusercontent.com/21222589/142183864-c064cc39-19fa-485f-b8dd-3e515fd01ff1.png)

Please investigate and fix this.

Thank you.

**Comment by alexx2000** [comment]
Lazarus bug. I added workaround.

**Comment by funkymaster** [comment]
Thx!

Unfortunately I cannot test the workaround because I am currently not receiving a version for Debian_Testing due to unsolved build problems. Let me know when you want me to investigate this.

**Comment by funkymaster** [comment]
Works perfect.
Thank you!
