### ISSUE TITLE
How to increase the size of the functions buttons?

### ISSUE THREAD

**Issue by peter099** [doublecmd/doublecmd#263]
Double Commander has great many options for configurations but i couldn't find option to increase the size of the functions button at the bottom bar. It is not a big issue but on my screen they appear small in size. I am using Double Commander on mx linux.

**Comment by alexx2000** [comment]
https://doublecmd.github.io/doc/en/faq.html#cs_size

**Comment by peter099** [comment]
Thanks, that worked, and i like the simplicity of how is implemented.

I have another question: can i make filtering as default option when i start typing to search for files in a pane?

**Comment by j2969719** [comment]
options>keys>letters>quick filter

**Comment by peter099** [comment]
Thanks!

I started using Double Commander from few days and i really like it. I was using Krusader, but i think i will move to Double Commander.
