### ISSUE TITLE
Add TotalCommander like FTP button

### ISSUE THREAD

**Issue by mrx23dot** [doublecmd/doublecmd#265]
Please add the missing FTP button to Double Commander.
Everyone got use to this, currently it's hidden under network menu.
![totalcomm775](https://user-images.githubusercontent.com/4163396/142188443-ce2e988e-3ea3-438b-88ed-0f072971fe9a.jpg)

**Comment by hgdrn** [comment]
This is a command button in TC's button bar. You might want to edit DC's button bar and add a command button yourself.

**Comment by mrx23dot** [comment]
Or we could have it as default, since the goal is to make it similar to TC out of the box. 
I had a quick look there wasnt any FTP named internal cmd button that was a quick fix.

**Comment by hgdrn** [comment]
Add button
for internal command
cm_networkconnect

**Comment by mrx23dot** [comment]
Thanks, that works, I vote to have it as default, maybe with a bit more intuitive icon.
