### ISSUE TITLE
[SOLVED] DC cannot set permissions

### ISSUE THREAD

**Issue by antodc** [doublecmd/doublecmd#272]
I am using DC 1.0.0 with Windows 10 (1909). Since version 1.0, every time I copy a file DC asks for administrator privileges to set permissions (no idea what permissions it needs to set). Unfortunately, it says it cannot set them even when privileges are granted and keeps showing the same warning message every time I copy a file. Even executing DC as administrator does not help. There are no issues when I move a file.

**Comment by j2969719** [comment]
in the F5 dialog try to press 'options' button and change 'When cannot set property'

**Comment by antodc** [comment]
Thank you for your kind reply, but I did not get it. When I press F5 DC tries to copy the file to the other panel. Then, I dialog box "Can not set permissions for FILENAME" appears and the options are "Skip", "Skip All", "Ignore All", "Abort". I do not see the "options" button.

**Comment by j2969719** [comment]
![copy](https://user-images.githubusercontent.com/30291994/143047886-3d5cd81c-a02c-44a7-b66a-54b120ef0fc3.png)

**Comment by antodc** [comment]
Great! In the past I disabled that dialog box in the "Drag & Drop" options. For this reason I did not see it. Thanks a lot!!
