### ISSUE TITLE
Error when sending search results of duplicate files to the listbox

### ISSUE THREAD

**Issue by Jankosx7** [doublecmd/doublecmd#273]
When I search duplicate files, an error occurs when results are sent to the listbox. I noticed that error occurs if brief view is selected in listbox. The error does not occur when I search files in standard mode and I send results to the listbox. I have tested this on 2 different computers and in 32 and 64 bit versions.

[https://drive.google.com/drive/folders/1C7Y-irCX45TkE9O4zQI1hJ04qEltz0HP?usp=sharing](url)

doublecmd.err
`--------------- 25-11-2021, 12:17:56 ---------------
| DC v1.0.1 beta Rev. 35 -- x86_64-Win64-win32/win64
| Windows 10 21H1 x86_64 | PID 6688
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007FF60C6CA68A in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C6CA724 in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60CB74DA3 line 761, column 3 of fileviews/ucolumnsfileview.pas in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60CB8B0FF line 1909, column 29 of fFindDlg.pas in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C9CD6B7 line 230, column 7 of uformcommands.pas in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60CB875C0 line 954, column 3 of fFindDlg.pas in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C6EC3EC in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C8C6F03 line 98, column 8 of include/containedaction.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C8C8B82 line 246, column 13 of include/customaction.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C6EC18B in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C85969B line 2960, column 5 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C882CC9 line 55, column 3 of include/buttoncontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C8833B9 line 169, column 3 of include/buttons.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C882BC2 line 21, column 5 of include/buttoncontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C6D0801 in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C858441 line 2287, column 24 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C84C6F9 line 5429, column 28 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe

--------------- 25-11-2021, 12:17:57 ---------------
| DC v1.0.1 beta Rev. 35 -- x86_64-Win64-win32/win64
| Windows 10 21H1 x86_64 | PID 6688
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007FF60CD72C60 in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C8464A0 line 2520, column 8 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C846E24 line 3130, column 45 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C846A90 line 3232, column 11 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C84E6C0 line 6449, column 5 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DAB line 3079, column 7 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859DE8 line 3081, column 48 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C859B5C line 3129, column 7 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C8487C9 line 3546, column 7 of include/wincontrol.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C853EDE line 393, column 9 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C853E9D line 388, column 7 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
  $00007FF60C853E9D line 388, column 7 of include/control.inc in C:\Users\user\Desktop\doublecmd\doublecmd.exe
`

**Comment by FlowXP** [comment]
Hello, I see the ticket is closed, just wanted to add the same is for Linux version, 
**doublecmd.err :** 
--------------- 29-11-2021, 15:16:14 ---------------
| DC v1.0.1 beta Rev. 35 -- x86_64-Linux-gtk2
| Linux Mint 20.2 Uma -- GTK 2.24.32 | PID 304867
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00000000007AF8B1 line 5542, column 13 of grids.pas in /usr/lib/doublecmd/doublecmd
  $0000000000AE2ECA line 658, column 3 of fileviews/ucolumnsfileview.pas in /usr/lib/doublecmd/doublecmd
  $00000000009C57C4 line 230, column 7 of uformcommands.pas in /usr/lib/doublecmd/doublecmd
  $0000000000B0A884 line 954, column 3 of fFindDlg.pas in /usr/lib/doublecmd/doublecmd
  $00000000006FB62D line 246, column 13 of include/customaction.inc in /usr/lib/doublecmd/doublecmd
  $00000000004A067F in /usr/lib/doublecmd/doublecmd
  $000000000064494A line 55, column 3 of include/buttoncontrol.inc in /usr/lib/doublecmd/doublecmd
  $0000000000645193 line 169, column 3 of include/buttons.inc in /usr/lib/doublecmd/doublecmd
  $0000000000644836 line 21, column 5 of include/buttoncontrol.inc in /usr/lib/doublecmd/doublecmd
  $000000000043450F in /usr/lib/doublecmd/doublecmd
  $00000000005EA87D line 5411, column 28 of include/wincontrol.inc in /usr/lib/doublecmd/doublecmd
  $000000000078DD02 line 112, column 36 of lclmessageglue.pas in /usr/lib/doublecmd/doublecmd
  $000000000079EF31 line 2486, column 34 of gtk2wsstdctrls.pp in /usr/lib/doublecmd/doublecmd
