### ISSUE TITLE
Can't launch Qt version executable, must run the .sh

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#276]
I've downloaded [the 64-bit Qt 1.0.1 beta](https://github.com/doublecmd/doublecmd/releases/download/v1.0.1/doublecmd-1.0.1.qt.x86_64.tar.xz) but when I execute `./doublecmd` on KDE Neon 5.23 (X), I get this error:

    ./doublecmd: error while loading shared libraries: libQt5Pas.so.1: cannot open shared object file: No such file or directory

That file *is* in the current directory. I've extracted the entire archive.

If I run `doublecmd.sh`, that works, but this isn't documented anywhere.

**Comment by alexx2000** [comment]
Next portable version will not require `doublecmd.sh`.

**Comment by Skif-off** [comment]
> If I run `doublecmd.sh`, that works, but this isn't documented anywhere.

http://doublecmd.github.io/doc/en/faq.html#repo : _Also portable versions are available (see details [here](http://doublecmd.github.io/doc/en/help.html#usage))._ > 
http://doublecmd.github.io/doc/en/help.html#usage : _use doublecmd.sh to launch_.
