### ISSUE TITLE
Deprecased newsfeeds

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#277]
The README links to "various [news feeds](https://github.com/doublecmd/doublecmd/wiki/News-feeds)". Are any of those still actual?

**Comment by ags1234** [comment]
I just tested the feeds.

These still work:
https://sourceforge.net/api/file/index/project-id/188452/mtime/desc/limit/20/rss
http://sourceforge.net/export/rss2_keepsake.php?group_id=188452
http://doublecmd.sourceforge.net/mantisbt/issues_rss.php

Does not work:
http://doublecmd.sourceforge.net/forum/rss.php

PS: Nici nu știam de ele! Thanks, Dan!

**Comment by dandv** [comment]
Salut. There should be one source of truth for bugs (this repo, not Mantis) and releases (GitHub, not sourceforce). This splitting between resources doesn't help (it's not mirroring); it creates confusion.

**Comment by alexx2000** [comment]
Links fixed.
