### ISSUE TITLE
Viewer не верно выделяет позицию текста.

### ISSUE THREAD

**Issue by johndoe71rus** [doublecmd/doublecmd#28]
Calculate linux xfce x86_64 
При выделении текста в просмотрщике позиция выделения не совпадает с курсором.
видео.
http://dropmefiles.com/EsP7k
В редакторе выделяет корректно.

**Comment by nowayelse** [comment]
Аналогично, xubuntu 22.04.1, xfce4.16
Чтобы не "unable to reproduce" - какие дебаги могу я собрать?

**Comment by alexx2000** [comment]
В связанных issue выяснили что шрифта Monospace не существует, под его именем может скрываться любой шрифт. И в некоторых случаях под ним скрывается совсем не моноширинный шрифт. Поэтому проверять следует с каким-либо реальным, моноширинным шрифтом. Сравнивать редактор и вьювер напрямую нельзя, они используют разные принципы отрисовки текста.

**Comment by johndoe71rus** [comment]
забавно.
Как то можно отследить какой шрифт скрывается под настройками monospace? какой реально выбирается.

**Comment by alexx2000** [comment]
В том-то и дело что нет. Я там приводил пример, у меня в системе в качестве "Monospace" настроен "Liberation Mono". Однако при отрисовке используется совсем другой шрифт. Поэтому было решено при первом запуске DC, посредством libfontconfig, заменять "Monospace" на реальный моноширинный шрифт настроенный в системе.
