### ISSUE TITLE
Gets darker and darker

### ISSUE THREAD

**Issue by irtools** [doublecmd/doublecmd#283]
Double Commander
Version: 0.9.8 beta
Revision: 9296
Build date: 2020/02/09
Lazarus: 2.0.6.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: elementary OS 6 Odin

Widgetset library: GTK 2.24.32

This is completely new behaviour: When a focal window is opened to, say, copy or move a selection of files, the background used to get darker until the operation is over and the window closes. The new 'feature' is that it remains darker, and then gets almost black after a new focal window is raised.

**Comment by bubersson** [comment]
I'm hitting the same issue on Elementary OS. My guess is that elementary is a bit weird about rendering gtk2 and at the same time doublecommander doesn't reset the background fading for some dialogs. 

Only some dialogs are causing it though. E.g. "copy" is ok, but "delete" or "create directory" dialog causes the whole window to get darker every time you open the dialog. After couple times it makes the whole application unusable.

**Comment by irtools** [comment]
I have found the solution: avoid Elementary OS like the plague. It is based
on an outdated Ubuntu by definition, many things do not work, and
installing a new version kills your home by design and various external
drives by error. If you want an Ubuntu that looks nice out of the box but
really works, Budgie is the way to go.
