### ISSUE TITLE
Doublecmd  fonts become dots Linux QT5 Sway/Wayland.

### ISSUE THREAD

**Issue by siyia2** [doublecmd/doublecmd#286]
Hello, sometimes when i change workspace back n forth, or the screenlocker runs, all fonts in doublecmd-qt5 become dots. Happens only with qt5 version of the program.

**Comment by siyia2** [comment]
![2021-12-08-013703_grim](https://user-images.githubusercontent.com/46220960/145122582-1cd30280-0165-4e94-9f39-b7a80ad7f230.png)

**Comment by alexx2000** [comment]
Hi, I guess it can be some incompatibility with XWayland, see also #193

**Comment by siyia2** [comment]
Thx, that could be it, although with current pascal + lazarus version doublecmd seems to run natively on wayland. Damn why did you chose to write it in pascal? that's an odd choice of a programming language.

**Comment by alexx2000** [comment]
Current version use XWayland by default. How to execute on native Wayland written [here](https://github.com/doublecmd/doublecmd/issues/193#issuecomment-950313068).

Because Pascal is a great and pleasant language. But it undeservedly forgotten today.

**Comment by ags1234** [comment]
> Damn why did you chose to write it in pascal? that's an odd choice of a programming language.

For me it is not odd at all. It is a more than the right choice.
You have no idea how awesome can Pascal be. It has a very long list of features and advantages and combined with Lazarus, the visual development environment for Free Pascal Compiler, it is a complete and great package to work with.

Note these features:
- a mature IDE where you can quickly create a program by drag-and-dropping components of a form
- easily readable syntax
- high speed of execution
- low memory use
- fast, mature and very optimized compiler
- the programs it creates do not depend on any external frameworks and *.dll libraries, and can be distributed as single *.exe files, compatible with a very wide range of operating system versions
- it can create programs for Linux, Windows, MacOS and may other platforms. Very easily, with little or no modifications to the code
- compile software that runs on bare hardware, without operating system, or the web
- the syntax is compatible with that of Delphi
- I am sure there are more, but I don't remember them now.

And if I look at TIOBE ranking for December 2021, I see that Object Pascal is #16 as the most searched for programming language. So it's not all that forgotten. It's just burried in a lot of modern day crap.

@siyia2: How can this be an odd choice? How many languages do you know that can do this?

**Comment by j2969719** [comment]
bruh

**Comment by siyia2** [comment]
lol ok

**Comment by ags1234** [comment]
@siyia2: It is possible that C could be a little more efficient, but if I have to guess, I would say by a small percent only.
However, this world cannot be full of kings. There also have to exist queens. Would you settle for a queen, siyia2? :))

**Comment by j2969719** [comment]
bruh2
lets agree that electron is the future queen or something and get the discussion back on track

**Comment by siyia2** [comment]
> bruh2 lets agree that electron is the future queen or something and get the discussion back on track

a Bloated queen at that

> @siyia2: It is possible that C could be a little more efficient, but if I have to guess, I would say by a small percent only. However, this world cannot be full of kings. There also have to exist queens. Would you settle for a queen, siyia2? :))

I ll take the queen no prob lol

**Comment by ags1234** [comment]
> > bruh2 lets agree that electron is the future queen or something and get the discussion back on track
> 
> a Bloated queen at that

> > @siyia2: It is possible that C could be a little more efficient, but if I have to guess, I would say by a small percent only. However, this world cannot be full of kings. There also have to exist queens. Would you settle for a queen, siyia2? :))
> 
> I ll take the queen no prob lol

:)))

**Comment by siyia2** [comment]
Hello, i figured this was a general issue with qt5 in wayland enviroment.
Setting:

```
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_FONT_DPI=101
```

in /etc/enviroment resolves the font issue
