### ISSUE TITLE
DoubleCmd omits unicode characters in files and folders and doesnt display them

### ISSUE THREAD

**Issue by bidzapfc** [doublecmd/doublecmd#287]
[https://imgur.com/a/pkiJbZx](url)

Issue with reading unicode characters in folders. Double commander just omits them.

Back to back same folder in dolphin and doublecmd in link above.

This leads to entire folders not displayed in doublecmd.

**Comment by alexx2000** [comment]
It should work with DC 1.0.1. Execute DC from console and copy output here.

**Comment by bidzapfc** [comment]
Double Commander
Version: 0.9.8 beta
Revision: 9296
Build date: 2020/02/09
Lazarus: 2.0.6.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.3 LTS

Widgetset library: GTK 2.24.32

**Comment by bidzapfc** [comment]
> It should work with DC 1.0.1. Execute DC from console and copy output here.

Thank you thank you.

Working in

Double Commander
Version: 1.0.1 beta
Revision: 35
Commit: 10850f10f
Build date: 2021/10/31
Lazarus: 2.0.12.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.3 LTS

Widgetset library: GTK 2.24.32
