### ISSUE TITLE
Command "Edit New file" could respect "Select file name without extension" option

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [doublecmd/doublecmd#289]
1) Have option "Select file name without extension" in options:    
![0153R](https://user-images.githubusercontent.com/46539653/145538697-1dcb9819-699f-494c-91f9-7e00a21304a4.png)
2) Use "Edit New file" (create new file) command:    
![5356L](https://user-images.githubusercontent.com/46539653/145538798-a079741d-1e7e-4590-87ee-7f98fce78890.png)
3) Pop-up, asking for filename will occur, with all file name, including extension pre-selected:    
![5408p](https://user-images.githubusercontent.com/46539653/145538923-45ed3a15-8d23-4923-93c0-7ae90a75c71f.png)

It would be great, if only filename, without extension would be preselected at step 3 if option from step 1 is set. I understand, that option in step 1 is not directly related to command at step 2, but having this option set implies, that user is "Filename-first" type of person :)

```
Double Commander
Version: 1.1.0 alpha
Revision: 10009
Commit: 987bcfa12
Build date: 2021/12/05
Lazarus: 2.2.0.3
FPC: 3.2.2
Platform: x86_64-Win64-qt5
OS version: Windows 10 Home 20H2 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1
```

**Comment by Skif-off** [comment]
Hm... Why?

If you want to rename file, you will change base name (i.e. "new" in your screen) only (usually), but with ```cm_EditNew``` you can create a file with any name and any extension. Also ```cm_EditNew``` allows you to open an existing file (any file with any name and any extension).
And ```cm_EditNew``` uses a file under cursor.

**Comment by WhiteChairFromIkea** [comment]
I was not aware that name offered comes from already selected filename. So it seems my wishlist does not make sense.

My usual workflow is to create only *.txt files (usually, with base name "readme"), so I would like to click on icon (or hit a shortcut), type in the name ("readme" in my case) and press enter. With current behavior I am forced to enter "readme.txt", instead of just "readme". Maybe separate command should be implemented, called "cm_createNewFile", which has these options configurable:   
1) proposed filename.ext;
2) checkbox "Preselect filename without extension".

I have seen, that some internal commands can be configured with advanced flags (https://doublecmd.github.io/doc/en/cmds.html). Probably there is a way to implement advanced configuration options for current `cm_EditNew` command behavior to accommodate my workflow. I should investigate further.

**Comment by Skif-off** [comment]
For local filesystem (not virtual, like ftp.wfx and so on) you can try something like
```lua
local params = {...}

if #params ~= 1 then
  Dialogs.MessageBox('Check the number of parameters!\nRequires only one.', 'Create "readme.txt"', 0x0030)
  return
end
h = io.open(params[1] .. 'readme.txt', 'w')
h:close()

DC.ExecuteCommand('cm_Refresh')
DC.ExecuteCommand('cm_QuickSearch', 'search=on', 'direction=first', 'matchbeginning=on', 'matchending=off', 'casesensitive=on', 'files=on', 'directories=off', 'text=readme.txt')
DC.ExecuteCommand('cm_QuickSearch', 'search=off')
DC.ExecuteCommand('cm_Edit')
```
Add button with ```cm_ExecuteScript``` and params
```
path-to-CreateReadMe.lua
%"0%D
```
and hotkey.

**Comment by Skif-off** [comment]
Forgot path delimiter, fixed.

**Comment by WhiteChairFromIkea** [comment]
Thank you for generous help, I will try the script. (Already using script for pasting clipboard contents to txt file), I like the flexibility of dc is superb 🙂
