### ISSUE TITLE
"Select file name without extension when renaming" does not work properly on macos

### ISSUE THREAD

**Issue by antonsoroko** [doublecmd/doublecmd#296]
В macos 11.6.1 и doublecmd-1.1.0-10014.cocoa.x86_64.zip
если включить в "Файловые операции"
```
msgid "Select &file name without extension when renaming"
msgstr "П&ри переименовании выделять только имя файла, без расширения"
```
https://github.com/doublecmd/doublecmd/blob/master/language/doublecmd.po#L5789

то оно работает как-то супер странно:
F2 1й раз - выделяет всё
F2 2й раз - выделяет всё
F2 3й раз - выделяет расширение
F2 4й раз - выделяет имя
F2 5й раз - выделяет расширение
F2 6й раз - выделяет имя
и уже по кругу

на linux всё норм - сразу выделяет имя.

если без опции:
F2 1й раз - выделяет всё
F2 2й раз - выделяет имя
F2 3й раз - выделяет расширение
F2 4й раз - выделяет первую часть имени до пробела
F2 5й раз - выделяет вторую часть имени до пробела
F2 6й раз - выделяет расширение
F2 7й раз - выделяет первую часть имени до пробела
и уже по кругу

Тоже не уверен, что так должно быть, но может и норм.

спасибо.

**Comment by czosnkowy666** [comment]
for me 2nd time F2 selects file name without extension. But then 4th and 5th time may select different potions of file name depends on format of it for example in file `DSC_4324.NEF`. 4th F2 selects `DSC` and 5th `4324`
