### ISSUE TITLE
Access violation when try to calculate any blake hash on macos

### ISSUE THREAD

**Issue by antonsoroko** [doublecmd/doublecmd#299]
DC shows `Access violation` when try to calculate any blake hash on macos:

```
--------------- 20-12-2021, 17:47:47 ---------------
| DC v1.1.0 alpha Rev. 10014 -- x86_64-Darwin-cocoa
| Mac OS X 10.16.0 | PID 42064
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $0000000100544582 line 40, column 3 of Hashes/blake2_avx.inc in /Applications/Double Commander.app/Contents/MacOS/doublecmd
  $000000010052840D line 126, column 33 of uhash.pas in /Applications/Double Commander.app/Contents/MacOS/doublecmd
  $00000001004F565F line 440, column 10 of filesources/filesystem/ufilesystemcalcchecksumoperation.pas in /Applications/Double Commander.app/Contents/MacOS/doublecmd
```

**Comment by zxcat** [comment]
"Find duplicates by hash" is also broken on macos (revision 10539).

@alexx2000, is it hard to fix this?

**Comment by rich2014** [comment]
should be fixed in DC 1.1.0.

should we close this issue?

**Comment by rich2014** [comment]
I tested Blake2S / Blake3 / SHA2_256, it works fine.

how should it be verified?

**Comment by alexx2000** [comment]
Calculate hash for a very large file. Is your processor supports AVX instructions set?

**Comment by alexx2000** [comment]
It is only x86_64 problem as I mentioned above. I can reproduce crash with Blake2B hash. But I have an idea how to fix it. I will try it.

**Comment by rich2014** [comment]
that's great

**Comment by zxcat** [comment]
> It is only x86_64 problem as I mentioned above. I can reproduce crash with Blake2B hash. But I have an idea how to fix it. I will try it.

@alexx2000, do you see, which op exactly causes crash?
if some read/write, then it's possible data alignment problem.
if return from function, then maybe some registers not saved.

anyway, to prevent crash you can do some fallback like (pseudo-code):
```
try {
  avx_blake(args…);
} catch {
  pas_blake(args…);
}
```
maybe there is not a big difference if a bottleneck is in HDD, not CPU

**Comment by alexx2000** [comment]
Yes, I guess it is a code/data alignment problem.

**Comment by rich2014** [comment]
0611623 works fine on MacOS with Intel CPU.

issue should be closed.

**Comment by zxcat** [comment]
I can confirm it works now. Found another algorithmic issue while tested: #933.

btw, in "Calculate checksum…" dialog it seems that I can select several hashes at once, but `Shift`/`Cmd` didn't make it work. Is it possible to select several?

**Comment by alexx2000** [comment]
> Is it possible to select several?

No.
