### ISSUE TITLE
нет виртуального диска от Mail.ru (disk-o: )

### ISSUE THREAD

**Issue by Allozio** [doublecmd/doublecmd#304]
на некоторых компах (версия коммандера крайняя) нет вообще виртуального диска, подключенного через Диск-О:
тотал видит, комп видит, в проводнике есть. 
в doublecmd - пусто, вообше ничего нет

**Comment by alexx2000** [comment]
Виртуальные диски не поддерживаются.

**Comment by Allozio** [comment]
не уточнил, извиняюсь - под виндой поддерживаются. уже работаем.
выяснилось, что если запускаешь менеджер "из-под админа" - то диска нет. 
обычным пользователем = все хорошо.
или скорее, тем же юзером, что и прогу Диск-О: - тогда видит и работает

**Comment by alexx2000** [comment]
Ну значит диск скорее сетевой, чем виртуальный. А для сетевых это нормальное поведение.
