### ISSUE TITLE
Wrong progress info for copy operation to network device on Linux

### ISSUE THREAD

**Issue by szatan81** [doublecmd/doublecmd#308]
Identical issue as described here: https://doublecmd.sourceforge.io/mantisbt/view.php?id=2086
but on Linux (Linux pop-os 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP)

Double Commander
Version: 1.1.0 alpha
Revision: 10021
Commit: 2632f5ef8
Build date: 2021/12/27
Lazarus: 2.0.12.0
FPC: 3.2.0
Platform: x86_64-Linux-gtk2
OS version: Pop!_OS 21.04

Widgetset library: GTK 2.24.33

**Comment by szatan81** [comment]
Almost one year later the issue is still there.

Double Commander
Version: 1.1.0 alpha
Revision: 10415
Commit: 056efc6
Build date: 2022/11/05
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Pop!_OS 22.04 LTS

Widgetset library: GTK 2.24.33

**Comment by alexx2000** [comment]
What network file system do you use SMB, NFS?

**Comment by szatan81** [comment]
NFS, recently more annoying than wrong progress info is that doublecmd would freeze completely when copying/moving "small" files like around ~1GB

**Comment by alexx2000** [comment]
Try with
```
Version: 1.1.0 alpha
Revision: 10418
Commit: b0379a1f4
```

**Comment by szatan81** [comment]
rev 10419 Overall it looks better and copy/move operation is now starting with normal speed but looks lagged, progress bar stops and starts like it would do checksum on the fly or something and before it was fluid. Small files do not freeze DC now. Maybe you could do some tuning. Thanks

**Comment by alexx2000** [comment]
I made some tuning. It's a maximum that I can do.
