### ISSUE TITLE
Qt Version doublecmd can't input Chinese words properly when using Chinese IME

### ISSUE THREAD

**Issue by yinkaisheng** [doublecmd/doublecmd#313]
> Double Commander
Version: 1.0.2 beta
Revision: 63
Commit: 7dd1451a6
Build date: 2021/12/11
Lazarus: 2.2.0.3
FPC: 3.2.2
Platform: x86_64-Win64-qt5
OS version: Windows 10 Home 21H2 x86_64
Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1

Microsoft Pinyin is the default IME on Windows 10 Chinese edition.
When I use the default IME to input Chinese words on doublecmd, the Chinese words can't be inputted properly. See the gif.
The pascal version doublecmd doesn't have this issue.
I also tried other Qt5 applications, they don't have this issue too.
![dcqt](https://user-images.githubusercontent.com/5846696/147718238-f826d700-73dc-423f-b62a-984faab96a2c.gif)

**Comment by gnozil** [comment]
We have better alternatives in Windows:

- If you like to pay a small amount of money, Total Commander is definitely the best option. I am a paid user and it is much better than DC, which is just to mimic TC.
- Other free option like http://multicommander.com/ did much better than DC too.

I am a Linux user now mainly, so I have to use DC which is the only option which is closer to TC in Windows.

**Comment by yinkaisheng** [comment]
I like doublecmd.

**Comment by alexx2000** [comment]
Qt5 version experimental and should be used when dark mode needed only.

**Comment by alexx2000** [comment]
Qt version is obsolete. Use native version instead.
