### ISSUE TITLE
Build failure with: ufilesystemwatcher.pas(1043,14) Error: (5000) Identifier not found "SameMethod"

### ISSUE THREAD

**Issue by corvus1** [doublecmd/doublecmd#314]
```
lazbuild --version
2.3.0
```

Possibly due to: https://github.com/doublecmd/doublecmd/commit/de65d29811e1948046af52c11d43b848ffb1bf0e

**Comment by j2969719** [comment]
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/814e4ba4e2e69b6ef9a6e98ceac642366a55beae

**Comment by alexx2000** [comment]
So simply update Lazarus to latest version from Git.

**Comment by corvus1** [comment]
Yeah, that worked, thanks.
