### ISSUE TITLE
list of files for multivolume archives

### ISSUE THREAD

**Issue by publine2** [doublecmd/doublecmd#317]
The problem is in the extension of multivolume archives: .7z.001, .7z.002, etc. If i change the extension of first volume(.7z.001) to just .7z - than it opens well inside doublecmd. But with addition .001 its opening outside doublecmd by external program. To fix that we need some "Variable to interface" which will represent the number at the end of extension. 
For example like regex: .7z.[\d\d\d]

**Comment by Skif-off** [comment]
Go to "Configuration" in the main menu > Options... > Archivers:

- Windows: copy "7Z (ro)" and rename ("7Z (multiv)"?), enable and change the "Extension" field: clear and add `001`. Or try `7z.001`, but move "7Z (multiv)" in the first position (with mouse). Add path to `7z.exe` in the "Archiver" field.

- Linux: enable "7Z (ro)" (if not) and add `001` iin the list of extensions. Or try `7z.001`, but in the beginning of line. Install p7zip, 7zip or add [7-Zip for Linux](https://www.7-zip.org/download.html) to the PATH.

**Comment by publine2** [comment]
Thank you very much for reply, that is partially solved the problem. But what if I try to open 7z.002 instead of 7z.001??? Should I add all 100500 volumes to the extension field????

**Comment by publine2** [comment]
Another question: what means "ro" in "7Z (ro)" ? Is that means read only, which is archive can not be updated???

**Comment by Skif-off** [comment]
> But what if I try to open 7z.002 instead of 7z.001??? Should I add all 100500 volumes to the extension field????

Try mask: `7z.0??` or `7z.???`. But for what purpose? `7z.n` where n > 1 is a part of the archive and in this case 7-Zip does not show full content (if at least something will show).

> what means "ro" in "7Z (ro)" ? Is that means read only, which is archive can not be updated???

Using "7Z (ro)" was just a very simple way with minimal changes :) If you want, try to read [help page](http://doublecmd.github.io/doc/en/multiarc.html).
Does 7-Zip support changing multi-volume archives?

**Comment by Skif-off** [comment]
@publine2
Is your problem solved? In this case, please, close this issue ;)

**Comment by Korb** [comment]
> Using "7Z (ro)" was just a very simple way with minimal changes :) If you want, try to read [help page](http://doublecmd.github.io/doc/en/multiarc.html). Does 7-Zip support changing multi-volume archives?

A search on the page you specified for the "`(ro)`" returned nothing.
