### ISSUE TITLE
Portable packages not work "Run Terminal"

### ISSUE THREAD

**Issue by Augusto7743** [doublecmd/doublecmd#318]
Using the portable version if using the command in menu \ Commands \ Run Terminal not work.
Double Commander not open Terminal window.

**Comment by Skif-off** [comment]
Xubuntu 20.04: works fine (both, gtk2 and qt5).
Go to "Configuration" in the main menu > Options... > Tools > Terminal and check commands (DC uses `xterm` by default).

Try to replace on `x-terminal-emulator` (in Debian/Debian-based by default).

**Comment by Augusto7743** [comment]
Using "x-terminal-emulator" works.
Thanks very much.
Have a nice week.

**Comment by Skif-off** [comment]
You use Wayland and you have not `/usr/bin/xterm` (default _**X**_ terminal), right?

**Comment by Augusto7743** [comment]
No Wayland.
Using X11 and Lubuntu 20.04.3.

**Comment by alexx2000** [comment]
xterm is not installed by default for a long time. User should choose terminal emulator in portable version manually. DC 1.1 tries to determine default terminal emulator.

**Comment by Danfro** [comment]
Just wanted to let you know, this does not only apply to portable installation of double commander.
I am using Ubuntu 21.10 with X11. I installed double commander via apt. 
Here terminal would not open either. Setting to "x-terminal-emulator" fixed it though.

**Comment by Augusto7743** [comment]
Thanks very much.
