### ISSUE TITLE
<PathLabel> from <Colors> shows incorrect colors.  

### ISSUE THREAD

**Issue by tukanos** [doublecmd/doublecmd#320]
I have changed the `doublecmd.xml` based on the [xml config documentation](https://doublecmd.github.io/doc/en/configxml.html)

     <PathLabel>
      <ActiveColor>$99B4D1</ActiveColor>
      <ActiveFontColor>$903A3A</ActiveFontColor>
      <InactiveColor>$BFCDDB</InactiveColor>
      <InactiveFontColor>$903A3A</InactiveFontColor>
    </PathLabel>

Which is according to documentation [Current directory bar](https://doublecmd.github.io/doc/en/help.html#iface_dir).  The colors changes but to incorrect colors.

The colors are somehow shifted.  Note that there is a darker/lighter color, but the color itself is completely different.

I'm adding a picture where I have the color I want to achieve and below is doublecmd and the actual color displayed:

![pathLabel_incorrect_colors](https://user-images.githubusercontent.com/731154/148534822-3f583643-df88-445e-9558-0adc4b133d8b.jpg)

**Update:** Also present in the latest *1.0.3. beta*:

![doublecmd_version](https://user-images.githubusercontent.com/731154/148536170-f2036b44-0020-40e4-ba1f-107587812c4a.jpg)

**Comment by alexx2000** [comment]
You set color in the wrong format.

`About color format: We can set color as hex number using format $BBGGRR (for example, if we want to use blue color, we would write $FF0000).`

So it should be $D1B499 instead of $99B4D1.

**Comment by tukanos** [comment]
Ah, that did not occur to me :).  Thank you.
