### ISSUE TITLE
Renaming file breaks the visible length of the other file names

### ISSUE THREAD

**Issue by neuro-fishy** [doublecmd/doublecmd#321]
I don't know how to explain it good. Under certain conditions, if I rename long filenames to something very short, sometimes all the files from that folder will have the visible name very short, showing (...)

Please take a look at an short illustration here, it tells the story better than me:
https://imgur.com/TdLr8D3

Edit: I've reproduced the error with 1.0.2 and 1.0.3 and I've uploaded the movie also into the issue

https://user-images.githubusercontent.com/63467346/148592983-0134c058-329f-45be-b507-5085aa4cc931.mp4

**Comment by Alexey-T** [comment]
In the #1565, I gave steps to reproduce this bug. If it is the same bug.

**Comment by alexx2000** [comment]
It is already fixed in the latest version.
