### ISSUE TITLE
Loading favorites occastionally causes access violation

### ISSUE THREAD

**Issue by bertradio** [doublecmd/doublecmd#322]
I am running beta 1.0.3 build 68 under Linux Mint 20.3. I have a continuing issue from past versions of doublecmd. I have set up some favorite tabs to be my default. Occasionally when I try to load tjem shortcut, I get an access violation. Here is my error log. 

`
--------------- 08-01-2022, 06:04:54 ---------------
| DC v1.0.3 beta Rev. 68 -- x86_64-Linux-gtk2
| Linux Mint 20.3 Una -- GTK 2.24.32 | PID 153314
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $0000000000433265 in /home/bert/bin/doublecmd/doublecmd
  $00000000004844D9 line 929, column 31 of lclproc.pas in /home/bert/bin/doublecmd/doublecmd
  $000000000062D9C6 line 1575, column 26 of include/canvas.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005E299F line 63, column 3 of include/controlcanvas.inc in /home/bert/bin/doublecmd/doublecmd
  $000000000043326B in /home/bert/bin/doublecmd/doublecmd
  $000000000063C28E line 72, column 3 of include/speedbutton.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000004A1006 in /home/bert/bin/doublecmd/doublecmd
  $0000000000606F0E line 5128, column 3 of include/control.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F41A9 line 6644, column 3 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $0000000000609A0E line 40, column 3 of include/customcontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000004E4BEE line 316, column 3 of include/scrollingwincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000008557AC line 201, column 3 of frames/fquicksearch.pas in /home/bert/bin/doublecmd/doublecmd
  $0000000000606F0E line 5128, column 3 of include/control.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F41A9 line 6644, column 3 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000009DF24B line 722, column 3 of fileviews/ufileview.pas in /home/bert/bin/doublecmd/doublecmd
  $0000000000606F0E line 5128, column 3 of include/control.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F41A9 line 6644, column 3 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd

--------------- 08-01-2022, 11:24:13 ---------------
| DC v1.0.3 beta Rev. 68 -- x86_64-Linux-gtk2
| Linux Mint 20.3 Una -- GTK 2.24.32 | PID 192726
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $000000000051FA6F line 3902, column 3 of fmain.pas in /home/bert/bin/doublecmd/doublecmd
  $00000000005F1E9F line 5684, column 14 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F21C3 line 5815, column 7 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F20F4 line 5796, column 14 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F54C3 line 7204, column 38 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $000000000043380A in /home/bert/bin/doublecmd/doublecmd
  $00000000005F1505 line 5411, column 28 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000007B192A line 4845, column 31 of grids.pas in /home/bert/bin/doublecmd/doublecmd
  $00000000007920A8 line 112, column 36 of lclmessageglue.pas in /home/bert/bin/doublecmd/doublecmd
  $0000000000773B05 line 3780, column 68 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $0000000000771355 line 1961, column 43 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $0000000000770315 line 2393, column 12 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000007809F5 line 768, column 13 of gtk2callback.inc in /home/bert/bin/doublecmd/doublecmd
  $00007F44B0EB5B9B in /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

`

**Comment by alexx2000** [comment]
What shortcut and command do you use to load favorite tabs?

**Comment by bertradio** [comment]
Thanks for the quick reply. I reaally love doublecmd -- great work!

For a long time I was using cm_ReloadFavoriteTabs and had the problem. I thought maybe there was an issue with that command so yesterday I changed to using cm_LodTabs with the file Default.tab which is attached. Same problem from time to time. I have assigned the command to the shortcut key ctrl-0 (ctrl-zero). These files come from ~/.config/doublecmd.

I have also attached doublecmd.err. This does not seem repeatable since it does not always happen -- maybe once a day. 

Bert

**Comment by bertradio** [comment]
Just happened again. Any ideas?

Thanks

--------------- 11-01-2022, 07:05:54 ---------------
| DC v1.0.3 beta Rev. 68 -- x86_64-Linux-gtk2
| Linux Mint 20.3 Una -- GTK 2.24.32 | PID 18516
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00000000009F6112 line 1880, column 22 of umaincommands.pas in /home/bert/bin/doublecmd/doublecmd
  $00000000009C68C7 line 230, column 7 of uformcommands.pas in /home/bert/bin/doublecmd/doublecmd
  $000000000083E62B line 1225, column 77 of uhotkeymanager.pas in /home/bert/bin/doublecmd/doublecmd
  $00000000005F1E9F line 5684, column 14 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F21C3 line 5815, column 7 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F20F4 line 5796, column 14 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000005F54C3 line 7204, column 38 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $000000000043380A in /home/bert/bin/doublecmd/doublecmd
  $00000000005F1505 line 5411, column 28 of include/wincontrol.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000007B192A line 4845, column 31 of grids.pas in /home/bert/bin/doublecmd/doublecmd
  $00000000007920A8 line 112, column 36 of lclmessageglue.pas in /home/bert/bin/doublecmd/doublecmd
  $0000000000773B05 line 3780, column 68 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $0000000000771355 line 1961, column 43 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $0000000000770315 line 2393, column 12 of gtk2proc.inc in /home/bert/bin/doublecmd/doublecmd
  $00000000007809F5 line 768, column 13 of gtk2callback.inc in /home/bert/bin/doublecmd/doublecmd
  $00007F2A60275B9B in /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

**Comment by alexx2000** [comment]
No. I don't use this feature so I can't catch this bug.

**Comment by bertradio** [comment]
I have a set of default tabs. I'm looking for a way to use a keyboard shortcut to reload them after I've gone to other folders and tabs.

Is there another way to do this?

**Comment by bertradio** [comment]
I think I may have found the problem. In the hotkey definition it seems tha checking the "Files Panel" box fixed it:

I have now been running this way for days and have not had any crashes.

**Comment by bertradio** [comment]
Just had another crash. So that does not seem to fix it.

**Comment by alexx2000** [comment]
I guess it fixed in the related issue #236.
