### ISSUE TITLE
OneDrive - Synced files from sharepoint issue with AutoSave

### ISSUE THREAD

**Issue by Dennizzzzz** [doublecmd/doublecmd#325]
I have mutiple locations from SharePoint synced with OneDrive to my local drive. This way I can open and edit Excel and Word documents without going to the SharePoint (Office 365) site and work in the browser. 

If I open the files with the Windows Explorer, autosave is turned on in Word and Excel so every change will be uploaded to Sharepoint.

But when I open the files using Double Commander, autosave is turned off, and the files are not synchronized to SharePoint. 
When I chose the option Autosave, i only can chose one of the OneDrive settings but not the right one.

My onedrive settings (image 1):
![image](https://user-images.githubusercontent.com/10248136/149353234-415dc825-913c-4a9b-8fef-3aaee3b72cff.png)

When opening from DC and turn on AutoSave (image 2):
![image](https://user-images.githubusercontent.com/10248136/149353291-fb2f845f-40f7-4fda-9964-6d1d48480e18.png)

The account at number 1 on image 1 is the account at number 2 on image 2.

**Comment by alexx2000** [comment]
Are you execute DC as normal user or as administrator? [Similar problem](https://www.ghisler.ch/board/viewtopic.php?p=409914) in TC.

**Comment by Dennizzzzz** [comment]
As administrator

**Comment by alexx2000** [comment]
Try to execute as normal user. I guess it does not work under administrator due Windows security policy.

**Comment by JustDen1234** [comment]
> Try to execute as normal user. I guess it does not work under administrator due Windows security policy.

Thanks, this works. This would be the first time using Windows that i need to run a program NOT as admin :-D
