### ISSUE TITLE
[improvement] Allow adding multiple extensions (file types) at once

### ISSUE THREAD

**Issue by tukanos** [doublecmd/doublecmd#329]
Allowing to enter multiple extensions at once would be **very** helpful when configuring the "extensions" at "File associations".

For example, if you would press "add" button then you could add something like (each of the extension separated by semi-colon) :
_pdf; epub; mobi; xps; djvu; chm_

This would add all extensions each at separate line, like adding it manually by pressing add/ok buttons.  This could mean substantially faster configuration.

**Comment by alexx2000** [comment]
You can add multiple extensions, for example "txt|log".

**Comment by tukanos** [comment]
> You can add multiple extensions, for example "txt|log".

Ah, missed that. Thank you.
