### ISSUE TITLE
Dark mode? (Windows 10)

### ISSUE THREAD

**Issue by TobiasDev** [doublecmd/doublecmd#33]
Is there anyway we are going to see a dark-mode added to Double Commander? The current bright white is kind of strong when I'm working in the middle of the night on something. :)

**Comment by alexx2000** [comment]
https://doublecmd.sourceforge.io/forum/viewtopic.php?p=32017#p32017

**Comment by TobiasDev** [comment]
Ah, thanks! :)

**Comment by kirill-shtrykov** [comment]
I'm sorry, but was this the [one and only](https://github.com/doublecmd/doublecmd/releases/download/v1.0.1/doublecmd-1.0.1.x86_64-win64-qt5.dark.7z) act of unprecedented generosity?

**Comment by WhiteChairFromIkea** [comment]
> I'm sorry, but was this the [one and only](https://github.com/doublecmd/doublecmd/releases/download/v1.0.1/doublecmd-1.0.1.x86_64-win64-qt5.dark.7z) act of unprecedented generosity?

Every qt snapshot is dark, updated yestertay (April 9)

**Comment by leao-nardo** [comment]
it have it already by now. but i think is to clear graysh . i change the panel background color to black to make it better - that really should be the default
