### ISSUE TITLE
Qt per-monitor Scaling got broken with newest version of doublecmd

### ISSUE THREAD

**Issue by vn971** [doublecmd/doublecmd#332]
Qt per-monitor Scaling broke after the newest update. Previously, I could set the environment variables:
```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS="eDP-1=1;DP-1=2"
```
, and Doublecmd + Qt would pick it up, meaning it would use scaling factor of 1 on my (smaller) notebook monitor, and scaling factor 2 on my external HiDPI monitor.

After the newest upgrade, this behavior is broken. I don't remember the previous version, but the new version is `1.0.3 beta`:
```
Double Commander
Version: 1.0.3 beta
Revision: 68
Commit: b3740938d
Build date: 2022/01/09
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Arch Linux

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1
```

Hard-setting the desired Scale for all monitors simultaneously still works, e.g. the app responds to the environment variable QT_SCALE_FACTOR
```
export QT_SCALE_FACTOR=2
```

Any thoughts on why that could have happened? Any ideas?

P.S. Nice to see Double Commander being well :tada: , and moving to a new platform (GitLab would also be a good choice!)
Thanks for continuing to build this!
P.P.S. If there'll be donation options such as a European bank transfer or some cryptocurrencies to support the project, count me in :)

**Comment by alexx2000** [comment]
I think the reason is the new Lazarus version 2.2.0. It was updated 2022-01-09.

**Comment by vn971** [comment]
@alexx2000 interesting, it doesn't say much about Qt and nothing scaling.. :thinking:
( I was looking here https://wiki.freepascal.org/Lazarus_2.2.0_release_notes )

**Comment by vn971** [comment]
// Still broken unfortunately. I hoped it'll get fixed with some Qt/Lazarus releases, but it has not.
// Not really asking anything specific at the moment either, just reporting the status quo..

**Comment by alexx2000** [comment]
#575
