### ISSUE TITLE
Feature request : column with lifetime

### ISSUE THREAD

**Issue by gle2n** [doublecmd/doublecmd#34]
Hi,

the idea of the feature is to be able to configure a column to show **how old** a file is (since last saved for example).
For now, you can use [DC().GETFILETIME{}] to show the date in your default format, but sometimes it is more efficient to compare "age" instead of "birth" of files.

An additional feature request (wich must be harder to implement) is the possibility to use file coloring scheme like it is already possible, but only to a specific(s) column(s).

Combining those two, you could color the "age" colomn according to it's age **and** following other coloring schemes.

Thanks for the great work and have a nice day

-Glenn

**Comment by alexx2000** [comment]
Hi, such function can be added via WDX-plugin. Plugin [Age](http://totalcmd.net/plugring/Age.html) has similar function. It is possible to write simple plugin using Lua.

**Comment by gle2n** [comment]
Hi,
Is it possible to use a lua script directly in a column "content" field or does it have to be compiled as wdx before ?
If so, how must it be entered ? someting like [Plugin(/path/to/lua-script.lua).function{}] ?
Thanks

**Comment by alexx2000** [comment]
It should be added as usual wdx-plugin via options. After this it will appear in the custom columns settings.
You can try agewdx.lua plugin from this post https://doublecmd.sourceforge.io/forum/viewtopic.php?p=32307#p32307

**Comment by gle2n** [comment]
thanks, I managed to get exactly the result I wanted by forking the link you provided :)
But they're still one little bug that's a bit itchy (and I don't know if it comes from agewdx.lua or my added code) ;
Sometimes (~2/3 of the times), when launching doublcmd, I get a double error and the column stay blank. This seems not to happen when launching in admin mode... Only tested on windows 10.
Thanks

**Comment by Skif-off** [comment]
@gle2n 
> I get a double error

Which errors?

> my added code

Show please.

**Comment by gle2n** [comment]
Hi, sorry for my french ^^ (working PC is in french)

> Erreur:
> External exception E24C4A02
> 
> Merci de rapporter cette erreur sur le "bug tracker" avec une description de ce que vous étiez en train de faire ainsi que le fichier suivant :
> \path-to-dblcmd-\doublecmd.err
> 
> Cliquez Ignorer pour continuer ou Arrêter pour quitter le programme

inside this error log file is :


> --------------- 05-11-2020, 10:54:10 ---------------
> | DC v0.9.9 beta Rev. 9478M -- x86_64-Win64-win32/win64
> | Windows 10 1803 x86_64 | PID 6460
> Unhandled exception: EExternalException: External exception E24C4A02
>   Stack trace:
>   $00007FF8010DA388 in C:\Windows\System32\KERNELBASE.dll
>   $0000000066D86559 in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $0000000066D8683B in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $0000000066D868DD in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $0000000066D86A43 in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $0000000066D894A3 in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $0000000066D8F6C7 in P:\Applications\doublecmd 0.9.9\lua5.1.dll
>   $00007FF7B02A35AC line 389, column 3 of uluapas.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02A3656 line 403, column 48 of uluapas.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B026ADFC line 936, column 3 of uwdxmodule.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B026936C line 522, column 15 of uwdxmodule.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02853F7 line 428, column 27 of ufilefunctions.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B027EF1C line 680, column 49 of filesources/filesystem/ufilesystemfilesource.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02C22B9 line 892, column 102 of fileviews/ufileviewworker.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02C077D line 346, column 9 of fileviews/ufileviewworker.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02C07E0 line 359, column 3 of fileviews/ufileviewworker.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe
>   $00007FF7B02C761C line 155, column 17 of ufunctionthread.pas in P:\Applications\doublecmd 0.9.9\doublecmd.exe

code from the plugin is :

```
-- agewdx.lua (cross-platform)
-- 2020.10.24
--[[
Returns age (the date of the last modification will be used):
number of seconds, minutes, hours, days, weeks, months or years
Notes:
- it will be the largest integer smaller than or equal to result;
- returns nothing if the current time is less than the file time (i.e. result should be >= 0).
]]

local atd = {0, 0, 0}
local filename = ''

function ContentGetSupportedField(FieldIndex)
	if FieldIndex == 0 then
		return 'Age (modif. date)', 'seconds|minutes|hours|days|weeks|months|years|multi', 8
  	end
  	return "", "", 0
end

function ContentGetDefaultSortOrder(FieldIndex)
	return 1; --or -1
end

function ContentGetDetectString()
	return 'EXT="*"'
end

function ContentGetValue(FileName, FieldIndex, UnitIndex, flags)
	if FieldIndex > 0 then return nil end
	if filename ~= FileName then
		local h, fd = SysUtils.FindFirst(FileName)
		if h == nil then return nil else SysUtils.FindClose(h) end
		if fd.Attr < 0 then return nil end
		if math.floor(fd.Attr / 0x00000004) % 2 ~= 0 then return nil end
		--if math.floor(fd.Attr / 0x00000010) % 2 ~= 0 then return nil end
		--if math.floor(fd.Attr / 0x00000400) % 2 ~= 0 then return nil end
		atd[1] = os.time()
		atd[2] = fd.Time
		atd[3] = atd[1] - atd[2]
		filename = FileName
  	end
	if atd[3] == 0 then
		return 0
  	elseif atd[3] > 0 then
		if UnitIndex == 0 then
	  		return atd[3]
		elseif UnitIndex == 1 then
	  		return math.floor(atd[3] / 60)
		elseif UnitIndex == 2 then
	  		return math.floor(atd[3] / 3600)
		elseif UnitIndex == 3 then
	  		return math.floor(atd[3] / 86400)
		elseif UnitIndex == 4 then
	  		return math.floor(atd[3] / 604800)
		elseif (UnitIndex == 5) or (UnitIndex == 6) then
	  		local ct = os.date('*t', atd[1])
	  		local ft = os.date('*t', atd[2])
	  		local cy = ct.year - ft.year
	  		if UnitIndex == 5 then
				if cy == 0 then
		  			return ct.month - ft.month
				else
		  			return cy * 12 + ct.month - ft.month
				end
	  		else
				return cy
	  		end
		elseif UnitIndex == 7 then
			if (atd[3] < 365.25*24*60*60) then -- < 1 year
				if (atd[3] < 30.4375*24*60*60) then -- < 1 month
					if (atd[3] < 7*24*60*60) then -- < 1 week
						if (atd[3] < 24*60*60) then -- < 1 day
							if (atd[3] < 60*60) then -- < 1 hour
								return tostring(math.floor(atd[3]/60)).." '"; -- < 1 hour
							end
							return tostring(math.floor(atd[3]/60/60)).." H"; -- < 1 day
						end
						return tostring(math.floor(atd[3]/60/24/60)).." D"; -- < 1 week
					end
					return tostring(math.floor(atd[3]/60/24/7/60)).." W"; -- < 1 month	
				end
				return tostring(math.floor(atd[3]/60/24/30.4375/60)).." M"; -- < 1 year
				-- local output = tostring(atd[3])
				-- return 	"a";		
			else
				return ">"..tostring(math.floor(atd[3]/60/24/365.25/60)).." Y"; -- return string
				-- return math.floor(atd[3])
			end
		end
  	end
  	return nil
end
```

I added the part where UnitIndex == 7

**Comment by Skif-off** [comment]
Hmm... Looks fine, at first sight...
Don't mix string and numeric values, because you won't be able to use file search with plugin normally (expressions like "Age in months > 2"). Also very many mathematics: will need to calculate every time for each file.

I added two additional fields to `agewdx.lua`: "Float", like your, and "Today" from my old `modiftimeistodaywdx.lua`. Can you try?

**Comment by gle2n** [comment]
Tested your version and the "Float" field works like a charm. Though I prefer when the "time dimension" is 1 character long (', H, D, W, M, Y) so all the numeric are right aligned (I use a mono font especially for that^^).
As for te file search, I don't mind it, I still use DC().GETFILETIME() for that.
Thanks alot !

**Comment by Skif-off** [comment]
> Though I prefer when the "time dimension" is 1 character long (', H, D, W, M, Y) so all the numeric are right aligned

Yes, this is useful, fixed. But I didn't use `"` and `'` because this characters for a plane angles, not for time.
