### ISSUE TITLE
Some options are unreachable on the copy / move (F5/F6)

### ISSUE THREAD

**Issue by israelio** [doublecmd/doublecmd#340]
On Mac using v1.1.0 alpha build 10045 2022/01/06

When one click on the options button you cant get to the options in the bottom, the window is not resizable nor can scroll up/down the options there.

![image](https://user-images.githubusercontent.com/2522999/151866307-441e8eeb-7578-4cf1-b8c6-eb682822e906.png)

![image](https://user-images.githubusercontent.com/2522999/151866673-acaf36f9-0f18-4c2d-a096-734399ea67cf.png)

**Comment by alexx2000** [comment]
Lazarus bug.

**Comment by israelio** [comment]
@alexx2000 The resizing of the bottom part of the window or just expending is a little is not fixable ???

**Comment by alexx2000** [comment]
It should be fixed in the Lazarus. This bug exists only under macOS with LCL-Cocoa.
