### ISSUE TITLE
Unable to toggle off reserve space for good

### ISSUE THREAD

**Issue by israelio** [doublecmd/doublecmd#341]
On the options windows at the copy / move there is an option to toggle off the Reserve space - which slows down heavily the copy operation. It works fine but i am missing to turn it off for good via configuration or once and for all... toggle it off once and let it be remembered and not have to press the option each time and turn it off.

![image](https://user-images.githubusercontent.com/2522999/151867199-ecea48f9-0425-49d9-9059-145021056683.png)

Using Mac build v1.1.0 alpha build 10045 2022/01/06

**Comment by alexx2000** [comment]
Really this dialog has "save" button (which saves current options as default):

![Untitled](https://user-images.githubusercontent.com/13401398/151914709-e1ee4b41-f93e-4473-a954-dd89756f9b25.png)

but it invisible due #340

**Comment by israelio** [comment]
For the record - Mac Users ... open the option tab, click shift+tab which will bring you to the unreachable Save there option as default then Space and later enter and click on the start.... it will save the options as default 
This is a TEMP solution and from my opinion it should be fixed... as it is fixable

**Comment by j2969719** [comment]
>as it is fixable

how exactly?
