### ISSUE TITLE
Is it possible to sponsor this project somehow? 

### ISSUE THREAD

**Issue by nutnutwin** [doublecmd/doublecmd#344]
Previously I asked here
https://doublecmd.h1n.ru/viewtopic.php?f=7&t=7075&p=34819&hilit=nutnutwin#p34819
about making a donation to this project
Regrettably I know no Russian, and I see there are other guys who wants to buy you a coffee

---

I am not very familiar with Github sponsor, but I seem to able to support other developers like
https://github.com/sponsors/ransome1

---

Maybe Patreon is a good idea too? 

✨I simply cannot over-state how this app has helped me in my life and work. 

@alexx2000 

Thank you.

**Comment by nutnutwin** [comment]
Seems a little hard now to make donation

In case you need anything please let me know. @alexx2000

**Comment by ags1234** [comment]
@nutnutwin: how was this resolved? Did you donate?

**Comment by nutnutwin** [comment]
@ags1234 
regrettably no. 
I received no response, and I don't understand Russian. 

In case Alex need I can pay monthly through Paypal

**Comment by ags1234** [comment]
If I recall correctly, this is not the first time he refuses donations. I wonder why.

**Comment by nutnutwin** [comment]
> If I recall correctly, this is not the first time he refuses donations. I wonder why.
> 
> Maybe some extra money would be a motivation to fix some bugs / complete some code.

Maybe he prefer to work at own pace? 
Simply want to show my gratitude for the work
