### ISSUE TITLE
Powertoys Rename error message

### ISSUE THREAD

**Issue by fossist** [doublecmd/doublecmd#345]
![AfraidSpadefoot-TF3AxKcc4Qg2](https://user-images.githubusercontent.com/86028957/152660543-7dc0511f-8223-4cb2-a351-00e325c3f6d9.gif)

**Comment by alexx2000** [comment]
Really it is a PowerToys bug. PowerToys shell extension always [returns E_FAIL](https://github.com/microsoft/PowerToys/blob/2cdf6f9cc086ef88ac540b2dc3999cc24fdf00c3/src/modules/powerrename/dll/PowerRenameExt.cpp#L121) error code. It should [return S_OK](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-icontextmenu-invokecommand#return-value). But I think it's safe to ignore E_FAIL in this case. I guess Explorer ignore it.
