### ISSUE TITLE
Too long timeout in HotDir Menu

### ISSUE THREAD

**Issue by jerry-ne** [doublecmd/doublecmd#347]
**Describe the bug**
When I have saved samba share (folder) in Favorites Menu and path is currently not accessible (VPN is not connected). In Doublecmd I clicked on asterisk button and wait around 90 seconds **for timeout**. Menu is not shown. Meantime app is frozen (not responding). I must click once again on asterisk button (after timeout)- Menu is shown immediately. 
Wait 2-x minutes and hit asterisk button again, once again I have 90 seconds timeout.

When I click on this non-accessible item (path) in Menu, again around 90 seconds timeout. Why not 10 seconds? Again when I wait on finishing this timeout, app is still frozen- not responding.

**Expected behavior**
Timeout around 10 seconds, not 90. 

Or why you test path before Menu is shown? Expected behavior is test path when I click on item in this Menu.

**Desktop (please complete the following information):**

  * OS: Win 10, 21H1
  * doublecmd version: 1.0.4 beta, rev84, 2022-02-05 (installed from github, msi x64)

**Comment by alexx2000** [comment]
Should be fixed in the latest version.
