### ISSUE TITLE
FYI: doublecmd.dark chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [doublecmd/doublecmd#348]
I have [published](https://github.com/majkinetor/au-packages/tree/master/doublecmd.dark) dark version of the doublecmd and will maintain it in the future. The package update is automatic which means that it follows GitHub releases with less then 1 day latency. All historic versions are kept and will always work as DC is embedded into the package.

- https://community.chocolatey.org/packages/doublecmd.dark

You can install it via command: `choco install doublecmd.dark`

Related to this, I also maintain [a collection](https://community.chocolatey.org/packages?q=tag%3Atcplugin) of Total Commander plugins that can be used with DC more or less fully and [1 theme](https://community.chocolatey.org/packages/dcc-unlit). Plugins can be cherry picked individually or installed all via single virtual pacakge [tcp](https://community.chocolatey.org/packages/tcp#dependencies). For example `cinst doublecmd.dark tcp` will install DC and ~20 plugins; later, all plugins can be updated to latest versions via single command. Anyone can write and publish totalcmd package using this system trivially easy if they depend on [tcps](https://community.chocolatey.org/packages/tcps) package.

**Comment by majkinetor** [comment]
> Why? Standard size (i.e. 16, 24, 32) usually looks better.

I can't remember, probably looked the best at the time in both TC and DC (since there is equivalent theme for TC). Its parameter anyway, you can specify your own during install: `cinst dcc-unlit --params "/IconSize: 24"`

> Maybe DC will automatically choose a language?

Its semi-standard to use english by default on Chocolatey package. I also made this mostly for myself, I don't like it when it uses Serbian. Its a theme, and as such its opinionated. I could add this as param if you want to specify your own language.

**Comment by Skif-off** [comment]
I understood, but in any case 20 is not standard: have you monitor with HiDPI and/or 125%/150% scaling? I mean that the proposed value as default is not universal :)

> Its semi-standard to use english by default on Chocolatey package.

I did not find recommendations, but it sounds strange. I think that this part of your preferences is not like the value that will suitable for a majority of users.


P.S. 

> I also made this mostly for myself, I don't like it when it uses Serbian.

```bash
$ export LANG=en_US && msgfmt --check --statistics doublecmd.sr.po
1743 translated messages, 286 fuzzy translations, 1096 untranslated messages.
```

Serbian translation is Serbian by 55-60% only :) Unfortunately.

**Comment by majkinetor** [comment]
> Serbian translation is Serbian by 55-60% only :) Unfortunately.

That is irrelevant. English only in my case :)

> I think that this part of your preferences is not like the value that will suitable for a majority of users.

Its also irrelevant. The system is setup you can create your own ting in a minute.

Theme is unimportant, if you like it use it, if not stick with what you want. Plugins are most relevant since this is the only way out there to automate installation and keep it up to date. Also it makes it more stable since recently we had several major DOS moments on Totalcmd.net so all plugins were not available. This didn't affect chocolatey packages since they contain the plugins.
