### ISSUE TITLE
sha256 checksum file requires an extra space for checking

### ISSUE THREAD

**Issue by tukanos** [doublecmd/doublecmd#349]
I'm usually checking checksum files via `shaXXXsum` command.  Today I found out that DC is able to check the file too, but is requiring extra space between the checksum and file which in my eyes is a **bug**.

The file for sha256sum:
`AC7F7862E685C7A7D9826A58EA32D183D4893FCC8F8FD6D900C9769A987E77F0< space >postsignum_qca4_root.cer`

The file for DC must be (otherwise the first character is missing from the file name):
`AC7F7862E685C7A7D9826A58EA32D183D4893FCC8F8FD6D900C9769A987E77F0< space >< space >postsignum_qca4_root.cer`

The picture is worth thousand of words:

![sha256sum_vs_double_commander](https://user-images.githubusercontent.com/731154/153558686-f114c281-a524-4e82-b8a5-6b093321e969.png)

**Comment by alexx2000** [comment]
I checked md5sum/sha256sum/sha512sum, it creates checksum with two spaces. Quote from md5sum [documentation](https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html):
> For each file, ‘md5sum’ outputs by default, the MD5 checksum, a space, a flag indicating binary or text input mode, and the file name. Binary mode is indicated with ‘*’, text mode with ‘ ’ (space). Binary mode is the default on systems where it’s significant, otherwise text mode is the default. The cksum command always uses binary mode and a ‘ ’ (space) flag. 

So checksum file with one space is not standard. But sha256sum can verify it too.

**Comment by tukanos** [comment]
Thank you for the patch.  I wanted to send a patch for this one, but I failed to setup the Lazarus IDE correctly.  I don't normally use it.  I will have to get into it once again.

**Comment by ags1234** [comment]
@tukanos: use fpcupdeluxe [here](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases). It's a very useful program to install Lazarus and free pascal compiler.

**Comment by tukanos** [comment]
> @tukanos: use fpcupdeluxe [here](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases). It's a very useful program to install Lazarus and free pascal compiler.

Thank you.  Will check it out.  The DoubleCMD is quite large project.  It is tricky to have everything setup correctly.
