### ISSUE TITLE
[minor] port 631

### ISSUE THREAD

**Issue by pwn0r** [doublecmd/doublecmd#358]
more feature than a bug I guess. 
But **linux** version of doublecmd tries to connect to port  631. Actually twice, first ip4, then ip6. Both localhosts, i.e. 127.0.0.1 and then ::1. 

Funny thing happens if you deny this connection, doublecmd freezes on start. Not forever, for about 1-2 minutes, then starts regardless.  Can we reduce this timeout?

**Comment by alexx2000** [comment]
DC itself does not connect to this or any other port. I guess some low level library can do it.
