### ISSUE TITLE
"Go to root directory" button doesn't work for tabs "Locked with Directory Changes Allowed" tab option

### ISSUE THREAD

**Issue by jozefdurina** [doublecmd/doublecmd#359]
Latest published version - Double Commander v1.0.4 and also previous versions. 

When I am nested in directory tree deeper and have my tab "Locked with Directory Changes Allowed" and click "Go to root directory" button no jump to root directory happen. This is not expected. 

Other Tab options (Normal, Locked, Locked with Directories Opened in New Tabs) in combination with the "Go to root directory" button works as expected. 

This behaviour is easily reproducible ... 

Happy user Jozef

![01-Locked with Directory Changes Allowed](https://user-images.githubusercontent.com/89970971/154646720-a331c5c9-18bf-48ca-b00c-25607698c6a5.png)
![02-Go to root directory](https://user-images.githubusercontent.com/89970971/154646725-2455272d-fc6b-489c-956b-7e39a85ede4e.png)

**Comment by alexx2000** [comment]
In the locked tabs "Go to root directory" works differ, it go to locked path.

**Comment by jozefdurina** [comment]
Thank you! 
Anyway I compared it with Total Commander's (TC's) behaviour and is resembling to Double Commander (DC). TC put small exclamation mark to the left of asterix on tab with tab-option "Locked, but directory changes allowed" when you leave locked directory. Clicking on the "\" backslash button will lead you to Locked directory (same as DC).
