### ISSUE TITLE
Reading of tar archives with files larger than 4 and 8GiB fails

### ISSUE THREAD

**Issue by malind** [doublecmd/doublecmd#36]
I noticed that the tar plugin for double commander has issues with archives with files larger than 4 and 8GiBs.

The 8 GiB limitation is that is shows the wrong size (and I assume, will unpack it wrong) and comes from that tar encodes size etc as a 12 character ascii string with octal numbers. There is a star extension from 2001 that adds a base 256 mode, but the tar implementation in fp archive does not support it. See https://en.wikipedia.org/wiki/Tar_(computing).

The 4GiB issue is that is does not show files later in the archive if a file is > 4GiB and comes from seeks > 32bit. I found an alternative api with a bit of googling that supports 64bit arguments. See https://www.freepascal.org/docs-html/rtl/classes/tstream.seek.html.

I fixed both issues in the attached diff, but with the caveat that I have never programmed in pascal before, so this is just from looking at the sorrounding code and a bit of googeling. 

I did not find any contribution guidelines, but you can take this issue report as permission to use and/or re-license my changes to double commander source file plugins/wcx/zip/src/fparchive/abtartyp.pas freely. 

[tarfix.diff.txt](https://github.com/doublecmd/doublecmd/files/5435476/tarfix.diff.txt)

**Comment by alexx2000** [comment]
Thanks, patch merged. Line `Result := Ord(Oct[0]) - 128;` is useless, it is always zero in this case.

**Comment by malind** [comment]
Right, that looks like a bug in my patch. The if statementen should probably have been something like "if ((Ord( Oct[0] ) and 128) = 128) then begin" (or just Ord(Oct[0]) >= 128, perhaps?). 
But with 12 bytes in the field it would need a 10*26 bytes large file to need those last 7 bits, and I really hope tar is obsolete by then :P, so I think your change is fine as as-is.

**Comment by malind** [comment]
Oh, with the change in [r9576], it probably make sense to put the (Result := Ord(Oct[0]) - 128) back (or change -128 to (and 128) I guess.

**Comment by alexx2000** [comment]
Really it should be something like [this](url=https://github.com/libarchive/libarchive/blob/12caafda8b6e1b1baa0aa492a37c73f02fee122b/libarchive/archive_read_support_format_tar.c#L2687)

**Comment by malind** [comment]
Yes, that looks like it handles negative values, overflow etc as well.

**Comment by alexx2000** [comment]
Rewrote using algorithm from libarchive.
