### ISSUE TITLE
Access violation error when search/find in Quick View panel

### ISSUE THREAD

**Issue by TuzeszSzarkany** [doublecmd/doublecmd#364]
Hi,

I'm getting an "Access violation" error when trying to search for a text in the Quick View panel.

How to reproduce:

1. Navigate to a text file and switch to Quick View panel (Ctrl + Q)
2. Click inside the QV panel and press Ctrl + F (Find)

Error details:

--------------- 22-02-2022, 22:24:30 ---------------
| DC v1.1.0 alpha Rev. 10123 -- x86_64-Win64-qt5
| Windows 10 Dev x86_64 -- Qt 5.13.0, libQt5Pas 5.6.1 | PID 12928
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $0000000061BD3690 in C:\Users\seges\doublecmd\Qt5Gui.dll
  $0000000061BE9917 in C:\Users\seges\doublecmd\Qt5Gui.dll
  $00007FF6049F5CC0 line 2762, column 25 of qt5/qtobjects.pas in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF6049F5E7C line 2839, column 3 of qt5/qtobjects.pas in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF60493CF01 line 2264, column 37 of qt5/qtwinapi.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604948FDF line 887, column 13 of qt5/qtlclintf.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604913AD4 line 152, column 22 of include/lclintf.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF6048AC9E7 line 1368, column 3 of include/canvas.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604D16B15 line 2026, column 5 of viewercontrol.pas in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604D15D8F line 1714, column 9 of viewercontrol.pas in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604D13155 line 711, column 14 of viewercontrol.pas in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF60496E612 line 123, column 5 of include/customcontrol.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604958473 line 4873, column 9 of include/wincontrol.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF60495C215 line 6836, column 23 of include/wincontrol.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF60496E527 line 103, column 28 of include/customcontrol.inc in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF6047D4901 in C:\Users\seges\doublecmd\doublecmd.exe
  $00007FF604965431 line 2282, column 26 of include/control.inc in C:\Users\seges\doublecmd\doublecmd.exe

Thanks,
TuzeszSzarkany

**Comment by alexx2000** [comment]
Works fine with latest snapshot.
