### ISSUE TITLE
Links in the Double Commander UI open Firefox instead of the default browser

### ISSUE THREAD

**Issue by bviktor** [doublecmd/doublecmd#366]
Such as Help / Contents or Visit Double Commander Website, or the link on the About dialog, they all open in Firefox instead of my default browser. None of my other programs do this, only Double Commander. I checked, Firefox is not a default handler for anything.

```
Double Commander
Version: 1.0.4 beta
Revision: 84
Commit: a1d58d4dd
Build date: 2022/02/05
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H2 x86_64
```

Apparently another bug in OS detection too, because I'm on Windows 11. Opening another ticket for that.

**Comment by alexx2000** [comment]
DC use Lazarus function to open default browser. So it is a Lazarus problem.

**Comment by bviktor** [comment]
Guess what, I did not make any changes to settings, but it works fine now. If I had to guess, it's because of this update:

[Microsoft is finally making it easier to switch default browsers in Windows 11](https://www.theverge.com/2022/3/29/23001277/microsoft-windows-11-default-browser-new-options)
