### ISSUE TITLE
OS detection is unaware of Windows 11

### ISSUE THREAD

**Issue by bviktor** [doublecmd/doublecmd#367]
Help / About:

```
Double Commander
Version: 1.0.4 beta
Revision: 84
Commit: a1d58d4dd
Build date: 2022/02/05
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H2 x86_64
```

`winver`:

![image](https://user-images.githubusercontent.com/5798552/155900190-a71678ca-015c-43bb-808e-59bf936fcb60.png)

**Comment by Skif-off** [comment]
It's interesting, DC uses [OSVERSIONINFOA](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-osversioninfoa) structure and `dwMajorVersion`, but [here](https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version) we can see

| Operating system | Version number |
|---|---|
| Windows 11 | 10.0* |
| Windows 10 | 10.0* |

O_o

I found that need to check `dwBuildNumber`: if >= 22000 then Win11. This is strange :)

**Comment by alexx2000** [comment]
Yes, Microsoft did not increase version number. All known functions returns Windows 10, also system files has version 10. Even console command `ver` returns `Microsoft Windows [Version 10.0.22000.493]`. Only build number can be used to detect Windows 11 indirectly.

**Comment by bviktor** [comment]
What a mess :) I found this:

https://stackoverflow.com/questions/69038560/detect-windows-11-with-net-framework-or-windows-api

Which echoes your findings. So I guess that's the way to go. But still stupid on MS' part...
