### ISSUE TITLE
GPG issue

### ISSUE THREAD

**Issue by edmundlaugasson** [doublecmd/doublecmd#37]
At https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-gtk you have (Ubuntu -> xUbuntu 20.04):
```
echo 'deb http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:Alexx2000.list

curl -fsSL https://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:Alexx2000.gpg > /dev/null
```
I got an error, when apt-get update:
```
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/home:Alexx2000.gpg'
gpg: keyblock resource '(null)': General error
```

I suggest to remove old ones and add fixed ones:
```
rm -fr /etc/apt/sources.list.d/home:Alexx2000.list /etc/apt/trusted.gpg.d/home:Alexx2000.gpg

echo 'deb http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/doublecmd.list

curl -fsSL https://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/doublecmd.gpg > /dev/null
```
Basically this means, that colon in filename is not a good idea.

**Comment by alexx2000** [comment]
It is a build.opensuse.org bug and should be reported there.
See also https://doublecmd.sourceforge.io/mantisbt/view.php?id=2520

**Comment by edmundlaugasson** [comment]
> It is a build.opensuse.org bug and should be reported there.

Where exactly? Looks like https://github.com/openSUSE has 471 repositories for now. Perhaps https://github.com/openSUSE/software-o-o ? Perhaps there is already reported that filename issue, so it can be voted upwards in todo list. Found https://github.com/openSUSE/software-o-o/issues/86 but it might not be correct one.

> See also https://doublecmd.sourceforge.io/mantisbt/view.php?id=2520

Yes, I've used Mantis but GitHub is much more usable.

**Comment by alexx2000** [comment]
I guess

- https://github.com/openSUSE/open-build-service
- https://forums.opensuse.org/forumdisplay.php/692-Open-Build-Service-(OBS)

**Comment by edmundlaugasson** [comment]
Well, let's hope it's on right place, [filed a bug](https://github.com/openSUSE/open-build-service/issues/10348)

**Comment by alexx2000** [comment]
Fixed upstream.
