### ISSUE TITLE
Unnecessary GTK Library Loading in Windows

### ISSUE THREAD

**Issue by Skibicki** [doublecmd/doublecmd#374]
GTK+ libraries are loaded by Double Commander. Can Double Commander prevent this? Can GTK+ be restricted to software requiring it?

Double Commander
Version: 1.1.0 alpha
Revision: 10133
Commit: 9b479b805
Build date: 2022/03/08
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 8.1 x86_64

**Comment by alexx2000** [comment]
DC does not load GTK libraries. DC can load librsvg library for SVG support (if it available in the %PATH%), which depends on libglib.

**Comment by Skibicki** [comment]
Last year, I noticed Double Commander crashing when right-clicking to open the context menu and this was after installing GTK+ for Weasyprint. The crashes stopped when I uninstalled GTK+.

This is the installer used.
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

### ListDLLs and Process Hacker show many files loading, so I tried searching only one.
Example:
Listdlls64.exe -d libcairo-2.dll
doublecmd.exe pid: 1836
Command line: "C:\Other_Programs\Double Commander_Snapshot\doublecmd.exe"

Base                Size      Path
0x00000000cdfd0000  0x110000  C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll

### doublecmd.exe Properties:

![shot-20220314T044646](https://user-images.githubusercontent.com/3906813/158138297-1fdfd318-1c54-4b88-8c2c-ee4941fc6404.png)

**Comment by alexx2000** [comment]
Yes, librsvg uses libcairo to render SVG.

**Comment by Skibicki** [comment]
I understand, and the crashes appear to be fixed with the latest versions of everything.
Thank you.
