### ISSUE TITLE
Windows DoubleCommander 1.0.4 + QT5

### ISSUE THREAD

**Issue by mtlmarko89** [doublecmd/doublecmd#376]
Hi there,

I used the DoubleCommander 1.0.3 with QT5 for dark mode and it worked perfectly. Now I have tried the update to 1.0.4 (unpacking and replacing existing files), and the QT5 libraries are still available, but the dark mode does not work.

Were there problems using QT5 so that this functionality has been disabled again? Unfortunately, I have not found new ZIP for Windows with the QT5, or did I do anything wrong with the update?

I'm sorry if I have overlooked a corresponding issue, I had tried to find an existing issue, but found everyone not really belonging.

I am also sorry for my bad English!

**Comment by alexx2000** [comment]
I did not release 1.0.4 Qt5 version because it have several unfixable problems. So I moved it back to alpha state.

**Comment by mtlmarko89** [comment]
Ok, thank you for the information. So is, as suspected. Then this issue could be closed. Nevertheless, I hope that the unfixable problems can be fixed at a time. Thank you for the good work at the DoubleCommander! I like this tool.
