### ISSUE TITLE
Filenames in different language aren't shown

### ISSUE THREAD

**Issue by anodynos** [doublecmd/doublecmd#38]
On Kubuntu x64 20.04 & Double Commander 0.9.9 beta, all filenames containing Greek characters (I tried creating files on Linux & on WIndows) are completely hidden. (I noticed the problem on 0.9.8 also, and I upgraded just in case, so its not new to 0.9.9.)

I can see the files fine with `$ ls` and on Dolphin but not on Double Commander...! 

I have Show Hidden & System files enabled, just in case...

![image](https://user-images.githubusercontent.com/856453/97359130-f344af00-18a4-11eb-9665-aabb4b03426d.png)

**Comment by anodynos** [comment]
Also added as https://doublecmd.sourceforge.io/mantisbt/view.php?id=2546

**Comment by alexx2000** [comment]
Check your locale settings, see:
https://doublecmd.sourceforge.io/forum/viewtopic.php?f=6&t=6038&p=29503
https://doublecmd.sourceforge.io/forum/viewtopic.php?f=5&t=5898&p=28651

**Comment by anodynos** [comment]
Thank you very much @alexx2000 for your response and most of all for this AMAZING software - I am so addicted to it!

So, it worked when I unchecked **Detailed Settings** from the **Formats** app (on Kubuntu 20.04).

But when I have changed (as below), it breaks. 

![image](https://user-images.githubusercontent.com/856453/97608604-3c1e7400-1a1b-11eb-8286-072fb6a3e0b9.png)

In both cases 

```
$ locale
LANG=en_UK.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

The weird thing is I get this behavior only on Double Commander :-(

Konsole, Dolphin & Krusader all work fine 

![image](https://user-images.githubusercontent.com/856453/97609210-fd3cee00-1a1b-11eb-9245-ab1a56b1942a.png)

Is this something that can be fixed?

**Comment by alexx2000** [comment]
Try with version from latest snapshot, I hope it should be better.

**Comment by anodynos** [comment]
Thank you @alexx2000 - I can only see **MS Windows 32/64 bit | Mac OS X >= 10.11 32/64 bit** on snapshots, not Linux version ;-(

**Comment by Skif-off** [comment]
@anodynos , see [FAQ 2.2](http://doublecmd.github.io/doc/en/faq.html#repo).

**Comment by anodynos** [comment]
> @anodynos , see [FAQ 2.2](http://doublecmd.github.io/doc/en/faq.html#repo).

Thanks @Skif-off - I tried installing https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/xUbuntu_20.04/all/doublecmd-qt5_1.0.0~0+svn9579_all.deb from https://software.opensuse.org/download.html?project=home:Alexx2000:doublecmd-svn&package=doublecmd-qt5 but I get 

```
╰─$ sudo dpkg -i doublecmd-qt5_1.0.0_0+svn9579_all.deb                                                                                                 130 ↵
(Reading database ... 769549 files and directories currently installed.)
Preparing to unpack doublecmd-qt5_1.0.0_0+svn9579_all.deb ...
Unpacking doublecmd-qt5 (1.0.0~0+svn9579) over (1.0.0~0+svn9579) ...
dpkg: dependency problems prevent configuration of doublecmd-qt5:
 doublecmd-qt5 depends on doublecmd-qt (>= 1.0.0); however:
  Version of doublecmd-qt on system is 0.9.9-0+svn9478~testing.

dpkg: error processing package doublecmd-qt5 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 doublecmd-qt5
```

**Comment by Skif-off** [comment]
@anodynos 
In Debian/Ubuntu DC is not one package, in your case list should be:
[doublecmd-qt_1.0.0~0+svn9579_amd64.deb](http://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/xUbuntu_20.04/amd64/doublecmd-qt_1.0.0~0+svn9579_amd64.deb)
[doublecmd-common_1.0.0~0+svn9579_all.deb](http://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/xUbuntu_20.04/all/doublecmd-common_1.0.0~0+svn9579_all.deb)
[doublecmd-plugins_1.0.0~0+svn9579_amd64.deb](http://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/xUbuntu_20.04/amd64/doublecmd-plugins_1.0.0~0+svn9579_amd64.deb)

Delete `doublecmd-qt5` package: `sudo apt-get purge doublecmd-qt5`
Download and use `sudo dpkg -i doublecmd*.deb`

Maybe just add repository? (In this case also see [#37](https://github.com/doublecmd/doublecmd/issues/37).)

**Comment by anodynos** [comment]
Perfect - v1.0.0 worked perfectly, I'm closing the issue (thanks @Skif-off for help & @alexx2000 for creating this amazing software)
