### ISSUE TITLE
When right-click on a directory, the program be dead

### ISSUE THREAD

**Issue by jack-liew** [doublecmd/doublecmd#380]
In windows systems,When right-click on a directory, the program be dead.**

**Comment by WhiteChairFromIkea** [comment]
One probably means "not responding". I see this with latest qt x64 dark snapshot, but cannot repriduce reliably.

**Comment by jack-liew** [comment]
Hi:
  Yes,Its “not responding”.
  my OS is windows 11 x64,after execute double cmd ,everytime to right click on a directory, the programe is not responding.
  Even if I reinstall it, it still doesn't respond.

Thanks.


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

**Comment by alexx2000** [comment]
I guess problem with some shell extension, see:
https://ghisler.ch/board/viewtopic.php?t=25124
https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash

**Comment by Jason2013** [comment]
I encountered the same problem.
Double Commander: 1.0.6 beta build 121
OS: Microsoft Windows 10 Version 21H1 (OS Build 19043.1766)

**Comment by Jason2013** [comment]
> I guess problem with some shell extension, see how to find it: https://ghisler.ch/board/viewtopic.php?t=25124 https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash

I right click a directory in the File Explorer, the quick menu pops up correctly. I right click a directory in the Double Commander, it doesn't response any more.

**Comment by Jason2013** [comment]
> I guess problem with some shell extension, see how to find it: https://ghisler.ch/board/viewtopic.php?t=25124 https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash


The following method worked for me:
https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash

The following registry entry caused the problem:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shellex\ContextMenuHandlers\YunShellExt]
@="{6D85624F-305A-491d-8848-C1927AA0D790}"
```

This application is a cloud drive client downloaded from the URL: https://pan.baidu.com/download

I disabled the `YunShellExt` by adding the following registry entry and fixed the problem:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked]
"{6D85624F-305A-491d-8848-C1927AA0D790}"=""
```

Now the Double Commander works properly.

**Comment by jack-liew** [comment]
> > I guess problem with some shell extension, see how to find it: https://ghisler.ch/board/viewtopic.php?t=25124 https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash
> 
> The following method worked for me: https://www.ghisler.ch/wiki/index.php/Right_click_or_Ctrl-C_causing_crash
> 
> The following registry entry caused the problem:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\Directory\shellex\ContextMenuHandlers\YunShellExt]
> @="{6D85624F-305A-491d-8848-C1927AA0D790}"
> ```
> 
> This application is a cloud drive client downloaded from the URL: https://pan.baidu.com/download
> 
> I disabled the `YunShellExt` by adding the following registry entry and fixed the problem:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked]
> "{6D85624F-305A-491d-8848-C1927AA0D790}"=""
> ```
> 
> Now the Double Commander works properly.

It‘s worked,Thank U
