### ISSUE TITLE
Add support for QuickLook

### ISSUE THREAD

**Issue by zohozer** [doublecmd/doublecmd#381]
Hi. I am used with other filemanagers like Finder on MacOS, [Nemo Preview for Linux](https://community.linuxmint.com/software/view/nemo-preview) and recently with [QuickLook for Windows](https://www.microsoft.com/store/productId/9NV4BS3L1H4S) to press the spacebar and have a quick preview at the highlighted file by pressing the Spacebar.

Will be possible to implement this feature in DoubleCommander?

If I use the other mentioned file managers, when I press the Spacebar I can see the preview but if I press the Spacebar in DoubleCommander the cursor will just go down to the next file instead to use the QuickLook features like in the other file managers.

It would be great if Double Commander can add support to use this native QuickLook plugins on each OS and an option to be used by pressing Spacebar like on the other cases mentioned above.

**Comment by JonnyTech** [comment]
Quick view = CTRL+Q
View file = F3
You can remap keys
