### ISSUE TITLE
...Where the code at?!

### ISSUE THREAD

**Issue by Coldblackice** [doublecmd/doublecmd#39]
Is it just me, or is the repository now devoid of any and all files and code?

**Comment by j2969719** [comment]
https://sourceforge.net/p/doublecmd/code/HEAD/tree/

**Comment by dandv** [comment]
That's documented at https://github.com/doublecmd/doublecmd/wiki/Development#getting-the-source-code but I'm not clear on the purpose of this repo... This project is [spread all over the place](https://github.com/doublecmd/doublecmd/issues/49).

**Comment by Kissaki** [comment]
The code is in this repository now.

See also #6
