### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by tbinsx1** [doublecmd/doublecmd#391]
I want to suggest two improvements:
- in "Visualize" the very useful "unique list" of all subdirectories is missing;
- in "Commands > Syncronize dirs" show button do not allow a clear state so, I suggest to add check boxes.
Thank in advance and congrats for the good job done so far. 
Tiziano

**Comment by alexx2000** [comment]
1. What do you mean?
2. Works fine

**Comment by tbinsx1** [comment]
1. TotalCommander has a view of all the files contained in the directory
and all the down-subdirectores, in a unique list.

2. Yes, it works but the button status are not clearly intelligible, thus
risking to miss something.

Hope I was clear enough.
Regards, tb

**Comment by alexx2000** [comment]
1. Menu->"Commands"->"Flat view" or Ctrl+B.

**Comment by tbinsx1** [comment]
Perfect. Did not realize it.
Thank you

**Comment by gitgt** [comment]
Please close the issue. And give meaningful title next time.
