### ISSUE TITLE
Confirmation when accidentally pressed Esc during copying/moving/etc

### ISSUE THREAD

**Issue by sakhdevel** [doublecmd/doublecmd#393]
Hi! 

Can you please add confirmation when user accidentally presses Esc key in the copy/move window?
Because now it simply stops the process
![image](https://user-images.githubusercontent.com/23290296/162597897-71053779-e22a-45cf-8617-a117d3e5a754.png)

**Comment by j2969719** [comment]
humbly ask you to add an optional flag for suppressing such confirmations in the config
