### ISSUE TITLE
Allow pass directories to external differ

### ISSUE THREAD

**Issue by SAASTN** [doublecmd/doublecmd#394]
Hi,
Many diff tools (e.g. WinMerge) can also compare contents of directories. But running the "Compare By Contents" in DC, when directories are selected, will show an error message saying : "Invalid selection.".
It also can be a different command than `cm_CompareContents` that sends both open directories themselves to the external differ.

BTW, I cannot find the syntax that DC uses for sending additional parameters. It seems that it is a fixed syntax like:
```
[external app path] [additional parameters] [left file path] [right file path]
```
It's a good idea to allow paths of files to be sent in a more flexible way. For example they can be explicitly mentioned in "Additional Parameters" as defined variables, like `$left` and `$right` or something. But if these variables were not present in "Additional Parameters", the default syntax can be used. This can be useful in cases when more additional parameters should be passed after paths of files. For example, WM can take a third path to store the merged results. In this case the Additional Parameters can be something like this:
```
/u /e $left $right /o "c:\somefile.txt"
```

Thanks for the great app
Regards

**Comment by alexx2000** [comment]
Hi, `cm_CompareContents` can do it. Execute it with `dir` parameter (you can assign it to the toolbar button or hotkey).
