### ISSUE TITLE
viewer window size not saved

### ISSUE THREAD

**Issue by glebsts** [doublecmd/doublecmd#395]
Hello,
First of all thank you for great software. Really saves me on Linux, I never completely moved to Linux because there was no TC, and I just recently discovered DC.

Problem:
Viewer image size not saving -  it starts in very small window (compared to 1920x1200 resolution is is more than 4 time smaller. I make it bigger with dragging one of the corners, I close it, next time viewer window starts with original size again. 

I found this old topic that was never answered - https://doublecmd.h1n.ru/viewtopic.php?p=13516
What am I doing wrong?
Anything that could be changed? I am not yet ready to send a pull request for that :)

Kubuntu 20.04, KDE Plasma 5.18.8

**Comment by alexx2000** [comment]
Hi,

I cannot reproduce. Works fine for me.

**Comment by glebsts** [comment]
Reinstall fixed for me, seems like permission issue, sorry for bothering.
