### ISSUE TITLE
[QT5] When renaming, two-byte characters disappear or special characters cannot be entered.

### ISSUE THREAD

**Issue by mspt2student** [doublecmd/doublecmd#396]
### Describe
When renaming, two-byte characters disappear or special characters cannot be entered.
Watch the video below.
Normal build is ok, only qt5 build has problems.

![renaming issue](https://user-images.githubusercontent.com/101167961/163172974-c8887ec2-3525-49c7-a5e9-39bbdc288595.gif)

### Version information
> Double Commander
Version: 1.1.0 alpha
Revision: 10159
Commit: c3b1ce863
Build date: 2022/04/10
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-qt5
OS version: Windows 11 21H2 x86_64
Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1

**Comment by mspt2student** [comment]
It's working without any issues.

**Comment by alexx2000** [comment]
OK. 

Qt5 version is obsolete and don't build anymore.

**Comment by ags1234** [comment]
Wow! A native dark version? Excellent news, thank you!
