### ISSUE TITLE
Manjaro KDE: double click always opens Dolphin (default file manager) at first

### ISSUE THREAD

**Issue by regisz** [doublecmd/doublecmd#397]
Hi,

For some reason (I haven't changed anything in my operating system) DoubleCMD always opens Dolphin (default file manager) first when I double click (or single click depending on the settings). It then opens the application I want to open, but also opens all the previously opened files. I have to always close all tabs in Dolphin to avoid this very annoying "feature".
If I use Dolphin directly and double click in it, everything is fine.

Any idea?

Thx!

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.6
Codename:       Qonos

$ plasmashell --version
plasmashell 5.24.4

$ kf5-config --version
Qt: 5.15.3
KDE Frameworks: 5.92.0
kf5-config: 1.0

$ uname -o -m -s -r -v
Linux 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux
```

**Comment by alexx2000** [comment]
Hi,

Under KDE DC uses `kioclient  exec "/path/to/some/file"` command to open files. Try to execute this command from console with some real file and look what happen.

**Comment by alexx2000** [comment]
Program `kioclient5` is a part of KDE. So I can't help here.

**Comment by regisz** [comment]
It was a config "error?" for me.
I should remove the next both lines from my `$HOME/.config/mimeapps.list`:
`x-scheme-handler/file=org.kde.dolphin.desktop;`
And it fixed my problem.
Thx the help!

**Comment by regisz** [comment]
The solution was I had to remove the two `x-scheme-handler/file=org.kde.dolphin.desktop;` lines from  `$HOME/.config/mimeapps.list`.
(See https://bugs.kde.org/show_bug.cgi?id=452819#c5)
