### ISSUE TITLE
How can I access my Android phone from DC?

### ISSUE THREAD

**Issue by ags1234** [doublecmd/doublecmd#400]
I can access the phone through MTP from other file managers, so it is not a problem with the phone.

**Comment by alexx2000** [comment]
Under Windows you can use two plugins for this task:

- http://totalcmd.net/plugring/winmedaudio2.html
- http://totalcmd.net/plugring/android_adb.html

Under Linux DC can work with Android phone directly via GVFS.

**Comment by ags1234** [comment]
Yes, in Windows I need it.
Tried the Android ADB plugin. It is not working.
![2022-04-21 21 11 33](https://user-images.githubusercontent.com/21011513/164527385-6be1fce2-a93b-4f69-bde7-9f062266753f.gif)

**Comment by j2969719** [comment]
https://developer.android.com/studio/command-line/adb#Enabling

**Comment by ags1234** [comment]
I got it. I had to allow popup windows asking permission on the phone.

**Comment by Dimchkin** [comment]
@alexx2000 Have a similar problem, but under Linux (Manjaro). gvfs installed. Other managers see the device without problem. Also tried with USB debugging ON with no avail.
![mtp](https://user-images.githubusercontent.com/46589070/177416649-b3d158e2-3d44-4b97-9d08-952f0bb364fa.png)

**Comment by jewuwu** [comment]
No one with any idea?

**Comment by jewuwu** [comment]
Still looking for the fix.

**Comment by alexx2000** [comment]
Sorry, without problem device I cannot help. But I guess you can  go to "/run/user/1000/gvfs/mtp:host=Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752" path in DC.

**Comment by jewuwu** [comment]
You are right, this really does the trick. Thank you!

So, as it is not a problem of the phone not being accessible, it might just be an internal misconfig of the DC itself?


> Sorry, without problem device I cannot help. But I guess you can go to "/run/user/1000/gvfs/mtp:host=Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752" path in DC.

**Comment by alexx2000** [comment]
I suspect your phone name has some special symbol. Can you open phone in the Nemo and copy address here?
Also execute in the terminal command `gio info address` and copy output here.

**Comment by jewuwu** [comment]
Nemo path:
mtp://Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752/

dings@bums ~ $ gio info mtp://Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752/
Anzeigename: ATOLL AB IDP  SN:16B6D31E
Name: Xiaomi_ATOLL-AB-IDP__SN:16B6D31E_5f6a2752
Typ: directory
Größe:  0
Adresse: mtp://Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752/
local path: /run/user/1000/gvfs/mtp:host=Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752
unix mount: gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
Attribute:
  standard::type: 2
  standard::name: Xiaomi_ATOLL-AB-IDP__SN:16B6D31E_5f6a2752
  standard::display-name: ATOLL AB IDP  SN:16B6D31E
  standard::icon: phone, phone-symbolic
  standard::content-type: inode/directory
  standard::size: 0
  standard::symbolic-icon: phone-symbolic, phone
  id::filesystem: mtp:host=Xiaomi_ATOLL-AB-IDP__SN%3A16B6D31E_5f6a2752
  access::can-read: TRUE
  access::can-write: FALSE
  access::can-execute: TRUE
  access::can-delete: FALSE
  access::can-trash: FALSE
  access::can-rename: FALSE
  filesystem::size: 144518737920
  filesystem::free: 3806928896
  filesystem::type: mtpfs
  filesystem::remote: FALSE
  metadata::nemo-default-view: OAFIID:Nemo_File_Manager_Icon_View
  metadata::nemo-icon-view-auto-layout: true
  metadata::nemo-list-view-sort-column: date_modified
  metadata::nemo-list-view-sort-reversed: true
  metadata::nemo-list-view-zoom-level: 1
  metadata::show-thumbnails: true

**Comment by alexx2000** [comment]
Copy this address to clipboard, right click on the path label in DC, paste address from clipboard and press enter. What will happen?
