### ISSUE TITLE
Qt 6

### ISSUE THREAD

**Issue by johnbbstv** [doublecmd/doublecmd#402]
Hi is it possible to add support for Qt 6, since Qt 5 is very outdated and very slow.
Thanks

**Comment by j2969719** [comment]
https://wiki.freepascal.org/Roadmap#General_status_of_LCL_interfaces

**Comment by alexx2000** [comment]
Someday Lazarus will support Qt6.

**Comment by xcom169** [comment]
Currently QT5 is the best frontend on Linux. GTK2 is really old.

**Comment by alexx2000** [comment]
Lazarus added Qt 6 support (Lazarus >= 2.3 from git).
