### ISSUE TITLE
[Suggestion] Qt5 builds as default (or a permanent option) to download for Windows

### ISSUE THREAD

**Issue by DmitriyWZR** [doublecmd/doublecmd#404]
Qt5 builds looks more sleek and modern (especially compared to old-fashioned TC) on Windows. Qt5 builds doesn't have an issue with dark mode on latest Windows builds. (We Windows users doesn't stick to only latest stable Win10, some of us use Windows 11 and i'm a windows dev insider, so dark mode in DC simply doesn't work for us. TC on the hand has a simple switch in settings for this and currently it is a significant benefit over DC). Yet users have no direct link to download them, only sometimes nightly builds has Qt5 versions. Also i can't name any drawback of Qt over regular. RAM usage is insignificantly higher for any PC that can access to download it. Many software veterans (like FCEUX emu for example) did it, achieving "this-era" look. I did my little investigation, sending a rev.10165 and 4 out-of 5 long time TC users said they wanna try a spin to DC, naming a better look as a main reason. Are Qt5 builds gonna be back at all?

**Comment by ags1234** [comment]
> issue with dark mode on latest Windows builds

I use DC 1.1.0 alpha build 10168 in Windows 11 21H2 22000.556 and did not see any dark mode problems. What exactly do you mean?

**Comment by WhiteChairFromIkea** [comment]
My windows 10 installation is also up to date, no issues with DC native dark build with the same version as AGS: `DC 1.1.0 alpha build 10168`

**Comment by alexx2000** [comment]
He say about Insider Preview Windows version. DC supports dark mode only on officially released Windows versions.

**Comment by DmitriyWZR** [comment]
> > issue with dark mode on latest Windows builds
> 
> I use DC 1.1.0 alpha build 10168 in Windows 11 21H2 22000.556 and did not see any dark mode problems. What exactly do you mean?

Cause it's hardcoded to work on some known builds rather than just be "Windows 10 and newer". If update gonna bump stable branch build, update to DC gonna be necessary.

**Comment by DmitriyWZR** [comment]
> officially released Windows versions.

Insider builds ARE officially released windows versions. And it's not a point here.

**Comment by alexx2000** [comment]
Insider Preview is not a release version. It is a dev/beta/preview version. Current official release: [Windows 11 21H2 build 22000.652](https://docs.microsoft.com/en-us/windows/release-health/windows11-release-information).

**Comment by DmitriyWZR** [comment]
> Insider Preview is not a release version

Omg. That's unrelated. Well ok, you don't care, how your software works outside of stable branch (which is not a good point, especially considering fixing it requires just one function to be coded right way, but it's your approach, no complains here). But next time stable branch update gonna bump build number and things are gonna be broken again, As it was with any stable 10 builds before. As it was, when 11 were released. That kind of approach makes it hard to be an open source alternatives ambassador, but i got your official point and i do respect it. Thank you for all of your work maintaining DC.

**Comment by WhiteChairFromIkea** [comment]
Well, qt5 builds has serious showstopper for me (https://github.com/doublecmd/doublecmd/issues/129), and it was super hard to fix. I am happy now that native build appeared, you should report visuality glitches instead, see how quickly easy to fix bugs are fixed: https://github.com/doublecmd/doublecmd/issues/405

**Comment by DmitriyWZR** [comment]
> Technically I can enable dark mode on all Win11 builds. But if API changes then DC can crash. I haven't figured it out yet how to workaround it.

1) Why it should? Nothing bad ever happened with apps, implemented it since the first days.
2) Let's imagine it would and it's gonna break dark mode on future Windows builds. How's "probably can be broken after update" is worse than "definitely gonna be broken after update"?
3) Windows has compatibility mode with Win 8 and lower, which disables the feature entirely. Not to mention that we gonna know about such changes from insider builds long before (at least ~6 month) those changes gonna leave the testers ring.
4) They've already down-ported changes from testing branches without bumping a current stable build number anyway.
5) That's a thing to concern, whether it's related to Windows 11 only. Windows 10 is still supported. Technically they still can bump build numbers for those who stayed on Win10 too. Right now it's seems like it's not gonna happen, but considering how much PCs they've left behind with a new system requirements, Windows 10 support can be around a little bit longer, than we think and can go unpredictable way, including adding a new features.

**Comment by alexx2000** [comment]
1. API was changed between Win 10 1809 and Win10 1903, function with number 135 was replaced by another function with same number.
2. It can crash at the first case and it will be light in the second case. So it is a question what is worse.

OK, I enable dark mode on Windows 11 Insider Preview. Time will tell what is better.
