### ISSUE TITLE
[Request] Internal Viewer - Unicode Support

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#409]
Unicode Support in Internal Viewer, is a must have feature !

**Without Unicode**
![doublecmd - no unicode support in viewer ! very bad](https://user-images.githubusercontent.com/104623174/165916906-cd635921-6453-4210-bb1e-09d2bc7ceba4.jpg)

![ansi](https://user-images.githubusercontent.com/104623174/165916968-65b82974-d9d6-42f6-ad19-24f620274720.jpg)

 

**With Unicode**
![unicode](https://user-images.githubusercontent.com/104623174/165917145-6004e215-405f-4d31-a834-5becda6d4ce9.jpg)
![unicode + ascii](https://user-images.githubusercontent.com/104623174/165917169-babdeb6e-1521-4046-a7e8-53865450d921.jpg)

**Comment by pRIVATEpIEsquare** [comment]
**yep got it. it works. many thanks.**
also could it make it work as a bin (binary too).
it only works in txt (text) !

ps. i was using this without knowing for some time !

**Comment by goyalyashpal** [comment]
> ps. i was using this without knowing for some time !

@pRIVATEpIEsquare what did you mean by "this" here?

also, this issue can be closed right?
