### ISSUE TITLE
[Request] File Search - Text find with Unicode !

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#411]
As already know by now Unicode is a key feature that it will show you the hidden functions, possible and most likely commands.
Now Double Commander has NOT a Unicode feature in, when doing a file search, text file.

![doublecmd - no unicode support in file text search ! very bad](https://user-images.githubusercontent.com/104623174/165918193-f27d4e1a-c1a9-4457-b745-966fb17f1f1f.jpg)

Expected to have a feature with Unicode search for Text inside, for every file(s) !

**Comment by alexx2000** [comment]
DC supports Unicode, choose correct encoding (UTF-16LE) from "Encoding" dropdown list.

**Comment by pRIVATEpIEsquare** [comment]
yep got it, thanks.
but internal viewer does not show unicode !
so having support in search but without in internal viewer is kind of incomplete !
