### ISSUE TITLE
[Request] Lite & Dark modes theme switch !

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#413]
It will be nice to have a direct setting withing doublecmd.exe, to switch between lite and dark mode(s).
Instead of having 2 (two) doublecmd.exe file(s) and another 2 (two) doublecmd.xml file(s) !

![doublecmd - dark theme](https://user-images.githubusercontent.com/104623174/165919286-39f145a7-dd11-4b44-8ae1-a05bea538bc9.jpg)
![doublecmd - lite theme](https://user-images.githubusercontent.com/104623174/165919306-26c46149-032f-41ce-8b2a-5fc05ee60e40.jpg)

**Comment by alexx2000** [comment]
Dark "doublecmd.exe" supports both modes. Used style depends on the Windows dark mode setting. DC requires restart to apply new mode.

**Comment by pRIVATEpIEsquare** [comment]
Thanks for quick response.
i will manage somehow, still the new dark mode is to stay as default since is a lot better and reduce by a lot the eyes strains..
thanks !

**Comment by alexx2000** [comment]
Added, "Options"->"Colors"->"Dark mode".

**Comment by gh-log** [comment]
Cant find the option.
![Screenshot 2023-05-24 161909](https://github.com/doublecmd/doublecmd/assets/16019542/53f0981a-7bbe-431a-a2f1-0480aed2eb0d)

**Comment by alexx2000** [comment]
You need DC 1.1.0.
