### ISSUE TITLE
[Dark Theme] Thanks !

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#421]
What you did to me Alex !
The Double Commander is looking GREAT !
With Dark Theme using laptop at late night has become a pleasure, no more irritating or forcing eyes, even laptop's battery had become better due of pixels brightness !
Dark Theme is a MUST and BEST way for human eyes health !
But now i had to do theme mod to other applications too, including the Windows 11 Lite Start Menu !

Heavy Double Commander Moddings !
![clippy a](https://user-images.githubusercontent.com/104623174/166191441-1d71577f-0a70-40d4-979e-36f0f563083b.jpg)
![clippy b](https://user-images.githubusercontent.com/104623174/166191550-2d3b03b5-427f-4d05-9515-37dd1a86215c.jpg)
![clippy c](https://user-images.githubusercontent.com/104623174/166191694-0f50de37-b285-4fd0-9a94-5ad1dd9b5e05.jpg)

Changes made to the **Editor** !    (_**But i use AkelPad..and now i must work on AkelPad for Dark Theme**_)
![editor](https://user-images.githubusercontent.com/104623174/166191722-759f47a9-0e9e-4c2b-b967-447065c84f6b.jpg)

Changes made to the **Differ** !
Btw i am still trying to sort colors on this Differ thing !
Still i use Diffinity as replacement !
![differ](https://user-images.githubusercontent.com/104623174/166191775-4d470422-9c9a-45d6-99f6-6f66e880a82a.jpg)

And Hackers Favorite TooL !
Ascii + Unicode !
![ascii + unicode](https://user-images.githubusercontent.com/104623174/166191904-c8169393-fd84-46e0-b055-71d0ef898664.jpg)

Again Thanks Alex !

**Comment by alexx2000** [comment]
Impossible. It will be only in the next stable release (1.1).
