### ISSUE TITLE
[Bug]  Viewer does not respect Copy to Clipboard !

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#426]
https://user-images.githubusercontent.com/104623174/166705505-1edc45eb-8f9f-4980-a26c-5ca1f3924dcf.mp4

Expected to honor the copy to clipboard, even if the selection is on another line/word !

**Comment by pRIVATEpIEsquare** [comment]
Editor is OK as is respecting the Copy to Clipboard selection !

https://user-images.githubusercontent.com/104623174/166708057-a8fbfebc-22a5-4dcc-be8e-b36adc15ddd4.mp4

**Comment by alexx2000** [comment]
It is a "feature". Viewer auto copy selected text to clipboard.

**Comment by alexx2000** [comment]
Can be disabled using [AutoCopy](https://doublecmd.github.io/doc/en/configxml.html#manualed) option.
