### ISSUE TITLE
DC for macOS request: ability to set hot key to open Options to regular macOS command (cmd/ ⌘) + , (comma)

### ISSUE THREAD

**Issue by LeeBinder** [doublecmd/doublecmd#428]
Hello.In macOS, in 99,9% of all apps, the hot key combo `⌘ + ,` is used to open an app's Preferences aka Options. In DC for Mac, that hot key can't be set. When I press it, the input field remains empty:

![Bildschirmfoto 2022-05-07 um 21 27 27](https://user-images.githubusercontent.com/39203497/167269011-97d7920e-e74e-4dcf-8b81-66dadae7c113.jpg)

Other hot keys, however, CAN be set, and DO work to invoke Options.

`⌘ + ,` is not being used for anything else in DC from what I can see, because when I press it, nothing happens.

I'm running the latest 64bit snapshot 1.1.0-10171.cocoa.x86_64 from https://doublecmd.sourceforge.io/site/eng/snapshots.php.

**Comment by rich2014** [comment]
fixed by #761

#428 should be closed.

**Comment by LeeBinder** [comment]
yes, thank you @rich2014 - confirmed working in latest snapshot🥇
