### ISSUE TITLE
Программа зависает, когда кликаешь правой кнопкой мыши на пустом поле без файлов.

### ISSUE THREAD

**Issue by soviet-man** [doublecmd/doublecmd#431]
Например, тут, под папкой **500gb**

![изображение](https://user-images.githubusercontent.com/33825590/168466919-c8ecead4-3053-4f47-921d-1e4c378b8425.png)

**Comment by AlkaliX** [comment]
На последнtй сборке под Windows не воспроизвелось:
![image](https://user-images.githubusercontent.com/2937504/168476443-fd1ada5a-0901-4257-b88b-6647cafc774f.png)

**Comment by alexx2000** [comment]
https://doublecmd.h1n.ru/viewtopic.php?f=10&p=36566
