### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by Kolcha** [doublecmd/doublecmd#435]
Hi there!
if anyone interested, I made a build for **Apple M1** Mac from master branch, commit b636e42eeaf1a57af67c714a0563ef91dec6df1c
**it can be downloaded [here](https://www.dropbox.com/sh/so03ywlwtfq3c89/AAC_T9du8AYH7NqT3-jMSIHIa?dl=0)!** build is only for Apple M1, it can't be used on Intel-based Mac.

very likely I will upload new builds pretty often, so this link points to folder. visit it again for new builds.

this is my first try with that application (and technogies stack), but looks like everything is fine. some issues exist, but they were also observed in nightly build for Intel-based Mac. very likely I'll be able to fix few of them, but I'm not familiar with Pascal and it looks too strange for me, so don't expect too much. enjoy!

<img width="1728" alt="Screenshot 2022-05-21 at 15 50 08" src="https://user-images.githubusercontent.com/947647/169654708-ff3e2408-4fb9-4384-a4b8-3e7b8f61fbed.png">

**Comment by Kolcha** [comment]
looks like Double Commander doesn't support macOS anymore, so my build is useless...
I don't know Delphi/Pascal and don't want to learn it, if it was written in C++ I would fix it...

**Comment by Skif-off** [comment]
> looks like Double Commander doesn't support macOS anymore

This is not true, see [this note](https://github.com/doublecmd/doublecmd/wiki/Supported-platforms#Mac_OS_X).
[Fox example](https://github.com/doublecmd/doublecmd/pull/420).

About Apple M1: It's ARM, isn't it? Technically it is possible, for example, in Debian, DC is compiled for the following platforms: AMD64 and x86, ARM, ARM with hardware FPU and 64bit ARM.

**Comment by alexx2000** [comment]
It is not supported [by me](https://doublecmd.h1n.ru/viewtopic.php?p=35121#p35121). But I accept patches from other developers and don't remove macOS support from source code. Also I build i386/x86_64 [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php). But it is a maximum that I can do.

**Comment by Kolcha** [comment]
> About Apple M1: It's ARM, isn't it?

yes, it is ARM, arm64 (or aarch64) more correctly.
I compiled Double Commander for that using native Cocoa as widgets backend (as it done for nightly builds), but it has some annoying UI issues (these issues are also present in official nightly builds for Intel-based macs), seems that issues comes from widgets system implementation.
also I tried to use Qt5 as widgets backend (as it was for a long time, at least for last few 0.9.x versions), situation became even worst... application is almost unusable... even more, to build it with Qt5 on macOS I had to modify some sources due to build issues. looks like it is not supposed to be compiled with Qt5 on macOS anymore (there are many places with some kind of defines "if Qt5 and not macOS").

and some last notes, used software/technology stack is definitely not truly cross-platform, this mostly Windows-only because this is just Delphi replacement. it works somehow in Linux just because it is open-source and community made a huge effort on it, but it also has a lot of annoying UI issues which are not exist in case of "native" (C/C++) development with the same UI kits. application just "inherit" these issues from used toolkit and just suffer from them... and I understand why author dropped macOS support.

**Comment by alexx2000** [comment]
DC 0.9.x used Qt4.

> this mostly Windows-only

I think also it is because Windows is most popular OS. So Lazarus community have many Windows developers, less Linux developers and a few macOS developers. Lazarus developers made a huge work but they does not have resources to support all OS at good quality level.

**Comment by huan810124** [comment]
Unfortunately, the download link is not working.

**Comment by Kolcha** [comment]
builds for Apple M1 are officially provided as snapshots, you can download it [here](https://doublecmd.sourceforge.io/site/eng/snapshots.php) (aarch64 is what you need)
