### ISSUE TITLE
FTP - cropping text files

### ISSUE THREAD

**Issue by plachow** [doublecmd/doublecmd#437]
When downloading (or viewing) files from FTP (conencted by TLS), DC crops some files. It can be reproduced. DC crops always the same files. Screenshot: download files from FTP and compare them with source. Three of them are cropped.
![image](https://user-images.githubusercontent.com/24429536/170025852-63e1c2f8-6355-4efd-a28c-572252359af6.png)

**Comment by alexx2000** [comment]
Try with [OpenSSL libraries](https://doublecmd.github.io/doc/en/faq.html#ftp_openssl).

**Comment by endo64** [comment]
That issue happens for binary files as well, see my comment https://github.com/doublecmd/doublecmd/discussions/1325

and the provided solution resolves that. Thanks a lot!

**Comment by dazu89** [comment]
Thank you, @alexx2000, for remembering and tagging me in #1356. I have noted nomacs not being able to open some transferred jpg files, which might be symptom of this same issue. Where are the '*.dll' files from the openssl library to be placed – the doublecmd root directory or `doublecmd\plugins\wfx\ftp\`?

**Comment by alexx2000** [comment]
doublecmd root directory
