### ISSUE TITLE
Thoughts !

### ISSUE THREAD

**Issue by pRIVATEpIEsquare** [doublecmd/doublecmd#438]
Hi Alex.
Question, please test this and tell me if if i can or can't apply some changes to doublecmd !

The archive must be unpacked ONLY in C:\ it must be like C:\Totalcmd

[Totalcmd.zip](https://github.com/doublecmd/doublecmd/files/8778788/Totalcmd.zip)

Please test also doublecmd internal editor and viewer.

**Comment by alexx2000** [comment]
Do you mean large toolbar buttons with captions? It should be optional.

**Comment by pRIVATEpIEsquare** [comment]
that one too. small toolbar is difficult to handle for faster workloads. and captions is a shortcut good for me,since it helps a lot as being faster than remember every programs icons. i also played a bit with the icons names.

also for portable mode there is one file named "doublecmd.inf" that is empty and now since darkmode added, there is second file *.ini "doublecmd.ini".
so i changed the sentence in glob of inf to ini so that i only have one file valid for both darkmode and portable check.
and further deleted the inf file since is obsolete.

the free space will be better defined as for ex: 10 M free of 15 M, instead of original 10 M of 15 M free.

i removed the splash screen. since it remind me of nags cracking old times.

plugins are old alex and give PROblems, and i removed all.

i removed parts of the queque since it can disturb hdd mechanics and cripple or hangs the i/o.

some minor modifications to colors to match the windows 11 explorer patterns.

i removed the build/beta/kapa and other informations on the windows name, just play it simpler instead of Double Commander build date source and so on as now is only Double Commander - Administrator or just user.
of course everything else is in the about window so what's the point having a soup of letter on the windows name.
is confusing. imagine windows explorer having
"Microsoft Windows Explorer build 10.2200.100 date 2021-10-11 Final Stable Administrator"

however something is bothering me, the auto refresh, since it does not perform well when mount with diskpart the drive letter is not appearing, and copy,delete operations too have problems to auto refresh after jobs done.

Thanks for your work, is the Best commander !

**Comment by Skif-off** [comment]
> i removed the splash screen. since it remind me of nags cracking old times.

```--no-splash``` does not work?

> plugins are old alex and give PROblems, and i removed all.

Some people use, strange solution.

**Comment by alexx2000** [comment]
I can accept toolbar changes. But it should be optional and backward compatible (toolbar icon size already can be changed).
> i removed parts of the queque since it can disturb hdd mechanics and cripple or hangs the i/o.

Just the opposite, queue do operations sequentially that is good for HDD.

**Comment by pRIVATEpIEsquare** [comment]
> `--no-splash` does not work?
the code related has been removed/no splash anymore.

> Just the opposite, queue do operations sequentially that is good for HDD.
i won't do the retesting's anymore, did it months ago..in my "personal" findings didn't pass well at all.. and i removed equivalent code.
got something similar with tc where i lost some gb, and was one of the reasons to switch to dc.
