### ISSUE TITLE
Sorting configuration options

### ISSUE THREAD

**Issue by antodc** [doublecmd/doublecmd#44]
First of all, so many thanks indeed for your priceless work with this software.
I was wondering whether there is any way to have the items in the left-hand part of the configuration options panel sorted in alphabetic order. In my case (Windows 10, Italian language) they appear in a rather random order, making it somewhat difficult to find a specific item. I see "Lingua", "Comportamenti", "Strumenti" and so on, and the order remains the same in English ("Language", "Behaviors", "Tools", and so on) and I suppose in other languages as well.

**Comment by j2969719** [comment]
configurazione>sort order of configuration...> alphabetic..

**Comment by antodc** [comment]
Wonderful!! Thanks a lot for the suggestion!
