### ISSUE TITLE
consider to use these 2 Lazarus components for dark mode on Windows

### ISSUE THREAD

**Issue by CudaText-addons** [doublecmd/doublecmd#446]
https://wiki.freepascal.org/Win32MenuStyler

and

https://wiki.freepascal.org/Win32TitleStyler

**Comment by WhiteChairFromIkea** [comment]
(please do not ruin current look, I have no issues at all)

**Comment by alexx2000** [comment]
I know about these components but I prefer my implementation which adds dark mode for all controls used by DC.
