### ISSUE TITLE
Add PeaZip to "Configuration of Archivers" templates list

### ISSUE THREAD

**Issue by Korb** [doublecmd/doublecmd#447]
_[Double Commander Official forum topic](https://doublecmd.h1n.ru/viewtopic.php?p=36790#p36790)_

**Comment by Skif-off** [comment]
PeaZip? Do you know that for the most part it's just a collection?

Windows: https://totalcmd.net/plugring/ZPAQ.html
Linux/other Unix-like OS: see [this](https://github.com/j2969719/doublecmd-plugins/blob/master/multiarc.ini.md#zpaq) or import [zpaq.ini](https://github.com/j2969719/doublecmd-plugins/blob/master/multiarc/zpaq.ini).

**Comment by Korb** [comment]
> PeaZip? Do you know that for the most part it's just a collection?

ZPAQ + "just a collection", — yes.

> Windows: https://totalcmd.net/plugring/ZPAQ.html

I forgot about the need to check the availability of this functionality through add-ons. Thank you!

![2022-06-04 16 01 03](https://user-images.githubusercontent.com/3509797/172000278-2c26260d-e20b-4d2d-b7e1-51187a326c54.png)

It remains to figure out how to use it not only to extract files from the archive, but also for packaging. But that's another question.
