### ISSUE TITLE
По нажатию Shift + Enter не выходит консоль в KDE Plasma (Manjaro)

### ISSUE THREAD

**Issue by daniilpetrov** [doublecmd/doublecmd#449]
Перешёл с GNOME на KDE Plasma, версию Double Commander теперь соответственно ставлю не GTK, а Qt5, но всё равно по нажатию Shift + Enter не запускаются скрипты. Помогите, кто чем может :)

**Comment by alexx2000** [comment]
Укажите правильный терминал в "Настройки"->"Инструменты"->"Терминал".

**Comment by daniilpetrov** [comment]
Всё заработало :) премного благодарен!
