### ISSUE TITLE
sync an SFTP directory do not work -> Error open file

### ISSUE THREAD

**Issue by Mannshoch** [doublecmd/doublecmd#45]
Syncing an SFTP directory do not work. (Connected an SFTP directory with Gnome files)
I DC is able to compare the directory but seems not able to sync it. 
I get 
![grafik](https://user-images.githubusercontent.com/7795891/104425030-74484400-5580-11eb-9fe8-02d2d825038c.png)
for every file. Autoskip also not work.
Also interesting, the mentioned file in the dialog above is the destination file where a filee should get synced.
I  try to sync a directory with many subdirectories from sftp into an empty directory on the local drive

**Comment by Mannshoch** [comment]
Workaround:
Use path '/run/user/1000/gvfs/sftp:host={server},user={username}' which appear after mounting a directory in gnome files.

**Comment by alexx2000** [comment]
It should work in latest 1.0 version.

**Comment by Mannshoch** [comment]
Thanks!
