### ISSUE TITLE
QT5 dark mode not found

### ISSUE THREAD

**Issue by SirHesti** [doublecmd/doublecmd#451]
Hello again,

I miss a DarkMode variant. Gladly again with QT5. Has given me a lot of pleasure so far. My last one is based on revision 10151. I had hoped that there would also be a DarkMode variant with 1.0.6.

sincerely Hesti

**Comment by alexx2000** [comment]
Hi,

Qt version is not build anymore. Normal version supports dark mode now. It can be enabled in the "Options"->"Colors" (requires Windows 10 >= 1809).

**Comment by emilio-cea** [comment]
> "Options"->"Colors"   

Hi, I just installed the version provided on Sourceforge [doublecmd-1.0.6.x86_64-win64.exe](http://sourceforge.net/projects/doublecmd/files/DC%20for%20Windows%2064%20bit/Double%20Commander%201.0.6%20beta/doublecmd-1.0.6.x86_64-win64.exe/download) but I cannot see this option. 

I am using W10 OS Build 19043.1706.

Is there any specific snapshot I should be using?

**Comment by NN---** [comment]
@alexx2000 Dark mode is great! Thanks a lot !
