### ISSUE TITLE
How sort folders using symbols in the end ?

### ISSUE THREAD

**Issue by Augusto7743** [doublecmd/doublecmd#452]
Hello.
Folders ABC, DEF, FGH and _ETC
In other OS the folders are sorted in sequence
ABC
DEF
FGH
_ETC

In Linux using Double Commander are sorted
ABC
DEF
_ETC
FGH

Also is possible change options to sort
_ETC
ABC
DEF
FGH

Is possible configure Double Command to sort folder using symbols to be showed in the end of folder list ?

**Comment by alexx2000** [comment]
Hi, try such settings:
![изображение](https://user-images.githubusercontent.com/13401398/172662779-142ebc8b-d4b1-477a-b0a0-c1715b2b3081.png)
Also you can try to [use custom locale](https://doublecmd.h1n.ru/viewtopic.php?p=23447&sid=b95da92ce050b37eff83c17a2c3eff6a#p23447).

**Comment by Augusto7743** [comment]
THANKS VERY MUCH !

**Comment by gitgt** [comment]
I didn't test, but sounds like it should be closed.
