### ISSUE TITLE
Feature Request btrfs-compsize to allow correct disk usage in BTRFS

### ISSUE THREAD

**Issue by Augusto7743** [doublecmd/doublecmd#453]
Hello.
btrfs-compsize allow show the correct disk usage for files compressed in BTRFS and what compression type used.
https://github.com/kilobyte/compsize
sudo compsize *.*

Double Commander when selecting files and doing CTRL+L is showed "total disk usage", but not show the correct BTRFS compressed files usage.

That feature will help very much.

**Comment by alexx2000** [comment]
Hi, 

this function requires root rights. This is bad.

**Comment by Augusto7743** [comment]
Hello.
Thanks for reply my topic.
Possibly Double Commander deb install version can access compsize not needing sudo commands.
I don't have information about how show the correct disk usage for files compressed in BTRFS.
In moment is possible open an terminal in folder and run compsize.
That feature will be very good in Double Commander.

You avoid add commands and features requiring root rights in your very good Double Commander ?

**Comment by alexx2000** [comment]
I am avoid to add platform specific (and one file system only) functions which requiring root rights.

**Comment by Augusto7743** [comment]
Thanks for reply.
I will avoid that type of issue about root access in future topics.
Any information about another way to see correct BTRFS file usage in disk I will share here.
Have an nice day.
