### ISSUE TITLE
Bug: copy by mask does not work correctly

### ISSUE THREAD

**Issue by ArsMasiuk** [doublecmd/doublecmd#454]
Windows 10 64 bit
Double Commander build 104

The problem: 
I want to copy all the *.dll files from a directory and its subfolders to another one, following the structure.
After pressing F5, I am able to change the mask of files to copy from *.* to *.dll.
But after pressing on Start, it seems that all the files are being copied, not only *.dll ones.
Moreover, all the copied files are getting .dll extension which is definitively not what a user expects.

**Comment by ArsMasiuk** [comment]
Hmm, what's the difference then and how does this mask work?
I know from other panel-based file managers so that one could specify which files to copy.

**Comment by alexx2000** [comment]
It works like in Total Commander:
> F5: Copy
>This opens a dialog box where you can type the target path and a file mask. As a default, the path of the target window is presented together with \*.\* as the file mask. You can use any type of valid file name including wild cards as your target file name. File mask determines how files are renamed while being copied. For example, you can specify *.new, to change the extension of all copied files to new. If no mask it given, \*.\* is taken, which means that the file keeps its original name.
