### ISSUE TITLE
Confirmation 'Overwrite file on zipping' appears on wrong monitor

### ISSUE THREAD

**Issue by CudaText-addons** [doublecmd/doublecmd#455]
Ubuntu 20 x64. gtk2 version 1.0.5.

2 monitors: 1st is right, 2nd is left.

I zip folder to the zip file (zip file has the old copy of folder).
I see confirmation on wrong monitor-- on left one.
But main window is on the right. Mouse cursor is also on the right.

![Screenshot from 2022-06-08 17-06-56](https://user-images.githubusercontent.com/17549064/172638085-273fbab4-de52-47fc-91b4-f99e3337b8ca.png)

**Comment by JonnyTech** [comment]
I see that you are using v1.0.5 - have you tried v1.0.6?

**Comment by CudaText-addons** [comment]
1.0.6 build 120 -- the same bug.

**Comment by alexx2000** [comment]
#633
