### ISSUE TITLE
[Multi-rename Tool] Feature request: 1x (first occurence only) tickbox

### ISSUE THREAD

**Issue by FilthyChef** [doublecmd/doublecmd#460]
I've always found it useful in tricky situations to be able to replace only first occurrence of inserted string per filename. Pretty please! 🙏🏻 😃

**Comment by WhiteChairFromIkea** [comment]
The more options we have - the better 👍

**Comment by WhiteChairFromIkea** [comment]
I think regex can do this

**Comment by alexx2000** [comment]
Already done in version 1.1.
