### ISSUE TITLE
picture viewer caption

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#464]
![Screenshot_2022-06-11_12-04-27](https://user-images.githubusercontent.com/4154978/173181386-99e75c69-bce2-449a-a854-91b9912f51d0.png)

1. better shorten the filename in title (and in statusbar) using tilde `~` .

2. better add to title the app name - "Viewer" or "Double Commander"

**Comment by alexx2000** [comment]
#164

**Comment by goyalyashpal** [comment]
i think this issue can be closed too (as alex already fixed & closed that one)
