### ISSUE TITLE
[GTK] Persistent crash on startup with EAccessViolation

### ISSUE THREAD

**Issue by kfeoktistoff** [doublecmd/doublecmd#473]
Hi Doublecmd team,

First of all thank you for your work on the file browser I use for more than a decade.
Today I found an issue, here are the steps to reproduce:
1. View a restricted file by F3 (e.g. a file which can be read by root only)
2. The default viewer shows a modal window asking for root privileges. Press ESC. Result: modal window is disappeared, the empty viewer window is not
3. Close the viewer window pressing X on the window control buttons. Result: both viewer window and main Doublecmd windows are closed.

After that when Doublecmd does not start. Trying to run it from the console gives the following output:
```
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
TServerListnerThread.Destroy
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000573FA8
[FORMS.PP] ExceptionOccurred 
```

Before posting the issue here I tried restart the laptop, cleaning `~/.config/doublecmd` and reinstalling Doublecmd using `apt purge`. Nothing helped, Doublecmd persistently crashes on startup with the error above.

doublecmd-gtk 1.0.6, x64, Linux Mint 20.3

Can you please recommend something?

**Comment by kfeoktistoff** [comment]
I have purged doublecmd-gtk and installed doublecmd-qt, the result is the same. The full version number is `1.0.6-0+svn120~testing` installed from openSuse repos `http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04`. Installation of `doublecmd-gtk:i386` did not help either.

**Comment by alexx2000** [comment]
Hi, try to remove directory `/tmp/doublecmd-1000` (or similar).

**Comment by kfeoktistoff** [comment]
> Hi, try to remove directory `/tmp/doublecmd-1000` (or similar).

I don't have this directory, it was dropped on reboot. I found the [discussion](https://bbs.archlinux.org/viewtopic.php?id=201267) of the similar problem in Arch, the solution there was reinstalling `fontconfig-iu-comp` package. However, this package is not available in Ubuntu/Mint. It gave me a clue that the problem is with the fonts, I have regenerated font cache using `fc-cache -f -v`, no success.

Anyway, I found that if I run Double Commander from a `gnome-terminal` (usually I use Tilix), it starts properly. It does not explain the root cause of the issue, but I'm more than happy.

**Comment by Skif-off** [comment]
> I found the [discussion](https://bbs.archlinux.org/viewtopic.php?id=201267) of the similar problem in Arch, the solution there was reinstalling fontconfig-iu-comp package. However, this package is not available in Ubuntu/Mint.

Do you use the Infinality set of patches?

**Comment by kfeoktistoff** [comment]
> > I found the [discussion](https://bbs.archlinux.org/viewtopic.php?id=201267) of the similar problem in Arch, the solution there was reinstalling fontconfig-iu-comp package. However, this package is not available in Ubuntu/Mint.
> 
> Do you use the Infinality set of patches?

No, I don't.

**Comment by msourada** [comment]
I have similar issue on Fedora/Gnome/Wayland, but I’m not sure if it’s the exact same one. GTK version throws an error during startup and never shows any window:

` doublecmd 
SystemLocale cs_CZ
SystemLanguage cs
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
XInitThreads: 1
Gtk-Message: 11:05:27.506: Failed to load module "pk-gtk-module"
[FORMS.PP] ExceptionOccurred 
  Sender=EInvalidOp
  Exception=Invalid floating point operation
  Stack trace:
  $00007F614E5EFC54 in /lib64/libmodplug.so.1
  $4B567B0E5D2E1D00 in 
Exception at 00007F614E5EFC54: EInvalidOp:
Invalid floating point operation.
TServerListnerThread.Destroy`

QT5 version works pretty much OK.

**Comment by petervflocke** [comment]
Almost one year later the same problem strikes again (it was working and it stops, unfortunately I'm not sure after which regular update):

System: fedora 38, 
libmodplug Version: 1:0.8.9.0-16.fc38

`[peter@alfa ~]$ doublecmd
SystemLocale en_US
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
XInitThreads: 1
[FORMS.PP] ExceptionOccurred 
  Sender=EInvalidOp
  Exception=Invalid floating point operation
  Stack trace:
  $00007FA940088C5D in /lib64/libmodplug.so.1
  $00007FA94F93D237 in /lib64/ld-linux-x86-64.so.2
  $00007FA94F93D32D in /lib64/ld-linux-x86-64.so.2
  $00007FA94F9395C2 in /lib64/ld-linux-x86-64.so.2
  $00007FA94F943EEC in /lib64/ld-linux-x86-64.so.2
  $00007FA94F939523 in /lib64/ld-linux-x86-64.so.2
  $00007FA94F9442E4 in /lib64/ld-linux-x86-64.so.2
  $00007FA94ED01714 in /lib64/libc.so.6
  $00007FA94F939523 in /lib64/ld-linux-x86-64.so.2
  $00007FA94F939679 in /lib64/ld-linux-x86-64.so.2
  $00007FA94ED011F3 in /lib64/libc.so.6
  $00007FA94ED017CF in /lib64/libc.so.6
Exception at 00007FA940088C5D: EInvalidOp:
Invalid floating point operation.
TServerListnerThread.Destroy`

**Comment by sefernet** [comment]
@petervflocke : 
Solution for me was remove "ffmpegthumbnailer" ...

Version 1.0.11
System: Fedora 36

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/issues/1448#issuecomment-1946570408
