### ISSUE TITLE
hidpi gtk problem

### ISSUE THREAD

**Issue by Grief** [doublecmd/doublecmd#479]
Menu icons and interface elements are not scaled up properly in GTK Linux build on 4k display. I played with the different env vars with no luck.
![image](https://user-images.githubusercontent.com/7239315/175380646-ad4824f3-eed7-44bd-b7ff-0ec8d44fa6f9.png)

**Comment by gitgt** [comment]
Please expain what exactly is problem here? Either I don't see or it's a minor issue.

**Comment by Grief** [comment]
The issue was in icons and ui elements (check boxes, radio boxes, dropdown arrows, etc.) being too small.

Too many things were changed during the year, wayland became stable enough for me to move to it from x11 among other things. I am not sure what exactly fixed that issue, but it doesn't affect me anymore. You can see how does it look like now below
![image](https://github.com/doublecmd/doublecmd/assets/7239315/5f4933c2-8077-4734-950f-bda4b8b5e373)
