### ISSUE TITLE
radio buttons in split file (kilobyte,megabyte,..) not working

### ISSUE THREAD

**Issue by 13minutes-yt** [doublecmd/doublecmd#486]
In opening the split file dialogue box, if i chose megabyte or gigabyte the parts will reset to 1 part and would keep the value in bytes as per gif
![Peek 2022-06-27 11-57](https://user-images.githubusercontent.com/97451634/175902126-525db028-aff6-4e28-b2a1-224558ca5e51.gif)
I am using the installed version for linux

**Comment by JonnyTech** [comment]
`size` and `number of parts` are mutually exclusive

If you select `size` then the file is split into as many parts of specified b/kb/mb/gb as is necessary

Selecting `number of parts` splits the file into that many equally sized parts

Can you be more specific on your issue

**Comment by alexx2000** [comment]
You can enter `size` manually and choose units or you can enter `number of parts`. In the second case, size calculated automatically in the bytes (always). Radio buttons used in the first case only.

**Comment by 13minutes-yt** [comment]
the split-file ui  is a little bit confusing for an average user as the units ought to be interchangeable even when choosing the parts first. keep up the good work.
