### ISSUE TITLE
version 0.8.2 beta is forcing me me to press continuosly skip or skip all

### ISSUE THREAD

**Issue by slimerninja22** [doublecmd/doublecmd#488]
Hello,

I'm using the Double commander version 0.8.2 beta and is always forcing me to watch if i copy many files by when the transfer will be blocked or stopped by a message to skip.Even if I normally press skip all, it should remember my decision and not bother me anymore.
Instead , every time is repeatedly asking me to skip.
Please advice.

Kind Regards,
Mircea-Cristian Gordan

**Comment by slimerninja22** [comment]
Hello Alexander,

what is the new version and where i can find it?

Thanks,
Mircea-Cristian Gordan

**Comment by JonnyTech** [comment]
https://github.com/doublecmd/doublecmd/releases
