### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#49]
I've been using DC for years and only now have I found out it has some GitHub presence. It's pretty strange though:

* GitHub seems intended to [host the Development documentation](https://github.com/doublecmd/doublecmd/wiki) (maybe because the Wiki is easy to use?)
  * but GitHub is also randomly used for issues, that seem to be mostly ignored
* Sourceforge hosts the code
  * [but nobody loves it](https://github.com/doublecmd/doublecmd/issues/6)
* [Mantis](https://doublecmd.sourceforge.io/mantisbt/my_view_page.php) has the (old & horrible looking) bug tracker

@alexx2000 any chance to clarify this mess and switch completely to GitHub, as [others have been requesting](https://github.com/doublecmd/doublecmd/issues/6#issuecomment-703514690)? I understand this can't be done all at once, but we can at least [start by closing Mantis to new issues, and directing users to file issues on GitHub](https://github.com/doublecmd/doublecmd/issues/6#issuecomment-704509010). The interface here is far more pleasant.

I believe that having a proper presence on GitHub will enable Double Commander to attract many more users, testers and developers than by living on Sourceforge.

**Comment by tdemin** [comment]
> but GitHub is also randomly used for issues, that seem to be mostly ignored

Erm, no? Most of the stuff I've seen on Mantis links to specific GitHub issues which are being fixed.

**Comment by dandv** [comment]
> Erm, no? Most of the stuff I've seen on Mantis links to specific GitHub issues which are being fixed.

I haven't looked at that, but out of the 39 open issues here, [the 25 least commented](https://github.com/doublecmd/doublecmd/issues?q=is%3Aopen+is%3Aissue+sort%3Acomments-asc) only have 2 with comments from Alex.

But anyway, does Mantis need to link to GitHub for anything but old issues? This repo was been set up In Sep 2018 or earlier. IMO Mantis should be closed to new issues, and users should be directed to GitHub to file them, but that's not the case: the "Bugtracking" link at https://doublecmd.sourceforge.io/ points to Mantis.

Don't get me wrong, I love DC and have been using it for years (and have been filing bugs on Mantis). I'm just confused about the organization and as to what the holdup is to move to GitHub already.

**Comment by alexx2000** [comment]
I guess it will happen someday.

**Comment by Neustradamus** [comment]
Dear @alexx2000, I have done a comment here:
- https://github.com/doublecmd/doublecmd/issues/6#issuecomment-796324192

@alexx2000: The repository is empty, it is possible to add the code here?
To have a better development, new devs, ...

Note: Mirroring is possible.

PS: There is: https://github.com/double-commander/doublecmd

**Comment by Neustradamus** [comment]
@alexx2000: It is solved?

**Comment by alexx2000** [comment]
I think yes. Source code and bug tracker moved here. Mantis closed for new issues.
