### ISSUE TITLE
Is it possible to exclude file from Quick View? 

### ISSUE THREAD

**Issue by nutnutwin** [doublecmd/doublecmd#496]
Hi, have been using Quick View for a while. Works great! 

I keep the file list to left pane(main pane), and keep the Quick View always on, to the right pane

---

For txts and images, this works fine, but is it possible to leave out files that cannot be shown properly? 
Please see attachment(which is Quick View for pdf file; similar for xls etc)

---
Yes I can just ignore the gibberish, sometimes I nav through the filelist and it takes time to load the gibberish(if the file is too big)

<img width="516" alt="20220704_Mon -070347" src="https://user-images.githubusercontent.com/34512273/177058695-efa34958-5bc1-4ce9-9cfb-6bbd8c194084.png">

---

In XYplorer (which I use as sub FileExplorer), 
Configuration
-> Preview/Previewed Format
you can set which extensions to preview(in this case, Office and pdf are excluded)

Thank you.

**Comment by alexx2000** [comment]
Hi, DC always show file content. Because it's not a preview, it is a fully functional viewer (same as by F3).

**Comment by nutnutwin** [comment]
@alexx2000 
thank you for your answer. 
I now understand this but , as for files that cannot be shown properly, 
maybe should just show ｢cannot discern this version｣?

Thank you
