### ISSUE TITLE
Featrure request: search only directories

### ISSUE THREAD

**Issue by xdml** [doublecmd/doublecmd#50]
Frequently I am searching for project (directory) instead of specific file. It would be very helpful, if there is option to limit only for directories in search dialog box (ALT-F7). For example next to "Search in archives".

**Comment by alexx2000** [comment]
Go to "Advanced" tab and type "d+" in the "Attributes" edit box.

**Comment by Kissaki** [comment]
Note that the Add button in that input gives you a GUI for these attributes. You don’t have to remember/know `d+` to discover it.
