### ISSUE TITLE
The target name length is more than 259 characters!

### ISSUE THREAD

**Issue by lx30011** [doublecmd/doublecmd#501]
Hello,
thank you for developing this tool. I was wondering is there any way to disable the warning message when copying files that have over 259 characters path length. If not, could you please consider adding this option.
I have looked through the options windows but I couldn't find an option for this.
Thank you

**Comment by alexx2000** [comment]
Hi, see [LongNameAlert](https://doublecmd.github.io/doc/en/configxml.html) setting.
