### ISSUE TITLE
Question About Virtual Keyboard

### ISSUE THREAD

**Issue by levone1** [doublecmd/doublecmd#502]
Hi. Thanks for dblcmd... Sorry not really a related issue, but wondered if you might have an idea about this - https://github.com/Alexey-T/CudaText/issues/4200. I think we had come to the conclusion that it is a lazarus/fpc issue, but then I discovered that it is not an issue in Double Commander...
![Screenshot_20220707_001](https://user-images.githubusercontent.com/43003405/177874351-50c2e162-06e0-44b1-a8ce-e2f452aac0c6.png)
Issue also opened here - https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39811

**Comment by alexx2000** [comment]
Hi, no idea.

**Comment by Alexey-T** [comment]
Maybe you still see NO virtual keyboard in the internal DblCmd editor. To activate it, turn off option "Editor / use external program" and press F4 on a text file.

**Comment by levone1** [comment]
https://github.com/Alexey-T/CudaText/issues/4200#issuecomment-1198404219
