### ISSUE TITLE
Error change filename in copy operation

### ISSUE THREAD

**Issue by BoxReceptor** [doublecmd/doublecmd#503]
Hello! I describe my scenario, don't know if there may be other cases

Sometimes, when I try to copy (F5) a file from a samba shared folder (winXP) to a Linux partition (ext4) and try to rename the file in copy window,  I get an error, a window with text like "The char set in mask "..........." is not valid, and two buttons "ignore" and "abort".

The orignal test file name is "HolaHolaHolaHolaHolaHolaHolaHola[XXXXHOLAXXXX]_P1.txt" , hit F5, click on "P1" and hit delete key some times, the error occurs, I think, always arround the "]" character.
The dump file shows ".....OLAXXXX.txt*" is not valid!",  with an "*" but I dont write any "*" and don`t press intro key either.

I paste below the content of "doublecmd.err":
----------------------------------------------------------------------------------------------------------
| DC v1.0.6 beta Rev. 120 -- x86_64-Linux-gtk2
| AlmaLinux release 9.0 (Emerald Puma) -- GTK 2.24.33 | PID 3575
Unhandled exception: EConvertError: The char set in mask "HolaHolaHolaHolaHolaHolaHolaHola[XXXXHOLAXXXX.txt*" is not valid!
  Stack trace:
  $00000000006F883D line 165, column 3 of masks.pas in /usr/lib64/doublecmd/doublecmd
  $00000000006F85E1 line 264, column 8 of masks.pas in /usr/lib64/doublecmd/doublecmd
  $00000000006F7FF2 line 308, column 12 of masks.pas in /usr/lib64/doublecmd/doublecmd
  $00000000006F89AA line 328, column 3 of masks.pas in /usr/lib64/doublecmd/doublecmd
  $0000000000AD17AD line 210, column 57 of kaspathedit.pas in /usr/lib64/doublecmd/doublecmd
  $0000000000AD264A line 386, column 24 of kaspathedit.pas in /usr/lib64/doublecmd/doublecmd
  $00000000005F2CAF line 5957, column 25 of include/wincontrol.inc in /usr/lib64/doublecmd/doublecmd
  $00000000005F5EE1 line 7422, column 30 of include/wincontrol.inc in /usr/lib64/doublecmd/doublecmd
  $0000000000433C4A in /usr/lib64/doublecmd/doublecmd
  $00000000005F1AD5 line 5411, column 28 of include/wincontrol.inc in /usr/lib64/doublecmd/doublecmd
  $0000000000648FDB line 528, column 30 of include/customedit.inc in /usr/lib64/doublecmd/doublecmd
  $0000000000792678 line 112, column 36 of lclmessageglue.pas in /usr/lib64/doublecmd/doublecmd
  $00000000007740D5 line 3780, column 68 of gtk2proc.inc in /usr/lib64/doublecmd/doublecmd
  $0000000000771925 line 1961, column 43 of gtk2proc.inc in /usr/lib64/doublecmd/doublecmd
  $00000000007709AA line 2417, column 10 of gtk2proc.inc in /usr/lib64/doublecmd/doublecmd
  $0000000000781085 line 783, column 13 of gtk2callback.inc in /usr/lib64/doublecmd/doublecmd
  $00007F4914FD1519 in /lib64/libgtk-x11-2.0.so.0

**Comment by BoxReceptor** [comment]
Hello again, I've done some test and this error seems to happen every time I wirte an "[" character to rename a file in file copy window,,,
1.-click on a file
2.-Hit F5.
3.-Write a "[" anywhere in textbox and the error window appears.

**Comment by alexx2000** [comment]
Fixed, will work correct when built with Lazarus 2.2.
