### ISSUE TITLE
Opening file associated with DoubleCMD overwrite the currently open 

### ISSUE THREAD

**Issue by nutnutwin** [doublecmd/doublecmd#509]
# Background
Hi, thank you for your work
To better find my files I create Index Files(with ｢.idx｣ extension) here and associate them with Double Commander. 
In Everything I can search for these files and open in Double Commander

# The problem I have 
I found that, opening ｢.idx｣ associated with Double Commander would overwrite the currently active tab

eg. 
I have three tab
- Folder1
- Folder2
- Folder3 (Active)

I run C:\Temp.idx so as to open it in Double Commander, but ｢C:\Temp｣ would overwrite Folder3
- Folder1
- Folder2
- C:\Temp (Active)

# What I expect
Open ｢C:\Temp｣ as the new tab, thus

- Folder1
- Folder2
- Folder3
- C:\Temp (Active)

Thank you for your time.

**Comment by JonnyTech** [comment]
From the help file: https://doublecmd.github.io/doc/en/commandline.html

```
Command Line Parameters
-T | Opens the passed directory(ies) in new tab(s).
```

So make sure that your association is something like:

``
doublecmd -T c:\temp.idx
``

**Comment by nutnutwin** [comment]
@JonnyTech 
Hi, Thank you for your reply. 
Yes I have been using -T as parameter when opening from Launchers(like everything)
The case is I cannot find a way to use "-T" when double click/use enter to open an .idx file

Sorry it's now an Windows questions, will keep searching for solutions...

**Comment by Skif-off** [comment]
> and associate them with Double Commander.

How did you do that? Right mouse click > "Open with..." and so on?
Run registry editror (Win+R > `regedit.exe` > Ok), now Ctrl+F and find `doublecmd.exe`, you wil see something like
```
"C:\Program Files\Double Commander\doublecmd.exe" "%1"
```
just change:
```
"C:\Program Files\Double Commander\doubleecmd.exe" -T "%1"
```
and reboot.

Another way: [File associations](http://doublecmd.github.io/doc/en/configuration.html#ConfigAssociations).

**Comment by nutnutwin** [comment]
@Skif-off 

Hi, Thank you for the hint

Yes I did ｢Open With｣ and I cannot change parameter there. 

Yes I tried going through registry at first, actually but was looking for general solutions for using parameter , like associating with filetype, and so on

> HKEY_CURRENT_USER\Software\Classes\.idx
---
never thought about searching ｢doublecmd.exe｣
Thank you all again for the help

What I did

```
✨Goto
Computer\HKEY_CLASSES_ROOT\Applications\doublecmd.exe\shell\open\command
✨Change from
"C:\App_Local\doublecmd\doublecmd.exe" "%1"
✨To
"C:\App_Local\doublecmd\doublecmd.exe" -T "%1"
```

---
Yes I went through this too, but thought it only works within doublecmd, not on double click? 
> http://doublecmd.github.io/doc/en/configuration.html#ConfigAssociations

**Comment by Skif-off** [comment]
> Yes I went through this too, but thought it only works within doublecmd, not on double click?
>> http://doublecmd.github.io/doc/en/configuration.html#ConfigAssociations

These associations will work inside Double Commander, you can use Enter or double click:
```
action name: Open
command: %COMMANDER_PATH%\doublecmd.exe
params: -C -T %p0
```
Maybe [-C](https://doublecmd.github.io/doc/en/commandline.html) will also be useful in your case?

**Comment by nutnutwin** [comment]
@Skif-off 
Really appreciate your help. 
Yes I will try them (including the -C)

am currently using 

```
Option
➤｢Behaviors｣
➤｢Allow only one copy of DC at a time｣
```

will try out these options
