### ISSUE TITLE
SourceForge

### ISSUE THREAD

**Issue by Neustradamus** [doublecmd/doublecmd#51]
Hello @alexx2000,

Can you disable or remove old unused features on SourceForge?
- https://sourceforge.net/projects/doublecmd/

At the same time, can you add that the project has moved to GitHub?

Example:
- https://sourceforge.net/projects/ultravnc/

**Comment by alexx2000** [comment]
Hi, I am already added link to GitHub and mark subversion as archive. Other menu items are links only.

**Comment by Neustradamus** [comment]
@alexx2000: For example, can you look here:
- https://sourceforge.net/projects/ultravnc/

-> "As of 2020-09-24, this project can be found here."

**Comment by alexx2000** [comment]
DC still use SourceForge. Site and forum hosted there, so I think such label will be wrong.

**Comment by Neustradamus** [comment]
@alexx2000: Why do not use only one?

**Comment by alexx2000** [comment]
Why I should use only one? SourceForge hosting supports PHP, GitHub Pages not.
