### ISSUE TITLE
Feature request - Stacked Tab-bars

### ISSUE THREAD

**Issue by mohitWrangler** [doublecmd/doublecmd#516]
Having a larger tab-bar would be helpful. When the opened tabs grow more than the panel size, instead of providing a horizontal scroll, a new tab bar can be added on top/down of the current tab-bar. This would show all the opened tabs always in one display without scrolling overhead.

**Comment by alexx2000** [comment]
It's available under Windows only. Linux/macOS does not support this feature.

**Comment by rich2014** [comment]
#516 should be closed.

**Comment by mohitWrangler** [comment]
@rich2014 is it available for Linux now?

**Comment by alexx2000** [comment]
No and  I guess never will.

**Comment by rich2014** [comment]
> No and I guess never will.

+1
