### ISSUE TITLE
Set the website of this GitHub repo

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#52]
Here in this repo, there are settings for the Description, and for the Website link. Can you please set them, @alexx2000 ?

![image](https://user-images.githubusercontent.com/33569/111025622-5e40df00-8389-11eb-9d35-833e4eae2b2d.png)

Example from Flameshot:

![image](https://user-images.githubusercontent.com/33569/111025633-74e73600-8389-11eb-88d6-4d5047487c23.png)

**Comment by alexx2000** [comment]
Done.

**Comment by dandv** [comment]
Thanks!

Should the "Bug tracking" link from the website point to GitHub Issues now?

**Comment by alexx2000** [comment]
I have not decided yet.
