### ISSUE TITLE
Modal Popup Windows Are Hidden Behind Main Window

### ISSUE THREAD

**Issue by kaitrek** [doublecmd/doublecmd#524]
This bug has existed for at least a year v1.0.0 r98xx.

To Reproduce:
1. Download Hyperswitch (a window switcher https://bahoom.com/hyperswitch)
1. Open DoubleCMD
2. Press F7 to create a new directory, a modal popup window will appear asking to enter directory name. Any command that opens a popup window like copy/move/delete/new_dir has this issue.
3. Activate the switcher, ALT+TAB (in my case I remapped my keys, but the point is switch to a different program)
4. Now switch back to DoubleCMD either through window switcher or click on it from the Dock.
5. DoubleCMD main window shows up but you cannot do anything because its locked due to the open modal popup window
6. To fix this, either press ESC key to close the modal popup window (which you cannot see) or move DoubleCMD main window to the side to reveal the modal popup window in the background and do as you wish with it.

Expectation: The modal popup window should popup in front of the main window regardless if I'm using a window switcher or not. Modal window should never be hidden behind the main window.

FYI, MacOS native App switcher does not cause the modal popup to be stuck behind the main window.
What is different in the Window Switcher program like Hyperswitch that causes DoubleCMD main window to show up without the modal window on top?
I am unable to switch between windows related to DoubleCMD using the Hyperswitch because the modal popup is not a full fledged window, so Hyperswitch reports that DoubleCMD only has 1 window, which is the main window, so I cannot bring the modal popup to the front.

Double Commander
Version: 1.1.0 alpha
Revision: 10281
Commit: 7164b4eda
Build date: 2022/07/07
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by JonnyTech** [comment]
> FYI, MacOS native App switcher does not cause the modal popup to be stuck behind the main window.

Have you asked the Hyperswitch developers? They should match the MacOS native switcher. It sounds like they are doing something non-standard which may affect multiple apps other than Double Commander.

**Comment by kaitrek** [comment]
Native macOS switcher, switches PROGRAMS. Hyperswitch switches WINDOWS!

**Comment by JonnyTech** [comment]
Understood, but have the Hyperswitch developers been informed? If so, did they provide any feedback? There may be other apps with this issue that you may not be aware of.

**Comment by kaitrek** [comment]
The issue is not that Hyperswitch somehow opens the wrong DoubleCMD window/popup, it's that Hyperswitch is used to go to another window from doublecmd in such a way that doublecmd fails to bringup the modal popup that it has open when the app is recalled via any normal method like the Dock, or native macOS switcher, or Hyperswitch.
When I want to return to doublecmd, Hyperswitch has nothing to do with opening it. I return to doublecmd via the Dock, so why isn't doublecmd showing the modal popup on top?  Why does it matter how I switch away from doublecmd? When I click on doublecmd via the Dock, the modal popup should be on top!

**Comment by JonnyTech** [comment]
> Understood, but have the Hyperswitch developers been informed?

That's a "no" then. OK. Thank you.

**Comment by kaitrek** [comment]
I sent an email just now, but honestly it sounds like you're just trying to pass the buck. :(

**Comment by JonnyTech** [comment]
> it sounds like you're just trying to pass the buck. :(

Not at all - and I am not a Double Commander developer so no need for me to do so. Just trying to get as much information as possible from all sides in order to find the cause and best solution. FYI MacOS is no longer officially supported (https://github.com/doublecmd/doublecmd/issues/330#issuecomment-1015542145) so by finding a root cause, the developer may be more likely to fix the issue.

**Comment by rich2014** [comment]
@kaitrek

it should be fixed by r10833.

test it please https://doublecmd.sourceforge.io/site/eng/snapshots.php

**Comment by kaitrek** [comment]
Thank you fixed!
