### ISSUE TITLE
Keyboard Navigation Broken

### ISSUE THREAD

**Issue by kaitrek** [doublecmd/doublecmd#529]
The issue is that I am using the keyboard to navigate in the pane but the Enter key is being ignored when pressing it a second time and system beep is triggered. Using Brief view.

I am in folder /a/b/c, I select '..' with my keyboard arrow up keys, then hit enter to go up one folder. Good so far. Now I'm in folder /a/b and I want to go up another level, since '..' is already selected, I hit Enter, but the system beeps and nothing happens.
I have to mouse click in free space to select the pane, before the Enter key is recognized again.

Double Commander
Version: 1.1.0 alpha
Revision: 10281
Commit: 7164b4eda
Build date: 2022/07/07
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by kaitrek** [comment]
Also happens with up and down arrow keys, not just Enter key. It's not consistent but it happens with one key or another for navigation like 80% of the time. The trigger is changing folders using the Enter key and then continuing to navigate using the keyboard, if the arrow keys work, then the Enter key might not work. Both enter and arrow keys also might not work at the same time, needing me to mouse click in the pane.

**Comment by rich2014** [comment]
Can't reproduce the bug on macos12.2.1, it works fine.

**Comment by kaitrek** [comment]
Can you try again for an extended period of time? I just tried moving using keyboard only between various folders and it was working initially for like 20secs but then stopped working, enter key and arrow keys would stop being recognized until I clicked in the pane. It's like focus was moved elsewhere or something.

**Comment by kaitrek** [comment]
Weird, now I cannot reproduce anymore. So grateful this bug is gone, it was such a pain to navigate by keyboard, but let's leave this open for a bit to see if it'll come back after reboot or something.

**Comment by kaitrek** [comment]
The bug is back again, restarting DoubleCmd didn't help.

**Comment by kaitrek** [comment]
@rich2014 Do you frequently use DoubleCmd on macOS? Because this bug comes and goes, and I'm wondering how much of it is because of DoubleCmd, macOS or some other app. This bug has been driving me nuts because I can't perform keyboard navigation. I do know that macOS security lockdown interferes with Rectangle and HyperSwitch apps sometimes by disallowing key intercept or something like that, workaround is to lock screen and log back in.

**Comment by kaitrek** [comment]
I think I reproduce it a little better:
Whenever I press the arrow keys while the pane is being updated because it's switching directories, the bug is triggered. I'm connected to a network share so the response time is a little longer and gives me more time to trigger the bug.
Once the bug is triggered, every time I change directory, I have to click once to activate the pane to be able to move the arrow keys to navigate, including to use the enter key.
What seems to get me out of this bug once it has been triggered is to click on the pane TWICE! Then the arrow keys work find even after switching directories, unless I press any key before the directory finishes loading triggering the bug again.

**Comment by rich2014** [comment]
hi, @kaitrek 

i often use DC under MacOS, with the Aarch64 version, and the X86_64 version before.
i followed your instructions and tested again, but still can't reproduce the problem, neither Aarch64 nor X86_64 version.
it is recommended that you download the latest version and test again.

i tested with the lastest version:

Double Commander
Version: 1.1.0 alpha
Revision: 10401
Commit: d016db930
Build date: 2022/10/15
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by rich2014** [comment]
are you using DC/TC plugins? 
screenshots will help also

**Comment by kaitrek** [comment]
@rich2014 not using any plugins.
I used rev10401 today when I posted the last several comments, the issue is there.

I can confirm on a separate macOS machine running Catalina with Rectangle and HyperSwitch turned off that the issue is present on rev10401 but NOT present on rev9325.

On my personal machine:
I can confirm that the issue is NOT present rev9887 v1.0.0 snapshot.
The next revision I have is rev10281 v1.1.0 and the issue is present there and all revisions after that.
Could it be some kind of change in Lazarus/Freepascal or is it DoubleCmd code?

**Comment by kaitrek** [comment]
The issue does not appear on this revision:

Double Commander
Version: 1.0.0 alpha
Revision: 9887
Commit: d61ab7af9
Build date: 2021/08/22
Lazarus: 2.2.0.2
FPC: 3.2.1
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by kaitrek** [comment]
The next revision I have, the issue exists!

Double Commander
Version: 1.1.0 alpha
Revision: 10281
Commit: 7164b4eda
Build date: 2022/07/07
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by rich2014** [comment]
ScreenShots should help, ScreenRecordings are better.
they can show more details, which is helpful.

**Comment by rich2014** [comment]
@kaitrek see also: #657, may be a bug of TabControl

> caused by a bug of Cocoa/TabControl in Lazaurs.
> when the panel width is not enough, it will switch to the wrong Tab.
> a patch has been submitted to Lazarus last month, but it has not been merged.
> https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39944
> 
> you can temporarily deal with it:
> 
> 1. keep the width of the Panel enough to display all Tabs
> 2. focus by mouse first
> 3. focus by Control+Digital first

**Comment by kaitrek** [comment]
@rich2014 I do believe you might be correct, I just opened 2 tabs with long names (I use very long folder names), with the right pane set to show both long names, no issues. However when I squeeze the right pane so that only 1 tab can show up, then when I switch folders and the long folder name shows up in the tab view, the focus is lost!
Thank you for fixing this and finding the issue. Both the lost focus and the jumping tab has been a major problem for me!

**Comment by rich2014** [comment]
@kaitrek version [r10471](https://doublecmd.sourceforge.io/snapshots/doublecmd-1.1.0-10471.cocoa.aarch64.dmg) in snapshots had fixed it.
