### ISSUE TITLE
Columns aligned wrongly when window maximized (or scaled bigger)

### ISSUE THREAD

**Issue by amra** [doublecmd/doublecmd#53]
When resizing a double commander window columns resize is wrong.
Currently everything is aligned to the left. This is wrong because there is plenty of unused space next to attribute column, while long file names are not fully visible/readable.
Name column should be aligned to the left, all other columns to the right.

Original window
![from](https://user-images.githubusercontent.com/174620/111030356-0f835b80-8402-11eb-9d3e-9bd670c577d4.png)

Maximized  window - aligned wrongly
![to-wrong](https://user-images.githubusercontent.com/174620/111030546-270f1400-8403-11eb-858f-24a5e73bf1c5.png)

Maximized  window - aligned correctly
![to-correct](https://user-images.githubusercontent.com/174620/111030357-114d1f00-8402-11eb-9543-a4e02843a0a8.png)

**Comment by Skif-off** [comment]
> Name column should be aligned to the left

You should try to open configuration window, for example: Files views > Columns > `Auto fill columns` > `Auto size column=first`.

**Comment by amra** [comment]
I see. Thanks.
