### ISSUE TITLE
Sorting by date doesn't sort folders, just files

### ISSUE THREAD

**Issue by eblis** [doublecmd/doublecmd#532]
I selected to sort a folder by modified date, but only the files get sorted, the folders remain the same.
I have the option to show folders before files, if that makes a difference

**Comment by eblis** [comment]
I selected to sort a folder by modified date, but only the files get sorted, the folders remain the same.
I have the option to show folders before files, if that makes a difference

**Comment by alexx2000** [comment]
#197

**Comment by eblis** [comment]
Ooops, sorry, didn't find the issue. Searched a bit but used sort instead of order and didn't find it.
