### ISSUE TITLE
Synchronize directories by ignoring hidden & system items

### ISSUE THREAD

**Issue by junk123321** [doublecmd/doublecmd#533]
Is there any setting to control synchronizing directories by ignoring hidden & system items? As I would like to backup files from PC to removable storage devices, hidden items such as .git folders are expected to be excluded from backup. Thanks in advance!

**Comment by alexx2000** [comment]
You can do it using search template, use "filter" button.

**Comment by junk123321** [comment]
Thank you! It works. How about adding a checkbox to configure ignoring hidden & system items directly? It would be a convenient way if there are many different item names that cannot be easily "filtered".
