### ISSUE TITLE
[Feature Request] Jump to Specific Tab # Keyboard Shortcut

### ISSUE THREAD

**Issue by megamorphg** [doublecmd/doublecmd#547]
Forgive me if I am unable to find this feature but I am noticing there are no keyboard shortcuts to go to tab # X (1,2,3,etc.).

This feels like an indispensible feature, similar to browsing on the internet and needing to go to a specific tab in the set (without having to CTRL+Tab through them).

**Comment by alexx2000** [comment]
See `Alt+digit (1..9)` [shortcut](https://doublecmd.github.io/doc/en/shortcuts.html):
> Activate tab by index (see cm_ActivateTabByIndex)
