### ISSUE TITLE
Screen glitches (in Double commander only)

### ISSUE THREAD

**Issue by rav242** [doublecmd/doublecmd#548]
Hi!

I have strange glitches (green/blue/white squares and purple/white/black dashes) in folder and file names (when I try to rename them), in other editable fields (when using "file search", "Synchronize directories" and others) and in top menu. The squares and dashes are moving when I move cursor. Tried Wayland and X Window System - the result is the same. GPU is OK. Glitches are only in Double commander and only in Linux. Double commander works fine in Windows. Tried run MSI Kombustor in Windows with artifacts detection. No artifacts were detected.

My setup:
Dual boot Windows 10 / Ubuntu 22.04.1 LTS

Ubuntu:
Ubuntu 22.04.1 LTS 64-bit
Intel® Core™ i5-6600 CPU @ 3.30GHz × 4
AMD® Radeon rx 6700 xt
Gnome 42.2
Wayland

Tried:

Double Commander - flatpak
Version: 1.0.5 beta
Revision: 104
Commit: c02347051
Build date: 2022/04/12
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.1 LTS
Widgetset library: GTK 2.24.33

and

Double Commander - downloaded tar.xz and AppImage
Version: 1.0.6 beta
Revision: 120
Commit: b1d0f2f15
Build date: 2022/06/04
Lazarus: 2.0.12.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.1 LTS
Widgetset library: GTK 2.24.33

![Screenshot from 2022-08-15 23-24-44](https://user-images.githubusercontent.com/34181780/184676929-d61f56d8-8daf-46af-b8fe-79edda2f9b22.png)
![Screenshot from 2022-08-15 23-25-14](https://user-images.githubusercontent.com/34181780/184676938-e14fd7bd-eca9-44b3-995e-32d7a9d57941.png)
![Screenshot from 2022-08-15 23-25-41](https://user-images.githubusercontent.com/34181780/184676942-03504f9d-bd1f-4a03-ad7c-8c33a1efd30e.png)
![Screenshot from 2022-08-15 23-49-12](https://user-images.githubusercontent.com/34181780/184678999-3af210c7-451f-48f7-a90c-907efa337815.png)

**Comment by rav242** [comment]
Also there is no glitches in QT AppImage version. It seems there is something wrong in GTK libraries or is it an AND GPU driver bug?

**Comment by frithrah** [comment]
Could this be a Wayland thing? I'm running DC GTK version on X (Xfce) using AMD drivers and everything looks good.

**Comment by rav242** [comment]
Hi. No , I've tried Wayland and X Window System - the result is the same.

**Comment by rav242** [comment]
Sorry it's not Double commander issue. It's GTK2 or AMD driver or Mesa
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6456

ARE THERE ANY PLANS TO MOVE TO GTK4?

**Comment by alexx2000** [comment]
No. It depends on Lazarus developers. I hope some day it will be happen.
https://forum.lazarus.freepascal.org/index.php/topic,12126.45.html
