### ISSUE TITLE
Feature: skip long path confirmation

### ISSUE THREAD

**Issue by itlezy** [doublecmd/doublecmd#55]
![2021-03-13 18_28_25-Double Commander](https://user-images.githubusercontent.com/24484050/111038556-fd1d1800-8429-11eb-9d95-b3bc49993a3e.png)

Hi, can this confirmation be driven by a setting or by an initial confirmation in the copy dialog?
Sometimes it interrupts the copy process and it needs manual attention to resume.

Thanks

**Comment by alexx2000** [comment]
Added, see "LongNameAlert" key in "doublecmd.xml".
