### ISSUE TITLE
Drag & Drop not working in wayland

### ISSUE THREAD

**Issue by graygrotesque** [doublecmd/doublecmd#551]
I recently switched from xfce to sway and noticed that I'm not able to drag & drop files from double commander into other apps like I could under X, for example "Musicbrainz Picard" "mpv" or "mkvtoolnix-gui". Could this functionality be added or is there another solution?

Using the latest version of Double Commander 1.0.6 beta
Arch with sway
Ryzen 9 3900X
RX 6700 XT

**Comment by carnager** [comment]
I can confirm the described behavior and want to add that dragging to Xwayland Clients does work, just not to wayland native clients.

**Comment by alexx2000** [comment]
Try native Wayland DC version, see #193 for details.

**Comment by graygrotesque** [comment]
Thanks! Works perfectly.
