### ISSUE TITLE
text chars 'g','q','p' are cropped here on bottom

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#557]
![Screenshot from 2022-08-22 09-48-38](https://user-images.githubusercontent.com/4154978/185856918-a8b917d5-acf3-40f5-99d2-7c2d82a776c2.png)

Double Commander
Version: 1.0.6 beta
Revision: 120
Commit: b1d0f2f15
Build date: 2022/06/04
Lazarus: 2.0.12.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.4 LTS

Widgetset library: GTK 2.24.32

**Comment by alexx2000** [comment]
It is a [Lazarus bug](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/38268).
