### ISSUE TITLE
Repeat keystrokes

### ISSUE THREAD

**Issue by grassvalley** [doublecmd/doublecmd#561]
Repeat keystrokes
In the mint21 + fcitx5 environment, if you want to change the file name or other places where you can enter text, you will encounter the problem of repeated keystrokes. For example, press `a` and `aa` will appear.

**Comment by alexx2000** [comment]
Well known Lazarus problem. Try Double Commander Qt5 version instead.

**Comment by alexx2000** [comment]
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/30863
