### ISSUE TITLE
How to change owner & group with recursive?

### ISSUE THREAD

**Issue by Francewhoa** [doublecmd/doublecmd#563]
I need to batch change both the owner and the group for a folder and all its sub-folders and sub-files. In other words, recursive. By "batch" I mean all the above at once. I searched both the documentation and the ticket/issues. But found no answer.

I found how to change attributes under "File" ---> "Change attribute". There is a useful "Recursive" option in this window. But this changes only the attributes with recursive. Not the owner and group with recursive.

I also found "File" ---> "Show files properties"---> "Properties". But unfortunately, this windows does not have a "Recursive" option.

**Comment by alexx2000** [comment]
No way.

**Comment by Francewhoa** [comment]
Thanks for your comment @alexx2000

**Comment by Francewhoa** [comment]
I'll create a new ticket to suggest this as a new feature

**Comment by Francewhoa** [comment]
Done. I created a new ticket at https://github.com/doublecmd/doublecmd/issues/593
