### ISSUE TITLE
Console cannot change directory when Windows encoding is set to UTF-8

### ISSUE THREAD

**Issue by oldium** [doublecmd/doublecmd#564]
Situation: DoubleCommander 1.0.6 beta on Windows 11 with [UTF-8 mode enabled](https://itsontreinamentos.com/2022/05/05/how-to-change-character-encoding-windows-11/) (just select the Beta: UTF-8 option).

Problem: Internal console cannot change directories with message “System cannot find the specified path” - see screenshot (folder name is `C:\Users\oldium\Záloha`). It works on folders without diacritics, though.

Usually my system is CP1250/IBM852 (Czech cs_CZ locale), but when enabling UTF-8, my system is UTF-8 (CP65001).

DoubleCommander issue:
![image](https://user-images.githubusercontent.com/1260936/187031603-01001454-8bba-4528-b68b-e01d5c35a6ab.png)

Windows Command Prompt:
![image](https://user-images.githubusercontent.com/1260936/187031726-5e11640f-78a8-41ba-ac2e-8fac4c955392.png)

**Comment by alexx2000** [comment]
DC 1.1 use new build-in console which does not have such problem.

**Comment by oldium** [comment]
Verified with revision 10519 on Windows 11 22H2 build 22621.963 with UTF-8 mode enabled, works fine. Thanks 👌
