### ISSUE TITLE
"Compare by Contents" freeze/crash when file sizes differ

### ISSUE THREAD

**Issue by redmist77** [doublecmd/doublecmd#565]
Scrolling to the bottom of the "Compare by Content" viewer causes a freeze/crash if the files are binary and the sizes are not the same.

**Comment by alexx2000** [comment]
I cannot reproduce. Can you give example files?

**Comment by redmist77** [comment]
It happens with any two different-sized files.  Maybe it's a Windows-only issue.  Here's a demo.

![Comp_Error](https://user-images.githubusercontent.com/81495478/189584337-68f2fb8b-4983-43ac-85ad-d944846f5941.gif)

**Comment by alexx2000** [comment]
Strange, I tested with different binary files and could not reproduce.

**Comment by redmist77** [comment]
I can't NOT reproduce it.  Any different-size files.  Windows 10 or 11.  Tried Nvidia and Intel-based PCs and various video drivers.

**Comment by alexx2000** [comment]
Try with latest release.

**Comment by redmist77** [comment]
Gave it a quick try,  It seems to be fixed.  Nice job.
