### ISSUE TITLE
Feature request  - change drive by letter

### ISSUE THREAD

**Issue by nocturneop15** [doublecmd/doublecmd#568]
Hello, 
I'm trying to make DC as fast and handy as Altap salamander, but I'm missing one crucial feature - change drive not by index, but by its letter - in Salamander, it's implemented by Shift+"letter" shortcut. 

If I missed something in current setup, let me know, but I dod nofind how to set this up.

**Comment by JonnyTech** [comment]
Ctrl+digit(1..9) - see https://doublecmd.github.io/doc/en/shortcuts.html

**Comment by JonnyTech** [comment]
Oops sorry, I misread the question.

**Comment by nocturneop15** [comment]
"not by index" is meant exactly "not using digit, but drive letter" which makes me a lot more sense in windows environment. I use this across like 8 mapped drives in multiple domains, so indexing is quite hard to use...

**Comment by JonnyTech** [comment]
I am a Linux user so drive letters are an oddity to me. Have you tried alt + f1 or f2, to bring up the left/right drive dropdown, followed by the letter? Else you can define your own shortcuts, but for each drive letter a..z with a modifier.

**Comment by nocturneop15** [comment]
I tried, but that it quite "totalcommander" styled - and much less comfortable, at least for me. Dropdowns I don't like them, they are really clumsy relict from the past.  You might say it is just one more keystroke - but the whole thing together might took scond or two. 

alt+F1/F2 itself is also quite strange thing for me, I prefer one shortcut that modifies actually active pane. 

Custom shortcuts are quite static option. I can make them, but I still prefer this to be native funcion - it is one of Salamanders most addictive features that makes this program really productive if you traverse a lot. Double commander looks like best option on the market that could replace it - Salamnder is unmaintained for a long time.

cm_OpenDriveByLetter (very similar to cm_OpenDriveByIndex) should be really helpful here.

**Comment by Skif-off** [comment]
Text editor, regular expressions and several minutes...
Close DC, open the configuration file with the current set of hotkeys (`shortcuts.scf` by default), find `<Form Name="Main">`. Below this line add the following:
```xml
      <Hotkey>
        <Shortcut>Shift+A</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>A:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+B</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>B:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+C</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>C:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+D</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>D:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+E</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>E:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+F</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>F:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+G</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>G:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+H</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>H:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+I</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>I:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+J</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>J:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+K</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>K:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+L</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>L:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+M</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>M:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+N</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>N:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+O</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>O:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+P</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>P:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+Q</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>Q:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+R</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>R:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+S</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>S:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+T</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>T:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+U</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>U:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+V</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>V:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+W</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>W:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+X</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>X:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+Y</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>Y:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
      <Hotkey>
        <Shortcut>Shift+Z</Shortcut>
        <Command>cm_ChangeDir</Command>
        <Param>Z:\</Param>
        <Control>Files Panel</Control>
      </Hotkey>
```
Save. Now open something like [this](https://www.youtube.com/watch?v=wXVQNSlFJ6M) and relax.

**Comment by WhiteChairFromIkea** [comment]
I use "Directory Hotlist" feature for similar reason (access drives fast, but this involves mouse movement, or navigating by menu). Configure this menu with path shortcuts for your liking (like drive names in your situation), and assign a hotkey to open "Directory Hotlist".

I see this menu (where I can access C and D drives fast, but in graphical way) every time I press F1 when DC is active:
![1758G](https://user-images.githubusercontent.com/46539653/188064529-bbc7876d-fc9b-4433-a867-859217407e0e.png)

You can make "C" and "D" as topmost in this menu for faster access.

You can configure Hotlist menu here:
![2553k](https://user-images.githubusercontent.com/46539653/188065107-ff555d65-4efd-4f4d-a670-4d65692d1516.png)

**Comment by Skif-off** [comment]
@WhiteChairFromIkea

> access drives fast, but this involves mouse movement, or navigating by menu

[Tree View Menu](https://doublecmd.github.io/doc/en/configuration.html#ConfigTreeMenu) with filter?

**Comment by WhiteChairFromIkea** [comment]
> @WhiteChairFromIkea
> 
> > access drives fast, but this involves mouse movement, or navigating by menu
> 
> [Tree View Menu](https://doublecmd.github.io/doc/en/configuration.html#ConfigTreeMenu) with filter?

Thanks, it was a suggestion to OP user, because one looks like a "hotkey guru" type of user and does not prefer gui. I am happy with current implementation of Hot list, and I would like for it to be even more gui-fancier: https://github.com/doublecmd/doublecmd/issues/282. Tree menu is not for me (does not look nice enough for me personally).

**Comment by nocturneop15** [comment]
> 

This looks promising,  but does not work - by shift+letter, DC starts search with capitals :-(

**Comment by alexx2000** [comment]
You should to disable quick search by letter ("Options"->"Keys") if you want to use Shift+Letter hotkeys.

**Comment by nocturneop15** [comment]
That completely breaks navigation and makes DC useless as file manager. Quicksearch is tightly bound with navigation - respectively, it seems to be the same function.  
Bad thing is that both filtering and quicksearch are accepting shift as letter case modifier for search string, but the search/filter itself ignores case letter completely (which seems as bug to me, or at lease incomplete funcion) 

 This goes deeper than I expected :-(

**Comment by alexx2000** [comment]
Only one function can use Shift+Letter at one time, so if quick search has higher priority for you then you should use another hotkeys for change drive.

> but the search/filter itself ignores case letter completely 

It depends on the case sensitivity option, you can change it in the [options](https://doublecmd.github.io/doc/en/configuration.html#ConfigQuick) globally or at the search panel by "Aa" button.

**Comment by nocturneop15** [comment]
@alexx2000 - Thanks, DC has so many hidden features and options...one never finds them all :-) 

 DC is great software, packed with functions, but specificay these limits does not fit my needs. I will try it from time to time, but now I prefer simplier and faster approach of Altap Salamander, regardless of it being a bit outdated.

**Comment by goyalyashpal** [comment]
hey @nocturneop15 did u try with alt+letter?

i haven't done any tests or any validity verification at all, but thought to share.

**Comment by goyalyashpal** [comment]
hey @nocturneop15 did u try with alt+letter?

i haven't done any tests or any validity verification at all, but thought to share.

**Comment by goyalyashpal** [comment]
> The Drives button bar helps you to change the drive quickly with one mouse click.
> \-  [doublecmd documentation ](https://doublecmd.github.io/doc/en/help.html#iface_drive_pane) 

i was just thinking that aside from this suggestion, what is the current way to change drive from keyboard?

**Comment by alexx2000** [comment]
Standard hotkeys Alt+F1 and Alt+F2. It is written about it in the documentation that you link.

**Comment by goyalyashpal** [comment]
> Standard hotkeys Alt+F1 and Alt+F2

alt f1, f2, f3, f9 are taken by nvidia on my system

**Comment by alexx2000** [comment]
And what's the problem. You can go to nvidia options and disable this hotkeys or go to DC options and change hotkeys.

**Comment by Skif-off** [comment]
As alternative: [drive letter + ":"](https://doublecmd.github.io/doc/en/help.html#iface_path).

**Comment by vertigo220** [comment]
Why not have a hotkey for toggling modes, i.e. between quick search and drive selection?
