### ISSUE TITLE
doublecmd-qt 1.0.6 doesn't work anymore with QT_SCALE_FACTOR=2

### ISSUE THREAD

**Issue by wviechtb** [doublecmd/doublecmd#575]
On a 4k display, I use QT_SCALE_FACTOR=2 with doublecmd-qt, which worked up to now. However, with version 1.0.6, doublecmd starts but nothing is shown. Starting with `QT_SCALE_FACTOR=1 doublecmd` works just fine and the `librsvg-WARNING` shown below is gone.

This issue only arises when installing Double Commander via the Ubuntu 20.04 ppa (http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04/). If I grab the release directly from here (i.e., https://github.com/doublecmd/doublecmd/releases/download/v1.0.6/doublecmd-1.0.6.qt.x86_64.tar.xz), then `QT_SCALE_FACTOR=2 doublecmd` works fine.

    SystemLocale en_US
    SystemLanguage en
    SystemEncoding UTF-8
    DefaultSystemCodePage 65001
    DefaultFileSystemCodePage 65001
    DefaultRTLFileSystemCodePage 65001
    Starting GuiMessageQueue
    Starting Double Commander
    Double Commander 1.0.6 beta
    Revision: 120
    Commit: b1d0f2f15
    Build: 2022/06/04
    Lazarus: 2.2.2.0
    Free Pascal: 3.2.2
    Platform: x86_64-Linux-qt5
    System: Ubuntu 20.04.5 LTS
    Desktop Environment: Xfce
    Widgetset library: Qt 5.12.8, libQt5Pas 5.6.1
    This program is free software released under terms of GNU GPL 2
    (C)opyright 2006-2022 Alexander Koblov (alexx2000@mail.ru)
       and contributors (see about dialog)
    Executable directory: /usr/lib/doublecmd/
    Loading configuration from /home/wviechtb/.config/doublecmd/
    Loading lng file: /usr/lib/doublecmd/language/doublecmd.en.po
    Error loading configuration file /home/wviechtb/.config/doublecmd/favoritetabs.xml
    PollThread: Start polling
    PollThread: AddPoll 24
    Creating PixmapManager
    Loading icon theme Suru++ Asprómauros
    Loading icon theme Hicolor
    Loading icon theme DCTheme
    Loading icon theme DCTheme
    
    (doublecmd:137054): librsvg-WARNING **: 10:13:09.967: cannot render on a cairo_t with a failure status (status="invalid matrix (not invertible)")
    TColumnsFileView.Create components
    Creating TFileSystemFileSource
    TColumnsFileView.Create components
    PollThread: AddPoll 31
    UDev: Begin monitoring
    FileSystemWatcher thread starting
    Detecting mounts through /proc/self/mounts
    PollThread: AddPoll 32
    frmMain.frmMainShow

**Comment by alexx2000** [comment]
Lazarus 2.2 [bug](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39610). I will try to patch it.

**Comment by alexx2000** [comment]
Try with latest DC 1.0.7. It build using patched Lazarus.

**Comment by wviechtb** [comment]
Works again -- thanks for the quick fix!
