### ISSUE TITLE
MacOS dmg for brew?

### ISSUE THREAD

**Issue by BertKoor** [doublecmd/doublecmd#576]
I'm using DoubleCommander v 0.9.8-9296, installed via brew.
The latest commit there marked this as 'discontinued'
https://github.com/Homebrew/homebrew-cask/commit/9b9cdfcce72a4e574b0bd5ab88dcaa7a332be263

Now I see here there's work being done on v1.0.x-beta.
On the page with release assets I only see Windows-related builds.
Has MacOS indeed been discontinued?

**Comment by JonnyTech** [comment]
Snapshots available at https://doublecmd.sourceforge.io/site/eng/snapshots.php

Reasons: https://doublecmd.h1n.ru/viewtopic.php?f=5&t=7126

**Comment by rich2014** [comment]
DC MacOs version 1.1.0 alpha in Snapshots Page works well

**Comment by BertKoor** [comment]
right, thank you.

**Comment by rich2014** [comment]
Double Commander 1.1.0 beta for macOS officially supported released!
https://doublecmd.h1n.ru/viewtopic.php?f=5&t=7694

and DC can also be installed through homebrew now.
