### ISSUE TITLE
Build for ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#578]
When installing doublecmd on raspbian / raspberry pi os, it pulls in v0.9.1 from their repositories. Is there an updated build available for the platform?

**Comment by alexx2000** [comment]
Which OS version do you use? Looks like it's Debian 10 based. Which architecture do you need arm64, armel or armhf?

**Comment by JonnyTech** [comment]
The image is the standard one available at https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit which is based on Debian 11 (bullseye) and is armhf.

The Debian 10 images https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy are considered legacy.

They also produce a 64bit build but I have not tried it.

It was just a general question whether you produced regular builds or if we should compile it ourselves?

**Comment by alexx2000** [comment]
You wrote that you have DC 0.9.1 which was in the Debian 10 repo, Debian 11 has DC 0.9.10.
Link to my repo you can find in the [documentation](https://doublecmd.github.io/doc/en/faq.html#repo) and at official download page. But this repo doesn't have ARM builds now.

**Comment by JonnyTech** [comment]
> But this repo doesn't have ARM builds now.

Ah, I must have typed incorrectly. Thank you, I shall build.
