### ISSUE TITLE
Please support word wrap in internal editor

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#579]
Please support word wrap in internal editor (like in internal viewer).

**Comment by Skif-off** [comment]
DC uses SynEdit and [as far as I remember] this component does not currently support word wrapping.

**Comment by alexx2000** [comment]
https://doublecmd.sourceforge.io/mantisbt/view.php?id=2293

**Comment by alexx2000** [comment]
https://doublecmd.sourceforge.io/mantisbt/view.php?id=2293

**Comment by ags1234** [comment]
Aren't there any other components better than SynEdit, that could replace it?
If SynEdit doesn't even know how to word-wrap, it is easily imaginable it has a lot of other shortcomings.

**Comment by alexx2000** [comment]
Editor component is a large thing. I don't want to depend on large third-party component because of such a small thing like word-wrap.

**Comment by Skif-off** [comment]
> original Delphi SynEdit has word wrapping [source + SynEditWordWrap.pas](https://forum.lazarus.freepascal.org/index.php/topic,26227.msg161353.html#msg161353)

For some reason, no one has ported the latest changes in this Delphi component to Lazarus, a fork of one of the previous versions is used.

**Comment by alexx2000** [comment]
https://forum.lazarus.freepascal.org/index.php?topic=61258.0

**Comment by Skif-off** [comment]
@alexx2000 ,
this is not a port of some changes from the Delphi component, is it?

**Comment by zxcat** [comment]
> Lazarus SynEdit has experimental word wrap support:
> https://forum.lazarus.freepascal.org/index.php?topic=61258.0

Fun stuff there:
>>> Ok, thank you. And how to disable it after it has been enabled?

>> That isn't implemented yet....

But anyway, that can be worked around even by
* recreating anything to return in non-wrap mode
* or let an user do it himself (switching to text mode and then to code mode)

**Comment by alexx2000** [comment]
@Skif-off, looks like it is an independent implementation. Lazarus SynEdit was forked from Delphi long time ago. So it is a two different components today.

**Comment by Heavygrass** [comment]
Hi,
I'd like to request line-warp support in editor also.
Thanks

**Comment by Raart** [comment]
Hi,
are we kidding? Word wrap function in a viewer/editor is important as showing characters on the screen. If other's code lack basic functions... you know what to do. No excuses are acceptable.
BTW - I'm investigating on this by myself. If we have such a blocking dependency and can't come to a solution for such a simple problem, then let's cut out the dependency.

**Comment by alexx2000** [comment]
Hi, I think that this is an unimportant function in the built-in editor. However the latest SynEdit supports a word-wrap so it can be added to DC in the future.

**Comment by Heavygrass** [comment]
@alexx2000 
> I think that this is an unimportant function in the built-in editor. 

Hi!
Built-in editor is whats being opened every time we press F4. I already got a custom to split text into new line on every single dot (and sometimes even have to do on comma also) to be able to read it.
You usually can't do this with code though.

> However the latest SynEdit supports a word-wrap so it can be added to DC in the future.

Great news, IMHO this needs to be a priority.

**Comment by anatanna** [comment]
> Hi, I think that this is an unimportant function in the built-in editor. However the latest SynEdit supports a word-wrap so it can be added to DC in the future.

One year passed since this message.
@alexx2000  Can you please consider adding this wordwrapping feature to DC Editor?

**Comment by tredondo** [comment]
Word wrapping is one of the most basic features of an editor.

Back in the 90s, Dos Navigator had it.

Unbelievable that now when an LLM could create an editor component from scratch pass all of tests in SynEdit, plus have word wrapping, we don't have word wrapping.

**Comment by anatanna** [comment]
@tredondo  Hi Ted, word wrapping was kindly implemented by @alexx2000 almost the next day after my message here in thread. Confusion is that it is not yet came to main branch, but you can find it in 1.3 versions / snapshots. [https://github.com/doublecmd/snapshots/releases](url)
Thanks to the great DC developers team. ❤
