### ISSUE TITLE
Feature request: Separate configuration for header and footer file size formatting

### ISSUE THREAD

**Issue by karfau** [doublecmd/doublecmd#58]
I would love to have separate formatting for header and footer file size formatting, since the footer shows a different kind of information which allows me to easily see if to files have the same size.

**Comment by karfau** [comment]
Thank you for implementing this.
@alexx2000 can you help me to understand in which version(s) this will be available? 

Thank you

**Comment by alexx2000** [comment]
Version 1.0.

**Comment by karfau** [comment]
Do I understand correctly from looking at the docs in this repo, sourceforge and package managers that v1.0 is not available anywhere as of now, even as alpha/beta, and most like the timeline is not fixed?
(Not any criticism, looking forward to be able to switch to it when it's available.)

**Comment by alexx2000** [comment]
Alpha version is available at [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.html) (Windows, macOS) page and [repo ](https://software.opensuse.org/download.html?project=home:Alexx2000:doublecmd-svn&package=doublecmd-qt)(Linux)
