### ISSUE TITLE
File Search Settings 

### ISSUE THREAD

**Issue by mohitWrangler** [doublecmd/doublecmd#582]
Is it possible for the default file search to turn off the "Match Beginning" and "Match Ending" options? Most of the time I need them off.

**Comment by alexx2000** [comment]
What search do you mean? Quick search options are [here](https://doublecmd.github.io/doc/en/configuration.html#ConfigQuick), normal file search options are [here](https://doublecmd.github.io/doc/en/findfiles.html#configuration).
But it must be taken into account that quick search remember last used options, default options applied at first search after start.
