### ISSUE TITLE
Text selection in file viewer looks wrong.

### ISSUE THREAD

**Issue by corvus1** [doublecmd/doublecmd#587]
![Screenshot_20220916_125307](https://user-images.githubusercontent.com/4068104/190599122-6066367e-ec99-4bc0-b78d-265453ad603e.png)

If you turn your attention to that gap between the mouse cursor and the selected text, that's strange. 

And then these strange notches in the selection. It looks as if there are white rectangles ovelapped over it. If you look at the word NextPart, it's actually `"_NextPart_"`, it has underscores before and after, but they become invisible if I select anything. Same with any descenders on any characters, like p, q or g. Anything that goes below the text line becomes invisible.

And finally, it seems impossible to select a word by double clicking on it.

**Comment by alexx2000** [comment]
What font do you use? What text encoding?

**Comment by corvus1** [comment]
The font is Monospace, the encoding is CP1251, but I suspect any modern font will have descenders on letters like p or q.

**Comment by corvus1** [comment]
I just realized, monospace is not the name of the font, but a category. 
The real font is probably Hack.
![Screenshot_20220916_133158](https://user-images.githubusercontent.com/4068104/190606596-daba65d1-0950-4c02-9b55-c4bc0f76ef75.png)

https://github.com/source-foundry/Hack

**Comment by alexx2000** [comment]
Which DC version do you use? Copy here full version info from "About" dialog.

**Comment by corvus1** [comment]
Double Commander
Version: 1.1.0 alpha
Revision: 10341
Commit: f4ba5ad05
Build date: 2022/09/06
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: "Gentoo"

Widgetset library: Qt 5.15.5, libQt5Pas 5.6.1

**Comment by alexx2000** [comment]
Strange, it does not work with "Monospace" font. But works fine with "Hack" font when I choose it in the DC settings.
Text width calculated wrong with "Monospace" font, I have no idea why it happen. So use some other monospace font.

**Comment by corvus1** [comment]
Any chance of setting the default to something that works?

**Comment by corvus1** [comment]
Putting hack instead of monospace in DC settings fixes it for me too.

**Comment by nowayelse** [comment]
#28 is the same issue. Changing the viewer font (to Cousine in my case) solves the problem.

**Comment by JonnyTech** [comment]
This seems to be a qt5 issue, switching to gtk2 builds do not have this ptoblem.

**Comment by corvus1** [comment]
It's hard for me to bring myself to use gtk2 in 2022.

**Comment by alexx2000** [comment]
I can get a full font list and find first monospace font.


> As I understand, `monospace ` is a system alias for the default system monospace font, so such problem looks like maintainer's or user's mistake.

Yes, it looks like a system misconfiguration.
