### ISSUE TITLE
[Feature sugestion] Open directory in opposite panel

### ISSUE THREAD

**Issue by SilverKnight-Z** [doublecmd/doublecmd#588]
Would it be possible to add a command which I could open a folder in the opposite panel? What I mean is if I'm in the left panel, I can open a folder in the right panel and viceversa. And in case of having horizontal panels: if I'm in the superior panel, I can open a folder in the inferior panel and viceversa. 

If possible, it would be really helpful.

**Comment by Skif-off** [comment]
Ctrl+left / Ctrl+right? I.e. [cm_TransferLeft / cm_TransferRight](https://doublecmd.github.io/doc/en/cmds.html#cm_TransferLeft).
Also see [#518](https://github.com/doublecmd/doublecmd/issues/518).

**Comment by SilverKnight-Z** [comment]
> Ctrl+left / Ctrl+right? I.e. [cm_TransferLeft / cm_TransferRight](https://doublecmd.github.io/doc/en/cmds.html#cm_TransferLeft).
> Also see [#518](https://github.com/doublecmd/doublecmd/issues/518).

The script you made in #518 is exactly what I was looking for, thank you.

I'm also trying to set it up as an action for folders in the file associations configuration, but I read in documentation that I can only specify one parameter. 

Is there a way to trick double commander into think that all is just one parameter,  or this script can only work as a button? I tried separating the parameters with spaces and commas respectively, and also copying the parameters on a text file and using its full path in the parameter field, but neither of that worked

**Comment by Skif-off** [comment]
This script can only work as a button, but you can also just add a hotkey.

**Comment by SilverKnight-Z** [comment]
I just did just that. Thank you for your help
