### ISSUE TITLE
DoubleCommander 1.0.8 does not read the config file in user directory

### ISSUE THREAD

**Issue by leolopez89** [doublecmd/doublecmd#599]
I was using version 1.0.6, after downloading the new version I updated in the config file, first manually, then directly in the `DC config GUI`; the variable to use the config file in the user home.

After starting the new version of `DC`, it did not load the configuration.
I copied the file directly to `DC_path` and it worked, but not with `~/.config/doublecmd/doublecmd.xml`. 

Double Commander
Version: 1.0.8
Revision: 191
Commit: ee1f44b3c
Build date: 2022/09/18
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 22.04.1 LTS

Widgetset library: GTK 2.24.33

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/wiki/Testing-different-version#using-doublecmdinf-file

**Comment by leolopez89** [comment]
The problem was solved by removing the mentioned file. Thanks!!

Note: With previous versions that file wasn't a problem. It worked well.
