### ISSUE TITLE
The creation time is not preserved

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#60]
It does not preserve the creation time for directories and files on the Double Commander macOS version. It always sets on the transfer time.
[doublecmd-0.9.10-9640.qt.x86_64.dmg](https://sourceforge.net/projects/doublecmd/files/DC%20for%20Mac%20OS%20X%2064%20bit/Double%20Commander%200.9.10%20beta/doublecmd-0.9.10-9640.qt.x86_64.dmg/download)

When I test the Double Commander Windows version then there are no problems by default it preserves the creation time when copying directories and files locally.
[doublecmd-0.9.10.x86_64-win64.exe](https://sourceforge.net/projects/doublecmd/files/DC%20for%20Windows%2064%20bit/Double%20Commander%200.9.10%20beta/doublecmd-0.9.10.x86_64-win64.exe/download)

**Comment by alexx2000** [comment]
This function is not supported in macOS version.

**Comment by Guntriaske457** [comment]
> This function is not supported in macOS version.

Thanks for the infomation.

Is it possible to support it? I have many files and directories on my macOS 11 MacBook and would like to preserve all 3 timestamps (created, modified and accessed time) when copying. So just like the Windows version.

**Comment by alexx2000** [comment]
Yes, this can be added. But I don't sure that I will be able to continue support macOS at all.

**Comment by Guntriaske457** [comment]
> Yes, this can be added. But I don't sure that I will be able to continue support macOS at all.

It would be good if you continue to support macOS (Unix like), because it is one of the few operating systems besides Windows that fully support created time.

**Comment by rich2014** [comment]
I test on MacOS 12.6, it preserve create time on APFS.

has this problem been fixed since then?

**Comment by alexx2000** [comment]
It is impossible. DC does not copy creation time under Unix-like operating systems, [see](https://github.com/doublecmd/doublecmd/blob/0611623c6a266e1116f3682327d84d99d78aadf0/components/doublecmd/dcosutils.pas#L542). DC copy only access and modification times.
