### ISSUE TITLE
Compare by content - auto compare inconsistent

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#607]
When performing `compare by contents`, I like to have `auto compare` enabled.

But I noticed that sometimes the auto compare does not work.

Looking for `autocompare` in `doublecmd.inf` yields no result.

But there is a match in `session.ini`:

```
[TfrmDiffer(1920x1080)]
actAutoCompare_Checked=1
```

Does that mean that if I change screen resolution then the auto compare needs to be set again?

Is it possible to set the value globally in `doublecmd.inf`?

**Comment by alexx2000** [comment]
> But I noticed that sometimes the auto compare does not work.

When it does not work? Current version always automatically compare files on start.
`Auto compare` option affects only when you reload files or change compare options or choose another file via open dialog.

> Looking for `autocompare` in `doublecmd.inf` yields no result.

I guess you are mean `doublecmd.xml`, because `doublecmd.inf` does not store any options.
> Does that mean that if I change screen resolution then the auto compare needs to be set again?

Yes.
> Is it possible to set the value globally

Really I planned to remove this option.

**Comment by JonnyTech** [comment]
> When it does not work? Current version always automatically compare files on start.

Sometimes I need auto compare disabled, depending on the types of files that I am comparing, the highlight is not required.

> I guess you are mean doublecmd.xml, because doublecmd.inf does not store any options.

Indeed, my typo.

> Really I planned to remove this option.

Please reconsider, and move it to `doublecmd.xml` if at all possible.

**Comment by Skif-off** [comment]
> Really I planned to remove this option.

Why?

**Comment by alexx2000** [comment]
Because it's a confusing option, as I remember we are discuss it at the forum.

OK, I will move it to `doublecmd.xml` so far.

**Comment by JonnyTech** [comment]
Thank you. Sorry, I forgot to check the forum.
