### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by krisfremen** [doublecmd/doublecmd#61]
Hi there,

Since the project is now officially on GitHub, it would be nice to implement GitHub Actions and have checks and builds done automatically!

I would like to give this a shot over the next few days and automate at the least Windows and Linux builds. Possibly Mac as well.

This would open up the path for providing snap and AppImage builds as well.

Cheers!

**Comment by Skif-off** [comment]
https://doublecmd.github.io/doc/en/faq.html#repo

**Comment by j2969719** [comment]
actually having travis/github ci would be nice. not only for the sake of artifacts, but also simply to see if the new pull requests compiles successfully

but lazarus has a bad habit of sometimes crashing at compile time, although this rarely happens.

**Comment by krisfremen** [comment]
@Skif-off it's a great thing to have a repo for following master branch release, but as more people contribute, it's hard to maintain just a single "nightly" release as there might be multiple branches getting PR'd at the same time. 
While a deb/rpm repo is great to have, sometimes just downloading the package from the github repo is easier and faster.

And as @j2969719 said, it's great to see that something compiles straight away and get artifacts to test with!

@j2969719 unfortunately, travis-ci changed their open source offering and no longer have a fully free open source plan as they used to before and their minutes don't replenish anymore.

**Comment by alexx2000** [comment]
Snapshots for Windows and macOS builds automatically via GitHub Actions now. Snapshots for Linux builds automatically by openSUSE Build Service via GitHub Webhooks notification.
