### ISSUE TITLE
complie with the latest master branch of FPC and Lazarus

### ISSUE THREAD

**Issue by rich2014** [doublecmd/doublecmd#619]
hi,Alexa

i had commited two PR to FPC and Lazarus, related to Darwin and Cocoa, and will affect the MasOS version of Double Commander. both PR had been merged into the main branch.

1. if a non-system font is set in Double Commander, the text will be cluttered due to the BaseLine error.
`Lazarus PR: FIX: Cocoa: offset display error in TEdit(NSTextField)`
https://gitlab.com/freepascal.org/lazarus/lazarus/-/merge_requests/109

2. aarch64: Mounted Driver no label , this issue had been resolved by workaround #554
`FPC commit: FIX: DARWIN: aarch64: tstatfs.fstypename length error (#39873)`
https://gitlab.com/freepascal.org/fpc/source/-/commit/7bcefd287d8109ed80190797e33bb5422395436a

is it possible to compile with the latest master branch of FPC and Lazarus, so that temporary workarounds is no longer necessary.

**Comment by alexx2000** [comment]
Hi

Yes, I can use latest Lazarus version. But I am prefer to use latest stable FPC version.

So I can build snapshots using Free Pascal 3.2.2 and Lazarus 2.3.0.

**Comment by alexx2000** [comment]
Hmm... It works fine for x86_64 and aarch64. But does not work with i386. Lazarus has incompatibility with i386-darwin target, `lazarus/components/lazutils/lazutf8.pas` should call `System.Move` instead `Move` everywhere.

**Comment by rich2014** [comment]
i think we can stop supporting i386 on MacOS:
1. x86_64 CPU has been widely used since 2004, which has been 18 years old
2. Apple has fully supported x86_64 since 2009, which has been 13 years old

**Comment by alexx2000** [comment]
OK, I removed i386 build. Current snapshot built using Free Pascal 3.2.2 and Lazarus 2.3.0.

**Comment by rich2014** [comment]
works well

**Comment by rich2014** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/102933068/193454782-dbe45a06-65ba-42d7-ad84-6f907a6b593e.png">

**Comment by rich2014** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/102933068/193454827-d3c97422-62c7-48d1-ac3c-56315f8fd368.png">

**Comment by rich2014** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/102933068/193454925-3d1a2399-ddf9-4b0b-becf-1fef542794f6.png">

**Comment by rich2014** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/102933068/193454947-1816c20c-4b21-4a72-bef7-6bc27bbcf824.png">

**Comment by rich2014** [comment]
which script did you use to build the snapshoot of MacOS version?
can you codesign when building?

**Comment by alexx2000** [comment]
I use modified version of `create_packages.mac`. I build snapshots under Linux using cross-compiling so I cannot codesign.

**Comment by rich2014** [comment]
the user may not even know that a signature is required now.
or we can add a script to the zip file, it will give the user a hint to run the script to codesign after unzipping.

**Comment by alexx2000** [comment]
GitHub action builds packages with signature. So signature problem is solved.
