### ISSUE TITLE
Cannot open `\\wsl$` path on Windows

### ISSUE THREAD

**Issue by kkarbowiak** [doublecmd/doublecmd#624]
I am using Windows Subsystem for Linux on my Windows 10 computer. I can access the underlying filesystem by entering `\\wsl$` path in File Explorer, but when I enter the same path in Double Commander's path pane above the file list, I get the following error: "Cannot find network name" (translated from Polish "Nie można odnaleźć nazwy sieciowej", so might be slightly wrong).

Is there some other way to access this path, or some implementation is needed?

**Comment by alexx2000** [comment]
I don't know how to get a list of installed Linux distributions. But you can open installed distro directly using path like:
`\\wsl$\Ubuntu-20.04`

**Comment by kkarbowiak** [comment]
Cool, this works, indeed. Thanks!

Also, it looks like getting the list of installed distributions is a hassle, so I am not sure it would be worth it.

I'm closing this.

**Comment by kkarbowiak** [comment]
Just for reference, this works since 1.9.0 (see #724).

Thanks!
