### ISSUE TITLE
Verification dialog appears on the wrong display in a multi monitor config (right display is the primary)

### ISSUE THREAD

**Issue by csimpi** [doublecmd/doublecmd#633]
Version: 1.0.8 (and with the previous versions too)
When I try to copy a file and there is a file with the same name in the destination folder, the overwrite confirmation dialog shows up on the wrong display, if the primary display is on the right side.
[](url)
The confirmation dialog should appear on the same display as the DC instance is on. Interestingly the first dialog (with the progress bars) always appears on the expected display, but the second (confirmation) dialog always on the wrong one.

Maybe this is because I use three displays, and the rightmost display is my primary display and I use DC there, and for some reason the dialog considers the leftmost monitor the "first" display.
The confirmation dialog should appear the same place the the parent dialog (with the progress  bars).
![doublecommanderbug](https://user-images.githubusercontent.com/6192067/195063582-666e7d2d-0880-4b6a-96b4-a08fb177b24a.png)

Thank you!

**Comment by csimpi** [comment]
UPDATE:
I've tested it in in virtual environment, fresh arch install, xorg + awesome-wm, exactly the same effect as described .

**Comment by csimpi** [comment]
this issue is so frustrating, I've even added rules to awesome wm and restrict it to one screen, but still the secondary dialogs are appearing in weird places of the multi display environment.

**Comment by csimpi** [comment]
@alexx2000 thank you so much, when are you guys going to release a new version with this fix included? I can't wait to upgrade cause this bug is very frustrating. I don't want to install all the dev tools to compile a version from source.

**Comment by alexx2000** [comment]
Very soon.
