### ISSUE TITLE
Selection by mouse: click on an unselected item unselects all

### ISSUE THREAD

**Issue by idanmiara** [doublecmd/doublecmd#634]
Hi all,
Thanks for this awesome tool !

When `Mouse`: `Selection by mouse` is active:

Say I select a few files with ctrl(or command)+click and/or shift+click
Then if I click on a file that is already selected then it doesn't effect the section (which is good)
But if I click on a file that is not selected then the entire selection is unselected.

Expected behavior:
Clicking on a file without command/shift should not effect selection.

Tested versions confirming this issue: 
`doublecmd-1.0.8.x86_64-win64.exe`
`doublecmd-1.1.0-10394.cocoa.x86_64.zip`

**Comment by Skif-off** [comment]
When `Mouse` >`Selection by mouse` > `Left button` is set:

> But if I click on a file that is not selected then the entire selection is unselected.

This is the only way to reset the selection using the mouse. And this is normal and expected behavior for similar graphical widgets ("graphical control elements" or just "controls") - list view, list box, grid.
This works everywhere, from file managers to spreadsheets (MS Excel, LO Calc, Gnumeric an so on).

If you want to move the cursor then try to enable `By clicking on icon`: the first click will select the file and move the DC cursor to it, the second will deselect it. Or use Ctrl+click twice.

**Comment by idanmiara** [comment]
> This is the only way to reset the selection using the mouse. And this is normal and expected behavior for similar graphical widgets ("graphical control elements" or just "controls") - list view, list box, grid. This works everywhere, from file managers to spreadsheets (MS Excel, LO Calc, Gnumeric an so on).

Thanks for your comment :) You have a good point here. 
After decades with totalcmd I was sure this is unintended behavior (as this is inconsistent with TC).
I'm suggesting to consider making a toggle to be compatible with the TC behavior.

I've checked with LO Calc and Finder (on Mac) and it unselects the entire selection if you click on any item (selected or not selected) without holding command(win: ctrl)/shift - so also not exactly the same.

**Comment by Skif-off** [comment]
> After decades with totalcmd I was sure this is unintended behavior (as this is inconsistent with TC).

Tnconsistent? You can use the left (as in Windows Explorer) or right (Norton Commander, Far) mouse button to select: by default TC uses the right button, but DC uses the left button. And you can change it: go to "Configuration" in the main menu > Options... >
- TC: Operation > Mouse selection mode;
- DC: Mouse > Selection by mouse > Mode.

(If I understood correctly :))

**Comment by idanmiara** [comment]
> > After decades with totalcmd I was sure this is unintended behavior (as this is inconsistent with TC).
> 
> Tnconsistent? You can use the left (as in Windows Explorer) or right (Norton Commander, Far) mouse button to select: by default TC uses the right button, but DC uses the left button. And you can change it: go to "Configuration" in the main menu > Options... >
> 
> * TC: Operation > Mouse selection mode;
> * DC: Mouse > Selection by mouse > Mode.
> 
> (If I understood correctly :))

Perfect! that's exactly what I was looking for, thanks!!!
