### ISSUE TITLE
Show "Directory Hotlist" in columns if large

### ISSUE THREAD

**Issue by gitgt** [doublecmd/doublecmd#635]
"Directory Hotlist" can have many items.  With my monitor resolution, only up to 40 can be seen plus bottom 3 commands.
That single column of directories can be scrolled but it's not practical for frequent use. 
If we have more items, it would be useful to have an option "show in columns if more than X items".

**Comment by Skif-off** [comment]
Have you tried the [Tree View Menu](https://doublecmd.github.io/doc/en/configuration.html#ConfigTreeMenu) with quick filter?
Submenu is also supported.

**Comment by gitgt** [comment]
I didn't know about Tree View Menu. 
I never realized that submenu is possible, it helps.
I should've read this before.. https://doublecmd.github.io/doc/en/directoryhotlist.html

Not sure if request should stay open and be considered ever, now it's of little importance. 
I'll close. Anyone still wanting this in addition to all other optons, feel free to comment.
