### ISSUE TITLE
Files associations made in KDE doesn't affect Double Commander

### ISSUE THREAD

**Issue by igormironchik** [doublecmd/doublecmd#637]
I created a new mime type in Kubuntu with system settings, assigned icon to the some file extension. I see the result in Dolphin, but not in Double Commander.

**Comment by alexx2000** [comment]
Did you restart Double Commander?

**Comment by igormironchik** [comment]
Sure, I restarted and Linux, and Double Commander. FYI, I use Qt build of Double Commander.

**Comment by alexx2000** [comment]
Yes, such icon association is not supported.

**Comment by igormironchik** [comment]
And? You will do nothing? Or you will implement such feature request?

Guys, as Krusader gone into the history, I don't see any support on it. Double Commander will become number 1 twin-panel on Linux. And a lot of people desire to have fully featured, not error-prone application.

**Comment by alexx2000** [comment]
Most likely it will be fixed.
