### ISSUE TITLE
[bug] Killing cmd.exe also kills doublecmd.exe

### ISSUE THREAD

**Issue by Worldwidebrine** [doublecmd/doublecmd#640]
Reproduce:
1. Open CMD
2. Execute command `C:\path\to\doublecmd.exe`
3. Kill CMD

Result:
* doublecmd would also be killed.

Expected Result:
* doublecmd won't be killed.

**Comment by WhiteChairFromIkea** [comment]
@Worldwidebrine , how do you kill cmd? There may be two options: kill process an kill process tree. Later will produce the behavior you described, as expected. I don't think this is related to dc. Have you tried the same with other exe?

**Comment by Worldwidebrine** [comment]
@WhiteChairFromIkea 
Not only killing cmd, but also just closing the window of cmd can reproduce this.

I think I know the reason why is this happening now.
This happens on wine([SteamPlay/Proton](https://github.com/ValveSoftware/Proton)).
I also tried explorer.exe. When I close cmd window, even explorer will get killed.

The behavior is by wine's cmd.exe instead of doublecmd.exe.
Sorry.
