### ISSUE TITLE
Show confirmation window option does no effects

### ISSUE THREAD

**Issue by sybaris** [doublecmd/doublecmd#641]
Hi,

Version : 1.0.8
The options "Show confirmation window for : " 
- "Copy operation"
- "Move operation"
have no effects
![image](https://user-images.githubusercontent.com/11009997/196609699-5a95da54-8083-4c76-a6ed-498e53d30394.png)

When I make a file copy, I have still the same window dialog, and I have to click on start :
![image](https://user-images.githubusercontent.com/11009997/196609849-49a9c288-bcbc-44d8-80bc-984d56a8f2c5.png)

Thanks for advance
Regards
Sybaris

**Comment by Skif-off** [comment]
Drag & Drop and [Show confirmation dialog after drop](https://doublecmd.github.io/doc/en/configuration.html#ConfigMouseDD)?

**Comment by sybaris** [comment]
Hi,

Thanks for your answer. 
You are rigth, the "Show confirmation dialog after drop" is the option I was searching.
And I confused with the "File operation / Show confirmation window for : Copy operation"
So this solve my question.
But what's its use of "File operation / Show confirmation window for : Copy operation" ?

Regards
Sybaris

**Comment by alexx2000** [comment]
It's for normal copy via F5.

**Comment by gitgt** [comment]
Please close.
