### ISSUE TITLE
Cannot drag and drop files to start executables (exe, bat)

### ISSUE THREAD

**Issue by unitwobble** [doublecmd/doublecmd#645]
Files cannot be dragged and dropped to executables (exe, bat) to start them using the dragged file as parameters.

**Comment by gitgt** [comment]
If WontFix, please close.

**Comment by ags1234** [comment]
> Files cannot be dragged and dropped to executables (exe, bat) to start them using the dragged file as parameters.

Do you know of an orthodox file manager that can do this?

**Comment by domportera** [comment]
> Do you know of an orthodox file manager that can do this?

windows' native file explorer can do this

**Comment by ags1234** [comment]
> > Do you know of an orthodox file manager that can do this?
> 
> windows' native file explorer can do this

But Windows Explorer is not an orthodox file manager.
However, I didn't know Windows Explorer can do this. It is an interesting feature.

**Comment by domportera** [comment]
> But Windows Explorer is not an orthodox file manager.

oh my bad. OneCommander can do it too. not sure if you'd call it an orthodox file manager but it's close if it's not

**Comment by flesti** [comment]
> > Files cannot be dragged and dropped to executables (exe, bat) to start them using the dragged file as parameters.
> 
> Do you know of an orthodox file manager that can do this?

why shouldn't dc be the first then ?
