### ISSUE TITLE
[Suggestion] Shortcut to only rename filename without extension

### ISSUE THREAD

**Issue by DHentzschel** [doublecmd/doublecmd#646]
I love doublecommander and recently I had a simple idea to improve the workflow.

I thought it would be useful to have an option to rename only the filename without modifying the file extension. So I can rename a bunch of files easily without locating the position before `.<extension>` using arrow keys.

A simple (configurable?) shourtcut e.g. `Ctrl` + `F2` would be a practical enhancement for the existing rename function.

It should be relatively simple to implement.
When there are multiple dots, just cut the rest beginning at the latter dot and work with the result.

What do you think about that?

**Comment by alexx2000** [comment]
Also you can enable option [Select file name without extension when renaming](https://doublecmd.github.io/doc/en/configuration.html#ConfigOperations).

**Comment by DHentzschel** [comment]
Oh, my bad. Thank you anyway for this.
