### ISSUE TITLE
How save selected "sort by name" for each path ?

### ISSUE THREAD

**Issue by Augusto7743** [doublecmd/doublecmd#648]
Hello.
When an path folder have media files with several extensions is selected "sort by name".
Is possible save the selected "sort by name" only for an path folder ?

Have an nice week.

**Comment by alexx2000** [comment]
Hi, no. But you can save this folder to directory hotlist and choose needed sorting in the hotdir settings. And use directory hotlist to open this folder later.

**Comment by alexx2000** [comment]
See also #605

**Comment by vagra** [comment]
I want this function.
