### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by kkarbowiak** [doublecmd/doublecmd#649]
[This screenshot](https://doublecmd.sourceforge.io/gallery/images/MainWindowDark.png) on the SourceForge page shows Double Commander with a dark theme. I like it very much, but cannot find a way in options to enable it. Is there a way to switch to dark theme?

I am on Windows 10 with system-wide dark theme.

**Comment by JonnyTech** [comment]
https://github.com/doublecmd/doublecmd/issues/413#issuecomment-1146351532

**Comment by alexx2000** [comment]
Also you need DC version from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by kkarbowiak** [comment]
Thank you both.

**Comment by gh-log** [comment]
why is it taking so long for stable version to have Dark Mode?
