### ISSUE TITLE
[FR] Hotkey to switch between two tabs (MRU)

### ISSUE THREAD

**Issue by megamorphg** [doublecmd/doublecmd#653]
Frequently I have over a dozen tabs open in one pane and I'd like to switch between the two tabs (without having to replace the opposite pane). Can we create a simple hotkey to switch between the two most recent tabs?

A more advanced version of this would be to show a temporary MRU pop-up (as in VS Code's or Firefox) where user can continue pressing tab to go further back in history and upon release it would switch to the selected tab.

**Comment by JonnyTech** [comment]
Does `ctrl+tab` not work for you?

**Comment by JonnyTech** [comment]
I just reread your report, you probably want `alt+0` instead. See https://doublecmd.github.io/doc/en/shortcuts.html for more keyboard shortcuts.

**Comment by gitgt** [comment]
ctrl+tab goes forward thru tabs. That's like default Firefox behavior. But Firefox has _very useful_ option "**Ctrl+Tab cycles through tabs in recently used order**" which I would like to see in DC.
