### ISSUE TITLE
Puts configdir to an unwritable location.

### ISSUE THREAD

**Issue by corvus1** [doublecmd/doublecmd#666]
```
Warning: Config file "/usr/share/doublecmd/doublecmd.xml" is not accessible for writing. Configuration will not be saved.
Loading configuration from /usr/share/doublecmd/
```

Am I stupid or is this an insane default for configdir? I had to specify `--config-dir '~/.config/doublecmd'` for it to become less insane.

```
Double Commander
Version: 1.1.0 alpha
Revision: 10420
Commit: 82960ca5a
Build date: 2022/11/12
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: "Gentoo"

Widgetset library: Qt 5.15.5, libQt5Pas 5.6.1
```

**Comment by Skif-off** [comment]
Looks like portable package (`doublecmd-*.tar.xz` ) from [here](https://github.com/doublecmd/doublecmd/releases) or from [here](https://sourceforge.net/p/doublecmd/wiki/Download/).

Try to check and (if exists) delete: `/usr/share/doublecmd/doublecmd.inf` or `/usr/lib/doublecmd/doublecmd.inf`
And inform the author of the ebuild file, it should be fixed.

**Comment by corvus1** [comment]
> Looks like portable package (`doublecmd-*.tar.xz` ) from [here](https://github.com/doublecmd/doublecmd/releases) or from [here](https://sourceforge.net/p/doublecmd/wiki/Download/).

It's built from gihub.

> Try to check and (if exists) delete: `/usr/share/doublecmd/doublecmd.inf` or `/usr/lib/doublecmd/doublecmd.inf` (if not found, try [command line](http://doublecmd.github.io/doc/en/help.html#iface_path) with `cd %COMMANDER_PATH%/doublecmd.inf`) 

It is present, though empty, removing it doesn't change the behavior.

> And inform the author of the ebuild file, it should be fixed.

Consider me well informed. :-) Could you tell me how to fix it?

**Comment by corvus1** [comment]
```
desktop /usr/share/doublecmd # cat doublecmd.sh 
#!/bin/sh

# Use this script for execute portable version of Double Commander

cd "`dirname "$0"`"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)

./doublecmd
```

Is that normal, by the way?

**Comment by alexx2000** [comment]
> Could you tell me how to fix it?

Go to directory where doublecmd binary located (in some other file manager, doublecmd should be closed), remove `doublecmd.inf`, remove `UseConfigInProgramDir` tag from `doublecmd.xml` if exists.



> Is that normal, by the way?

Your version is not portable so this file should not be used.

**Comment by corvus1** [comment]
Okay, that's much better, thanks!

Is there a way I can specify something at build-time or whatever, to build a stationary version, instead of portable, or will I have to `sed` that line out in the ebuild?

**Comment by Skif-off** [comment]
You can try `--install-prefix` instead of `--portable-prefix` or delete `doublecmd.inf` & `doublecmd.sh` before packaging.
And don't add `doublecmd.xml` (like [here](https://github.com/gentoo/gentoo/pull/14528)).

[Polkit action file](https://github.com/doublecmd/doublecmd/blob/master/install/linux/org.doublecmd.root.policy) may be useful.

**Comment by alexx2000** [comment]
> Is there a way I can specify something at build-time or whatever, to build a stationary version, instead of portable, or will I have to `sed` that line out in the ebuild?

What ebuild do you use?

You should build and install doublecmd like:
```
./build.sh release qt5

install/linux/install.sh --install-prefix=???
```

**Comment by corvus1** [comment]
> What ebuild do you use?

Something pretty nasty I'm cobbling together here:

```
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=7

EGIT_REPO_URI="https://github.com/doublecmd/doublecmd"

inherit eutils xdg-utils git-r3 desktop

ABBREV="doublecmd"
DESCRIPTION="Cross Platform file manager."
HOMEPAGE="http://${ABBREV}.sourceforge.net/"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS=""

IUSE="gtk qt4 qt5"
REQUIRED_USE=" ^^ ( gtk qt4 qt5 )"
RESTRICT="strip"

DEPEND=">=dev-lang/lazarus-1.8
        dev-libs/libqt5pas"
RDEPEND="
        ${DEPEND}
        sys-apps/dbus
        dev-libs/glib
        sys-libs/ncurses
        x11-libs/libX11
        gtk? ( x11-libs/gtk+:2 )
        qt4? ( >=dev-qt/qtpascal-2.5 )
        qt5? ( >=dev-qt/qtcore-5.6 )
"

S="${WORKDIR}/${PN}-${PV}"

src_prepare(){
         eapply_user

        use gtk && export lcl="gtk2"
        use qt4 && export lcl="qt"
        use qt5 && export lcl="qt5"
        use amd64 && export CPU_TARGET="x86_64" || export CPU_TARGET="i386"

        export lazpath="/usr/share/lazarus"

        find ./ -type f -name "build.sh" -exec sed -i 's#$lazbuild #$lazbuild --lazarusdir=/usr/share/lazarus #g' {} \;
}

src_compile(){
        ./build.sh beta || die
}

src_install(){
        diropts -m0755
        dodir /usr/share

        install/linux/install.sh --portable-prefix=build

        newicon pixmaps/mainicon/colored/v4_3.png ${ABBREV}.png

        rm "${S}/build/${ABBREV}/${ABBREV}.inf" || die "can't delete the inf"

        rsync -a "${S}/build/" "${D}/usr/share/" || die "Unable to copy files"

        dosym ../share/${ABBREV}/${ABBREV} /usr/bin/${ABBREV}

        make_desktop_entry ${ABBREV} "Double Commander" "${ABBREV}" "Utility;" || die "Failed making desktop entry!"
}

pkg_postinst() {
        xdg_desktop_database_update
}

pkg_postrm() {
        xdg_desktop_database_update
}
```

So, `/usr/share/doublecmd/doublecmd.xml` is not needed? I thought it was the default config or whatever. 

Anyway, it seems to work fine after deletion of the `inf` file.

**Comment by corvus1** [comment]
lol, that `/usr/share/doublecmd/doublecmd.xml` wasn't even under portage's control. I must've done something even nastier and blocked the memories of doing it. :-D It was just garbage in `/usr/share`

**Comment by alexx2000** [comment]
> So, `/usr/share/doublecmd/doublecmd.xml` is not needed?

No, default install does not include it.

So you had problem because use `--portable-prefix` which creates portable version. 

Removing `doublecmd.inf` convert it to normal version.

**Comment by corvus1** [comment]
It's not the only difference, though. The directory structure of the install image changes somehow. I'll have to take a closer look. And the whole ebuild of course needs to be reworked. I sometimes try to do it, when I'm in the right mood, but I'm not sure I'm making it better or worse on every such "rework".
