### ISSUE TITLE
Синхронизация каталогов и фильтры

### ISSUE THREAD

**Issue by WWolf13** [doublecmd/doublecmd#670]
Не работает синхронизация при применении фильтра из шаблона. Если вручную вставить список из шаблона, то всё работает
![Снимок экрана от 2022-11-16 16-50-47_ 2](https://user-images.githubusercontent.com/98021524/202198969-a14f98c8-cf9c-4f2c-b6f9-d974744ae851.png)
![Снимок экрана от 2022-11-16 16-50-47](https://user-images.githubusercontent.com/98021524/202198989-bac47b47-1d9d-415e-af8b-1333efe93bad.png)

**Comment by alexx2000** [comment]
Оказалось что при поиске по шаблону игнорируются подкаталоги, исправил этот момент. Попробуйте с ревизией  10439.

**Comment by WWolf13** [comment]
Отлично! Теперь работает как надо.
