### ISSUE TITLE
Сборки для Haiku

### ISSUE THREAD

**Issue by Katarn** [doublecmd/doublecmd#671]
Приветствую!

Lazarus уже поддерживает данную ОС: https://wiki.freepascal.org/Installing_Lazarus_on_Haiku
А вот чего ей не хватает, так это прикладного софта. Особенно такого незаменимого как двухпанельники.

**Comment by alexx2000** [comment]
Привет!

Хотел попробовать ради интереса собрать, но оказалось что все пакеты необходимые для разработки требуют Haiku R1 beta4 которая еще не выпущена. Где её можно скачать непонятно.

**Comment by Katarn** [comment]
Возможно вы имеете в виду репозиторий https://eu.hpkg.haiku-os.org/haiku/r1beta4/$(getarch)/current который можно подключить по инструкциям:

https://haiku-os.fandom.com/ru/wiki/Репозитории_пакетов
https://www.haiku-os.org/docs/userguide/ru/preferences/repositories.html

А вообще, можете заглянуть в уютненький чатик https://t.me/haiku_ru, там много разработчиков, которые занимаются портированием всего и вся. На любые вопросы ответят.

**Comment by alexx2000** [comment]
Я пробовал установить пакеты Qt (которые необходимы для Lazarus) через штатный менеджер пакетов HaikuDepot. Никаких дополнительных репозиториев при этом не подключал.

**Comment by Katarn** [comment]
Я про то, что обновиться до beta4 можно через подключение репозитория ссылку на который дал выше. После того как подключите, в том же HaikuDepot выбирайте проверку обновлений и система обновится до beta4.

**Comment by alexx2000** [comment]
Напильник и черная магия творят чудеса:

![VirtualBox_Haiku_17_11_2022_23_17_44](https://user-images.githubusercontent.com/13401398/202551096-205acf89-8682-49fb-bb77-a493f130f3c2.png)

**Comment by Katarn** [comment]
Мощщь!

**Comment by alexx2000** [comment]
Добавил начальную поддержку Haiku. Сам DC теперь собирается и в основном работает.

**Comment by Katarn** [comment]
Спасибо!

**Comment by alexx2000** [comment]
Экспериментальная сборка [Double Commander 1.1.x](https://sourceforge.net/projects/doublecmd/files/Haiku).
