### ISSUE TITLE
[Bug] Filter Mode is not persisted

### ISSUE THREAD

**Issue by limex** [doublecmd/doublecmd#675]
Steps:
* Enable "Keep saving setting modifications for next session" in Setting
* Use the Search/Filter Feature (below the files list) and click the "Filter" Button to enable Filter Mode.
* Close the feature with the 'X" button
* Use Search/Filter Feature again.

Expected Result:
* "Filter" Button is set and therefore Filter Mode enabled

Observed Result:
* "Filter" Button is NOT set and therefore Search Feature enabled

Version:
1.1.0. 10436

**Comment by alexx2000** [comment]
It's not a bug. Search mode start by Ctrl+S, filter mode start by Ctrl+F. Button only switch between this modes on the fly.
