### ISSUE TITLE
zips > 4gb

### ISSUE THREAD

**Issue by pwn0r** [doublecmd/doublecmd#68]
Can we finally have a fix for this problem? its been a while, I currently use 9640 build.

In this case we have centos.  Creating smaller ZIP archives works as expected, and is pretty fast.
When selecting multiple folders totalling about 6.5GB (and about 70k files total) the following happens:

when zipping doublecmd quickly goes to approximately 90% completion mark then gets in a loop. 
Basically for whatever reason it looks like doublecmd keeps deleting and creating a zip file. You can see this in the target listing. 
The size of target zip gradually increases like 50mb, 100mb, 200mb etc, then it suddenly resets to zero and then starts increasing again. 

At this point you may as well just cancel archiving process altogether as it would take forever. It looks like your zip archiver has troubles when creating zips >4gb. 

The same folders can be packed into zip eg. with a file roller GUI normally. 

I have just described one case which I had today on centos, but the actual problem is not new. I've seen a similar behavior from a default doublecmd app on 20.04 ubuntu, for instance. I think they use outdated 0.9.8 version there.

**Comment by Skif-off** [comment]
Which version?
Try the current release (0.9.10) or alpha version: [FAQ](http://doublecmd.github.io/doc/en/faq.html#repo). Portable [here](https://sourceforge.net/p/doublecmd/wiki/Download/).

**Comment by Skif-off** [comment]
From bug tracker: [0002465: DC silently produces broken ZIP when packing file of size >4G](https://doublecmd.sourceforge.io/mantisbt/view.php?id=2465), was fxed in 0.9.9.

**Comment by pwn0r** [comment]
> Which version?
> Try the current release (0.9.10) or alpha version: [FAQ](http://doublecmd.github.io/doc/en/faq.html#repo). Portable [here](https://sourceforge.net/p/doublecmd/wiki/Download/).

yeah, Im aware about this issue in the old version. BTW, can somebody actually kick ubuntu repo maintainers? They still have 0.9.8 version there

> apt list *doublecmd*
>Listing... Done
>doublecmd-common/focal,focal,now 0.9.8-1 all
>doublecmd-gtk/focal,now 0.9.8-1 amd64 [installed]
>doublecmd-help-en/focal,focal 0.9.7-1 all
>doublecmd-help-ru/focal,focal 0.9.7-1 all
>doublecmd-help-uk/focal,focal 0.9.7-1 all
>doublecmd-plugins/focal,now 0.9.8-1 amd64 
>doublecmd-qt/focal 0.9.8-1 amd64

**Comment by alexx2000** [comment]
Try with version 1.0.
