### ISSUE TITLE
Cannot connect to server via SSH (v1.0.8 and latest development version)

### ISSUE THREAD

**Issue by edmundlaugasson** [doublecmd/doublecmd#688]
I tried to open a new ftp connection selecting "SSH". I got the log in DoubleCMD:
```
Info: [3], Network error detected, attempting to reconnect...
Info: [3], Connecting to: myserver
Info: [1], 
Info: [3], Connection established
Info: [3], Key exchange method: curve25519-sha256
Info: [3], Encryption method: aes128-ctr
Info: [3], Host key method: ecdsa-sha2-nistp256
Info: [3], Server fingerprint: (MD5) <filtered>
Info: [3], Server fingerprint: (SHA1) <filtered>
Info: [3], Server fingerprint: (SHA256)  <filtered>
Info: [3], Authentication succeeded
Error: [6], SSH ERROR Unexpected error
Error: [6], SSH ERROR Unexpected error   
```
Tried with keyfile and also with password - both do not work. At the same time from terminal I can connect, even key agent will work and I do not need password for my SSH private key. Also file manager Dolphin can connect as it is KDE desktop environment.

Connection settings I tried:
general tab
Host
- myserver
- myserver:22
username is filled
password field is empty in case of using SSH public key
tried also with password, then SSH key file field was empty
SSH is selected, TLS is not selected.

advanced tab
- SSH key file is filled with full path (absolute address)
- tried separately:
  - SCP
  - SSH+SCP (no SFTP)

... it connects after long time but folder is empty but actually remote server is not empty.

When no one was selected on SSH section on Advanced tab, then it could not connect at all -> error message is then "Can not connect to the server!". It will ask password even in case of SSH key file is configured and no password will fit. Although in log window it shows, that connection succeeded...

proxy setting is none

**DoubleCMD versions**
Initially used [latest stable Qt version from Arch packages](https://archlinux.org/packages/community/x86_64/doublecmd-qt5/):
Double Commander
Version: 1.0.8
Revision: 191
Commit: ee1f44b3c
Build date: 2022/10/05
Lazarus: 2.2.4.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: EndeavourOS Linux
Widgetset library: Qt 5.15.7, libQt5Pas 5.6.1

Then latest development version as AppImage:
Double Commander
Version: 1.1.0 alpha
Revision: 10471
Commit: 8d21868
Build date: 2022/11/26
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: EndeavourOS Linux
Widgetset library: Qt 5.15.7, libQt5Pas 5.6.1

... still didn't work at all even with development version. I remember I could connect at November 4th, 2021 via SSH to same server with same credentials. Certainly then was older DoubleCMD. I used Linux Mint (Cinnamon probably) then. I usually use repository to install DoubleCMD.

**Comment by alexx2000** [comment]
Sorry but without test server there are no way to determine what is wrong. In this case **libssh2** library returns error `Unexpected error`. I don't know when it can happen.

**Comment by corvus1** [comment]
![Screenshot_20221130_081109](https://user-images.githubusercontent.com/4068104/204705873-17bc5fc5-240e-42a0-a026-9f4c6f567959.png)

there's a fun one

**Comment by alexx2000** [comment]
`SCP` option doesn't make sense and do nothing when [SSH+SCP (no SFTP)](url) are enabled.

**Comment by corvus1** [comment]
well... yeah, you are right.

```
Nov 30 09:16:51 router2 sshd[12136]: subsystem request for sftp by user corvus failed, subsystem not found
Nov 30 09:16:52 router2 sshd[12136]: Received disconnect from 192.168.1.2 port 34578:11: Normal Shutdown
Nov 30 09:16:52 router2 sshd[12136]: Disconnected from user corvus 192.168.1.2 port 34578
Nov 30 09:16:52 router2 sshd[12131]: pam_unix(sshd:session): session closed for user corvus
```

**Comment by corvus1** [comment]
I noticed one weird thing about ssh-agent. When authenticating with a private RSA key, it works fine in shell, or for SCP, but for SFTP it tries to use the deprecated ssh-rsa signature algorithm, and recent versions of openssh server just refuse the connection. I reproduced in midnight commander and dolphin. 

My solution was to regenerate my private keys to ed25519 instead of RSA, which is recommended anyway.

**Comment by gitgt** [comment]
Seems  like this should be closed.

**Comment by zacisco** [comment]
i have same problem ...
for keys rsa and ed25519 same errors

if using pub + priv keys
```
Информация: [3], Connection established
Информация: [3], Key exchange method: diffie-hellman-group-exchange-sha256
Информация: [3], Encryption method: aes128-ctr
Информация: [3], Host key method: ssh-rsa
Информация: [3], Server fingerprint: (MD5) <>
Информация: [3], Server fingerprint: (SHA1) <>
Информация: [3], Server fingerprint: (SHA256) <>
Информация: [3], Auth via public key for user: admin-evan
Ошибка: [6], Authentication by publickey failed 
```

if using priv only (show pass dialog,after enter > very long wait)
```
Информация: [1], 
Информация: [3], Connection established
Информация: [3], Key exchange method: diffie-hellman-group-exchange-sha256
Информация: [3], Encryption method: aes128-ctr
Информация: [3], Host key method: ssh-rsa
Информация: [3], Server fingerprint: (MD5) <>
Информация: [3], Server fingerprint: (SHA1) <>
Информация: [3], Server fingerprint: (SHA256) <>
Информация: [3], Authentication succeeded
Ошибка: [6], SSH ERROR Timed out waiting on socket
Ошибка: [6], SSH ERROR Timed out waiting on socket
Ошибка: [6], SSH ERROR Timed out waiting on socket
Ошибка: [6], SSH ERROR Timed out waiting on socket
Информация: [1], CONNECT /NAME
Ошибка: [6], SSH ERROR Timed out waiting on socket
```

**Comment by alexx2000** [comment]
Try with DC from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).
