### ISSUE TITLE
SSH FTP private key requires password for each copied file

### ISSUE THREAD

**Issue by toamz** [doublecmd/doublecmd#697]
While trying to copy multiple files from SSH FTP to local disk with authentication by password protected private key, doublecmd asks for the password before transferring each individual file in selection (maybe except the first one).

I would expect it to either remember the password from the initial connection for browsing the files, or ask for it just once before starting copying the files.

(Select multiple files or a folder containing them on the server, F5 to copy, password prompts start to appear)

Version:
Double Commander
Version: 1.1.0 alpha
Revision: 10480
Commit: cc3ca9662
Build date: 2022/11/28
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 Home 21H2 x86_64

**Comment by alexx2000** [comment]
I cannot reproduce. I added private key passphrase caching. Try with revision 10490.

**Comment by toamz** [comment]
Looks like it is fixed in the newest revision.
I tried it again in the old version, and found that it doesn't happen with quick connection, but just with saved connection. Maybe that's why it didn't happen.
Anyway, good job.
