### ISSUE TITLE
Download pages (wiki and SF.net) miss the macOS Cocoa version! Bad!

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#698]

**Comment by alexx2000** [comment]
I do not support macOS officially. LCLCocoa has too many issues. I provide only snapshots as is.

**Comment by Alexey-T** [comment]
I cannot install the Cocoa x64 snapshot!

![dc Screenshot from 2022-12-03 23-45-09](https://user-images.githubusercontent.com/4154978/205461412-b894e7ff-5434-4f8a-b311-08945a889289.png)

**Comment by alexx2000** [comment]
Disk image creates with APFS file system which macOS 10.11 does not support. I changed it by HFS+.
