### ISSUE TITLE
Can't sort by date by clicking on "Date" Column

### ISSUE THREAD

**Issue by grappas** [doublecmd/doublecmd#70]
Actually I can't sort anything if there's more items than screen can display.

![obraz](https://user-images.githubusercontent.com/1036957/113523854-e42c0080-95aa-11eb-8717-eed3bfb264ef.png)
![obraz](https://user-images.githubusercontent.com/1036957/113522864-3fa6c000-95a4-11eb-8439-8eb599564595.png)

**Comment by sl5net** [comment]
for that i use two commanders. i use "Midnight Commander" for sorting Folders.
