### ISSUE TITLE
[Samba]: show list of available shares when accessing \\Address

### ISSUE THREAD

**Issue by PetbkA** [doublecmd/doublecmd#708]
### Description

**OS:** Windows 10 LTSC 2021 (version 21H2) x64
**DC:**
```
Double Commander
Version: 1.0.9
Revision: 222
Commit: a844456e4
Build date: 2022/12/03
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H2 x86_64
```

If I'll open Windows share by entering `\\Address`:
1. In Total Commander I'll see a list of available shares (e.g. admin shares);
2. In Double Commander I'll see [nothing](https://user-images.githubusercontent.com/22843816/206843676-4f4b6d5a-153e-4963-a125-08cba83e3806.png).

It would be nice to see list of available shares

**Comment by alexx2000** [comment]
DC supports it. Enable Menu->"Show"->"Show Hidden/System Files" to see admin shares.

**Comment by PetbkA** [comment]
Indeed, thank you! :)
