### ISSUE TITLE
Hash info button

### ISSUE THREAD

**Issue by Xant1k** [doublecmd/doublecmd#71]
How to create button to get blake2bp(sp) hash sum of file and size in bytes of the view 82,1 КБ (84 160 bytes) and filename? And then copy to clipboard or save to .txt file?

**Comment by Skif-off** [comment]
Windows? Try to add new [Blake2Hash](http://forum.wincmd.ru/viewtopic.php?t=17081), add column set and use "Copy all shown columns" (internal command `cm_CopyFileDetailsToClip`).

Other ways:
- `cm_CheckSumCalc` and script (Lua, Python and so on) for file size adding;
- `hashlib` or `pyblake2` (Python);
- some script with `b2sum`.

**Comment by Xant1k** [comment]
Как не пытался заставить отображаться корректно - не выходит.
По шагам:
1. Заходим в настройки > Параметры > Плагины > Плагины WDX, добавляем вышеуказанный.
2. Далее там же в параметрах переход к Список файлов > Колонки > Наборы колонок, создаём новую колонку указав нужный хэш.
3. Переходим в Панель инструментов, выбираем внутренняя команда и из выпадающего списка выбираем cm_CopyFileDetailsToClip, кнопка будет добавлена.
4. Выделяем файлы и жмём по кнопке, получается примерно такое
btsearch	html	15	29.12.2020 15:25:53	--a-----	9eac16d2546663af008007a30c8a76464ddfef3f876c07252e844e13761f5d564985b09df29df93b17f12ebe5ad6df37b31164e6e6f9a229e2b2589379706630

**Comment by Skif-off** [comment]
2. Создаём новый набор колонок и оставляем только одну колонку:
```[тут-нужное-поле-плагина] [DC().GETFILESIZE{}] [DC().GETFILEPATH{}][DC().GETFILENAME{}]```
Переходим в раздел "Список файлов" и меняем формат размера файлов на байты ("Б").
3. В главном меню Выделение > Копировать содержимое всех колонок.
4. Получаем примерно такое
```
818aacd3 15 639 728 /usr/lib/doublecmd/doublecmd
```
Только с размером не всё гладко, DC, похоже, всегда с группировкой по разряду выдаёт (плагин под Win с разбегу не нашёл, в принципе, в крайнем случае можно на Lua набросать).

**Comment by Skif-off** [comment]
> Переходим в раздел "Список файлов" и меняем формат размера файлов на байты ("Б").

Ошибся, не нужно, достаточно заменить `[DC().GETFILESIZE{}]` на `[DC().GETFILESIZE{BYTE}]`.

**Comment by alexx2000** [comment]
Для вопросов лучше использовать [форум](https://doublecmd.sourceforge.io/forum).
