### ISSUE TITLE
Allow toggling file pane orientation between vertical and horizontal

### ISSUE THREAD

**Issue by Gitoffthelawn** [doublecmd/doublecmd#711]
### Description

When taking full advantage of long filenames, orienting the file panes horizontally is advantageous.

Another file manager, FreeCommander can orient the panes horizontally, but it is a Windows-only application:
[FreeCommander Horizontal Panes Screenshot](https://freecommander.com/wordpress/wp-content/gallery/screenshots_en/Fc_en_grey.png)
(The above screenshot is from the FreeCommander website, and doesn't reflect the real power of horizontal panes.)

Would it be possible to allow toggling file pane orientation between vertical and horizontal in Double Commander?

**Comment by alexx2000** [comment]
[Horizontal Panels Mode](https://doublecmd.github.io/doc/en/help.html#mnu_view)
