### ISSUE TITLE
This is not a valid plugin! A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by gazeto** [doublecmd/doublecmd#719]
### Version

Double Commander
Version: 1.0.9
Revision: 222
Commit: a844456e4
Build date: 2022/12/03
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: i386-Win32-win32/win64
OS version: Windows 10 21H2 x86_64

### Description

Installing the [32-bit Excellence 1.20 plugin](http://totalcmd.net/plugring/xlsview.html) results in the above (subject line) error message.
It was discussed a long time ago and apparently resolved for TC here: https://ghisler.ch/board/viewtopic.php?t=28432&start=15
The solution for TC is auto-installation (opening the zip file from within TC) which is not possible in DC. Or is there a workaround? Is there any other way to get this work?

Or maybe any other plugin that I am not aware of that works not only with xlsx but also xlsm and xlsb? Is there any place to request plugins, by any chance?

Thanks!

**Comment by alexx2000** [comment]
> Or maybe any other plugin that I am not aware of that works not only with xlsx but also xlsm and xlsb?

[odbc-wlx](https://totalcmd.net/plugring/odbc-wlx.html) plugin supports all three formats: `ext="MDB" | ext="XLS" | ext="XLSX" | ext="XLSB" | ext="XLSM" | ext="DSN"`

**Comment by gazeto** [comment]
Thanks a lot!
I didn't like the fact that this requires MS Access Database Engine (using DC as portable/no admin rights).
However, the upside is that odbc-wlx is available for 64 bit...

**Comment by alexx2000** [comment]
Only Excellence plugin author can say what is wring.
