### ISSUE TITLE
DC зависает если есть подключенный виртуальный диск (шара)

### ISSUE THREAD

**Issue by Urvdmih** [doublecmd/doublecmd#72]
Есть переносной диск с кнопкой включения, на нем создана шара, подключенная в сеть через роутер Кинетик Гига 3.
Когда выключают, а затем включают электричество, то переноска не включается. В итоге DC при старте не может запуститься и более того, его процесс система не может завершить. Если в этот момент включить переноску - DC тут же продолжает запуск как ни в чем не бывало.

**Comment by Skif-off** [comment]
В альфа-версии проверяли? Полагаю, у вас Win: [тут](https://sourceforge.net/p/doublecmd/wiki/Download/) можно скачать портативную версию, [отсюда](https://doublecmd.sourceforge.io/site/eng/snapshots.html) скачать архив 7-Zip той же разрядности и распаковать его, заменив файлы портативной версии.

**Comment by Urvdmih** [comment]
> В альфа-версии проверяли? Полагаю, у вас Win: [тут](https://sourceforge.net/p/doublecmd/wiki/Download/) можно скачать портативную версию, [отсюда](https://doublecmd.sourceforge.io/site/eng/snapshots.html) скачать архив 7-Zip той же разрядности и распаковать его, заменив файлы портативной версии.

Вы правы, проблема ушла после обновления. Я вроде ченджлоги читаю, но видимо пропустил исправление этого бага.
