### ISSUE TITLE
add a function to access the wsl virtual machine?

### ISSUE THREAD

**Issue by jack-liew** [doublecmd/doublecmd#724]
### Description

![image](https://user-images.githubusercontent.com/102201538/208590183-86740677-a9df-4ee3-9f6a-4a290124d9f1.png)

![image](https://user-images.githubusercontent.com/102201538/208590394-3d110a4a-52b0-49a2-90dd-6c9e9f588006.png)

Thanks

**Comment by jack-liew** [comment]
> Enter "\wsl$" to the path and you will got it (DC 1.0.9 or higher).

I did not respond when I entered  \wsl$ in the command line of DC 1.0.9. 
where can I enter this command in the DC?

Thank u

**Comment by alexx2000** [comment]
https://doublecmd.github.io/doc/en/help.html#iface_dir

**Comment by jack-liew** [comment]
> https://doublecmd.github.io/doc/en/help.html#iface_dir

I see~~~, just like "\\wsl.localhost\Debian\".

Thank U

**Comment by doctorrsm** [comment]
> Enter "\wsl$" to the path and you will got it (DC 1.0.9 or higher).

"\\wsl$"

**Comment by doctorrsm** [comment]
> > Enter "\wsl$" to the path and you will got it (DC 1.0.9 or higher).
> 
> \\wsl$
