### ISSUE TITLE
Abitilty to create multiple files/folders

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#725]
### Description

In bash, one can create multiple files/folders such as:

```
mkdir name{00..99}
touch file{00..99}.txt
```

When trying from DC in either new directory dialog or command-line then multiple files are not created. Is it possible to pass such commands to the underlying shell to be executed?

**Comment by alexx2000** [comment]
DC does not have the underlying shell. If you want execute command in the terminal then you should use Shift+Enter hotkey or [enable built-in terminal](https://doublecmd.github.io/doc/en/configuration.html#ConfigLayout).
