### ISSUE TITLE
Hourglass cursor still shown indefinitely

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#728]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10526
Commit: 92899fb35
Build date: 2022/12/22
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.1.0

### Description

Unfortunately, the issue which is described in #699 still occurs in revision 10526. The symptoms are identical, and the way to reproduce the issue is also identical. See #699 for details.

Since I'm not allowed to re-open #699 (at least I found no button to do so), I'm opening a new ticket for this issue.

**Comment by rich2014** [comment]
R10526 works well on MacOS 12.6.

I'll test on MacOS 13.

**Comment by rich2014** [comment]
Fixed by #729

**Comment by Andreas0602** [comment]
I can confirm that the problem is solved for me now. Thank you very much, @rich2014!

**Comment by rich2014** [comment]
it's great!
