### ISSUE TITLE
Options - minor bug

### ISSUE THREAD

**Issue by quantum11110** [doublecmd/doublecmd#730]
Version: 1.1.0 alpha/Revision: 10526/Commit: 92899fb35/Build date: 2022/12/22/Lazarus: 2.2.5.0/FPC: 3.2.2
OS version: Windows 11 Home 22H2 x86_64
After clicking:
Config>Options...>Colors
![Screenshot - Error](https://user-images.githubusercontent.com/121349828/209442169-06aab921-5757-474d-bcc5-7004186137c8.png)
"Abort"      "Ignore"

**Comment by alexx2000** [comment]
What language file do you use?

**Comment by quantum11110** [comment]
Resolved.
Thank you
