### ISSUE TITLE
Hourglass cursor shown indefinitely (4)

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#733]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10528
Commit: 6e25b0725
Build date: 2022/12/25
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.1.0

### Description

First of all, I would like to thank you, @alexx2000 and @rich2014, for your hard work on Double Commander! I guess that the issue #731 is supposed to be fixed in the snapshot revision 10528. But it isn't, at least for me. The behavior described in #731 is unchanged. It would be great if you could fix it.

**Comment by rich2014** [comment]
I tested r10528 on MacOS 13.

it works well.

could it be that you tested the wrong version?

https://user-images.githubusercontent.com/102933068/209463595-dbe3331f-829c-45ff-a7be-3eef6c698946.mp4

**Comment by Andreas0602** [comment]
I tested the correct version. But I tested it in a different way than you. When I test it in the same way as you, then everything is fine for me too. But when I test it as shown in the attached mp4 file, it's not okay.

https://user-images.githubusercontent.com/79788982/209464794-3f73c6b6-c1b2-4ca0-8b92-b669378311a5.mp4

**Comment by rich2014** [comment]
interesting :)
fixed again.

**Comment by Andreas0602** [comment]
Yeah, I'm not able to reproduce the issue with the latest snapshot. Thank you very much again @rich2014 and @alexx2000 for your great support. 👍

**Comment by rich2014** [comment]
great!
