### ISSUE TITLE
repost: macOS bug with some symbols cannot be entered

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#737]
### Version

DC: 1.0.9~222
OS: macOS Ventura German locale

### Description

Bug  also exists in macOS version of DCmd.
https://github.com/Alexey-T/CudaText/issues/4728

@rich2014 You have good proposal for macOS keyboard handling. maybe DCmd can apply your fix locally? will it be fixed? you may 'tag' the username from my report and ask him to test.

**Comment by rich2014** [comment]
@Alexey-T 

i have tested that after applying the patches, most of the related issues can be fixed: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40008

**Comment by zxcat** [comment]
@rich2014, looks great. btw, can this patch help to set `⌘`+`,` hotkey to open Settings? Current hotkey dialog just ignores comma (and other non alpha/num/F* symbols) for me.

**Comment by rich2014** [comment]
@zxcat it's another issue.

**Comment by rich2014** [comment]
@zxcat `⌘`+`,` hotkey is supported now. try version 10563.
