### ISSUE TITLE
Ошибка во встроенном просмотрщике XML

### ISSUE THREAD

**Issue by Corsten56** [doublecmd/doublecmd#74]
Здравствуйте.

Выдаётся ошибка при попытке просмотра (F3) файла новостных групп NZB.
"Не удается отобразить страницу XML 
Не удается просмотреть ввод XML с использованием списка стилей . Исправьте ошибку и затем нажмите кнопку "Обновить" или повторите попытку позднее. 

--------------------------------------------------------------------------------

Неопознанная ошибка Ошибка при обработке ресурса ''http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd''."

Пример прилагаю.
[Rich Homie Quan - Walk Thru ft. Problem.zip](https://github.com/doublecmd/doublecmd/files/6341167/Rich.Homie.Quan.-.Walk.Thru.ft.Problem.zip)

**Comment by alexx2000** [comment]
Здравствуйте, полагаю у вас установлен какой-то плагин. По умолчанию DC просматривает XML как простой текст.

**Comment by Corsten56** [comment]
А, действительно, проблема в устаревшем HTMLView.
Смутило то, что при нажатии О программе - О просмотрщике пишет "Внутренняя программа просмотра Double Commander".
Попробую поискать другой плагин просмотра.
