### ISSUE TITLE
Removing language directory does problems ?

### ISSUE THREAD

**Issue by Augusto7743** [doublecmd/doublecmd#741]
Hello Double Commander creator.
Thanks very much making your software.

Inside Double Commander have an "language" directory without files related with english.
Removing that directory does problems ?

Have an nice day.

**Comment by alexx2000** [comment]
Hi, you can remove this directory if you use only English.

P.S. Use [discussions](https://github.com/doublecmd/doublecmd/discussions) to ask questions.

**Comment by Augusto7743** [comment]
Thanks for replying.
Excuse for posting in wrong area.

Thanks for making your amazing file manager helping extremely Linux users.
Have an nice week.
