### ISSUE TITLE
Hide drives/mount points if they are listed in Ignore list

### ISSUE THREAD

**Issue by hyperblast** [doublecmd/doublecmd#743]
### Description

It would be nice to allow hiding certain mounts from drive list / drive buttons / etc

**Comment by Skif-off** [comment]
"Configuration" in the main menu > Options... > Behaviors > [Drives blacklist](https://doublecmd.github.io/doc/en/configuration.html#ConfigBehaviors)?

**Comment by hyperblast** [comment]
> "Configuration" in the main menu > Options... > Behaviors > [Drives blacklist](https://doublecmd.github.io/doc/en/configuration.html#ConfigBehaviors)?

Didn't find that in the first try, thank you.
