### ISSUE TITLE
Ask Before Quitting (Exit Confirmation)

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#744]
### Description

On macos it's very easy to press `Cmd`+`Q` instead of QuickView. This instantly and silently closes the DoubleCommander, which is a poor user experience...

### Proposed technical implementation details (optional)

Add an option "**Exit Confirmation**": if enabled, DC will ask before exiting.

**Comment by alexx2000** [comment]
I added `ConfirmQuit` key to `doublecmd.xml`.

**Comment by zxcat** [comment]
Работает отлично, благодарю!

Но из самого DC установить опцию не удалось — перезаписывает конфиг при выходе.

**Comment by alexx2000** [comment]
Из самого DC надо редактировать через [Конфигурацию](https://doublecmd.github.io/doc/ru/configuration.html#ConfigDC), кнопки `Редактировать` и `Применить`.

**Comment by aliron19** [comment]
Hi, 

Great news! Where can I download v1.1.0? I can't find the `ConfirmQuit` key in `doublecmd.xml` on v1.0.10 (released yesterday). 

Thank you very much.

**Comment by ags1234** [comment]
https://doublecmd.sourceforge.io/site/eng/snapshots.php
