### ISSUE TITLE
Force text mode when open internal Viewer

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#745]
### Description

In TC we can press `Alt`+`Shift`+`F3` to view file in text mode (disable plugins/multimedia when show Lister window). It's useful for some tasks, but DC can't do it.

### Proposed technical implementation details (optional)

Some commands in DC have parameters (e.g. `cm_ActivateTabByIndex`). It should be simple to add some `forceText` parameter to `cm_View` command to open viewer in text mode (maybe also `forceHex`, `forceBin`).

The question is how to behave when multiple files selected. It's possible to:
1. parameter works only to view single file, ignored when several files selected.
2. open in text mode only 1st file. user can change mode, next file mode autodetected if so.
3. when move to another file, the mode returns to "text" even if user changed it.
4. separate parameter like `forceTextAll` to behave like **3)** if set and **2)** if not set

I almost always use this TC feature for single file so prefer **1)** or **4)**.

**Comment by alexx2000** [comment]
I implemented first variant. I added parameter `mode`, possible values:
```
mode=text
mode=bin
mode=hex
mode=dec
```

**Comment by zxcat** [comment]
works perfect, thank you!
