### ISSUE TITLE
Search "Find text in file" "Encoding" difficult to see !

### ISSUE THREAD

**Issue by nvdavsamd** [doublecmd/doublecmd#747]
### Description

Hi i left my glasses on Krypton and is hard to see the text in search in files !
![dcsearch](https://user-images.githubusercontent.com/122004809/211185955-34d71cf7-dd3b-49fb-8756-8620f5978002.jpg)

Thanks

### Proposed technical implementation details (optional)

The text is black and should be like UTF-16LE **White**

**Comment by ags1234** [comment]
I was also using his glasses :) and cannot clearly distinguish in this window which buttons are active and which are not.

![2023-01-08 10 30 20](https://user-images.githubusercontent.com/21011513/211187312-8d976d73-7778-4569-bbe5-3ffdc5f2dde3.png)

**Comment by ags1234** [comment]
Yay, you fixed them both! Thanks!
