### ISSUE TITLE
AkelPad source code for Visual Studio 2022 Community

### ISSUE THREAD

**Issue by nvdavsamd** [doublecmd/doublecmd#749]
### Description

Hi Alex off topic !
Please try this Notepad replacer !
 
https://github.com/nvdavsamd/AkelPad

### Proposed technical implementation details (optional)

Can You incorporate AkelPad into Doublecmd ?!
Is it doable ?

**Comment by alexx2000** [comment]
Hi, no of course. But you can set it as external editor in the options.
