### ISSUE TITLE
openSUSE Build Service - Qt5 deb packages are empty

### ISSUE THREAD

**Issue by shooreek** [doublecmd/doublecmd#75]
Qt5 packages for Ubuntu and Debian that can be found at:
https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-qt5
are empty. 

```
$ dpkg -c doublecmd-qt5_0.9.10-1_all.deb 
drwxr-xr-x root/root         0 2021-01-30 10:55 ./
drwxr-xr-x root/root         0 2021-01-30 10:55 ./usr/
drwxr-xr-x root/root         0 2021-01-30 10:55 ./usr/share/
drwxr-xr-x root/root         0 2021-01-30 10:55 ./usr/share/doc/
drwxr-xr-x root/root         0 2021-01-30 10:55 ./usr/share/doc/doublecmd-qt5/
-rw-r--r-- root/root       233 2021-01-30 10:55 ./usr/share/doc/doublecmd-qt5/changelog.Debian.gz
```

**Comment by Skif-off** [comment]
It's not a bug, `doublecmd-qt5` is a transitional package: don't use this packages for new installation, use `doublecmd-qt` instead.

**Comment by shooreek** [comment]
This Qt5 package is referenced at:
https://sourceforge.net/p/doublecmd/wiki/Download/

Does it make sense to present this transitional package like normal one? It is impossible to install it if no repo is added. But if repo is added, probably there is no need in this standalone package.

**Comment by shooreek** [comment]
Well, other packages also cannot be installed because they depend on `doublecmd-common` which is not available for download... So I don't know what is the purpose of package download on openSUSE Build Service... One has to add repository anyway.

**Comment by Skif-off** [comment]
In Debian/Ubuntu DC consists of three packages:

- `doublecmd-gtk` (GTK2) or `doublecmd-qt` (Qt5);
- `doublecmd-plugins`;
- `doublecmd-common` (icons, language files and other).

But openSUSE Build Service shows only main package (first package). If you want to install Dc manually, you should download all of them ([directly link](http://download.opensuse.org/repositories/home:/Alexx2000/) to the repository content).

Before Qt4 was dropped, DC was available as `doublecmd-gtk` (GTK2), `doublecmd-qt` (Qt4) and `doublecmd-qt5` (Qt5), but now `doublecmd-qt5` allows to transparently migrate to a new version when you update your distribution (Qt4-version will be automatically updated to Qt5-version) and not needed in other cases.

> One has to add repository anyway.

Best way :)
