### ISSUE TITLE
GTK build on Linux fails due to Image32 dependency failure

### ISSUE THREAD

**Issue by raxamit** [doublecmd/doublecmd#750]
### Version

Lazarus: 2.0.12.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: "Gentoo"
Widgetset library: GTK 2.24.33

Commit: 29fa477ad5ca705e2cc4d667c07764608b32e1c3 

### Description

Since about 1-2 weeks ago, DC fails to get built on Gentoo Linux for GTK environment.

Here are the steps:
```
git pull
git clean -fdx
lcl=gtk2 ./build.sh release
```
Log:

> (9022) Compiling resource /home/kanopus/Repos/doublecmd/plugins/dsx/DSXLocate/lib/DSXLocate.or
(9015) Linking /home/kanopus/Repos/doublecmd/plugins/dsx/DSXLocate/dsxlocate.dsx
(1008) 410 lines compiled, 0.1 sec
(1021) 5 warning(s) issued
(1022) 3 hint(s) issued
Error: (lazbuild) Broken dependency: Image32

**Comment by alexx2000** [comment]
Lazarus 2.0.12 is too old, DC requires at least Lazarus 2.2.0.

**Comment by raxamit** [comment]
Upgrading Lazarus (yet it is still in testing repository in Gentoo) resolved the issue - thank you very much!
