### ISSUE TITLE
Warning message about not enough space when copying to ramfs

### ISSUE THREAD

**Issue by MadMaxx64** [doublecmd/doublecmd#753]
### Version

Double Commander
Version: 1.0.9
Revision: 222
Commit: a844456e4
Build date: 2022/12/05
Lazarus: 2.0.0.4
FPC: 3.0.4
Platform: x86_64-Linux-qt5
OS version: MX 19.4 patito feo

Widgetset library: Qt 5.11.3, libQt5Pas 5.6.1

### Description

Minor bug: Mounted ramfs filesystems are displayed with 0 B free. When copying files to file system, a warning message pops up "No enough space on target drive" which can be overruled, but is annoying.

Expected behaviour: Either show and use the actual free size of ramfs or - if not possible - add an option to disable the message when copying to ramfs.
It shouldn't be disabled in general, since copying to ramfs CAN overflow the ram and halt the system.

**Comment by MadMaxx64** [comment]
Just updated on the affected system and works like a charm now. Nice solution.

**Comment by shula** [comment]
Problem is still there -- if it's related:

Filesystem mount type:  "adbfs"
adbfs on /home/user/andfiles type fuse.adbfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

(filesystem does not appear on `df` command!)

Double Commander
Version: 1.1.20 gamma
Revision: 607
Commit: d7d098956
Build date: 2024/11/10
Lazarus: 3.6.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt6
OS version: EndeavourOS Linux
