### ISSUE TITLE
Auto refresh does not work on macOS

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#755]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10546
Commit: c741965be
Build date: 2023/01/11
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.1.0

### Description

Auto refresh does not work on macOS. Steps to reproduce:

1. Press Shift+F4 and enter "Test.txt" as file name.
2. In the internal editor, type some text.
3. Press Esc.
4. In the dialog "File .../Text.txt changed, save?", press Enter to choose the default "Yes".

**Expected result:** In the file panel, the correct size of the file "Text.txt" will be shown.
**Actual result:** In the file panel, 0 will be shown as the size of the file "Text.txt".

<img width="665" alt="settings" src="https://user-images.githubusercontent.com/79788982/212476106-f840211a-d8e7-42e4-b405-d71f3a1921e8.png">

**Comment by rich2014** [comment]
it's not a bug, but limitation of kqueue/kevent.

there is plan to replace kqueue/kevent with fsevents on MacOS.

**Comment by rich2014** [comment]
you are welcome. and there is significant improvements in the revision 10563.

**Comment by alexx2000** [comment]
It is a feature, see [Highlight new and updated files](https://doublecmd.github.io/doc/en/configuration.html#ConfigViewEx) option. Simply it does not work under macOS before.

**Comment by rich2014** [comment]
@alexx2000 

i tested it on my computer.

the external editor may modify the Xattr attributes of the file multiple times, causing multiple events.

refresh has been reduced by fine-tuning in #784 so that the visuals are smoother.

**Comment by goyalyashpal** [comment]
was this issue same as this one: https://doublecmd.sourceforge.io/mantisbt/view.php?id=1900
