### ISSUE TITLE
Doublecmd downloads reveal that the 32-bit version is almost useless ! 

### ISSUE THREAD

**Issue by nvdavsamd** [doublecmd/doublecmd#760]
### Description
**december 2022** 
(total downloads)
![doublecmd](https://user-images.githubusercontent.com/122004809/213126319-f5fc6a04-b4ab-41b4-908e-85381aafa5a4.jpg)

**december 2021** 
(total downloads)
![2021](https://user-images.githubusercontent.com/122004809/213128129-bb90d875-418f-48d9-9e0e-2751a149ffe9.jpg)

More and more are quitting Total Commander for Double Commander !
Funny is that I got so many requests to scrap Total Commander and replace it with Double Commander in my projects !
https://berofusion.blogspot.com

At first in 2021 i was so skeptical of working on something else that Total Commander !
But due of so many request (hundreds and hundreds) and after i tested Double Commander, well i erased for good Total Commander and i don't use it over 1 year now !
Many thanks for the persons who pointed me to this wonderful Double Commander !

Double Commander is sure Navigates with most success OUR never ending files..

### Proposed technical implementation details (optional)

Honestly 64-bit is a must today and must be further optimized !
I would greatly appreciated if 32-bit code will be removed and will be only 64-bit !

**Comment by ags1234** [comment]
But isn't this just one code base with many compilation targets?
If is is so, x32 is created almost effortlessly by an automated process.

**Comment by nvdavsamd** [comment]
yes it is.
but what i mean was.. optimization for x64. speed like instant gui response.
as i open first time doublecmd, i still see a white 2 panel before full initialization.. even if the darktheme is set. it's not ok.

**Comment by alexx2000** [comment]
DC will support 32 bits as long as it is needed. DC has 64 bit optimizations where it is possible.

> but what i mean was.. optimization for x64. speed like instant gui response.
> as i open first time doublecmd, i still see a white 2 panel before full initialization.. even if the darktheme is set. it's not ok.

It is not related with 64 bit. I don't know a way to fix it.
