### ISSUE TITLE
Range check error with .tar.gz file

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#763]
### Version

Double Commander
Version: 1.0.9
Revision: 222
Commit: a844456e4
Build date: 2022/12/03
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 21.3 Wildflower

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

### Description

Similar to my other issue, now for `.tar.gz` file: [EdgeSwitch.tar.gz](https://github.com/doublecmd/doublecmd/files/10471021/EdgeSwitch.tar.gz)

**Comment by alexx2000** [comment]
Try with DC 1.0.10.

**Comment by JonnyTech** [comment]
I should have tried snapshots too. It is indeed fixed. Thank you.
