### ISSUE TITLE
Add an option to confirm before exit

### ISSUE THREAD

**Issue by aliron19** [doublecmd/doublecmd#765]
### Description

Hi,

Would it be possible to add an option to ask for confirmation before closing DC?

Right now, DC closes without warning or asking you before doing so, and if you have a lot of tabs open and close DC by error, it's a bit tedious to reopen all of them again. I think it would be useful to add a checkbox in the Configuration menu (under Behaviors, maybe?), that would allow the user to decide if he wants to be asked before closing DC.

Thanks.

**Comment by alexx2000** [comment]
Hi, DC 1.1.0 already has such option, see #744

**Comment by aliron19** [comment]
Hi, 

I didn't see that on the changelog. I've replied on [#744](https://github.com/doublecmd/doublecmd/issues/744), so you can close this now.

Thanks.
