### ISSUE TITLE
macos: cm_Transfer keyboard shortcuts not working

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#766]
### Version

I am no at the Mac any more:
doublecmd-1.1.0-10555.cocoa.x86_64.dmg
11.6.5 macOS Big Sur

### Description

Yesterday I was on a Mac and the `cm_TransferLeft` and `cm_TransferRight` default keyboard shortcuts (`ctrl+left` and `ctrl+right`) did not work - I remapped to `alt+cmd+left` and `alt+cmd+right` then all worked fine.

i shall be at a Mac again later this week if there are any tests that you would like me to try.

**Comment by JonnyTech** [comment]
From https://github.com/doublecmd/doublecmd/pull/761#issuecomment-1408773075

> ctrl+left and ctrl+right are the default system shortcuts of MacOS.

@rich2014, thanks for the reply. I do not use MacOS often and am unaware of those conflicting shortcuts.

Can you tell me what `ctrl+left` and `ctrl+right` do on that OS as they are not listed on Apple's Mac keyboard shortcuts list (https://support.apple.com/en-us/HT201236).

How I can disable them in the system, and why they are assigned in DC?

**Comment by rich2014** [comment]
`System Preferences` > `Keyboard` > `Shortcuts` > `Mission Control` > `Move left a space` / `Move right a space`
