### ISSUE TITLE
Unable to create file "/usr/lib/doublecmd/fsplugin.ini"

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#767]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 21.3 Wildflower

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

### Description

Double Commander is installed from .deb file into the system:

$COMMANDER_PATH = /usr/lib/doublecmd/
$DC_CONFIG_PATH = /home/user/.config/doublecmd/

(btw, how can I use these variables in a shell started by DC?)

I install adb plugin from https://www.uniqtec.eu/index.php/android-adb/

Change ADB binary path (bottom option):

![image](https://user-images.githubusercontent.com/3584732/213948992-ef501214-e271-487b-ba96-62167e818fbd.png)

Error when OK is pressed:

![image](https://user-images.githubusercontent.com/3584732/213948192-ad44f391-86ee-4ed5-8c53-5ef2c6209c64.png)

**Comment by alexx2000** [comment]
It is a plugin error message. So it should be reported to plugin author.

**Comment by JonnyTech** [comment]
Done, thanks. I shall update here if any response.
