### ISSUE TITLE
Feature request: Shortcuts Rename Tool

### ISSUE THREAD

**Issue by gitgt** [doublecmd/doublecmd#770]
### Description

DC is like a Swiss knife and it has Multi-Rename Tool for files. 
I think it would make sense to also include Shortcuts Rename Tool, with basic functionality of Searching a string and Replacing it for Pattern named shortcuts in Search folder.
Like "Shortcut Search And Replace" from http://jacquelin.potier.free.fr/ShortcutsSearchAndReplace.

**Comment by alexx2000** [comment]
It is a very very specific Windows-only  and rare task.
