### ISSUE TITLE
Please verify the forum domain.

### ISSUE THREAD

**Issue by rabyj** [doublecmd/doublecmd#771]
### Description

According to whois, the website domain of `doublecmd.h1n.ru` does not have a verified domain. This causes my university to block the whole forum. Would it be possible to contact the domain admin to have them verify it?

whois information:
~~~
domain:        H1N.RU
nserver:       ns1.hostiman.ru.
nserver:       ns2.hostiman.ru.
nserver:       ns3.hostiman.com.
nserver:       ns4.hostiman.com.
state:         REGISTERED, DELEGATED, UNVERIFIED
person:        Private Person
registrar:     REGRU-RU
admin-contact: http://www.reg.ru/whois/admin_contact
created:       2016-01-29T05:52:59Z
paid-till:     2024-01-29T05:52:59Z
free-date:     2024-02-29
source:        TCI
~~~

**Comment by alexx2000** [comment]
It is a free domain from hosting provider. So I don't think that it's possible.
