### ISSUE TITLE
Toolbal buttons are too small on Ubuntu with scaled mode turned on

### ISSUE THREAD

**Issue by efulmo** [doublecmd/doublecmd#78]
My environment: 
* Ubuntu 20.04.2 LTS.
* Double Commander
Version: 0.9.8 beta
Revision: 9296
Build date: 2020/02/09
Lazarus: 2.0.6.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.2 LTS
Widgetset library: GTK 2.24.32
* Screen resolution: 1920x1080 (scale 125%).

See the image for a bug. It looks fine when scaling feature is disabled (set to 100%), but with 125% scale toolbar buttons become really nanobuttons. It's impossible recognize them.
![DoubleCommanderNanoToolbar](https://user-images.githubusercontent.com/5500475/116614514-b1bfba00-a942-11eb-98a5-22967866a2f2.png)

**Comment by alexx2000** [comment]
#1628
