### ISSUE TITLE
Unconditional file overwrite on Shift + F4 when name has trailing whitespace

### ISSUE THREAD

**Issue by danpla** [doublecmd/doublecmd#786]
### Version

Double Commander
Version: 1.0.9
Revision: 222
Commit: a844456e4
Build date: 2022/12/03
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 14.04.6 LTS

Widgetset library: GTK 2.24.23

### Description

When opening a file with Shift + F4, DC strips trailing whitespace characters from the name. But it seems that it checks for an existing file before doing stripping, so instead of opening the existing file (the one without trailing whitespace in the name), this file gets unconditionally overwritten.

Steps to reproduce:
1. Use Shift + F4 to open (create) a new file "1.txt", write some text, and save.
2. Open another one with the name "1.txt " (note an extra space after the extension)
3. Note that original "1.txt" is opened instead, but its content is lost.

**Comment by JonnyTech** [comment]
> Version: 1.0.9

Have you tested with current release (v1.1.0)? Or latest snapshot?

**Comment by ags1234** [comment]
I cannot reproduce in build doublecmd-1.1.0.r10561.i386-win32.

**Comment by JonnyTech** [comment]
I am confused, you reported a bug with the Linux version, then tested on Windows. Can you test the snapshot on the system that you reported the original issue.

**Comment by JonnyTech** [comment]
I created the following files on Linux x64 on an ext4 filesystem:

```
$ echo "no space" > "1.txt"
$ echo "with space" > "1.txt "
$ cat "1.txt"
no space
$ cat "1.txt "
with space
```

Then with latest GTK and QT builds, tried `F3`, `F4` and `Shift+F4` without errors on both files.

Is there something else required to reproduce the issue or can this be closed?

**Comment by danpla** [comment]
Create the second file by using Shift + F4 and "1.txt " as the file name to be opened.
