### ISSUE TITLE
%P%S from Total Commader is missing

### ISSUE THREAD

**Issue by LIMUNADE** [doublecmd/doublecmd#788]
### Description

Unable to put selected files by utilizing "%" variables (basically %P%S total commander analogue) parameter.

**Comment by alexx2000** [comment]
https://doublecmd.github.io/doc/en/variables.html

**Comment by LIMUNADE** [comment]
Alright, and what variables should I use for multiple selected files? 
For example: I want to convert few audio files via .bat file. What variable this should be? There is none in variables section. The only fitting command is "under cursor" but that's for 1 file.

**Comment by JonnyTech** [comment]
There exists "numbered suffix": https://doublecmd.github.io/doc/en/variables.html#numsuffix

But why not use the MRT: https://doublecmd.github.io/doc/en/multirename.html

**Comment by LIMUNADE** [comment]
> There exists "numbered suffix": https://doublecmd.github.io/doc/en/variables.html#numsuffix
> 
> But why not use the MRT: https://doublecmd.github.io/doc/en/multirename.html
> 
> EDIT: Ah, convert, not rename - so numbered suffix should suffice

So you're suggesting to use %ps0 %ps1 %ps2 etc for all case scenarios because selected files variable doesn't exist double commander?

**Comment by JonnyTech** [comment]
I thought that you wanted to get at individual files.

If multiple files are selected then you can act upon them all, for example this command: https://doublecmd.github.io/doc/en/variables.html#prefixpostfix

Is a list not suitable?: https://doublecmd.github.io/doc/en/variables.html#listoffiles

Otherwise, how do you want the list to be presented - comma / tab separated, other list, etc?

Do you have a link to the Total Commander documentation to compare?

**Comment by alexx2000** [comment]
`%ps` - all selected files.

**Comment by LIMUNADE** [comment]
> `%p` or `%ps` - all selected files in the active panel.

Thx for the answer. As you noticed there are no information about such commands in variables page. 

 
> I thought that you wanted to get at individual files.
> 
> If multiple files are selected then you can act upon them all, for example this command: https://doublecmd.github.io/doc/en/variables.html#prefixpostfix
> 
> Is a list not suitable?: https://doublecmd.github.io/doc/en/variables.html#listoffiles
> 
> Otherwise, how do you want the list to be presented - comma / tab separated, other list, etc?
> 
> Do you have a link to the Total Commander documentation to compare?

[%S parameter ](https://www.ghisler.ch/wiki/index.php/Buttonbar#Special_parameters:)
