### ISSUE TITLE
choose terminal

### ISSUE THREAD

**Issue by yashpalgoyal1304** [doublecmd/doublecmd#792]
hi! thanks a lot for this awesome lightweight explorer app.

### Description
it would be awesome if we could also choose or specify the tty used for the terminal command in dc...

Currently, for dc 1.0.10 (239) on windows:
- it always opens with the windows `conhost`
- even if i set some terminal say `wezterm` as the command, then too, conhost launches first, which in turn executes the specified command.

Wanted would be the way to change the terminal which dc calls as well

<img src="https://user-images.githubusercontent.com/19423063/216792176-ca373298-5ec6-4fa6-9d8c-6db21201f6a1.png" width=400px/>

**Comment by alexx2000** [comment]
Hi, I don't understand what do you mean. DC does not execute `conhost`, DC execute same program as you set in the options and  Windows launches `conhost` if necessary.

**Comment by yashpalgoyal1304** [comment]
> DC execute same program as you set in the options and Windows launches `conhost` if necessary.

yeah, i had this feeling already... this is similar to https://github.com/msys2/MSYS2-packages/issues/2744 

- but maybe there can be some way to launch the command which doesn't involve launching `conhost` ?
- like if you enter the commands in start menu, there, it is launched directly and there's no conhost involved...
- but yeah, it would be too specific to windows i guess...

<img src="https://user-images.githubusercontent.com/19423063/216810270-3e12ae90-76cc-4120-936d-c41697b23db6.png" width=300px/>

**Comment by yashpalgoyal1304** [comment]
oh wait no... that launches conhost too...

so, i am closing this issue as not planned. 
feel free to reopen if u want

**Comment by yashpalgoyal1304** [comment]
hmm... wait, i just pulled back together... 

yeah, i was saying that some additional column can be there which directly takes in address of the terminal application and launches the command in there...

**Comment by alexx2000** [comment]
DC already has all needed options. You can setup terminal program and it's arguments. So if you find a terminal program which can execute commands without `conhost` then you could change DC options accordingly.

**Comment by yashpalgoyal1304** [comment]
thanks. it worked...

**Comment by yashpalgoyal1304** [comment]
Other than above (1st wow), I just made several really awesome things (4 wows) in double commander. 
These were the things I wanted to do for _YEARS_

## Special Dirs:

Accessible by: `*` "Directory Hotlist" or double click on the address bar

<p align=center><img src="https://user-images.githubusercontent.com/19423063/216812395-a2d9edb8-5356-4ca6-8511-0bbbe27d9f43.png" width=500px/></p>

## Address bar gems:

event | action | "[shortcuts]"
-- | -- | --
single click | `dirs` show dir stack/or [directory history] <br/> (3rd wow) | `Alt + ↓`
double click or middle click | show directory hotlist <br/> (2nd wow) | `Ctrl + d`
right click | edit address bar | `.` `F2` 

In last row: dot will select `..` and `F2` will rename i.e. "edit current path"

[shortcuts]: https://doublecmd.github.io/doc/en/shortcuts.html "via `Keyboard layout` via `doc/en/index.html`"

## Delete Directly
There was this folder i was NOT able to delete since years, I tried everything, changing write level, permissions, doing via command line.... 

Nothing worked... but dc did it in a jiffy. Awesome.

<img src="https://user-images.githubusercontent.com/19423063/216812873-9c02baa2-32ed-42ca-a16a-ba4e87a26987.png" width=450px/>

**Comment by yashpalgoyal1304** [comment]
## Questions:
(dot will select `..` and F2 will rename i.e. "edit current path"
* Any way to directly invoke "edit current path (as [cm_EditPath](https://doublecmd.github.io/doc/en/cmds.html#cm_EditPath))"
* Can it be diagnose what was the issue with those files? Like, i would like to dig into what was causing that. If u know smth about it?

**Comment by alexx2000** [comment]
Use [discussions](https://github.com/doublecmd/doublecmd/discussions) for questions.

- You can assign a [hotkey](https://doublecmd.github.io/doc/en/configuration.html#ConfigHotKeys) to it or add it to the [toolbar](https://doublecmd.github.io/doc/en/toolbar.html)
- I don't know

**Comment by yashpalgoyal1304** [comment]
it got fixed yesterday - aah, i should have shared screenshot. today it's starting in the same repo irrespective of which current directory i am in.
