### ISSUE TITLE
Undesired sound indicating invalid key press

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#797]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10570
Commit: 0e42b4055
Build date: 2023/02/05
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.2.0

### Case 1:

1. Select any file.
2. Press F8. This will open the confirmation dialog for file deletion.
3. Press the Enter key on the numeric keypad.

**Expected result:** The file will be deleted and no sound will be played.
**Actual result:** The file will be deleted and a sound will be played to indicate that an unexpected key has been pressed.

If you press the Return key in the "main" keyboard area in step 3, the issue will not occur.

### Case 2:

1. Select any file.
2. Press Shift+F6. This will make the file name editable.
3. Press Esc.

**Expected result:** The file name will no longer be editable and no sound will be played.
**Actual result:** The file name will no longer be editable and a sound will be played to indicate that an unexpected key has been pressed.

### Case 3:

1. Press F1. This will open the "About" dialog.
2. Press Esc.

**Expected result:** The "About" dialog will be closed and no sound will be played.
**Actual result:** The "About" dialog will be closed and a sound will be played to indicate that an unexpected key has been pressed.

**Comment by rich2014** [comment]
@Andreas0602 

fixed. test the new version please:

https://doublecmd.sourceforge.io/site/eng/snapshots.php

**Comment by rich2014** [comment]
@Andreas0602 

try again.
