### ISSUE TITLE
tab rename (ms explorer)

### ISSUE THREAD

**Issue by yashpalgoyal1304** [doublecmd/doublecmd#799]
### Description

* the [multi-rename tool] from dc is awesome: provides "masking" aka rename patterns, editing names as [text file]

<p align=center><img src="https://user-images.githubusercontent.com/19423063/216970159-d345a57c-1777-4ad5-ad66-a7328133beca.png" width=300px/></p>

But sometimes, just quick renaming in succession of very few files is all what's needed

In ms explorer:
- The <kbd>tab</kbd> while renaming saves the rename, and
- changes highlight to other file in rename mode

https://user-images.githubusercontent.com/19423063/216969024-c5b408be-824d-4a81-9e69-619764362894.mp4

[text file]: https://github.com/ivanmaeder/vimv

I am using dc 1.0.10 (239)

**Comment by yashpalgoyal1304** [comment]
this is just a lite suggestion - if it doesn't feel worth it, feel free to close it as not planned :smiley:

**Comment by alexx2000** [comment]
Please don't mess multi-rename and normal rename. It is a two different functions. About fast normal rename already exists feature request #316
