### ISSUE TITLE
Show `--` while calculating and `??` after calculating size for directories

### ISSUE THREAD

**Issue by yashpalgoyal1304** [doublecmd/doublecmd#806]
### Description

Currently:
- `<DIR>` is shown normally, while calculating, and also if the result is not calculated i guess? (refer the video below)
- The suggestion is to use `--` while calculating (will aid if calculation is taking long time)
- ... and `??` if the directory size is not calculated (like shown in the attached video)

<details>
<summary>This is in continuation of earlier issue on same matter:</summary>

* https://doublecmd.sourceforge.io/mantisbt/view.php?id=2289
* --> https://doublecmd.h1n.ru/viewtopic.php?f=6&t=2485&p=13711

> But when the folder is empty, its shown as <DIR> instead of 0 (zero). It can be confusing because if the folder have so many files & folder it takes a while to calculate and its also display <DIR>.

</details>

https://user-images.githubusercontent.com/19423063/218242548-97d3830b-3b92-4bfc-ae91-ca27dfe5fc71.mp4

**Comment by yashpalgoyal1304** [comment]
awesome, can i get the build artifacts for that to check it out :smiley:

[checking] the job, it seems it's only build for mac

[checking]: https://github.com/doublecmd/doublecmd/actions/runs/4150881937/jobs/7180830657#step:8:17

**Comment by alexx2000** [comment]
https://doublecmd.sourceforge.io/site/eng/snapshots.php

**Comment by yashpalgoyal1304** [comment]
Thanks. downloaded the `Revision 10576`
will check it later :)

**Comment by yashpalgoyal1304** [comment]
just tested it - wow, dark mode is looking pretty 😏

yep:
- zero is also shown now 
(it ain't shown for empty directories in doublecmd v1.0.10 (239) - so, it wasn't actually fixed in that older link i mentioned)
- the dash while loading works as intended - it looks super nice
- haven't stumbled upon `??` in brief testing so far

thanks a lot 😄:innocent:

**Comment by goyalyashpal** [comment]
Just for records: on repeatedly pressing `space` + `arrow` the `<DIR>` still shows up before calculating the size.
