### ISSUE TITLE
Malformed gif causes DC hangs

### ISSUE THREAD

**Issue by kzotoff** [doublecmd/doublecmd#811]
### Version

Double Commander
Version: 0.9.10 beta
Revision: 9640
Build date: 2021/01/10
Lazarus: 2.0.8.0
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Debian 10.13

Widgetset library: GTK 2.24.32

### Description

I have malformed .gif file and containing only header "GIF89a" (6 bytes total). I selected this file and pressed F3 and then I needed to force close DC as it hangs forever

**Comment by alexx2000** [comment]
Version 0.9.10 is obsolete and unsupported.
Actual version 1.0.10 does not have a such problem.
