### ISSUE TITLE
(maybe a regression) Unpacking file from zip with entering empty destination

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#826]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.5 LTS

Widgetset library: GTK 2.24.32

### Description

Before, I did this: in zip, i focus a file, call 'Copy file = F5', in the path dialog I enter "empty" destination,

![f1](https://user-images.githubusercontent.com/4154978/219972101-713c82a5-4e67-4bfb-bb0e-0fa840e2ea37.png)

and before DC unpacked file to the FOLDER OF CURRENT ZIP.
but it doesn't work now! I got error

![Screenshot from 2023-02-19 22-57-57](https://user-images.githubusercontent.com/4154978/219972139-14c0f72f-3404-4f15-900f-8ef35c8ba6ea.png)

**Comment by Alexey-T** [comment]
I wanted to say: about year ago , it was working scenario - empty path of unzip destination.

**Comment by alexx2000** [comment]
I guess it's never worked (checked with old DC 0.9.6). Maybe do you mess with Alt+F9.

**Comment by Alexey-T** [comment]
Maybe you are right.

**Comment by Alexey-T** [comment]
Thanks!
