### ISSUE TITLE
Wish: in the "Sync dirs" dialog, show additional info line

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#828]
### Description

I called Sync Dirs dialog and I got empty resulting listbox of files. it was not a bug, i just forgot to clear the filtering field in the center on the top:

![Screenshot from 2023-02-20 18-35-38](https://user-images.githubusercontent.com/4154978/220148419-efe93f1a-5a7b-461e-bead-61e41c356aab.png)

to avoid user's troubles, I suggest to show some 'label' over empty listbox: "Non-empty filter is set: xxxxxxxxxxxxxxxxx (text of filter input)".

**Comment by JonnyTech** [comment]
> to avoid user's troubles, I suggest to show some 'label' over empty listbox: "Non-empty filter is set: xxxxxxxxxxxxxxxxx (text of filter input)".

But the empty listbox could also be due to user (de)selecting the other compare options.

![image](https://user-images.githubusercontent.com/3584732/220150482-198b8a39-7234-4bda-b2cf-6afd9dbdbf8e.png)

**Comment by Alexey-T** [comment]
agree. so no easy solution.
