### ISSUE TITLE
Linux, symlink, F6 makes copy symlink, do not move.

### ISSUE THREAD

**Issue by wb027** [doublecmd/doublecmd#83]
Double Commander
Version: 1.0.0 alpha
Revision: 9778
Commit: d1a3aca09
Build date: 2021/04/30
Lazarus: 2.0.12.0-51630
FPC: 3.0.4
Platform: x86_64-Linux-gtk2
OS version: Linux Mint 20 Ulyana

Widgetset library: GTK 2.24.32

**Comment by alexx2000** [comment]
Fixed.
