### ISSUE TITLE
DC ignores WDX plugin file detection string when searching

### ISSUE THREAD

**Issue by danpla** [doublecmd/doublecmd#833]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 7 SP1 x86_64

### Description

When searching with WDX plugins, DC seems to ignore the file detection string returned by `ContentGetDetectString` (and, I guess, the `FT_FILEERROR` status from `ContentGetValue`), and calls the plugin for all paths. In some cases, this makes the search nearly useless, as it will match absolutely all files.

You can use the built-in audioinfo plugin as an example:
1. Switch to a directory that has no audio files (or at least a few)
2. Open the Plugins tab in the search dialog (Alt + F7)
3. Add a rule that uses the audioinfo to match tracks with an empty title (Filed = "Title", Operator = "=", Value = "" (empty))
4. Press Start and see that all files are included in the result, even those with extensions that don't match the plugin's detection string

At the same time, Total Commander doesn't call the plugin for files that don't match `ContentGetDetectString`, and also observes `FT_FILEERROR`. Consequently, such files are not included in the search result.

**Comment by alexx2000** [comment]
I fixed it. But looks like TC considers that `ft_fieldempty` is not equals empty string. So no way to find files with empty title at this time.

I think AudioInfo plugin also should be changed to return empty string instead `ft_fieldempty`.
