### ISSUE TITLE
Crash on deleting several files/dirs inside .tar.xz archive

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#838]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.5 LTS

Widgetset library: GTK 2.24.32

### Description

doublecmd.err
```

--------------- 02-03-2023, 19:56:45 ---------------
| DC v1.0.10 Rev. 239 -- x86_64-Linux-gtk2
| Ubuntu 20.04.5 LTS -- GTK 2.24.32 | PID 288311
Unhandled exception: EAccessViolation: Access violation
  Stack trace:
  $00007F4618DC26F8 in /home/user/doublecmd/plugins/wcx/zip/zip.wcx
```

what I did:

- download CudaText release 1.186.0 for linux-amd64-qt5. this is .tar.xz file. https://sourceforge.net/projects/cudatext/files/release/
- enter this archive in the left DC panel
- select (by Space) all files/dirs except the CudaText binary file 'cudatext'
- delete selection -> crash

![bug-dc](https://user-images.githubusercontent.com/4154978/222499231-a00af1df-db2a-419f-a3d4-7704a91f9a8b.png)

**Comment by alexx2000** [comment]
I cannot reproduce.

**Comment by Alexey-T** [comment]
Did you try on Ubuntu 20.04 ?

**Comment by alexx2000** [comment]
No, I tried with Arch Linux and Double Commander 1.0.10 portable.

**Comment by Alexey-T** [comment]
No repro :(

**Comment by ags1234** [comment]
Double Commander
Version: 1.1.0 alpha
Revision: 10630
Commit: 409cdae2b
Build date: 2023/03/05
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

The deletion works perfectly. Only the cudatext binary remains in the archive.
