### ISSUE TITLE
Search in text files with RegEx is broken

### ISSUE THREAD

**Issue by iszerencsi** [doublecmd/doublecmd#839]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x84_64-Win64-win32/win64
OS version: Windows 10 1909 x86_64

### Description

Searching in text files with ALT-F7, files *.txt, recursive, with RegEx is not working properly.
in RegEx "oneword.*otherword" 'kind of working' (find files), but a bit more complicated RegEx does not find anything (although the data is there, and can be found with dnGrep for example). For example [0-9][0-9]*[kKmMgG]$ is not working at all (want to find a text about 'some amount of memory' at the end of a line).
The text is CP-437, US-ASCII, nothing special.
I've even reinstalled DC, deleting the installation directory to get rid of any  plugins. (I haven't purge the registry yet.) Issue is the same.

**Comment by JonnyTech** [comment]
From the documentation at https://doublecmd.github.io/doc/en/regexp.html DC uses the TRegExpr library https://regex.sorokin.engineer/en/latest/ so maybe the issue should be created at https://github.com/andgineer/TRegExpr/issues

**Comment by alexx2000** [comment]
You should enable a multi line search by [(?m)](https://doublecmd.github.io/doc/en/regexp.html#modifiers) modifier, like this `(?m)[0-9][0-9][kKmMgG]$`

**Comment by Aliaksandr3by** [comment]
I think it is broken.
other soft work good
![image](https://github.com/doublecmd/doublecmd/assets/11432724/6ef8b7e0-8024-46ff-8b4b-8f1c209576d4)

![2023-10-21 (2)](https://github.com/doublecmd/doublecmd/assets/11432724/99b1d88e-f006-4abc-8e94-4f7875df8356)

**Comment by alexx2000** [comment]
DC does not support search in the EPUB files.
