### ISSUE TITLE
Interface is black after minimizing

### ISSUE THREAD

**Issue by soredake** [doublecmd/doublecmd#840]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

### Description

When you maximize double commander after minimizing it interface will be black for a second.

Example:
https://user-images.githubusercontent.com/5204968/222742394-84d376f3-4824-4c57-a8ee-38ff5150cf1f.mp4

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
The same issue occurs with me as well, and  hopefully it can be fixed sooner.

**Comment by ags1234** [comment]
I also have this in Win 11 24h2.
When DC is in full screen and the user is switching fast between minimize and maximize, the UI is redrawn very slow. In the short time that it can be seen, UI seems to be recomposed from a few different panels that come together to form one UI.
Probably hard to fix, not making any hopes. Or not?
