### ISSUE TITLE
[Windows][Hot Keys]: Ctrl+Alt combinations don't work

### ISSUE THREAD

**Issue by PetbkA** [doublecmd/doublecmd#86]
**Version**: 0.9.10 beta
**Revision**: 9640M
**Build date**: 2021/01/10
**Lazarus**: 2.0.8.0
**FPC**: 3.0.4
**Platform**: x86_64-Win64-win32/win64
**OS version**: Windows 10 Home 2004 x86_64

In Total Commander I'm using _Ctrl + Alt + Character_ buttons to change sorting in the active pane, for example:
1. _Ctrl + Alt + D_ to sort by Date;
2. _Ctrl + Alt + S_ to sort by Size

and so on.

In DC I can't do that 'cause instead of changing sorting combination activates filter. I've changed combinations to _Ctrl + Shift + Character_ and everything works OK. _Alt + Character_ and _Ctrl + Character_ combinations work OK too, the problem is only with _Ctrl + Alt + Character_

**Comment by Skif-off** [comment]
Works fine:
1. Go to "Configuration" in main menu > Options... > Keys > Ctrl+Alt+Letters > set `None`.
2. Now go to "Configuration" in main menu > Options... > Keys > Hot keys.

**Comment by PetbkA** [comment]
> Works fine:
> 
> 1. Go to "Configuration" in main menu > Options... > Keys > Ctrl+Alt+Letters > set `None`.
> 2. Now go to "Configuration" in main menu > Options... > Keys > Hot keys.

Indeed. Thank you!
