### ISSUE TITLE
The alt+f7 (search) keyboard shortcut no longer works.

### ISSUE THREAD

**Issue by grzegorz75jan** [doublecmd/doublecmd#862]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.5.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 Home 22H2 x86_64

### Description

Hi. Привет.
The alt+f7 (search) keyboard shortcut no longer works in several versions of DC. Using alt+f7 instead of the search panel brings up a directory creation dialog that is similar to using F7. The keyboard is technically sound.

I use several keyboard languages in Windows 10. The same error occurs in Polish and Russian. There is no alt+f7 response in the English keyboard language. I also changed the DC program language to match the keyboard language.

Uninstalling the DC and manually deleting the config files didn't help.
The portable version has the same error for me.

I haven't reported this issue before as I was hoping it would be fixed in future releases. I do not speak English. I use an online translator.
![02](https://user-images.githubusercontent.com/32609882/224389308-9735cba4-e79c-47c4-9b30-b2c8e2f0b46d.jpg)

**Comment by avmaksimov** [comment]
Hello! It's very strange. Did you check Alt+F7 in another program? It's all ok for me.

And if you choose from menu: Commands \ Search is it ok or not?

P.S. Дублирую немного развёрнуто по-русски. Должно всё работать хорошо. Может, что-то ещё перехватывает? В других программах проверьте. Тот же TC. Плюс из меню, если вызвать.

**Comment by grzegorz75jan** [comment]
> Did you check Alt+F7 in another program?

This is a valuable comment that motivated me to act.
I didn't check before, because the previous keyboard was a bit damaged, so I bought a new one. I haven't checked in other applications, because all keys in the new keyboard work and I don't use [Alt+F7] except for DC. Now I can use diacritics again ([right Alt+letter] = ą, ę, Ż, ł, etc.), but the problem in DC with [Alt+F7] remains.
However, I followed your suggestion. 
I installed TC and same problem. I looked further and to my surprise I found that using the right Alt key in various applications does not allow you to set the hotkey [Alt+F7], but sets [Ctrl+Alt+F7] or [Ctrl+Alt] automatically. In diagnostic programs, it sometimes activates Ctrl (Ctrl left and right) and left Alt simultaneously. 
![01](https://user-images.githubusercontent.com/32609882/224582127-d10d0c47-c4b6-4d05-a139-85a9d1d19d23.png)
Test keyboard/anti ghosting - [MultiKeyDisplay](https://drakeirving.github.io/MultiKeyDisplay/)

Sometimes the right Alt is represented as Alt Gr or AltGraph and that was a clue to discovering the source of the problem.
![02](https://user-images.githubusercontent.com/32609882/224582162-0bfe5269-ac5c-4cb7-af25-20cd37bc8dac.png)
[No18 - Elusien - Keypresses Visualiser and PNG Image Creator](http://www.elusien.co.uk/shotcut/resources/index.html)

> And if you choose from menu: Commands \ Search is it ok or not?

Yes. Works. Is fine. (It's okay.)

> I use several keyboard languages in Windows 10. The same error occurs in Polish and Russian. There is no alt+f7 response in the English keyboard language. I also changed the DC program language to match the keyboard language.

The problem remains when I choose Polish or Russian as the keyboard language. Today, however, [left Alt+F7] works it's strange (this satisfies me) and yesterday it didn't. I do not know why.
After selecting the English language, just restart DC for [Right Alt+F7] to work properly.

[The problem is the keyboard layout for some keyboard languages. Right Alt is then different from Left Alt. It is then Alt Gr or Alt Graph.](https://en.wikipedia.org/wiki/AltGr_key)
[AltGr](https://pl.wikipedia.org/wiki/AltGr)

Problem partially solved (I didn't have a problem in DC with [RAlt+F7] a long time ago. There was probably some change in Windows 10) so you can close the topic.

Thank you for your attention. / Спасибо за внимание.
