### ISSUE TITLE
Filename blinking

### ISSUE THREAD

**Issue by pwn0r** [doublecmd/doublecmd#866]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Ubuntu 22.04.2 LTS

Widgetset library: Qt 5.15.3, libQt5Pas 5.6.1

### Description

This problem is not new and not limited to just ubuntu 22.04 specifically. Lines in the file list blink when files get updated. 
Which gets pretty annoying if viewing e.g. /var/log folder, with a few log files being updated almost every second and you sort by date desc. Even more visible if you place a cursor over a file. 

Im aware you can disable auto-refresh, the refresh is fine by itself, it is the blinking part. First, the blink means a line is being blanked out first before overwritten which is strange. Second, when a file is being written to, the only part that visibly changes is its time. Yet the whole line blinks anyway (size change is not visible due to rounding, e.g. 10.1mb)

**Comment by alexx2000** [comment]
It is a feature, see [Highlight new and updated files](https://doublecmd.github.io/doc/en/configuration.html#ConfigViewEx)
