### ISSUE TITLE
Опреации с FTP/SFTP невозможно перевести в фон

### ISSUE THREAD

**Issue by svalx** [doublecmd/doublecmd#873]
### Description

Хотелось бы как с простым копированием иметь возможность переместить на панель.

**Comment by alexx2000** [comment]
![image](https://user-images.githubusercontent.com/13401398/225840963-8c2f2bad-7851-4ce8-b5a4-c21e0b92dbfa.png)

**Comment by svalx** [comment]
Да, отлично, прошу прощения. Но сам я не догадался бы... может какую-то подсказку в диалоге по-умочанию сделать или возможность перевода в отдельный поток "на ходу"?

**Comment by avmaksimov** [comment]
Как вариант, сразу переводить всегда в отдельное соединение, где будет добавляться в очередь.

**Comment by alexx2000** [comment]
Поведение [зависит от плагина](https://ghisler.github.io/WFX-SDK/fsgetbackgroundflags.htm), плагин FTP оставляет решение на пользователя.
Кроме того на сервере может быть ограничение: один пользователь - одно соединение.

**Comment by avmaksimov** [comment]
> Поведение [зависит от плагина](https://ghisler.github.io/WFX-SDK/fsgetbackgroundflags.htm), плагин FTP оставляет решение на пользователя. Кроме того на сервере может быть ограничение: один пользователь - одно соединение.

Тогда можно добавлять в очередь только, когда функция вернёт истину, а иначе создавать без)

**Comment by alexx2000** [comment]
Сейчас так и сделано, если функция возвращает истину, то галочка будет установлена по умолчанию.

**Comment by avmaksimov** [comment]
Тогда пока лучше и не придумаешь))

**Comment by avmaksimov** [comment]
> Да, отлично, прошу прощения. Но сам я не догадался бы... может какую-то подсказку в диалоге по-умочанию сделать или возможность перевода в отдельный поток "на ходу"?

Таки, может быть, закроете, если всё ок?!)

**Comment by svalx** [comment]
Да, конечно.
