### ISSUE TITLE
Dark mode stopped working after upgrading Windows 10 to 21H1

### ISSUE THREAD

**Issue by hakonrk** [doublecmd/doublecmd#88]
Double Commander no longer detects that Windows 10 is in dark mode after I installed Windows update 21H1 (build 19043.985).

I am currently running `doublecmd-1.0.0.r9785.x86_64-win64-qt5.dark` but the problem is the same on older builds (e.g. 9767).

**Comment by hakonrk** [comment]
Looking at the code, the reason seems obvious:
```pascal
function CheckBuildNumber(buildNumber: DWORD): Boolean; inline;
begin
  Result := (buildNumber = 17763) or // 1809
            (buildNumber = 18362) or // 1903
            (buildNumber = 18363) or // 1909
            (buildNumber = 19041) or // 2004
            (buildNumber = 19042);   // 2009
end;
```

Why not replace this with `buildNumber >= 17763` so that it doesn't break with every new Windows update? If a later version of Windows behaves differently, it seems to me that it is better to deal with that then, if it even becomes a problem.

**Comment by alexx2000** [comment]
Dark API is not officially published and can be changed with Windows update. So DC can be crash after such update.
I changed detect code so now it should be better.

**Comment by deepu2** [comment]
There's dark mode? Where can I find this?

**Comment by hakonrk** [comment]
> There's dark mode? Where can I find this?

Use a `qt5.dark` build from https://doublecmd.sourceforge.io/site/eng/snapshots.html and doublecmd will automatically use dark mode when the OS runs in dark mode.
