### ISSUE TITLE
Signing key at opensuse.org expired

### ISSUE THREAD

**Issue by gitgt** [doublecmd/doublecmd#881]
### Version

not-version related

### Description

Following https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-gtk and: 
curl -fsSL https://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_22.04/Release.key .....
 signing key expired at 2023-03-22. Please update.

**Comment by alexx2000** [comment]
I updated a signing key. It is needed to remove old key if exists and add new instead.

**Comment by sysms** [comment]
I can confirm, that the new key works for the Debian 11 repository.

**Comment by gitgt** [comment]
Thanks Alex. Based on previous confirmation ,I close.
