### ISSUE TITLE
Pressing enter on copy/move dialog no longer starts the action

### ISSUE THREAD

**Issue by muchachagrande** [doublecmd/doublecmd#887]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10655
Commit: 2d04c4b
Build date: 2023/03/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

Before, when chosing some files and press F5 or F6 to copy or move them, you were presented with the copy/move dialog, and you could confirm the action pressing ENTER.
Now, and since some revisions ago, you can not longer use ENTER to confirm action.
The only way to confirm the operation is pressing start button with the mouse or using ALT+Z, but ENTER key doesn't work anymore.

**Comment by rich2014** [comment]
try Revision `10656` please.

**Comment by muchachagrande** [comment]
Ok, now I have another non related problem. I cant update.
The following signatures were not valid: EXPKEYSIG 61508B60C33A8925 home:Alexx2000 OBS Project <home:Alexx2000@build.opensuse.org>
The repository signature has expired.

**Comment by avmaksimov** [comment]
> Ok, now I have another non related problem. I cant update. The following signatures were not valid: EXPKEYSIG 61508B60C33A8925 home:Alexx2000 OBS Project home:Alexx2000@build.opensuse.org The repository signature has expired.

https://doublecmd.h1n.ru/viewtopic.php?f=5&p=39093#p39093
