### ISSUE TITLE
The new style .p12 file is not recognized

### ISSUE THREAD

**Issue by tukanos** [doublecmd/doublecmd#891]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/02/11
Lazarus: 2.2.4.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Debian 12.0

Widgetset library: GTK 2.24.33

### Description

I use the openssl certificate overview functionality of doublecmd quite often.  I have found out that the new .p12 format is not parsable within the doublecmd and I have to check it manually via CLI, which is a pitty.

The my current openssl version is:
`OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023`

I'm including the file `paired_certificate.p12` within a zip file:

[paired_certificate.zip](https://github.com/doublecmd/doublecmd/files/11087628/paired_certificate.zip)

It can be checked with openssl CLI command:

`openssl pkcs12 -info -in paired_certificate.p12`

where password is: test

**Comment by alexx2000** [comment]
DC does not have a such function. I guess you are using some plugin like `fileinfo`.

**Comment by tukanos** [comment]
> DC does not have a such function. I guess you are using some plugin like `fileinfo`.

Ah, I see.  I have probably configured it way back and forgot about it.  I will then close the issue.
