### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alexswan** [doublecmd/doublecmd#900]
### Description

As a total commander fan,

i would like a small feature:

if i am in a folder in right pane, and switch focus to left pane, then choose the same drive as in the right pane (so, change drive) i would like that left pane to show the same folder as in right pane

**Comment by avmaksimov** [comment]
It already works as you wrote. May be you set "Always go to the root..." in Misc Options?

**Comment by goyalyashpal** [comment]
hi @alexswan can u rename the title to be more precise and descriptive? thanks :)

**Comment by JonnyTech** [comment]
@alexswan 

https://doublecmd.github.io/doc/en/help.html#iface_toolbar

![image](https://user-images.githubusercontent.com/3584732/229516147-5791a64a-6381-4815-a94b-6c349a63f631.png)
