### ISSUE TITLE
Sycronize dirs is not working

### ISSUE THREAD

**Issue by alexswan** [doublecmd/doublecmd#902]
### Version

Double Commander
Version: 0.9.9 beta
Revision: 9478
Build date: 2020/06/27
Lazarus: 2.0.3.0-61194
FPC: 3.0.4
Platform: x86_64-Darwin-qt4
OS version: Mac OS X 10.16.0

Widgetset library: Qt 4.8.6, libQt4Pas 4.5.3

### Description

i compare 2 dirs.
then i compare 2 files. although the file size is different, i see no difference
mac ventura 13.3 os, DC version 0.9.9 build 9478.

![Screenshot 2023-04-02 at 10 32 03](https://user-images.githubusercontent.com/2155531/229339199-bee39a56-0e01-45e1-b178-49a06c42df14.png)

**Comment by alexx2000** [comment]
Version 0.9.9 is obsolete and unsupported. Try with latest [snapshot](https://doublecmd.sourceforge.io/site/eng/snapshots.php). File can have different line-endings, encoding, etc. The new DC version reports this.
