### ISSUE TITLE
otg view options for Quick view panel

### ISSUE THREAD

**Issue by goyalyashpal** [doublecmd/doublecmd#903]
### Description

Having the ability to change the viewed type on the go will immensely widen the use of quick view panel:
- to view *.csv as text, or document files
- to view raw *.bmp as graphics, or hex
- etc...

I always used to miss this ability (view as hex for exe files - #905 ) - came to know about it being already present in [Internal File Viewer View Menu](https://doublecmd.github.io/doc/en/viewer.html#mnu_view) from #468 "reword view menu" issue.

### Proposed technical implementation details (optional)

Maybe in the marked areas? I am not sure about it

![image](https://user-images.githubusercontent.com/19423063/229349258-b7727fbc-57db-4b4e-b468-850dc2bb8d8a.png)

**Comment by alexx2000** [comment]
You can change view mode by 1-8 hotkeys if move focus to quick view window.

**Comment by goyalyashpal** [comment]
i think tab to "Switch between panels" or say to move focus to other panel doesn't work when quick view is enabled, is that so?

if yes, then any way to move focus to quick view from keyboard?

**Comment by goyalyashpal** [comment]
and how to reset to defautt?

**Comment by goyalyashpal** [comment]
one idea for improving discoverability - if u think it's worth it.

a bar can be added in quick view pane between the scroll bar and the status bar - to show these 8-9 options as clicable buttons - similar to how the action bar does for the whole window
