### ISSUE TITLE
Garbage under folders in Thumbnails view

### ISSUE THREAD

**Issue by cryham** [doublecmd/doublecmd#913]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2023/04/02
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Debian 11.6

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

### Description

I thought it was something I got in the 2019 fork I use, but checked it now on latest version and it is present too.
There are random garbage pixels around folder thumbnails. Folder icon is okay (just blurry) and preview image also.
This changes randomly like it was some not cleared memory or bitmap.

![0403_163435cr](https://user-images.githubusercontent.com/720641/229558283-8519d6d6-635b-45ed-8e55-6399f351cae1.png)

**Comment by alexx2000** [comment]
I cannot reproduce. But theoretically I know what to change.

**Comment by alexx2000** [comment]
Try DC 1.1.0 from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

**Comment by cryham** [comment]
Okay I tried both AppImage for qt and gtk and this issue is now solved, I don't see any garbage now.
