### ISSUE TITLE
Files moved to root of OneDrive when deleting files to Trash [MacOS Venture 13.3] 

### ISSUE THREAD

**Issue by ERoelofsAtHomeNL** [doublecmd/doublecmd#918]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10655
Commit: 2d04c4b60
Build date: 2023/03/21
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.3.0

### Description

When deleting files (to the trash bin) from a OneDrive synced location, the files are moved to the root of the OneDrive. Next, removing it from this root, it is gone for a short period and returns again with incrementing number behind it (when repeating). It is the same error as mentioned here for Forklift [MS365 OneDrive Community](https://answers.microsoft.com/en-us/msoffice/forum/all/files-and-folders-are-being-moved-to-root-folder/9cea1604-1fdf-489e-b267-ecce4c381f31)

Essential part: 

> "ForkLift devs told me that OneDrive needs to use this API when dealing with trash on Mac:
> https://developer.apple.com/documentation/foundation/filemanager/1414306-trashitem
> It seems it started to behave like this from macOS 13 Ventura."

NB my guess is that doing so will also solve the -unreported (by me )- issue of not showing copied files to/between OneDrive locations in the window panes. I now work around this by going up and down a directory..

Cheers, ER(ik)

_PS thanks for this great TC alternative. Been using double pane commanders since Norton ruled the world.. DC is my go-to on the Mac for a long time now._

**Comment by alexx2000** [comment]
I agree with ForkLift  developers. It looks like a OneDrive bug. DC moves file to trash using standard [function](https://developer.apple.com/documentation/foundation/filemanager/1414306-trashitem). What can we do?

**Comment by ERoelofsAtHomeNL** [comment]
Thanks for the quick response.
I appreciate your comment but don't understand what's going on.
When moving a file to Trash (in DC) from the ~/Library/CloudStorage/<OneDriveRoot> (which is linked to: ~/OneDrive -> /Users/erik/Library/CloudStorage/OneDrive) it instantly returns the file, with an updated number <filename><n++>.[ext].
And this is true, even when OneNote is not running. Also, the file does never end up in the Trash Bin. How can it then be a OneDrive bug? Is it the way MacOS (and/or DC) handles CloudStorage file manipulation?

**Comment by alexx2000** [comment]
I don't know how OneDrive works under macOS. But DC calls a system function which should move file to trash. DC does not control it. Maybe it is a system function bug.
