### ISSUE TITLE
"pkexec doublecmd"  cannot work in .desktop shortcut .

### ISSUE THREAD

**Issue by jack-liew** [doublecmd/doublecmd#920]
### Version

double-commander 1.0.10, Ubuntu 22.04

### Description

I can executed "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORIT doublecmd" in bash, but it cannot work in .desktop shortcut .

any suggest? Thanks

**Comment by alexx2000** [comment]
#915

**Comment by jack-liew** [comment]
> Two solutions:
> 
> 1. Create shell script and call it from .desktop file.
> 2. Copy [file](https://github.com/doublecmd/doublecmd/blob/master/install/linux/org.doublecmd.root.policy)  to `/usr/share/polkit-1/actions/` then you can execute DC using `pkexec doublecmd`.

Thank U, The first method worked for me.
