### ISSUE TITLE
[Major bug] incorrect version info in lastest msi installer

### ISSUE THREAD

**Issue by kelvin-dev** [doublecmd/doublecmd#925]
### Version

Version: 1.0.11 [checked both on github release channel and sourceforge]

### Description

the application still shows old version in latest release, please investigate the root cause and security matters in software packaging & release process

![image](https://user-images.githubusercontent.com/19224355/230745321-eb5aa250-860e-43e4-962c-90a9adb7eb3e.png)

**Comment by alexx2000** [comment]
That's not so! Installer contains correct version.
