### ISSUE TITLE
Text viewer hangs for 20sec on this file

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#926]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

Open this text file in viewer.
[n1.zip](https://github.com/doublecmd/doublecmd/files/11185179/n1.zip)

Press Ctrl+End to go to end. Pause of 20sec on my CPU Intel Core i3.

**Comment by alexx2000** [comment]
Viewer does not like a crazy long lines.

**Comment by Alexey-T** [comment]
Let the report be opened, until you make the change here.
