### ISSUE TITLE
Strange build time, 2017/01/01

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#928]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2017/01/01
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Fedora release 37 (Thirty Seven)

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

### Description

I see "Build 2017/1/1" (not "Build date") in the current version of DC when I press F1

When filing a new issue, the default build is "Build date: 2022/12/03".

Also, the "date" is added to the clipboard but not visible on screen.

**Comment by alexx2000** [comment]
"Build " and "Build date" is a same thing here. I guess OBS virtual machine has such time. So I am nothing can do here.
