### ISSUE TITLE
Ineffective "find dupes by size+hash" implementation

### ISSUE THREAD

**Issue by zxcat** [doublecmd/doublecmd#933]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10683
Commit: 0611623c6
Build date: 2023/04/10
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.15.7

### Description

**Steps to reproduce:**
1. Enter folder with large files (like movies)
2. Find files using "find duplicate files", "same size", "same hash" options together

**Expected behavior:**
DC first groups files by size and then calculates hashes only for files with same sizes (groups containing more than 1 file), so search is very fast

**Actual behavior:**
DC reads each file in its entirety (seems, it calculates every hash), search is very slow, "by size" option has no effect

**Comment by alexx2000** [comment]
DC in any case should calculate file hash. If file has different size then it will be in another group, but file hash should be calculated in this case too.

So it is better to use search duplicates by content. It compares size at first step.

**Comment by alexx2000** [comment]
I optimized it, but need more testing.
