### ISSUE TITLE
Request for new internal command: new file

### ISSUE THREAD

**Issue by deepu2** [doublecmd/doublecmd#94]
I only found new file and edit command, whereas sometimes i want to just create a new file and not open it with the internal editor. If there is something like this please assist me.

**Comment by Skif-off** [comment]
Try [CreateNewFile.lua](https://github.com/j2969719/doublecmd-plugins/blob/master/utils/CreateNewFile.lua), templates [here](https://github.com/j2969719/doublecmd-plugins/tree/master/utils/newfiles).

[Help page](http://doublecmd.github.io/doc/en/toolbar.html), button example with Lua script [here](http://doublecmd.github.io/doc/en/lua.html#exampleex).

**Comment by deepu2** [comment]
I will try this, thank you
