### ISSUE TITLE
Missing "doublecmd.exe" executable in windows development snapshots.

### ISSUE THREAD

**Issue by hkdemiralp** [doublecmd/doublecmd#941]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10699
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

### Description

Hi. The current windows development version snapshots that are available [here](https://doublecmd.sourceforge.io/site/eng/snapshots.php) do not have "doublecmd.exe" executable in 7z archives.
For revision 10699, both 32 and 64 bit version missing the "doublecmd.exe" executable. I believe this is the same for some previous revisions lately.

**Comment by alexx2000** [comment]
Hi, fixed.

**Comment by hkdemiralp** [comment]
Thank you very much.
🙏

**Comment by hkdemiralp** [comment]
Same bug appears again. "doublecmd.exe" executable is missing in windows development [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php) revision 11352.

**Version**
Double Commander Version: 1.2.0 alpha
Revision: 11352
Platform: x86_64-Win64-win32/win64
OS version: Windows 11 22H2 x86_64

**Comment by ags1234** [comment]
Also missing some wcx plugins.
It would be nice to have them back. Though the size of the archive is very attractive as it is now ;)
