### ISSUE TITLE
Can't copy file in the same directory

### ISSUE THREAD

**Issue by dandv** [doublecmd/doublecmd#946]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2017/01/01
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Fedora release 37 (Thirty Seven)

Widgetset library: Qt 5.15.8, libQt5Pas 5.6.1

### Description

I tried copying a file to the current directory, but it fails as in the screenshot. Notice the `/` at the start of the destination filename.

![DC - can't copy file in current directory](https://user-images.githubusercontent.com/33569/232938386-50685913-d60a-4c35-89ee-13be6869880b.png)

Using `./b.txt` as the path doesn't help. Pressing Esc in that error dialog freezes DC.

![Screenshot_20230418_175735](https://user-images.githubusercontent.com/33569/232938943-7dbdf0c6-1443-4b13-960f-d633d4b5fd1f.png)

**Comment by alexx2000** [comment]
You should enter only file name `b.txt` if you want copy to same directory or use `Shift+F5` hotkey.

**Comment by alexx2000** [comment]
`Shift+F5` is a correct way for this task in DC. Name changing can change path only within the same file system.
