### ISSUE TITLE
File panel content doesn't refresh after changes

### ISSUE THREAD

**Issue by HypnoticST8** [doublecmd/doublecmd#954]
### Version

Version: 1.1.0 beta
Revision: 10668
Commit: d074d08ef
Build date: 2023/04/02
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.3.1

### Description

Steps to reproduce:

1. click on the file pane to activate it
2. chose random file (i.e. aaa.txt) and press F2 to rename it
3. enter new file name i.e. bbb.txt
4. press enter to confirm new file name

The file name is actually changed but not reflected in file pane (pressing F3 to view the aaa.txt will result in 'no files found')
This goes for all other file/folder operations like folder creation and deletion. To see the changes in the directory where the changes were made, you need to change the path to the parent and back to the directory where the changes were made

**Comment by rich2014** [comment]
hi, did you enable `Auto refresh` in options?

<img width="784" alt="image" src="https://user-images.githubusercontent.com/102933068/235088094-0bed6cf2-efb2-4f32-a74f-82573a2ec182.png">

**Comment by HypnoticST8** [comment]
Hi, I haven't touch any configuration options and I see that it's enabled. Disabling both options solves the issue, the file pane refreshes as it should. This happened after recent update, it was working fine before it.  Actual settings from deoblecmd.xml
<AutoRefresh>
<Options>0</Options>
<ExcludeDirs/>
<Mode>1</Mode>

**Comment by rich2014** [comment]
1. before `10668`, DC for MacOS doesn't support `AutoRefresh` Options. it's always enalbe `AutoRefresh`, no matter what the options set.

2. but it should work when `AutoRefresh` enabled, not disabled.

3. are you sure it's the exact opposite?

**Comment by HypnoticST8** [comment]
Yes, I'm sure that it currently works the way as i describe it above.

**Comment by rich2014** [comment]
after you change the options, do you exit the DC first, and then check doublecmd.xml?

**Comment by HypnoticST8** [comment]
The <Option> value changes immediately after clicking apply in configuration dialog. Closing DC doesn't change this value after DC is closed and same goes for starting DC.

**Comment by exidler** [comment]
Double Commander
Version: 1.1.0 alpha
Revision: 10710
Commit: 15ba1f1ef
Build date: 2023/04/28
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.3.1

I have similar bug.
On native APFS all working fine (whatever Auto refresh enabled or not)
But for FUSE (gocryptfs) refreshing only when Auto refresh disabled in Settings.

**Comment by rich2014** [comment]
@exidler thx, I'll try to provide a test app

**Comment by rich2014** [comment]
> On native APFS all working fine (whatever Auto refresh enabled or not)
> But for FUSE (gocryptfs) refreshing only when Auto refresh disabled in Settings.

@HypnoticST8   is your issue the same?

**Comment by HypnoticST8** [comment]
I can't answer for the FUSE part because I don't use it. My APFS is encrypted. I won't be able to provide any additional info for the next week.

**Comment by rich2014** [comment]
> My APFS is encrypted

**Comment by HypnoticST8** [comment]
The one inside (Apple SSD), I don't use external drives except USB pendrives (I don't own this Mac, it's from my employer)

**Comment by rich2014** [comment]
@HypnoticST8 @exidler 

hi,

i uploaded a test app, it's a safe app.

it only watch a path you selected, and save the events to a log file by you.

it can't read the file content, it can't save anything except events.

please make a test and send the log file.

1. download and unzip: [testmonitor.app.zip](https://github.com/doublecmd/doublecmd/files/11359191/testmonitor.app.zip)

2. add the path you had problem to watch in `testmonitor.app`
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/102933068/235303267-0367be18-40d8-446e-a6aa-cabc498601db.png">

3. rename the file in the path with Finder or DC

4. save the log to a file in `testmonitor.app`
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/102933068/235303394-bf8c86f0-1cfa-4448-a341-99b7bc1ea7db.png">

5. upload the log file

thx

**Comment by exidler** [comment]
More details: 
1. APFS - renaming, creating new files, delete from DC - refresh working with enabled or not Auto Refresh in settings, but, changes made outside of DC - does not seen when Auto Refresh disabled
2. FUSE - activity from DC reflected when Auto refresh disabled, and ignored in any ways if enabled
3. Manual refresh of panel, works fine.

**Comment by rich2014** [comment]
thx, the cause should be symlink, i will check and fix it later.

PS. disabling AutoRefresh can detect changes made from DC, which is normal. because when AutoRefresh is disabled, DC will do a full refresh after file operation.

**Comment by rich2014** [comment]
@HypnoticST8 @exidler 

snapshot 10714 released, test it please.

[doublecmd-1.1.0-10714-cocoa-aarch64](https://doublecmd.sourceforge.io/snapshots/doublecmd-1.1.0-10714.cocoa.aarch64.dmg)

**Comment by HypnoticST8** [comment]
Sorry for late reply, I've been leaving recently near the black hole ;-). I'm using latest beta and can confirm that the bug is fixed.

**Comment by rich2014** [comment]
OK
