### ISSUE TITLE
Text viewer cannot show text with filesize>=2G

### ISSUE THREAD

**Issue by Alexey-T** [doublecmd/doublecmd#958]
### Version

Double Commander
Version: 1.0.10
Revision: 239
Commit: d00f8b7b7
Build date: 2023/01/21
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

Make file with python script:
```
f=open('test.log','w')
f.write('w\n'*0x80000010)
del f
```
Open this test.log with viewer -> viewer fails to show more than 14 lines. 14 ? IMO reason is - because TStream.ReadBuffer truncates Int64 size to LongInt value 14.

**Comment by Skif-off** [comment]
> 14 ?

[MaxTextWidth](https://doublecmd.github.io/doc/en/configxml.html) ?

**Comment by Alexey-T** [comment]
It is default here, `<MaxTextWidth>1024</MaxTextWidth>`
