### ISSUE TITLE
Crash on macos-smbfs browsing

### ISSUE THREAD

**Issue by exidler** [doublecmd/doublecmd#963]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10714
Commit: 51ca918fa
Build date: 2023/05/01
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 13.3.1

### Description

Latest snapshot bring crash (not handled Access violation) when browsing some directories mounted with smbfs
How to reproduce - does not know, because not all dirs crashing, but always easy to reproduce for me.
Just walk through some dirs mounted with smbfs
Snapshot 10710 does not have this crash

[dc-crash.txt](https://github.com/doublecmd/doublecmd/files/11367275/dc-crash.txt)
[dc-crash2.txt](https://github.com/doublecmd/doublecmd/files/11367276/dc-crash2.txt)

**Comment by exidler** [comment]
Decide do not create new issue
There something "freezing" when browsing smbfs directories.
It's not a network problem delays (parallel tests with ls -l same_dir).
Latest snapshot have this problem (10710, 10714)

I have record screen, but recording does not show ordinary mouse pointer, but when i'm waiting for dir content almost sees rainbow circle.
At the begin of record, I have try to open directory 'pigallery2', and content show after ~5seconds (ls from terminal works without any delay)
Maybe you have some ideas..
Can test anything to locate the problem.


[screen record](https://youtu.be/OwVWBYIgdzI)

**Comment by rich2014** [comment]
hi, a new PR submitted. you can test it after merged.

**Comment by rich2014** [comment]
@exidler 

try 10715 :)

https://doublecmd.sourceforge.io/site/eng/snapshots.php
