### ISSUE TITLE
QT: Incorrect text selected with internal viewer

### ISSUE THREAD

**Issue by JonnyTech** [doublecmd/doublecmd#964]
### Version

Latest AppImage: https://opensuse.mirror.liquidtelecom.com//repositories/home%3A/Alexx2000%3A/doublecmd-svn/AppImage/doublecmd-qt-latest-x86_64.AppImage

Double Commander
Version: 1.1.0 alpha
Revision: 10714
Commit: 51ca918
Build date: 2023/05/01
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 21.3 Wildflower

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

### Description

Selecting text with the built-in viewer highlights incorrect text.

Here I selected from a [plain text file](https://github.com/doublecmd/doublecmd/files/11367456/dummy.txt) the text `ninety minutes` but the text ` on the run` to the left of my selection was highlighted.

![image](https://user-images.githubusercontent.com/3584732/235512352-77a08cac-1df2-4113-88aa-16eddc1370c5.png)
 
Only an issue with the qt builds, the gtk ones work correctly.

**Comment by alexx2000** [comment]
#587

**Comment by JonnyTech** [comment]
Thanks, but the linked issue is for `gtk` builds, this is for `qt` builds.

I changed from `monospace` to `hack` and it fixed the issue:

```
<?xml version="1.0" encoding="UTF-8"?>
<doublecmd>
  <Fonts>
    <Viewer>
      <Name>Hack</Name>
    </Viewer>
</doublecmd>
```

Can that be changed to the default please?

**Comment by alexx2000** [comment]
> Thanks, but the linked issue is for `gtk` builds, this is for `qt` builds.

No, the linked issue [about Qt](https://github.com/doublecmd/doublecmd/issues/587#issuecomment-1249155709) builds.

> Can that be changed to the default please?

I will replace `Monospace` by some other font. Looks like Monospace [is not a real font](https://bbs.archlinux.org/viewtopic.php?id=177690).
