### ISSUE TITLE
Cannot load zip.wcx

### ISSUE THREAD

**Issue by ags1234** [doublecmd/doublecmd#976]
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10728
Commit: 5b7d7a4
Build date: 2017/01/01
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Fedora release 38 (Thirty Eight)

Widgetset library: Qt 5.15.9, libQt5Pas 5.6.1

### Description

I installed DC from repository here: https://download.opensuse.org/repositories/home:Alexx2000:doublecmd-svn/Fedora_37/home:Alexx2000:doublecmd-svn.repo
DC does not open zip archives and shows this error message:

![Screenshot_20230507_100053](https://user-images.githubusercontent.com/21011513/236663070-7f03a9d2-d414-45b8-a039-e41046ede7b7.png)

**Comment by alexx2000** [comment]
I cannot reproduce (checked with Fedora 38 in VirtualBox). Try to execute DC from console, open .zip archive and copy console output here.

**Comment by ags1234** [comment]
> Try to execute DC from console, open .zip archive and copy console output here.

This is the output from console. At the end, you'll see I tried 3 times to enter the archive.

![Screenshot_20230507_174927](https://user-images.githubusercontent.com/21011513/236684822-6c1f0813-16be-43d9-8434-16ca683dc753.png)

**Comment by ags1234** [comment]
Also, the output of `locate zip.wcx`:
```
/usr/lib64/doublecmd/plugins/wcx/zip/zip.wcx
```
So the file is there, but DC cannot reach to it.

**Comment by ags1234** [comment]
DC plugins config is the default one, I didn't change anything.
![Screenshot_20230507_180220](https://user-images.githubusercontent.com/21011513/236685561-cfb72064-9ecc-4dd5-b2f0-7f99382fd545.png)

**Comment by alexx2000** [comment]
Your config looks like it from Windows version. Try to replace path by `%commander_path%/plugins/wcx/zip/zip.wcx`.
Also I added repo for Fedora 38, so you try with it.

**Comment by ags1234** [comment]
OMG, I copied the config from the Windows version! I did not realize I needed to modify the paths! It works fine now.

Thank you for support!
