### ISSUE TITLE
Folders can't sort  by date

### ISSUE THREAD

**Issue by sl5net** [doublecmd/doublecmd#98]
Folders can't sort  by date by clicking on "Date" Column,

its possibe sort files by date by clicking on "Date" Column.

Please compare for eg to Midnight Commander. Thanks

Maybe please reopen: https://github.com/doublecmd/doublecmd/issues/70

I using :
```
Double Commander
Version: 0.9.8 beta
Revision: 9296
Build date: 2020/02/09
Lazarus: 2.0.6.0
FPC: 3.0.4
Platform: x86_64-Linux-qt5
OS version: Ubuntu 20.04.2 LTS
Widgetset library: Qt 5.12.8, libQt5Pas 5.6.1

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-55-generic
OS Type: 64-bit

**Comment by Skif-off** [comment]
Just try to enable this: go to "Configuration" in main menu > Options... > Files views > Sorting > _Sorting directories_ and use "sort like files and show first" or "sort like files".

**Comment by sl5net** [comment]
perfect, very good options there. pleas use add default, because i think newbies often see that as problem.

**Comment by alexx2000** [comment]
It is default now.
